### ISSUE TITLE
More creation functions.

### ISSUE THREAD

**Issue by lukasoppermann** [lucadegasperi/oauth2-server-laravel#175]
Hey,
are you planning to add more functions to for e.g. add scopes, clients, etc. in a production environment?

I am just wondering if you will be adding utilities for basically having someone sing up with an app or if it is worth writing something myself, because it is not on your roadmap.

Thanks.

**Comment by lukasoppermann** [comment]
Is there any news on this?

**Comment by vinkla** [comment]
@lukasoppermann @darkyen What kind of extra functions did you've in mind?

**Comment by lukasoppermann** [comment]
Just commands to create a new client with everything and a new grant.

**Comment by vinkla** [comment]
We'll eventually create a separate package to manage these sort of things. For now I'm closing this.

Thanks for contributing.
