### ISSUE TITLE
Blade template example

### ISSUE THREAD

**Issue by syphernl** [lucadegasperi/oauth2-server-laravel#258]
In [the wiki](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Auth-Code-Grant) there is a mention of a template. It would probably be nice include an example on the wiki so people know which (hidden) fields should be available in the view and where the form should post to.

I would add it if I could but I haven't been able to get 3.0 to work properly yet (getting "grant_type" errors).

**Comment by codivist** [comment]
@davzie and @syphernl instead of putting your grant_type, client_id, and client_secret in your header, put them in the form with your username and password and it should work.
