### ISSUE TITLE
Access token owners

### ISSUE THREAD

**Issue by joeauty** [lucadegasperi/oauth2-server-laravel#268]
Hello,

This is very likely not a bug with this library, but a result of my misunderstanding. However, if nothing more this might be something worth documenting...

I'm using the password grant type, and trying to determine the owner of the access tokens issued so that my application can assign ownership to certain database content.

I was expecting the owner_id column in oauth_sessions to contain this info, and I've been trying to retrieve this via: $this->authorizer->getResourceOwnerId(). However, this column does not reflect my user IDs. My access tokens are created as follows:

if (Auth::attempt(array('username' => Input::get('username'), 'password' => Input::get('password')), $rememberme))
{
	return Response::json(Authorizer::issueAccessToken());
}

My config:

'grant_types' => [
	'password' => [
    'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
    'callback' => function($username, $password) {
			
        return Auth::validate([
            'username'    => $username,
            'password' => $password,
        ]);
    },
    'access_token_ttl' => 3600
  ]
],

What is the best approach to determining the user id that owns these access tokens?

**Comment by mofman** [comment]
I'm using code very similar to yours, I was wondering how you ended up logging the user in? I'm currently adding this to my application. 

      $user_id = Authorizer::getResourceOwnerId();
      $User    = Auth::loginUsingId($user_id);

Is there a cleaner way to do this?

**Comment by zzal** [comment]
Ok, I _think_ I'm using this server correctly, but like Joe Auty, I can’t get the current Auth::user right (it always returns me the first record in the database), even if I use `Authorizer::getResourceOwnerId();`.

In my server steup, this is my configuration:
```
    'grant_types' => [

        'refresh_token' => [
            'class' => 'League\OAuth2\Server\Grant\RefreshTokenGrant',
            'access_token_ttl' => 3600,
            'refresh_token_ttl' => 604800,
            'rotate_refresh_tokens' => false,
        ],
        'password' => [
            'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
            'callback' => function($username, $password) {
                return Auth::validate([
                    'username' => $username,
                    'password' => $password,
                ]);
            },
            'access_token_ttl' => 3600,
        ]
    ],
```

And here is my route config:
```
Route::post('oauth/token/access', function()
{
  return Response::json(Authorizer::issueAccessToken());
});
Route::resource('user', 'UserController');
```

Where I use `GET /user` to actually get my user info, like this:
```
public function index()
{
	$resourceOwnerType = Authorizer::getResourceOwnerType();
	$resourceOwnerId = Authorizer::getResourceOwnerId();

	if ($resourceOwnerType === 'user')
	{
		$user = Auth::loginUsingId($resourceOwnerId);
		return Response::json($user);
	}
	return Response::make('god hates me', 404);
}
``` 

And this is what I get in the database, **even if I log with differents users**, it always write `owner_id=1`:
```
id  client_id     owner_type  owner_id   client_redirect_uri  created_at    updated_at
--  ------------  ----------  ---------  -------------------  ------------  ------------
XX  'client-id'   'user'      1          NULL                 2015-01-16 …  2015-01-16 …
```

Am I missing somthing?

**Comment by monooso** [comment]
@zzal You need to change the callback function in your `oauth2.php` config file, so it reads as follows:

~~~~~php
'password' => [
    'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
    'callback' => function($username, $password) {
        return Auth::attempt(compact('username', 'password'))
            ? Auth::id()
            : false;       
    },
    'access_token_ttl' => 3600,
],
~~~~~

**Comment by zzal** [comment]
@monooso Ah! That's why! Thank you so much…

**Comment by monooso** [comment]
@zzal You're welcome. It took me a while to figure it out too.

**Comment by thangchung** [comment]
@monooso Thanks your solution. That's really saving me a lot of time.

**Comment by monooso** [comment]
@thangchung No problem, glad you found it useful.
