### ISSUE TITLE
Access token parameter missing / request malfunctioned

### ISSUE THREAD

**Issue by prady00** [lucadegasperi/oauth2-server-laravel#271]
When token passed with query string, it works fine - 

    GET /protected-resource?access_token=Qkru1xEkxRX1J0stQBUBAMgNKLDZtrnjGwNGcEEb             HTTP/1.1
    Host: urthon.local
    Cache-Control: no-cache
    Content-Type: application/x-www-form-urlencoded

With following request it gives error -

    GET /protected-resource HTTP/1.1
    Host: urthon.local
    Authorization: Bearer Qkru1xEkxRX1J0stQBUBAMgNKLDZtrnjGwNGcEEb
    Cache-Control: no-cache
    Content-Type: application/x-www-form-urlencoded

Says - 

   {"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"access token\" parameter."}

What;s going on? In config, I have  'http_headers_only' => false,

**Comment by pddevins** [comment]
+1 @lollypopgr && @ChrisTerBeke

**Comment by jmazurpl** [comment]
Same problem here. Changing the .htaccess didn't help.
Anybody solved this issue?

**Comment by hpbrasileiro09** [comment]
Gentleman
I'm using apache and alter my .htaccess
and works fine, thanks ChrisTerBeke

**Comment by tallcoder** [comment]
When I switched to an Apache env from Nginx ... I had to make the update to htaccess file and it worked fine. Thanks!

**Comment by pewla** [comment]
@ChrisTerBeke  Dude you saved me a lot of headache today. Thanks a bunch.
