### ISSUE TITLE
Eloquent models

### ISSUE THREAD

**Issue by ChrisTerBeke** [lucadegasperi/oauth2-server-laravel#272]
Can you give any comment on building eloquent models for this package? I did a few myself now, but it would save many people a lot of time to have a full set of eloquent models available. Then things like adding clients, scopes and resetting access tokens would be really easy to do.

I might work on this myself as well if I can find some time and do a pull request.

**Comment by ChrisTerBeke** [comment]
Sounds logical. Any plan on making such a support package yourself? I'd be happy to help out.

**Comment by kevindierkx** [comment]
@ChrisTerBeke I started working on something similar recently: https://github.com/PCextreme/oauth2-server-manager-laravel

Purpose of above package is to make managing your OAuth2 server easier.
