### ISSUE TITLE
Check \"grant type\" parameter

### ISSUE THREAD

**Issue by dtirer** [lucadegasperi/oauth2-server-laravel#273]
I'm trying to setup OAuth with an API I'm building.  I'm using the Password grant and my OAuth2.php file looks as follows:

`'grant_types' => [
        'password' => [
            'class'            => 'League\OAuth2\Server\Grant\PasswordGrant',
            'callback'         => function($username, $password)
            {
                $credentials = [
                    'email'    => $username,
                    'password' => $password,
                ];
                if (Auth::once($credentials)) {
                        return Auth::user()->id;
                    } else {
                        return false;
                    }
            }
        ],
    ],`

I then have a basic route setup to test it (as per the docs)

`Route::post('oauth/access_token', function() {
    return Response::json(Authorizer::issueAccessToken());

});`

I'm using Postman to test the API.  I enter the URL / Route, and i choose x-www-form-urlencoded in Postman, and set the 2 parameters (email & password) to valid credentials that are in the DB.  However, I always get this error:

`{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"grant_type\" parameter."}`

Please advise, thanks.

**Comment by ahsenx** [comment]
I am trying to use it as a plugin, so once plugin is registered it writes the config in memory, 

```
class OAuth2ServiceProvider extends ServiceProvider
{
...
...
...
$this->app['config']['lucadegasperi/oauth2-server-laravel::oauth2.grant_types.password.callback'] = function ($username, $password)
        {
            try {
                $user = Sentry::findUserByCredentials(['email' => $username]);

                if(!$user->checkPassword($password))
                    return false;

                return $user->id;

            } catch (\Cartalyst\Sentry\Users\UserNotFoundException $e) {
                return false;
            }
        };
```

and i am getting the same error

```{"error":"unsupported_grant_type","error_description":"The authorization grant type \"password\" is not supported by the authorization server."}```

Any idea what i am missing?

**Comment by kodeine** [comment]
i was able to fix it, was setting wrong config.

```
class OAuth2ServiceProvider extends ServiceProvider
{
...
...
...
$this->app['config']['oauth2-server-laravel::oauth2.grant_types.password.callback'] = function ($username, $password)
        {
...
...
```

**Comment by manuraj** [comment]
You also have to specify the "protected $identifier = YOUR GRANT NAME "

**Comment by talhazekeriyadurmus** [comment]
I have the same issue.
my post is
{"email":"test@test.com","password":"test@test.com", "grant_type" : "password"}

and it returns error
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"grant_type\" parameter."}

**Comment by kodeine** [comment]
@talhazekeriyadurmus you need to add client_id and client_secret params too.

**Comment by arnold-almeida** [comment]
Just upgraded and facing a few issues. Just wondering if people have this working correctly in the wild ?

For me i found a problem with 
League\OAuth2\Server\AuthorizationServer::issueAccessToken() Line: 264

$grantType = $this->getRequest()->request->get('grant_type');

Seems to be loosing the "grant_type" parameter

And if its changed to : 

$grantType = $this->getRequest()->get('grant_type');

It seems to work as expected.

Will update as i debug more.

**Comment by codivist** [comment]
Also make sure you have enabled the 'password' grant_type in your oauth2.php config file
