### ISSUE TITLE
Allow easier setup of multiple auth code grant types in authorizer

### ISSUE THREAD

**Issue by dmyers** [lucadegasperi/oauth2-server-laravel#275]
The `Authorizer` class has a few specific references to `authorization_code`, but if you want to setup multiple auth codes for multiple user types like I am working on it's hard to use it.

Could you make it a parameter in the methods below and have it as the default for those who want to override? It would be really helpful I think.

Since the `check-authorization-params`  filter is loaded automatically using `before()` maybe it could look for a `grant_type` in the query string too.

https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/src/Authorizer.php#L112
https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/src/Authorizer.php#L125

**Comment by lucadegasperi** [comment]
Don't see why the code above is an issue for your use case, It's tied specifically to the authorization_code grant type in order to make it a bit easier to use.
If you explain me your use case a bit better and convince me the code should be changed, I'll gladly change it.
