### ISSUE TITLE
Allow easier setup of multiple grant types using config as identifier

### ISSUE THREAD

**Issue by dmyers** [lucadegasperi/oauth2-server-laravel#276]
I noticed in the grant type classes such as `PasswordGrant` there is an `identifier` property, but if you want to setup several password grant types for multiple user resource types you have to create your own classes which extend the `PasswordGrant` class and set the identifier property.

It seems what could be easier is inside the config use the key as the identifier of that grant instance instead. What do you think?

**Comment by lucadegasperi** [comment]
Can you provide me with an example of what you have in mind?
