### ISSUE TITLE
Ability to pass client credentials without token

### ISSUE THREAD

**Issue by dmyers** [lucadegasperi/oauth2-server-laravel#277]
Is there any way to do similar to what GitHub does where their API doesn't require getting a token, you can simply use your client credentials or you can also do basic auth too.

https://developer.github.com/v3/#oauth2-keysecret
https://developer.github.com/v3/#basic-authentication

**Comment by lucadegasperi** [comment]
Sorry I came across your issue this late.
Implementing an authorization method similar to the one GitHub offers is out of the scope of OAuth.
It is up to you, Most likely it's just a filter and a DB query.
