### ISSUE TITLE
Passing data via Content-Type: application/json

### ISSUE THREAD

**Issue by kfuchs** [lucadegasperi/oauth2-server-laravel#278]
The 1.x versions were able to issue tokens even if the data was passed via `application/json`. In version 3.x it's no longer possible. Was this intentional or just a side effect of upgrading to the newer League package?

Is there any opposition to adding this feature back in?
Yes, I know the RFC states "using the "application/x-www-form-urlencode format" everywhere but it doesn't say anything about dis-allowing other data types. I see no harm in supporting multiple datatypes as an addition feature. Thoughts?

**Comment by lucadegasperi** [comment]
Yes that's a side effect of the new version of the underlying package being updated to follow the specification more strictly.

**Comment by kfuchs** [comment]
Would you be willing to add this feature/accept a pull request?

**Comment by lucadegasperi** [comment]
That's not up to me. You need to talk with the maintainer of league/oauth2-server

**Comment by kfuchs** [comment]
this also would fix the problems faced in issue #225

**Comment by lukasoppermann** [comment]
@lucadegasperi @vinkla can you please reopen & fix it? This would be very awesome, as I run into the same problem.

**Comment by leemem** [comment]
@kfuchs thx,this fixed my problems.
I changed my code like this, cause i did't post data with json object.
`
public function registerAuthorizer()
{
...

    if ($app['request']->isJson()) {
        $app['request']->request->add($app['request']->all());
    }
    $authorizer->setRequest($app['request']);

...
}
`
