### ISSUE TITLE
Is it possible to fix the refresh token

### ISSUE THREAD

**Issue by teamsoo** [lucadegasperi/oauth2-server-laravel#279]
I'm able to issue the refresh token using the following grant

>       'refresh_token' => [
>			'class'                 => 'League\OAuth2\Server\Grant\RefreshTokenGrant',
>			'access_token_ttl'      => 3600,
>			'refresh_token_ttl'     => 604800
>      ],

My problem is the refresh token keeps changing every time I use it.
Is it possible to leave it unchanged for every use so that one refresh token can be used to get multiple access tokens

**Comment by prady00** [comment]
In your oauth2.php set 
    'rotate_refresh_tokens' => false

**Comment by teamsoo** [comment]
Thanks for the reply @prady00 ,

I've tried that but it didn't work for me. Have you tested it yet?

That was the first thing I did. It supposes to work the way I want, right?

**Comment by prady00** [comment]
You need to look into : https://github.com/lucadegasperi/oauth2-server-laravel/issues/189

**Comment by teamsoo** [comment]
@prady00 , I've looked into the issue and found nothing related to me problem.

My refresh token works just fine. It returns useable access token but the Authorizer always generates new refresh token which is not what I want. Do you have anything on your mind related to this?

Thank you so much, by the way. :)

**Comment by teamsoo** [comment]
I'm not sure if this is the correct way to do it.

I managed to edit RefreshTokenGrant.php
```php
....
// Expire the old refresh token
$oldRefreshToken->expire();

// Generate a new refresh token
$newRefreshToken = new RefreshTokenEntity($this->server);
$newRefreshToken->setId(SecureKey::generate());
$newRefreshToken->setExpireTime($this->getRefreshTokenTTL() + time());
$newRefreshToken->setAccessToken($newAccessToken);
$newRefreshToken->save();

$this->server->getTokenType()->setParam('refresh_token', $newRefreshToken->getId());
...
```

See that according to this,
```php
$newRefreshToken->setId(SecureKey::generate());
```
$newRefreshToken Id will be generated every call without any condition (I'm not sure where 'rotate_refresh_tokens' is being checked).

So, instead of generating a new id, I get the id from $oldRefreshToken, which is already expired ( the "$oldRefreshToken->expire()" delete the record from database ), like this
```php
$newRefreshToken->setId($oldRefreshToken->getId());
```

Now, I get a new refresh token with the same Id as the previous one.

Thanks, I'm going to close this.
