### ISSUE TITLE
Remembering and revoking access (and understanding oauth_sessions)

### ISSUE THREAD

**Issue by craigsssmith** [lucadegasperi/oauth2-server-laravel#280]
I have implemented a basic Auth Code flow successfully, but this requires the user to allow/deny the client access each time, even if the logged in user has previously allowed that client. So I'm looking to implement:

1. A shortcut whereby an auth code is returned immediately if the logged in user has already allowed the client.
2. A way for users to revoke access for specific clients.

For the first of these, I've followed the ideas in #123, and in particular the linked gist (https://gist.github.com/luchaos/993eeb18f2c27dc7aba8), and this appears to work, however I've noticed something: that a new entry is created in oauth_session each time a new auth code is generated. I see where this is happening, as a result of the call to Authorizer::issueAuthCode(...), but I don't understand why that happens. _Should it reuse an existing session, and if so, is there a way to achieve this?_

For the second of my goals, I'm simply deleting all records from oauth_sessions for a specific client_id, owner_id, and owner_type (always 'user' in this case). Is that the correct thing to do?

Many thanks in advance for any help or assistance you can provide.

**Comment by lucadegasperi** [comment]
For both of your points what you came up with is a perfectly valid way of doing it.

**Comment by craigsssmith** [comment]
Thanks for replying so quickly. I really appreciate that. So you're saying that it's perfectly fine to be creating lots and lots of sessions for a single user and for them to only be deleted when the user revokes access for that client? (I'm just keen to try and understand how it works under the hood)

**Comment by lucadegasperi** [comment]
Yes that's perfectly fine. Immagine a user logging in in one browser with a client and then an unauthorized access from another browser but with the same client. If they shared the same session (and tokens) the user might need to revoke the access to the client. Whereas having multiple sessions for a client, allows for a more granular control by the user.

**Comment by craigsssmith** [comment]
That makes a lot of sense. But in the case of it being the same user from the same browser with the same client. Shouldn't it then be the same session?

**Comment by lucadegasperi** [comment]
Not if the user has cleared the browser cookies or the session has expired. a client is responsible for storing and managing the access tokens.

**Comment by craigsssmith** [comment]
Thanks for all your help. I really do appreciate it.
