### ISSUE TITLE
Database seeder override laravel's seeder

### ISSUE THREAD

**Issue by ikhsan017** [lucadegasperi/oauth2-server-laravel#281]
Dear Luca,

Love your works so far, but I have problem when running ``` artisan db:seed ``` which call your DatabaseSeeder instead of laravel's DatabaseSeeder.

could it moved so it is not override the default seeder, or add command like ``` artisan oauth:seed ```

Best regards
Ikhsan

**Comment by lucadegasperi** [comment]
Weird, My Database seeder is meant to be run only for testing, I haven't had any conflicts with the default laravel seeder. I'll look into this issue a bit more nonetheless.

**Comment by ikhsan017** [comment]
Yeah, I see your message when running on production, but on my local dev machine, each time I run ```artisan db:seed``` it always run your seeder and disregards the one in app directory.

or maybe there is something I miss on the configuration or else? using Laravel 4.2 here

**Comment by kevindierkx** [comment]
Had the same problem a few days ago. The 'Laravel' DatabaseSeeder wasn't available in the Autoload, running ```php artisan dump-autoload``` resolved the problem for me.

Side note: I removed the default DatabaseSeeder and in a later stage re-added it to my project with the above problem as a result.
