### ISSUE TITLE
Refreshed access token (via refresh_token grant) does not get the same scope as original access token

### ISSUE THREAD

**Issue by nazan** [lucadegasperi/oauth2-server-laravel#282]
In the following method, notice that SessionEntity is never associated with the requested ScopeEntities.

> League\OAuth2\Server\Grant\AuthCodeGrant::newAuthorizeRequest(...)

Also notice that in the following method, ScopeEntities are associated to SessionEntity but the save() method of SessionEntity is never called (therefore not persisted into database).

> League\OAuth2\Server\Grant\AuthCodeGrant::completeFlow()

However in the following method (when using refresh_token grant type), it tries to retrieve ScopeEntities from the SessionEntity which gives an empty array. As a result the new access token ("REFRESHED" token) is never re-populated with the scopes from the original access token.

> League\OAuth2\Server\Grant\RefreshTokenGrant::completeFlow()

NOTE: I do realize that this problem is in League code and not the code in this repo. I wasn't sure where to post this, so I'm posting in both thephpleague/oauth2-server and this repo.

**Comment by nazan** [comment]
Care to shed some light on this issue? Anyone? In case my question is not understood.. Basically here is the problem:

- I want to use refresh_token grant type.
- I have already set everything up and I'm even getting a refreshed accessed token.
- But the problem is the refreshed access token does not get the same scopes as the original access token.

Example:
Suppose access token A has scopes 'abc,xyz,def'. When access token A expires I'm using refresh token grant mechanism to get a refreshed access token B. However access token B does not have scope 'abc,xyz,def'. In fact access token B does not have any scope at all.

**Comment by zzal** [comment]
I would be very interested to know how exactly do you use the refresh token grant mechanism.
I find the docs in the wiki hardly talkative  :
https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Refresh-Token-Grant
>  3. Whenever you request an Access Token using a grant that supports the use of the 
> Refresh Token grant, you'll get a Refresh Token together with the Access Token. 
> Once the Access Token expires, use the Refresh Token to require a new one.

??? And? How?

**Comment by nazan** [comment]
You have to add 'refresh token' grant type along with 'authorization code' grant type in the config file. Note that i'm referring to the config of this oauth 2 implementation library. Now every time you request for an 'access token' using an 'authorization code', u'll also receive a 'refresh token'. You may use this 'refresh token' to get a new access token without the intervention of the resource owner.

**Comment by zzal** [comment]
The Refresh Token grant is set in my config file. I'm using it along with the password grant type though:
```
    'grant_types' => [

        'refresh_token' => [
            'class'                 => 'League\OAuth2\Server\Grant\RefreshTokenGrant',
            'access_token_ttl'      => 3600,
            'refresh_token_ttl'     => 604800,
            'rotate_refresh_tokens' => false,
        ],
        'password' => [
            'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
            'callback' => function($email, $password)
            {
                $rememberMe = Input::get('remember_me', false);
                return Auth::attempt(compact('email', 'password'), $rememberMe)
                    ? Auth::id()
                    : false;
            },
            'access_token_ttl' => 3600,
        ]
    ],
```
The question remains: **how** use this 'refresh token' to get a new access token?

**Comment by zzal** [comment]
Ok, got it. 
I got an answer [here](https://github.com/thephpleague/oauth2-server/issues/193#issuecomment-70858929)
Thanks!

**Comment by nazan** [comment]
Ok great. My original question still remains. Maybe you can answer that for me. When you use refresh token to get a new access token, does it have the same scope as your original access token?

**Comment by nazan** [comment]
Is this fixed now? If so in which version?
