### ISSUE TITLE
Force Attack

### ISSUE THREAD

**Issue by aligokayduman** [lucadegasperi/oauth2-server-laravel#283]
Hi, How can i protect my http://www.example.com/oauth/access_token&grant_type=password&username=user1&password=pass..... link to brute force attack?  Or do not need?

my config: 

'password' => [
            'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
            'callback' => function($username, $password) {
             
             $auth = Auth::attempt(array(
                'username' => $username,
                'password' => $password
                ));

                if($auth){
                    $id = Auth::user()->id;
                    return $id;
                }else{
                    return false;
                }
                
            },
            'access_token_ttl' => 3600
        ],

https://tools.ietf.org/html/rfc6749#section-4.3.2 

"Since this access token request utilizes the resource owner's
   password, the authorization server MUST protect the endpoint against
   brute force attacks (e.g., using rate-limitation or generating
   alerts)."

**Comment by lucadegasperi** [comment]
This is out of the scope of this package but maybe this might help. https://github.com/GrahamCampbell/Laravel-Throttle

**Comment by aligokayduman** [comment]
Thank, I'll try and repord as soon as possible
