### ISSUE TITLE
Oauth2.php database config

### ISSUE THREAD

**Issue by dud3** [lucadegasperi/oauth2-server-laravel#284]
I have the following scenario:
Two databases ``X_database``, ``mysql``.
* ``X_database`` is used for OAuth
* ``mysql`` is used for Other data

In the ``oauth2.php`` I've set the ``database = X_database`` so I'll get the OAuth data from there.

```php
return [

    /*
    |--------------------------------------------------------------------------
    | Database Connection to use
    |--------------------------------------------------------------------------
    |
    | Set the default database connection to use for the repositories,
    | when set to default, it uses whatever connection you specified in your laravel db config.
    |
    */
    'database' => 'X_database',
...
```

OAuthentication goes through:
```php
Route::post('oauth/access_token', function()
{
    Response::json(Authorizer::issueAccessToken());
});
```

The problem is that I want to read data from the ``X_database`` and not ``mysql``, but for some reason when I try to access the route above, the database connection is overwritten with ``mysql`` database.

## References
Database configuration:
```sql
return array(

	'fetch' => PDO::FETCH_CLASS,

	'default' => 'mysql',

	'connections' => array(

		'mysql' => [...]

		'X_database' => array(
			'driver'    => 'mysql',
			'host'      => 'localhost',
			'database'  => 'frimann',
			'username'  => 'root',
			'password'  => '',
			'charset'   => 'utf8',
			'collation' => 'utf8_unicode_ci',
			'prefix'    => '',
		),
...
```

**Comment by lucadegasperi** [comment]
This is weird, It shouldn't happen, I'll check the codebase and report back.

**Comment by dud3** [comment]
Thanks a lot.

**Comment by lucadegasperi** [comment]
Which version of Laravel are you on and which version o this package are you using?

**Comment by dud3** [comment]
Composer says:
```
Laravel Framework version 4.2.16

league/oauth2-server  4.0.2   A lightweight and powerful OAuth 2.0 authorization and resource server library with support for all the core specification grants.

lucadegasperi/oauth2-server-laravel 3.0.1   A Laravel 4 wrapper for the popular OAuth 2.0 Server package league/oauth2-server

```

**Comment by lucadegasperi** [comment]
Most likely the configuration isn't read properly. When running the artisan Repl and typing
```Config::get('oauth2-server-laravel::oauth2.database');``` what does it output?

**Comment by dud3** [comment]
it output the ``X_database``, the correct one.

BTW: sorry for my late reply.

**Comment by mrgswift** [comment]
Was this ever resolved?  I am having the same problem as dud3.  I need to be able to use a separate database for oauth2.  Thanks!
