### ISSUE TITLE
Logging User in before routing?

### ISSUE THREAD

**Issue by mofman** [lucadegasperi/oauth2-server-laravel#285]
I've a number of routes for my website, which check for special permissions. 

The most basic being isAdmin

**routes.php**

	Route::group(array('before'=>'isAdmin'), function() {
		Route::resource('users', 'UserController');
		Route::resource('user', 'UserController');
	});

**filters.php**

	Route::filter('isAdmin', function($route)
	{

		if (User::isAdmin() == false) {
			return Response::make('Unauthorized', 401);
		}

	});

Obviously, if I pass this this through as  ['before'=>'isAdmin|oauth'] it will fail because Auth is not defined.

How would I go about checking for this as well as authenticating the access_token at the some time?

**BaseController.php**

    <?php

	class BaseController extends Controller {

		protected $currentUser;
		protected $isAPI;

		function __construct() {

			if (Input::has('access_token')) {
				$user_id           = Authorizer::getResourceOwnerId();
				$this->isAPI       = true;
				$this->currentUser = Auth::loginUsingId($user_id);
			}
			else {
				$this->isAPI       = false;
				$this->currentUser = Auth::user();
			}

		}

**Comment by dud3** [comment]
I believe the library has it's own filter:
```php
Route::group(array('before' => 'oauth'), function()
{
// your routes go here...
});
```

**Comment by mofman** [comment]
@dud3 but that still doesn't solve my problem whereby User is still undefined?

**Comment by dud3** [comment]
It seems like I didn't understand you're requirements completely.
Do you want to associate the user with the token somehow, or you just want to authenticate the user and then get the token ?

Password grant type example:
```php
'grant_types' => [
        'password' => [
            'class'            => 'League\OAuth2\Server\Grant\PasswordGrant',
            'access_token_ttl' => 604800,

            // the code to run in order to verify the user's identity
            'callback' => function($username, $password) {

                $credentials = [
                     'email'    => $username,
                     'password' => $password,
                 ];

                 if (Auth::once($credentials)) {
                            return Auth::user()->id;
                 } else {
                     return false;
                 }

            }
        ]...
```

**Comment by mofman** [comment]
My password grant seemed to be working fine

    'grant_types' => [
        'password' => [
            'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
            'callback' => function($username, $password) {
                if (Auth::attempt([
                    'email'    => $username,
                    'password' => $password,
                ])) {
                    return Auth::id();
                }
                else {
                    return false;
                }
            },
            'access_token_ttl' => 604800
        ],
        'refresh_token' => [
            'class' => '\League\OAuth2\Server\Grant\RefreshTokenGrant',
            'access_token_ttl' => 604800,
            'refresh_token_ttl' => 604800
        ]
    ],

I'm already able to authenticate a user, provide a token and give them access with using this token. My issue is that parts of my site already have specific filters such as isAdmin. Obviously these pages can only be served if the user has admin privileges. Essentially I'm trying to authenticate a user using oauth while simultaneously checking (using filters.php) if they have admin privileges

**Comment by dud3** [comment]
How about you modify the ``oauth_access_tokens`` and crate another column let's say ``user_id`` and then link the ``permissions`` based on that.

But for this to work, you might need to create you're own ``grant type``.

**Comment by teamsoo** [comment]
With oauth, you can't access user from Auth anymore.

In your isAdmin filter, you can get access_token from Input::get('access_token') and use that token to get session_id (in oauth_access_token table). 

Once you get oauth_sessions from the session_id, there is a field named "owner_id" which is your logged in user that associate with the input token. Use that id to query user table to see if he/she is admin.


Your route can be something like this.

```php
Route::group(array('before' => 'oauth'), function() {
     // Normal Get / Post ...
     Route::group(array('before' => 'isAdmin'), function() {
         // Admin stuff
     }
}
```

Hope this help.

**Comment by mofman** [comment]
Thanks for your help teamsoo,
Not sure how I didnt think of this, 

Heres what I ended up doing for anyone in the future looking to achieve the same thing

Created a new filter in filters.php

```php
Route::filter('setUser', function()
{
	$user_id = Authorizer::getResourceOwnerId();
	Auth::loginUsingId($user_id);
});
```

then in routes.php

```php
Route::group(['prefix' => 'api/v1', 'before' => 'oauth|setUser'], function(){

	Route::group(array('before'=>'isAdmin'), function() {
		Route::resource('users', 'UserController');
		Route::resource('user', 'UserController');
	});

	Route::get('projects', ['uses' => 'ProjectController@index']);
	Route::get('project/{project_id}', array('uses' => 'ProjectController@show'));

	// Nested Project Operations
	Route::group(['prefix' => 'project/{project_id}'], function(){

		// Audit Trail
		Route::resource('audit', 'AuditController');

	});
});
```

In my BaseContoller.php I set isAPI so i can test on this on my controllers and either return a view or json 

```php
	function __construct() {

		if (Input::has('access_token')) {
			$this->isAPI       = true;
		}
		else {
			$this->isAPI       = false;
		}
	}
```
