### ISSUE TITLE
$this->authorizer->getAuthCodeRequestParams() crashes

### ISSUE THREAD

**Issue by ChrisTerBeke** [lucadegasperi/oauth2-server-laravel#286]
Don't know exactly what's happening, but this command seems to crash my server over and over again.

**Comment by lucadegasperi** [comment]
You mean 500 errors or something even worse? Have some logs to share?

**Comment by ChrisTerBeke** [comment]
No error messages, the page just won't load and then fries my local dev server.

**Comment by lucadegasperi** [comment]
That's very weird but without any clue of what's happening I can't help you. There must be a log inside the laravel app.

**Comment by teamsoo** [comment]
@ChrisTerBeke  You might want to provide us with some Nginx log or apache log.

**Comment by ChrisTerBeke** [comment]
I'm running Laravel on a Google App Engine environment, maybe that might be a problem? Did work before though, but suddenly stopped working. I'll try a complete re-install of the package and report back to you guys

**Comment by ChrisTerBeke** [comment]
Solved it. Google Cloud Storage suddenly decided to block my application so my css files couldn't be loaded anymore blocking the page load and apparently pushing up the server load. Thanks for your time anyway :)
