### ISSUE TITLE
Invalid access token throws a 500 instead of a 401

### ISSUE THREAD

**Issue by geofflancaster** [lucadegasperi/oauth2-server-laravel#287]
When I use an expired access token, the response is a 500 status code with the body of... 

"{
    "error": "access_denied",
    "error_description": "The resource owner or authorization server denied the request."
}"

How can I get it to return a 401?

**Comment by geofflancaster** [comment]
This was due to the app's error handler which had been modified. I left the modified one in place and created a new one to catch only child exceptions of OAuthException. All works well.

**Comment by refear99** [comment]
@geofflancaster I have the same issue, Can you tell me some detail help me to fix this.

**Comment by geofflancaster** [comment]
@refear99 sorry for the delayed response. Missed this notification for some reason.

I added this to my global.php file

```php

App::error(function(\League\OAuth2\Server\Exception\OAuthException $exception) {
  if($exception->httpStatusCode == 500) {
    Log::error($exception);
  }
});
```
