### ISSUE TITLE
Right approach to implement log in and log out

### ISSUE THREAD

**Issue by adarshchacko** [lucadegasperi/oauth2-server-laravel#290]
I am using the following route to log-in to my website but I am not sure whether this is the correct approach.
```
Route::post('login', function() {
    if(Input::get('grant_type') === "password"){
        return Response::json(Authorizer::issueAccessToken());
    }
});
```
The access_token generated by the above-mentioned code is stored in a Session variable.

**Need advise regarding the following:**
1. Is it advisable to store the access_token as session to keep track of the logged in user.
2. Once logged in, how do I incorporate 'Log Out' ? Is it advisable to delete the record related to the  logged-in access_token from the table named *oauth_access_tokens*?

**Comment by lucadegasperi** [comment]
Sorry to say it is not the right way of doing it. Here's why:
The authorization server (except for the auth code exchange endpoint) is stateless. This means it should not read session or cookie data. Everything it needs to work correctly needs to be passed via HTTP. Your client application will do an http request to the access token endpoint with the required parameters for the grant type and the application will respond with an access token. Then it's the client application responsibility to store the access token somewhere secure, not the authorization server.
To delete tokens there's a draft in the works by the ietf but it is not currently supported by this package or the underlying one.

**Comment by adarshchacko** [comment]
Ok. So how should I go about implementing log-in and log-out? What do you suggest ?

**Comment by lucadegasperi** [comment]
Describe me your architecture (or what you have in mind) and see what we can do.

**Comment by adarshchacko** [comment]
I have a database which maintains the email id and password of users and I use this as credentials to get an access_token using the password grant_type.
What I thought was to store the access_token in a session variable in order to log-in a user. When he wants to log out I would get rid of the contents of the session variable.
But I guess this is not advisable. So I thought to put this up.

**Comment by lucadegasperi** [comment]
If this is your use case then just use the auth provided inside Laravel. No need need for OAuth (auth in this case stands for authorization not authentication). You would need something like OAuth if you have apps (clients) accessing and consuming an API on the user's behalf.

**Comment by adarshchacko** [comment]
Yes I do intended to implement that too but that it will have the grant_type 'client_credentials'. 

In this case a user will register a device and the device will login using the grant_type as mentioned above. After which the device is expected to send some data (that is after it logs in).

So in that case how do I go about implementing it.(i.e. login and logout)

**Comment by lucadegasperi** [comment]
The grant type you are going to use depends on who owns the data and how much you trust the client. Anyways, for a simple login just handle it as usual, no need for this package. When you move forward add this package to the mix. To log out simply delete the token from the client. Then run a cron on the server to periodically delete the expired access tokens.

**Comment by adarshchacko** [comment]
Don't get me wrong. Actually it was a mistake on my part and I am sorry for that. I should have mentioned about the device part in the beginning. I have kept a separate route to login a device and I am taking data from the device and storing it into a database table. 

I guess as you mentioned and I hope I got it right; for logging in I should store the acces_token into a table or store it into session variable and delete it when the device logs out. Correct me if I am wrong.

**Comment by lucadegasperi** [comment]
To authenticate your device use this package with the appropriate grant type then store the access token inside the device. To log out, just delete the access token from the device, nothing more is needed.

**Comment by adarshchacko** [comment]
Thank you so much Luca. Greatly appreciate the help. Just needed one more.
I am using  `Response::json(Authorizer::issueAccessToken()->getData()` to get the access_token. This works fine when the email id and password combination are correct. 
The problem starts when an incorrect combination is entered, where I get an error, which is expected. I wanted to capture this error message  but I am not sure how to do so because getData() is not able to do the trick in this regard.

**Comment by lucadegasperi** [comment]
This package provides you with an error handler built-in that spits out the correct json payload when an error occurs. Not sure why you want to keep the access token instead of directly returning it to the client in case of success. Since it is not the intended way for an oauth2 server to work.

**Comment by adarshchacko** [comment]
Will definitely keep that in mind. Thank you so much Luca.
