### ISSUE TITLE
Laravel 5 Install Not Working

### ISSUE THREAD

**Issue by raherediag** [lucadegasperi/oauth2-server-laravel#293]
After following these directions: https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Installation

I get the following error when trying to run: php artisan config:publish lucadegasperi/oauth2-server-laravel

"exception 'ReflectionException' with message 'Class Illuminate\Contracts\Exception\Handler does not exist' in \framework\src\Illuminate\Container\Container.php:595"

Also, When running 'php artisan list'. I don't see the command config:publish listed.

**Comment by lucadegasperi** [comment]
Are you on laravel 5? which version of this package have you downloaded?

**Comment by raherediag** [comment]
This is what i've got:
		"laravel/framework": "5.0.x-dev",                
                "lucadegasperi/oauth2-server-laravel": "4.0.x-dev"

**Comment by lucadegasperi** [comment]
This package is not yet compatible with Laravel 5 (but it will be soon) That's why it doesn't work.

**Comment by raherediag** [comment]
Thanks for your early reply

**Comment by pavankumar0440** [comment]
When can we expect this package is compatible with Laravel 5 version. Because im currently working on this package and thinking to move to L5

**Comment by lucadegasperi** [comment]
Probably by the end of the month (but i'm already working on it)

**Comment by pavankumar0440** [comment]
Thanks for the reply.

**Comment by lucadegasperi** [comment]
The master branch now works with L5, although some bugs might still need to be discovered.
