### ISSUE TITLE
Migration command don't work

### ISSUE THREAD

**Issue by StarpTech** [lucadegasperi/oauth2-server-laravel#295]
The migration command `php artisan oauth2-server:migrations` failed.

It seems that all is fine but no tables were created.

**Configuration:**
*Connection:* mysql

`
vagrant@vagrant-ubuntu-trusty-64:/vagrant/laravel$ php artisan oauth2-server:mig                                                                    rations
Published: 2015_02_05_123443_create_oauth_scopes_table.php
Published: 2015_02_05_123444_create_oauth_grants_table.php
Published: 2015_02_05_123445_create_oauth_grant_scopes_table.php
Published: 2015_02_05_123446_create_oauth_clients_table.php
Published: 2015_02_05_123447_create_oauth_client_endpoints_table.php
Published: 2015_02_05_123448_create_oauth_client_scopes_table.php
Published: 2015_02_05_123449_create_oauth_client_grants_table.php
Published: 2015_02_05_123450_create_oauth_sessions_table.php
Published: 2015_02_05_123451_create_oauth_session_scopes_table.php
Published: 2015_02_05_123452_create_oauth_auth_codes_table.php
Published: 2015_02_05_123453_create_oauth_auth_code_scopes_table.php
Published: 2015_02_05_123454_create_oauth_access_tokens_table.php
Published: 2015_02_05_123455_create_oauth_access_token_scopes_table.php
Published: 2015_02_05_123456_create_oauth_refresh_tokens_table.php
Generating optimized class loader
Running for workbench [roccomedia/neo4j-laravel]...
`

but only after migrate the package manually all tables were there. 
`php artisan migrate --package=vendor/package`

**Comment by lucadegasperi** [comment]
Using Laravel 5?

**Comment by StarpTech** [comment]
No I use Laravel 4.2

**Comment by lucadegasperi** [comment]
The ```php artisan oauth2-server:migrations``` command only published the migrations with the correct timestamps to your app's migration folder. Then you have to run the migrations. That's why.

**Comment by StarpTech** [comment]
Thanks, I don't know. This worflow is new for me.

**Comment by lucadegasperi** [comment]
No worries, it confused me at first as well since I don't use this command that often.

**Comment by dsantiago** [comment]
Luca you could update the doc for tables with this second command. I've got some trouble too installing the tables...  Anyway thx for the grat job !!!

Oh, the command:

php artisan migrate --package=lucadegasperi/oauth2-server-laravel
