### ISSUE TITLE
Laravel 5: oauth before filter

### ISSUE THREAD

**Issue by francorisso** [lucadegasperi/oauth2-server-laravel#296]
Hey guys, I'm trying to configure this on Laravel 5, and the before filter is not there anymore, so when I want to put oauth as before, it gives me an 500 error with "Not exists class". 
I've tried to fix this, and I think now I also need to place oauth in the routeMiddleware array in the app/Http/Kerner.php file, and it will look like this:

protected $routeMiddleware = [
		'auth' => 'App\Http\Middleware\Authenticate',
		'auth.basic' => 'Illuminate\Auth\Middleware\AuthenticateWithBasicAuth',
		'guest' => 'App\Http\Middleware\RedirectIfAuthenticated',
		'csrf' => 'Test\Http\Middleware\VerifyCsrfToken',
		'oauth' => 'LucaDegasperi\OAuth2Server\Middleware\OAuthExceptionHandlerMiddleware',
	];

Is this ok? Is not clear in the documentation. Thanks.

**Comment by lucadegasperi** [comment]
Hey Franco, the filters are still there and work like they did in Laravel 4.
```php
Route::get('/protected', ['before' => 'oauth', 'uses' => 'YourController@ProtectedMethod']);
```
The only changes are described in the Wiki. https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Laravel-5-Installation

**Comment by francorisso** [comment]
Right! Thanks a lot!

On Sun, Feb 8, 2015 at 1:50 PM, Luca Degasperi <notifications@github.com>
wrote:

> Hey Franco, the filters are still there and work like they did in Laravel
> 4.
>
> Route::get('/protected', ['before' => 'oauth', 'uses' => 'YourController@ProtectedMethod']);
>
> The only changes are described in the Wiki.
> https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Laravel-5-Installation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucadegasperi/oauth2-server-laravel/issues/296#issuecomment-73419117>
> .
>



-- 
Franco Risso.
