### ISSUE TITLE
Updating from 1.* to 4.* - migrations

### ISSUE THREAD

**Issue by HipsterJazzbo** [lucadegasperi/oauth2-server-laravel#299]
I've been working on this for a while now and am reasonably stumped as to the best way to do this.

The schema is obviously different, is there a recommended way to update from 1.* to 4.* without losing clients/scopes/etc from production databases?

**Comment by lucadegasperi** [comment]
Hello, 
Unfortunately, no guide has been written for an update from 1.x to 3.x or 4.x you most likely would need to roll your own migration system. The most important thing is that you don't loose the clients table and the relationships with the other tables (grants, scopes)

**Comment by HipsterJazzbo** [comment]
Yeah. It's proving to be quite the herculean endeavour. Oh well, thanks!
