### ISSUE TITLE
Checking user data in filters

### ISSUE THREAD

**Issue by jmazurpl** [lucadegasperi/oauth2-server-laravel#300]
Hi,

I'm wrting API secured by oAuth. My users have their roles. I want to check their roles with filter:

    Route::filter('admin', function()
    {
        if (!(Auth::check() && Auth::user()->isInRole(Roles::Administrator)))
        {
            return Response::json(null, 403);
        }
    });

But Auth::check() returns false - its becouse route is secured with oAuth. How can I get user making the current request in filter?

**Comment by teamsoo** [comment]
With OAuth, you can't check the logged in user by Auth::check() anymore.

You can get logged in **user id** by using this
```php
$user_id = Authorizer::getResourceOwnerId();
```
