### ISSUE TITLE
checking if user has an access token

### ISSUE THREAD

**Issue by navidos86** [lucadegasperi/oauth2-server-laravel#301]
Hi there everyone,

first of all i want to say that this is a great package, it makes things soo easy to implement and lets u understand oauth a bit altleast. Great Job!

I've the following issue i come cross with. im busy with making an Api with Laravel 5 and the goal of this API is to communicate with an IOS. 

What i want to achive is to check with the oauth access process if the user already has an Access token ,"and if the the token is still valid. If so well let the user authorise himself, otherwise if his token is expired refresh his token and sign him in. 

The current solution is that i query the user and check if the users id the same as the owner_id.

Is it possible to do this in an more elegant way?

Thank u very much!

**Comment by lucadegasperi** [comment]
Don't worry if the user already has an access token, If it is the first time they open the app, just request a new access token. If the iOS device already has an access token saved, check its expiration date and if its expired require a new one (or use the refresh_token gran type) to exchange the refresh token which comes with the access token for a new pair of access token and refresh token.

**Comment by navidos86** [comment]
but in this case a user can have multiple sessions, or should i check it as you said in the front end and if he already has one dont request for other one.

**Comment by lucadegasperi** [comment]
Multiple sessions = multiple access tokens. This way the user could eventually revoke the access to a single machine.

**Comment by navidos86** [comment]
So i don't even need to check on the device if the access token is from that user just check if there is one and if it is expired or not, did i understand that well? Thank u btw for the very fast reply.

**Comment by lucadegasperi** [comment]
Yes, the access token on the device is already associated with a user. You just need to query the API server for the user's info.

**Comment by navidos86** [comment]
Great explanation, thank u soo much!
