### ISSUE TITLE
Laravel 5  oauth2 v4 \"grant_type\" can't be found

### ISSUE THREAD

**Issue by SimonWayne** [lucadegasperi/oauth2-server-laravel#302]
Hello,

my POST output:

{
 "error": "invalid_request",
 "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"grant_type\" parameter."
}

My POST request:

http://api.my-website.com/oauth/access_token

x-www-form-urlencoded

grant_type = password
 client_id = ******
 client_secret = ******
email =*****
password = ******

All Grant Type in my Config files are available.
![error](https://cloud.githubusercontent.com/assets/8533856/6150916/7abfb772-b212-11e4-9a69-2661fc595d6e.jpg)

Thanks ;)

**Comment by lucadegasperi** [comment]
Have you tried with form-data? I'm using rested for my endpoint tests and il works just fine.

**Comment by SimonWayne** [comment]
Hello

yes i tried with form-data but the same issue.
i request an access token, no endpoint.

**Comment by lucadegasperi** [comment]
Weird, when the request doesn't go trough is usually a problem with the apache or nginx server. This guy might have the same issue as you do. Please mind that L5 support is still in the work it might be due to the request object not being passed correctly to the server.

**Comment by Gittinhub** [comment]
Ok. Did you completely disable your firewall????
Are you on a Linux or Windows? 
If windows, go to the control panel and shut it off completely!
If Linux, perform this commands on bash:
root> service iptables stop
root> service firewalld stop
Firewalls mess up everything, and guessing you are on a developing server, not production server, please, turn it off first.
Regards.

**Comment by SimonWayne** [comment]
Hello our Linux root Server works perfectly well oauth 2 with laravel 4 works too but not with laravel 5 
My request can't found any Grant_types

**Comment by Gittinhub** [comment]
Ok, but what i want you to have in mind is that an error message may not reflect reality because of a third software. An error message could not saying the truth, got? 
Please, even it working on L4, i insist to try with iptables and firewalld stopped as i described before.
Then, according to the picture you added before, you have a "bad request", not a grant-type not found.
Bad requests are caused by NOT following the protocol. You can find more about the protocol here: http://tools.ietf.org/html/rfc6749#section-4.4.1 
Note that if you are adding the right vars, you should setup a BASIC http authentication. This can be what you are missing.

**Comment by lucadegasperi** [comment]
I've just run a couple of tests with my local L5 install and the password grant type and there are no problems whatsoever. The issue may lay somewhere else.

**Comment by SimonWayne** [comment]
Ahh i can't access to the POST data. :/

**Comment by Gittinhub** [comment]
That's why it wasn't working before and you had to put data on the headers. 
You can NOT access the POST data because somewhere you are being tricked.
My best advice is start from scratch. 
Are you adding oauth to an existing project?

**Comment by JSila** [comment]
I changed method name from postAccessToken to getAccessToken (so you acquire access token via GET rather then POST) and it returned me a token.

**Comment by lucadegasperi** [comment]
don't EVER do THAT. The OAuth 2 Spec says you have to run a POST request in order to get an access token.

**Comment by crisu83** [comment]
The only thing I don't get is that we have to use form-data instead of json, that's just dump.
