### ISSUE TITLE
PHP Fatal error:  Class 'LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider' not found

### ISSUE THREAD

**Issue by koray-mobven** [lucadegasperi/oauth2-server-laravel#303]
Hello,

I know Laravel 5 is not supported officially by you yet but i faced an fatal error on last step. I installed it by looking Doc Laravel 5 Installation page. Made dump autoload and run "php artisan vendor:publish" and it gived "PHP Fatal error:  Class 'LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider' not found in /Applications/MAMP/htdocs/project/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 150
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider' not found' in /Applications/MAMP/htdocs/project/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:150
Stack trace:
#0 /Applications/MAMP/htdocs/project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}"

How can i fix that?

Thanks.

**Comment by lucadegasperi** [comment]
Have you added the ```LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider``` class into the ```config/app.php``` provider's array?

**Comment by koray-mobven** [comment]
Yes.

**Comment by lucadegasperi** [comment]
Weird, my local L5 install doesn't give any issues. Mind posting your $providers array?

**Comment by koray-mobven** [comment]
I tried another installation and it's ok now.

Btw, you say "If installation fails set "minimum-stability": "dev" in your composer.json file." but if i add this, composer update command add all packages' dev branch. I used --no-dev. Is this using correct?

**Comment by lucadegasperi** [comment]
You could set the @dev flag on a specific package in order to prevent the use of the minimum-stability flag.
