### ISSUE TITLE
cant create a resource with POST, asking for access_token

### ISSUE THREAD

**Issue by navidos86** [lucadegasperi/oauth2-server-laravel#305]
Hi there, 

Im having a problem for creating a resource, when i make a POST request to my route. 
My route looks like: 

Route::group(array('prefix' => 'api/v1', 'before' => 'oauth'), function()
{
    //Media Route
    Route::resource('media', 'PostController',['except' => ['create', 'edit']]);
});

when i post the resource it says i should provide an valid access token, but i already doing that. This is the resource uri.

appname.dev/api/v1/media/?access_token=ksfdkfjkfsj

even with: 
appname.dev/api/v1/media?access_token=ksfdkfjkfsj 

it doesn't work it throws an error with json response 

"error": "invalid_request",
    "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"access token\" parameter."

What am i doing wrong? 

Thx in advance

**Comment by Gittinhub** [comment]
For sure the request is invalid, you are not following the oauth protocol.
Please, take a look here: http://tools.ietf.org/html/rfc6749
What you are doing wrong is that you are POSTING and expecting it to use the GET URL parameter.
When you post it, the values should be posted, so access_token should be posted as the protocol describes.
The GET URL it will understand as the resorce (the page/the address) value, not many values.
Check the proto page i metion before and you will see.
Regards.

**Comment by navidos86** [comment]
i don't understand your point... i'm making a post request with parameters but i didn't post those in this item. When im posting the user that post this resource needs a valid access_token and i have a valid access token. 

but for you the parameters are: user id, status of the post and description. In raw format you can see it as: description=hello &status=public.

**Comment by navidos86** [comment]
I solved the issue by myself and put the access token in de header. Tnx.

**Comment by Gittinhub** [comment]
When you use GET, the parameters are IN/Concateneted IN the URL like -> description=hello &status=public.  
When you use POST you cannot PASS values IN/CONCATENETED IN the URL, the values are passed in the post and the URL just point WHERE you are POSTING the values, got?
By putting the access_token in the headers worked cause the protocol checks the headers AND the POST values IF you have a valid access_token. 
There is also a configuration option to check the access token ONLY in the headers here: https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Configuration-Options#http_headers_only
