### ISSUE TITLE
401 Unauthorized - Laravel 5 - Grant_Type=password

### ISSUE THREAD

**Issue by Gittinhub** [lucadegasperi/oauth2-server-laravel#306]
Ok.
First things first...
Is the grant_type=password already working on laravel 5 ????
I want to do the first authorization, the website LOGIN first, not a third part login.
So, i added to /config/oauth2.php , a "return 100", returning alwas TRUE to avoid any wrong checks anyway as described below:
    'grant_types' => [
        'password' => [
            'class'            => 'League\OAuth2\Server\Grant\PasswordGrant',
            'access_token_ttl' => 604800,
            // the code to run in order to verify the user's identity
            'callback'         => function($username, $password){
return 100;
            }
        ],
    ],
I added a dummy row on oauth_clients table BUT this has nothing to deal with this first part authorization, or it does? 
Again, i need to log the user in MY website first, the login, not authorize a 3rd application. Can be done without oauth, just using oauth to do it after.
It's a linux apache server.
What could be wrong?

**Comment by lucadegasperi** [comment]
Don't use oauth if you just need to log a user in. Use the provided Auth mechanism of L5.

**Comment by Gittinhub** [comment]
But how about the REST api requests from mobile apps? 
Today we don't only develop for web, but for a bunch of environments.
May i ask why not? It's the simplest. If it were not the best(safe&fast), wouldn't be widely used. 
But in my opinion not safe.
Please, why not? 
Could you also please answer my previous post. This will clarify lots of things for me. I need those answers and i waiting for them.
Thanks.

**Comment by lucadegasperi** [comment]
Yes, in that case use OAuth with the password grant type, but for the everyday login, you don't need it. The two can coexist.

**Comment by Gittinhub** [comment]
Thanks.
Is the grant_type=password already working on laravel 5 ????
As i did in the sample code i posted in first post it should be working, isn't? I returned always true to avoid any check errors as you can see in the code.

**Comment by lucadegasperi** [comment]
It should not return always true, that function is there to validate if the provided credentials are valid.
Here's an example of how it should look like
```php

        'password' => [
            'class'            => 'League\OAuth2\Server\Grant\PasswordGrant',
            'access_token_ttl' => 604800,

            // the code to run in order to verify the user's identity
            'callback'         => function ($username, $password) {

                $credentials = [
                    'email'    => $username,
                    'password' => $password,
                ];

                if (Auth::once($credentials)) {
                    return Auth::user()->id;
                }

                return false;
            }
        ],

```

**Comment by Gittinhub** [comment]
Thanks a lot.
That's what i was trying to figure out. By returning always true, i was trying to determine IF the authorization was beeing made in that part of the code or somewhere else. 
So, the problem is NOT there. I will keep trying to fix this...

**Comment by Gittinhub** [comment]
I am now guessing that the server somehow only accept httpS querys.
How can i simulate httpSs? 
How did that guy simulate posts like in this picture?
https://cloud.githubusercontent.com/assets/8533856/6150916/7abfb772-b212-11e4-9a69-2661fc595d6e.jpg

**Comment by lucadegasperi** [comment]
On production, you need to have HTTPS, on development HTTP is fine.
The guy is using a software called Postman https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm
If you have a mac you can find Rested on the App Store which is what I use.

**Comment by Dolphindevlopers** [comment]
@lucadegasperi i've chosen password_grant for grant type. i wanted to ask that do i need to add the refresh_token grant for refreshing the token along with the password grant ?

**Comment by lucadegasperi** [comment]
You don't have to use the refresh token grant if you don't want to. Problem is that when the access token expires, you have to ask the user for its username and password again, whereas with the password grant + the refresh token grant, when the access token expires you exchange the refresh token for a new pair.

**Comment by Dolphindevlopers** [comment]
@lucadegasperi  hmm, so i can i add multiple grants in the config?

**Comment by lucadegasperi** [comment]
yes you can.

**Comment by Dolphindevlopers** [comment]
@lucadegasperi  thanx for helping.
