### ISSUE TITLE
Client authentication failed 

### ISSUE THREAD

**Issue by Naranbat1123** [lucadegasperi/oauth2-server-laravel#307]
Hello. I need little help. i am trying to get an authorization from the server

My Route

    Route::get('oauth/authorize', ['before' => 'check-authorization-params|auth', function() {

          View::make('oauth/authorization-form', Authorizer::getAuthCodeRequestParams());

    }]);

Request

    http://www.example.com/oauth/authorize?
    client_id=54e1986b8b792
    &client_secret=3411
    &redirect_uri=www.example.com
    &access_token=RpsuQMfGtf2OHjy4JrlWVCiBoQhVwIUTsAqbaVzC

    result => {"error":"invalid_client","error_description":"Client authentication failed."}

**Comment by lucadegasperi** [comment]
why are you providing the access token in the request? Also, you need to add the redirect uri to the oauth_clients_endpoint table and associate it with the client. This is to prevent malicious requests to redirect somewhere else.

**Comment by Naranbat1123** [comment]
http://www.example.com/oauth/authorize?
    client_id=54e1986b8b792
    &redirect_uri=www.example.com

now way authentication failed
result => {"error":"invalid_client","error_description":"Client authentication failed."}

i`m removed 'check-authorization-params|auth' check
result => View [oauth/authorization-form] not found.

**Comment by lucadegasperi** [comment]
Those errors only mean you have not passed the correct client credentials.

And the oauth/authorization-form view is up to you to implement.

**Comment by Naranbat1123** [comment]
http://www.example.com/oauth/authorize?client_id=1&redirect_uri=www.example.com&response_type=code&&scope=scope1


 Session::get('authorize-params'); 
not work? no params ??

**Comment by Naranbat1123** [comment]
My Auth Code not work 
    http://www.example.com/oauth/authorize?
    response_type=token&
    client_id=54e1986b8b792&
    redirect_uri=http://localhost:9000



    Route::get('oauth/authorize', ['before' => 'check-authorization-params|auth', function() {
	    die('123');
        View::make('oauth/authorization-form', Authorizer::getAuthCodeRequestParams());
    }]);
result => {
error: "invalid_client",
error_description: "Client authentication failed."
}

**Comment by chrisfranko** [comment]
hey luca, it would be cool if there were some standard views that came with it as examples. :)

**Comment by FoxxMD** [comment]
:+1: @chrisfranko

**Comment by Batalha** [comment]
Tambem estou com o mesmo problema.....
{
    "error": "invalid_client",
    "error_description": "Client authentication failed."
}

**Comment by fontenele** [comment]
I used just `'before' => 'oauth'`

Here a skew working [larange](https://github.com/fontenele/larange)
