### ISSUE TITLE
L4 oauth2password grant error

### ISSUE THREAD

**Issue by ukenpachi** [lucadegasperi/oauth2-server-laravel#308]
Laravel: version 4.2.16
oauth2-server-laravel: version 3.0.2

Hi, I am trying to implement oauth2 authentication to my laravel site. I have fully the repo guide and trying the example for password grant when I encouter the error below.

My route

Route::post('oauth/access_token', function() {
    return Response::json(Authorizer::issueAccessToken());
});

my form

{{ Form::open(array('url' => '/oauth/access_token')) }}
{{ Form::email('email') }}
{{ Form::password('password') }}
{{ Form::submit('Click Me!') }}
{{ Form::close() }}

the error

{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"grant_type\" parameter."}

oauth2.php

 'grant_types' => [
         'password' => [
             'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
             'callback' => function($username, $password) {
                if(Auth::validate(array(
                    'email' => $username,
                    'password' => $password,
                ))) {
                $user = \App\User::where('email', $username)->first();
                    return $user->id;
               } else {
                  return false;
               }
            },
            'access_token_ttl' => 3600
        ],
    ],

App before filter

App::before(function($request, $response)
{
  header('Access-Control-Allow-Origin: *');
  header('Access-Control-Allow-Methods: GET, POST, DELETE, OPTIONS');
  header('Access-Control-Allow-Headers: Origin, Content-Type, Accept, Authorization, X-Request-With');
  header('Access-Control-Allow-Credentials: true');
  header('Content-Type', 'application/javascript');
  // Pre-flight request handling, this is used for AJAX
  if($request->getRealMethod() == 'OPTIONS')
  {
      return Response::json(array('Method' => $request->getRealMethod()), 200);
  }
});
    

I tried dd(Authorizer:: getIssuer()->getRequest()->get('grant_type')); and this shown null

Where I'm I going wrong?

**Comment by lucadegasperi** [comment]
Why are you submitting a form to the access token endpoint? What are you trying to achieve? Clearly the request for an access token always needs to have the client secret and client id and the grant type you are trying to use plus a series of parameters varying from grant type to grant type.

**Comment by ukenpachi** [comment]
Lucadegasperi thanks so much for the quick reply. What I am trying to achieve to assign a token to the user when the Login in. I haven't use oauth2 before but I have read a few articles about it.  In the oauth_clients table I have added a few test data. In real live usability will I store the id and secret on the client device? and pass it when the user submit the form?

**Comment by lucadegasperi** [comment]
The grant type you chose to use depends on how much you trust the client (the app) with the user's credentials. If it's a first party client (one you make) then the password grant type is the recommended one. In real life each client would have its own credential stored inside and passes them to the authorization server (together with the user's credential) in exchange for an access token. The request will eventually look like this:
```
POST https://example.com/oauth/access_token

grant_type=password
client_id=yourclientid
client_secret=yourclientsecret
username=user@email.com
password=userspassword
```

**Comment by ukenpachi** [comment]
Thanks again. In terms of how I am setting up my oauth2.php what do you think? Also in $user = \App\User::where('email',$username)->first(); I am getting Class 'App\User' not found and I have a User model

**Comment by lucadegasperi** [comment]
you can do Auth::once instead of Auth::validate and then do Auth::user()->id

**Comment by ukenpachi** [comment]
Lucadegasperi thanks.

I am using phonegap to interact with my application. 

(1)So when my user register do  I automatically create a cliend_id and client_secret and store it in the oauth_clients table? I know I need to store the access token somewhere, so where on the user device do you suggest I do this please? Also do I store that token in the database as well?

(2)
 Also if a client login from a different device and the device doesn't have an access token do I create a new one or if the access_token created before is stored in the database do i retrieve that for them?

**Comment by lucadegasperi** [comment]
(1) You got a couple of things wrong, a client in the oauth world is an app, what you think is a client, is a user. So you client could be the iOS app you're developing. You can store the access token on the device 's local storage (since it's a phone gap app)

(2) You get a new access token for every device

**Comment by ukenpachi** [comment]
Lucadegasperi thanks again. Just to clear things up do I hard code the client_id and client_secret in some javascript variables, if this is the case then wouldn't this be publicly known?
 If that understand is wrong, then how do you get the client_id and client_secret to pass it when requesting a token?

 Thank you

**Comment by ukenpachi** [comment]
Lucadegasperi thanks again. 
When the user register using my application I give them a token now I want to do a few things which I can't find the documentations which are.

(1) After I have giving a token to the client upon registering. How do I check that the token used by the client is valid? How do you suggest doing this using a filter.

(1a) You advice: Do you think I should reassign a new token even though the one provided by the client  is invalid but their username and password is valid?

(2) In the case of login in again, when the user login but doesnt have a token due to them using a different device. how do I incorporate this in the filter (1)?

By adding this example code shown here http://git.io/AfGc (refresh token) does that automatically refresh the token if it has expired?

Thanks again for your time

**Comment by lucadegasperi** [comment]
Sorry to say you are confusing some definitions and I don't want to confuse you even further by answering your question in a way that you understand improperly.
What you can do is try to tell me what are you trying to achieve and what are the parties involved, So that I can route you to the right solution.

**Comment by ukenpachi** [comment]
Lucadegasperi sorry for  mixing the terminologies in this case.

In my IOS and android app build by me and a laravel site also build build by me. So I owe both client and server provide. 
THE PROCESS: When a user clicks on register a pop just like facebook and twitter authentication does but this one is for my own site. The user then register using ajax I then post those details to my laravel site.

Here is where I need your suggestion and advice please. Do you think I should assign them an access token when they register or when the Login?


 When user then Login, I then pick the access token and sent it via ajax along with the username and password, if the token is valid, the user can process to doing their shopping etc. 

The access token will be posted with every request that has things to do with server side. 

(1) How do I check that the access token which was posted via ajax is a valid token? 

(I will ideally like to do this check in a filter that way I can just wrapper it with the routes that has things to do with server side.

(2) when the user login but doesnt have a token due to them using a different device. how do I incorporate this in the filter.

I hope that explain what I am trying to do.

 Thank you

**Comment by lucadegasperi** [comment]
Okay, here is how I would plan it.
1) The Client (App) has a client_id and a client_secret
2) You exchange the client_id and client_secret for an access token using the client_credentails grant type.
3) The user clicks on register and a native form pops up.
4) You submit the form using the access token the client has.
5) If the form is valid, you use the same credentials the user provided during the registration to get an access token using the password grant type.
6) Now you have an access token to do your requests on the user's behalf.
For users who already have an account and are on a new device, you simply display the login form and then request an access token with the password grant type.

If along the access token you request a refresh token. Once the access token expires (and you know when since it comes with a timestamp) You use the refresh token grant type to request a new pair of access token + refresh token. If both fail for whatever reason you show the login form again.

On the server side this library will provide you with a filter (oauth) that will parse the incoming api request and verify if everything is ok and if everything is indeed ok, You can use the ```Authorizer::getResourceOwnerType()``` and ```Authorizer::getResourceOwnerId()``` to get the user or client who is doing the request.

**Comment by ukenpachi** [comment]
Regards number 2) So at what point do I exchange the token when the app has been launch? Because I will need to sent an ajax get request to get the token. 

You said "On the server side this library will provide you with a filter (oauth)" looking at my filter I can't see anything the library has added which checks if a token is valid or not or do I have to add a Model for the oauth_access_tokens table?

Thanks you

**Comment by lucadegasperi** [comment]
Yes when the app launches if you don't have an access token for your client, you exchange its credentials for an access token (this is tied to the client and has nothing to do with the user) You'll use this token only to send the registration form. When the user enters username and password, you'll get an access token that is tied both to the client and the user.

**Comment by ukenpachi** [comment]
I found something. If i set a tokens to expiry to 30 days I get "expires_in":2630000" in the array. I then  storage in the device LocalStorage, one issue occurs, which is they is no way of checking if this token has expiry or not in other for me to use ajax to requests for a new token because the localStorage doesn't have the end time. 

So I looked in the oauth_access_tokens table and i see the expire_time columns which the name suggest its the expire period, so for that expires_in the expire_time is 1426968383 and converting it from seconds to days gives me  about 16516 days. 

What I want to know is how do you check what seconds or days the token expiry? so I can follow this method in jquery. 

Thanks

**Comment by lucadegasperi** [comment]
The date stored in the database is the unix time when it's going to expire, It refers to the seconds passed since Jan 01 1970. And so does the expires_in you get back with the access token.

**Comment by ukenpachi** [comment]
So when I get the "expire_time" from the oauth_access_tokens table i then convert it and the expires_in time to check if the date matches? What I am trying to do is depend on the device time because it could be wrong.

**Comment by lucadegasperi** [comment]
What you get in the JSON payload together with the access token is already a time difference in seconds from Jan 01 1970 (unix timestamp). The unix timestamp is timezone independent. When you require a unix timestamp from the device you can be sure is right. Then by doing a simple comparison you can know whether to require a new access token or not.

**Comment by ukenpachi** [comment]
Looks like you always have to set a token timer with access_token_ttl, I have tried setting it to "none", keeps coming up with "Undefined index: access_token_ttl" and i want my access token to be forever. 

Also the "limit_clients_to_grants" how does this work? How does it know the client? Do you have to pass in something of value to tell the library that this is the client?

**Comment by lucadegasperi** [comment]
1) Don't make your access tokens last forever, it's a security risk. Use access token in combination with refresh token to get new ones without the user having to enter its username and password.

2) ```limit_clients_to_grants``` works together with the ```oauth_grants``` and ```oauth_client_grants``` table. Here you can specify which clients are allowed to use which grant type. This allows for a more granular control of first-party and third-party clients and more-secure vs less secure clients.

2a) Every time you do an access token request, you pass the client_id and client_secret, this gets validated against the allowed grants for that client and the request is accepted or denied.

3) You check for an access token only on the resource server route (aka the API), not the login or any other "HTML" route.

4) An access token is owned by the resource owner (normally the user) and by the client (the app) who's requesting it. Sometimes the resource owner and the client can be the the same. To this exempt you can explicitly allow your api routes to users only by using the filter like this ```oauth:user```. Plus the Authorizer class offers you a couple of methods like: getResourceOwnerType and getResourceOwnerId and getClientId to help you out.

5) This should be done by you. Find each session the user has associated in the DB and delete it when he changes password.

**Comment by ukenpachi** [comment]
Why the input field always have to be set to username? I want to use the email instead because i dont use username in my application. Email is just has unique has the username. Anyways I when into user model under league folder and check username to email but this doesnt do it.

**Comment by ukenpachi** [comment]
Lucadegasperi I am trying to register and login in all at once.

 'grant_types' => array(
        //Password Credential
        'password' => array(
            'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
            'access_token_ttl' => 604800, // 7 days
            'callback' => function($username, $password) {
            $credentials = array(
                'email'     => $username,
                'password'  => $password,
            );
             $valid = Auth::once($credentials);

             if (!$valid) {
                return false;
             }
              return Auth::getProvider()->retrieveByCredentials($credentials)->id;
            }
        ),

        'refresh_token' => array(
            'class' => '\League\OAuth2\Server\Grant\RefreshTokenGrant',
            'access_token_ttl' => 604800,
            'refresh_token_ttl' => 604800
        ),
    ),

///sign up

	public function appSignUp() {
		//validations

		$validator = Validator::make(Input::all(),
			array(
				'name' => 'required|max:40',
				'email' => 'required|max:50|email|unique:users', 
				'password' => 'required|min:6'
			)
		);

		if($validator->fails()) {
			return 'false';
		} else {
			$name 	= Input::get('name');
			$email 		= Input::get('email');
			$password 	= Input::get('password');
			

			//create an account
			$user = User::create(array(
				'name' 		=> $name,
				'email' 	=> $email,
				'password' 	=> Hash::make($password),
				'active' 	=> 1,
				'group_id' 	=> 1
			));

			if($user) {
				//return access token
				return Response::json(Authorizer::issueAccessToken());
			} else {
				// return false
				return false;
			}
		}

		return false;
	}


this fails to register an access token

**Comment by ukenpachi** [comment]
I am not using Auth Code Grant because the app is my own app.

**Comment by lucadegasperi** [comment]
You are completely missing the point of oauth and how to use it. Please refer to the documentation here: https://tools.ietf.org/html/draft-ietf-oauth-v2-31
It's a bit useless to try and solve problems which shouldn't be there in the first place

**Comment by ukenpachi** [comment]
I read some of those and got a much more clear idea. In terms of your library. It looks like by default this looks at the username field in the database. Is they a way I can change this to look at the email field instead or without having to go into vendor folder to do so because I am testing on via servers and its will be abit annoying to do this in each environments because git doesn't commit the vendor folder?

**Comment by lucadegasperi** [comment]
username is what the specification recommends to use. you can pass an arbitrary string to this parameter though, it can be an email or everything else you want. The logic for checking wether the credentials are correct is up to you inside the configuration file.

**Comment by ukenpachi** [comment]
In my phone app. When a user register I want to save them to the database and also access them and access token. 

When a user login in using my app I want to assign them a token if they dont have one already.

This is what my route is set up like 
//register
Route::post('oauth/register', array(
		'as' => 'create_account',
		'uses' => 'AppController@appSignUp'
));

//login
Route::post('oauth/access_token', function() {
		return Response::json(Authorizer::issueAccessToken());
});

(1)In the appSign up method I save the users details and assign the client an access token but at the same time I want to sign them in using that access token. How will you recommend doing this either in server side or client side (app)

(2) If the user already have an existing account and then download my app at this point the client has no access_token but has an account.  When he/she login I assgn them an access token using the  "oauth/access_token" url.  (2a) what if the client already have an access token do I assign them a new one? if yes how will then assign the protected resource with this new token? 

Summary
(1) How do you give an access token and login at the same time? How will you set up the route or filter
(2) How do you give a client a token and using this token to log in, if the client already have a token how do you use this to log them in without giving them a new token.
 
Please try and be as clear and detail has you can be.  Thanks

**Comment by ukenpachi** [comment]
Last question. 

I am having to do this 
	  // Login
	     Route::post('oauth/access_token', function() {
			return Response::json(Authorizer::issueAccessToken());
		});
      //protect privileged endpoints
    	Route::group(array('before' => 'oauth'), function() {
		// user profile
    		Route::post('oauth/user/details', array(
    			'as' 	=> 'oauth_user_profile',
    			'uses' 	=>	'AppController@userProfile'
    		));
		});

which is i believe their is a better way of doing this.

When I login I get an access token.When I log out the client still has the access token. Is they a way you have suggested only giving the client an access token if it doesn't have one?  Thanks

**Comment by teamsoo** [comment]
@ukenpachi  

> When I login I get an access token.When I log out the client still has the access token. Is they a way you have suggested only giving the client an access token if it doesn't have one? Thanks

You don't need to worry about the access token because it will expire after time (depend on your setting). But if you do, you can just remove the access token from user's device (say Android App, etc.) when user log out.

Hope this is what you're asking.
Cheer

**Comment by ukenpachi** [comment]
Thanks @teamsoo
