### ISSUE TITLE
Securing API endpoints L5

### ISSUE THREAD

**Issue by sangar82** [lucadegasperi/oauth2-server-laravel#309]
Hello Luca!

How can I secure my api endpoints in Laravel 5? 

In Laravel 4, I do it:

````php
Route::group(array('prefix' => 'api', 'before'=>'oauth'), function() {
    ...
});
````

But L5 i have several errors when try to check the scope. It seems that the filter don't work well 

````php
     Call to a member function hasScope() on null
````

I tried to add to the routeMiddleware array but didn't work.
Routes.php
````php
     Route::group(array('prefix' => 'v1', 'middleware'=>'oauth'), function() {
````

Kernel.php
````php

	/**
	 * The application's route middleware.
	 *
	 * @var array
	 */
	protected $routeMiddleware = [
		'auth' => 'App\Http\Middleware\Authenticate',
		'auth.basic' => 'Illuminate\Auth\Middleware\AuthenticateWithBasicAuth',
		'guest' => 'App\Http\Middleware\RedirectIfAuthenticated',
		'csrf' => 'App\Http\Middleware\VerifyCsrfToken',
        'oauth' => 'LucaDegasperi\OAuth2Server\Middleware\OAuthExceptionHandlerMiddleware'
	]
````

**Comment by lucadegasperi** [comment]
Hello, the package in L5 works just like it does in L4.  You add the "oauth" before filter to your routes (or routes groups) and on top of that add the OAuthExceptionHandlerMiddleware to your global middleware, not the route ones.

**Comment by sangar82** [comment]
Solved! 

I forgot to add to .htaccess

````
RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
````
