### ISSUE TITLE
limit_* Config Options Don't Work in Laravel 5

### ISSUE THREAD

**Issue by mixnetworks** [lucadegasperi/oauth2-server-laravel#310]
It seems that the following configuration options don't work in Laravel 5.

limit_clients_to_grants
limit_clients_to_scopes
limit_scopes_to_grants

I believe FluentStorageServiceProvider should not be including the "oauth2-server-laravel" namespace when searching the config for the options. 

Example
LIne 67:  $limitClientsToGrants = $app['config']->get('oauth2-server-laravel::oauth2.limit_clients_to_grants');

should be 

 $limitClientsToGrants = $app['config']->get('oauth2.limit_clients_to_grants');

**Comment by lucadegasperi** [comment]
You're absolutely right, pushed a fix for this.

**Comment by mixnetworks** [comment]
Luca! Thank you very much! This package is great and I appreciate you speedy response!
