### ISSUE TITLE
Overriding default return error format?

### ISSUE THREAD

**Issue by kimsyversen** [lucadegasperi/oauth2-server-laravel#311]
Is it possible to override the returnformat of OAuth when getting access_denied error?

Default it looks like

```

{
  "error": "access_denied",
  "error_description": "The resource owner or authorization server denied the request."
}
```

Lets say I would like to change it to

```
{
  "error": [
     "description": "The resource owner or authorization server denied the request.",
     "foo": "bar"
   ]
}
```

**Comment by lucadegasperi** [comment]
Sorry to say that what you are trying to achieve is contrary to the OAuth 2 Specification. You certainly could but then your API won't be standard compliant. Is a styling difference worth the non-compliance?
Here's the section of the spec that states the parameter should be included in the root of the payload. https://tools.ietf.org/html/draft-ietf-oauth-v2-31#section-5.2

Hope this helps

**Comment by kimsyversen** [comment]
Oh, I didn't know about non-compliance. Of course should (and will) I be standard-compliant. 

Thanks for the information :)
