### ISSUE TITLE
FatalErrorException in routes.php line 52:  Class 'Authorizer' not found

### ISSUE THREAD

**Issue by avptechnocrats** [lucadegasperi/oauth2-server-laravel#312]
Hi,
Can you please help me in traoubleshooting why the class is not recognized and it shows not found in routes.php. 
I have already set all the settings required in Kernel.php and config/app.php.
I have started with Laravel 5. Here is the code written in routes.php

Route::get('oauth/access_token', function() {
return Response::json(Authorizer::issueAccessToken());
}); 

Immediate help will highly be appreciated.

Thanks.

**Comment by lucadegasperi** [comment]
In L5 you need to import with the ```use``` statement which classes you are going to use. I recommend doing this in a controller since the Aliases will be autoloaded in that case.

**Comment by avptechnocrats** [comment]
Thanks for your prompt response. I tried that too however there is another problem which you can see by going to this URL:
http://162.251.86.39:8004/oauth/access_token?grant_type=password&client_id=test_client_id&username=pksbbsr.jha@gmail.com&password=123456&redirect_uri=http://162.251.86.39:8004/

I have changed the routes to:
Route::resource('oauth/access_token', 'OAuthController@postAccessToken');

Here is the sshot of OAuthController I created by reviewing one of the tutorials:
http://www.evernote.com/shard/s486/sh/0626587f-7eff-4132-98ef-90c761abc075/46102bb95bae3ec91e80f18ed6ea8b08

Please help me as I am stuck with this .

Thanks.

**Comment by lucadegasperi** [comment]
I can't connect to your server from here. Anyway, the route call should be
```Route::post('oauth/access_token', 'OAuthController@postAccessToken');```

**Comment by avptechnocrats** [comment]
Not sure why you are unable to open my development URL. 
Moreover, I did the same and hit the URL using Firefox poster but I am still getting the error and unable to send the access token. Here is a sshot which I got when I changed the route to get()
http://www.evernote.com/shard/s486/sh/e6409da3-e45d-4f16-955c-d5a6e17da425/57977eedbbb2586c718c5034c7e7f7d1

Is there anything else not configured properly?

**Comment by lucadegasperi** [comment]
Your problem is with laravel in that case, not with this package.

**Comment by avptechnocrats** [comment]
I don't think so as other controller actions are working fine and I can access other URLs of the installation. I am having issues with oauth2. I just rewrite the route to another working controller:
Route::get('oauth/access_token', 'HomeController@postAccessToken');

I used "use LucaDegasperi\OAuth2Server\Authorizer;" in homecontroller however when I accessed the URL, it says :
Target [League\OAuth2\Server\Storage\SessionInterface] is not instantiable.

http://www.evernote.com/shard/s486/sh/32f73a7d-2090-45c3-936a-673cd7e5be4d/9d859dffe33095f47b29965853527d15

Please guide me where could be the issue so that I can trace the issue and fix it. I am new to Laravel. 

Thanks.

**Comment by lucadegasperi** [comment]
Have you added the StorageServiceProvider inside your app providers as well?

**Comment by avptechnocrats** [comment]
There are two providers added  in providers array as per the documentation:
'LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider',
		'LucaDegasperi\OAuth2Server\OAuth2ServerServiceProvider',

**Comment by lucadegasperi** [comment]
Yes, therefore is should work ok. Which version of this package and of laravel are you using?

**Comment by avptechnocrats** [comment]
I followed instructions mentioned for L5 at https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Laravel-5-Installation

**Comment by lucadegasperi** [comment]
Weird, it's only a matter of implementing it the right way i guess.

**Comment by avptechnocrats** [comment]
I am sorry, but where is the mistake and what should I do now? Please help me.

**Comment by lucadegasperi** [comment]
I have no clue, try removing the filters from the controller constructor for now, that will at least make sure the problem isn't there. but somewhere else.

**Comment by avptechnocrats** [comment]
I removed that with no luck. Is there anything big I missed out in the steps to configure oauth. I suspect that the tables related to oauth were not created automatically and hence I got tabels structures in some tutorial and created all the tables. 
I suspect that there is some step which I missed which would have created the tables automatically and do the other settings to run it properly. Below are the tables that my db has currently. Not sure if these are the correct ones.
http://www.evernote.com/shard/s486/sh/d0bff432-0be2-4011-961a-f0820198d013/f78a6f3750a0b79c4edf69e1db0a6f3a

**Comment by edyrkaj** [comment]
Hello! im using laravel 5 and i want to use OAuth2.0 to protect my API service.
I make curl call 

[First Call]
$ curl -X POST -d 'grant_type=client_credentials&client_id=client1id&client_secret=client1secret&redirect_uri=192.
168.8.165:8000/api/employees' 192.168.8.165:8000/oauth/access_token

[Received]:
{"access_token":"YSn6O0oXNnWvWfhEb6JMdsssaF51xm3j6mqHcpdp","token_type":"Bearer","expires_in":3600}

[Second Call]
$ curl -H "Authorization: bearer YSn6O0oXNnWvWfhEb6JMdsssaF51xm3j6mqHcpdp" -A "client1"  http://192.168.8.165:8000/oauth/authorize

[Received]
{"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client. Check the \"authorization_code\" parameter."}

I want to get access to call and to protect 192.168.8.165:8000/api/employees.

Any idea....
Thank you

**Comment by lucadegasperi** [comment]
Bearer with the capital B might be the problem.

**Comment by edyrkaj** [comment]
@lucadegasperi I got the same problem. I received access_token but cant authorize url

**Comment by lucadegasperi** [comment]
```
RewriteCond %{HTTP:Authorization} .
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

This should be in your .htaccess file

**Comment by mshanak** [comment]
this tutorial could help you https://medium.com/@mshanak/laravel-5-token-based-authentication-ae258c12cfea

**Comment by kn0ll** [comment]
i had this issue, the wiki says to use `LucaDegasperi\OAuth2Server\Facades\Authorizer`. with this i got class `Authorizer` not found. i changed the alias to `LucaDegasperi\OAuth2Server\Facades\AuthorizerFacade` and it works as expected.
