### ISSUE TITLE
"return Response::download(img)" fails on a route filtered by OAuth 

### ISSUE THREAD

**Issue by ryankennedys30** [lucadegasperi/oauth2-server-laravel#314]
I have a simple controller to GET an image (images are private and uploaded as an attachment). The route goes through OAuth, with grant_type = password.

With the OAuth enabled and testing with Postman for Chrome, my network inspector sees "400 bad request" when trying to find the image.

When I disable OAuth on that route, we see what we're meant to see.

The controller return line is just: "return Response::download($file);", so hopefully this is something simple to test for. 

Hopefully any clues?
Thanks!

The image here it's returning is just a screenshot, so apologies for it looking like screen-ception.
Here it is without oauth on the route
![screen shot 2015-03-01 at 3 42 52 pm](https://cloud.githubusercontent.com/assets/11158006/6429552/d2528c7e-c029-11e4-8c34-59f7edecace8.png)

Here it is with oauth on the route
![screen shot 2015-03-01 at 3 42 05 pm](https://cloud.githubusercontent.com/assets/11158006/6429553/d2818b64-c029-11e4-8f27-e5bfa7130184.png)

**Comment by ababkov** [comment]
Judging from your network monitor screenshot, there's two requests going on there - one (via requester.js) has the image returned with the correct payload size, the second issued via jquery is getting a 400.

Have you tried this outside of postman?
