### ISSUE TITLE
L5: http_headers_only does not work

### ISSUE THREAD

**Issue by dweber019** [lucadegasperi/oauth2-server-laravel#317]
Error message: {"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"access token\" parameter."}

if http_headers_only is set to false everything works.

This is the request I'm trying with http_headers_only set to true:
curl -X "GET" "http://laravel.dev/users/2" \
	-H "Authorization: Bearer 6SRhskkuLyV7V2ghXMXdaEAeKJvLsjW526Q6cyfP" \
	-H "Accept: application/json"

**Comment by lucadegasperi** [comment]
Weird, it should work in both cases, might have to do more with the underlying library, also check your htaccess file, some users were reporting problem with it.

**Comment by AlanRezende** [comment]
This has something to do with the Symfony components that laravel uses. Just put 
```
RewriteCond %{HTTP:Authorization} .
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```
in your htaccess file just after ```RewriteEngine On``` and you're good to go!
