### ISSUE TITLE
User model with other name generating laravel error

### ISSUE THREAD

**Issue by Raphael-C-Almeida** [lucadegasperi/oauth2-server-laravel#318]
Hello I’m starting with oAuth2 and I use laravel, but in my language "User" can be translated to "Usuario", so my model "User" is called "Usuario", but I believe that because of this factor when I try to send a post like this:

http://localhost/api-test/public/oauth/access_token
grant_type=password
client_id=XXXXXXXXXX
client_secret=XXXXXXXXXXXXXXXXXXXXXXXX
username=demo
password=123456

I receive this laravel error in response:
Class '\User' not found

Can anyone help me? There is a way to fix it? Change my module's name is the only way?
Thank you in advance. =)

**Comment by teamsoo** [comment]
Have you tried changing model config in auth.php

Mine is 
```php
'model' => 'User',
```

Your can be like
```php
'model' => 'Usuario',
```

Now, if you use **Auth** in oauth2.php config file. It will check user credentials using Usuario model.

**Comment by Raphael-C-Almeida** [comment]
Thank you teamsoo, I will try it, and then post the results here.

**Comment by Raphael-C-Almeida** [comment]
It works teamsoo =)
