### ISSUE TITLE
Authorization:Bearer [token] missing a.t

### ISSUE THREAD

**Issue by Naranbat1123** [lucadegasperi/oauth2-server-laravel#320]
GET http://project02/api/post

    Authorization:Bearer 8oUW10XVXK6sO90PioP0fi1AxBMe3cIbpxJzbqnF

{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"access token\" parameter."}

**Comment by lucadegasperi** [comment]
There needs to be a space between Authorization: and Bearer

**Comment by Naranbat1123** [comment]
![1](https://cloud.githubusercontent.com/assets/1202003/6551511/a95cd9d6-c674-11e4-89fc-0d292eeac448.png)

**Comment by lucadegasperi** [comment]
```
RewriteCond %{HTTP:Authorization} .
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

This should be in your .htaccess file

**Comment by Naranbat1123** [comment]
It`s work . TY

**Comment by portega-tild** [comment]
I was facing the same problem, also worked for me.
Would you be so kind to elaborate on the reason behind this rewrite condition?

**Comment by AlanRezende** [comment]
It has something to do with Laravel and the symphony component it uses, that looks for ```HTTP_AUTHORIZATION``` instead of ```Authorization```

**Comment by johnpaulmedina** [comment]
BUMP - ADD TO WIKI

Spent more time trying to diagnosis. Should definitely be in the WIKI

**Comment by lucadegasperi** [comment]
It is in the wiki indeed. https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Apache-ModRewrite
