### ISSUE TITLE
Laravel 5 config:cache throws exception

### ISSUE THREAD

**Issue by elliotfehr** [lucadegasperi/oauth2-server-laravel#323]
When using the password grant callback and caching the configurations in Laravel 5 I receive this exception:

`Call to undefined method Closure::__set_state()`

From:
```php
'password' => array(
    'class' => 'League\\OAuth2\\Server\\Grant\\PasswordGrant',
    'access_token_ttl' => 604800,
    'callback' => Closure::__set_state(array()),
)
```

**Comment by pvormittag** [comment]
The `config:cache` command processes the configuration array with `var_export`, [see here](https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/Console/ConfigCacheCommand.php#L56).

For the same reasons as `route:cache` cannot use closures, the same is true for `config:cache`. The only way to resolve this is to not declare Closures in configuration files (which isn't a good practice anyhow).

@lucadegasperi, A simple solve for this could be to use laravel-style class method syntax (e.g. Foo/Bar@baz) in place of using Closures. Or more "correctly" I suppose, a class could implement a supplied interface and then reference the class in the configuration, which would solve the problem similarly. Thoughts?

Example:

```php
'grant_types' => [

        'password' => [
            'class'            => 'League\OAuth2\Server\Grant\PasswordGrant',
            'access_token_ttl' => 604800,

            // the code to run in order to verify the user's identity
            'callback'         => 'App\Handlers\GrantTypePassword@callback'
        ],
],
```

**Comment by lucadegasperi** [comment]
problem is the underlying library doesn't resolve classes and methods out of the IoC but does a straight call_user_func with the closure passed. I'll have a look in detail.

**Comment by pvormittag** [comment]
Yeah I know what you're referring to. I believe it's a matter of initializing a closure during registration vs placing it in the configuration.

Doing something as:

```php
$grant->setVerifyCredentialsCallback(function() use ($app) {
	// Resolve the serialzable value in config.php to a closure which is returned.

	$instance = $app->make('Some/Class');
	return $instance->someMethodWhichReturnsVerifyCallbackClosure();
));
```

Instead of just passing the closure through from the configuration array, which is how it's [currently handled](https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/src/OAuth2ServerServiceProvider.php#L109).

I've never gone through the process of putting a PR together, but I'm glad to pitch in and discuss a solution.

**Comment by fabianweb** [comment]
Are there any updates for this issue? Thanks!

**Comment by lucadegasperi** [comment]
Not yet

**Comment by spronkey** [comment]
I'd put my vote forward for removing the callback from the config. Having it in the config actually makes it really difficult if you're using certain authentication schemes, and really doesn't seem like the right place.

To be brutally honest, I'd also support moving some of the grant creation out of the config files as well.

**Comment by lucadegasperi** [comment]
@spronkey  Agree on the first sentence. How would you proceed with moving the grant declaration out of the config?

**Comment by spronkey** [comment]
Effectively by requiring the user to declare their grants in a service provider. I'm not 100% sure on exactly how it would look. The thought came from my own experience implementing different grants for different facets of an application (e.g. I had certain endpoints that should only use client grant vs ones that should use password grant). Ended up implementing two service providers of my own and ditching the config completely.

**Comment by mcraz** [comment]
Will it be okay to just leave the config value blank and then set it using 
````php
config(['grant_types' => Closure])
````
in a service provider, perhaps the AppServiceProvider ?

**Comment by Doncode** [comment]
remove file bootstrap/cache/config.php

**Comment by elliotfehr** [comment]
@Doncode This not a solution to the problem.

**Comment by lucadegasperi** [comment]
This is solved now on develop.
