### ISSUE TITLE
Check the \"client_id\" parameter.

### ISSUE THREAD

**Issue by renyang9876** [lucadegasperi/oauth2-server-laravel#325]
I created a form 
`<form action="{{action('OAuthController@postAuthorize')}}" method="post">`
				`<input class="form-control" type="hidden" name="client_id" value="{{ $client->getId() }}" >`
				`{{ Form::hidden('approve',1) }}`
				`<input class="form-control" type="hidden" name="redirect_uri" value="{{ $redirect_uri }}" >`
				`<input class="form-control" type="hidden" name="scope" value="{{ Input::get('scope') }}" >`
				`<input class="form-control" type="hidden" name="response_type" value="code" >`
				`<input class="form-control" type="hidden" name="state" value="{{ Input::get('state') }}" >`
				`{{ Form::token() }}`
				`<button class="btn btn-primary" type="submit">approve</button>`
				`<button class="btn btn-default">exit</button>`
			`</form>`
Is there any problems?

**Comment by lucadegasperi** [comment]
Why would there be any problems?

**Comment by renyang9876** [comment]
When i submit the form, it tells me "{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"client_id\" parameter."}"

**Comment by lucadegasperi** [comment]
If I recall right, some of the parameters need to be in the query string as well as in the post payload.
