### ISSUE TITLE
Authorization: Bearer xxxx | Not working

### ISSUE THREAD

**Issue by di5abled** [lucadegasperi/oauth2-server-laravel#326]
Hy,

I assume passing the access token via headers should work with every request type (GET, POST, DELETE, ...) otherwise the setting `http_headers_only` wouldn't make that much sense right?

I think I have nearly tried everything but can't get this working. I'm using [Postman](https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm) to test my Requests and adding the header `Authorization` with the value `Bearer access_token_xyz`. When I pass the access token via query or post parameters everything works like expected. 

I use `Laravel 4.2` and version `3.*` of your package.

Do you have an idea where the problem is or what other things could couse this kind of problem? You can also give me some hints where/how I should debug this and I'll go and have a look.

**Comment by lucadegasperi** [comment]
There is a problem in how Laravel and Symfony handle the access tokens. https://github.com/lucadegasperi/oauth2-server-laravel/issues/320

**Comment by di5abled** [comment]
nice, the `.htaccess` entry fixed it :+1: 

maybe you should mention it in your wiki or the readme? 
I'm sure many people encouter this problem?
