### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by Gittinhub** [lucadegasperi/oauth2-server-laravel#329]
I am not being able to create a brand new laravel 5 instalation of your oauth2 server.

Can you please check and give me the command lines, it's not working.

>composer create-project laravel/laravel oauth2-server-laravel/
ok
Now add "lucadegasperi/oauth2-server-laravel": "4.0.x@dev" to composer.json and run 
>"composer update"
ok
--CONFIGURED /config/database.php
-- Added:
'LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider',
'LucaDegasperi\OAuth2Server\OAuth2ServerServiceProvider',
and
'Authorizer' => 'LucaDegasperi\OAuth2Server\Facades\AuthorizerFacade',
to /config/app.php
-- Added:
'LucaDegasperi\OAuth2Server\Middleware\OAuthExceptionHandlerMiddleware'
and 
commented : App\Http\Middleware\VerifyCsrfToken
at app/Http/Kernel.php
>php artisan vendor:publish
ok
-------------------NOW THE PROBLEMS START--------------------
>php artisan oauth2-server:migrations
 [InvalidArgumentException]                                       
  There are no commands defined in the "oauth2-server" namespace.  
>php artisan migrate
  [PDOException]                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)  
WHAT???? The file in config/database.php is NOT even configured for this user LOL!!!
I am guessing that it is not reading this config file, cause as i described before i already configure it and re checked 10 times...LOL!!!
-----------------------------------------------------------------------------
Please, try to create a new L5 project and add oauth to it and update the procedure.
Thanks.

**Comment by lucadegasperi** [comment]
On L5 the only command at your disposal is php artisan vendor:publish this should take care of moving all the needed files to the right directories.

**Comment by Gittinhub** [comment]
But the problem is the migration.
> php artisan oauth2-server:migrations  |  doens'nt work as described before
> php artisan migrate | doesn't work as described before.
Please, read the entire post and you will see.

**Comment by Gittinhub** [comment]
The database.php file of laravel 5 comes configured with an env(), i think for the environment variables.
It comes configured like:
'host'      => env('DB_HOST', 'localhost'),
...
so i removed the env() like :
'host'      => 'localhost',
...
AND IT WORKED!!!!

**Comment by Gittinhub** [comment]
Now i think you have to include this on the installation procedures or include the env() on your package.
This could be causing MANY database issues i think including :https://github.com/lucadegasperi/oauth2-server-laravel/issues/284 , cause maybe in that guy case, he should INCLUDE the ENV().
