### ISSUE TITLE
Request access token via application/json

### ISSUE THREAD

**Issue by di5abled** [lucadegasperi/oauth2-server-laravel#331]
Hello,

is it possible to request access tokens via application/json? 

As I undersood it currently not because the used server implementation doen't abstract this like the Laravel `Input::get(...)` function?

Have you planned to implement this feature in the future?

**Comment by lucadegasperi** [comment]
Nope. That's how the spec describes it should be done. Stick to it like everyone else does and everyone will be grateful :)

**Comment by di5abled** [comment]
true story :)
I'll use the spec for sure, didn't had this in mind, thank you.
