### ISSUE TITLE
vendor:publish always copy migrations to database/migrations

### ISSUE THREAD

**Issue by jenky** [lucadegasperi/oauth2-server-laravel#332]
When i add new package to composer then using `vendor:publish`, the new migrations were created. This causes troubles with `composer dumpautoload` and `migrate` commands.

**Comment by lucadegasperi** [comment]
Why would it cause any issues?

**Comment by jenky** [comment]
Because those migrations already run and the `migrate` command will throw errors

`Base table or view already exists: 1050 Table 'oauth_XXX' already exists`

and composer command `dumpautoload` will throw warnings

`Ambiguous class resolution, "CreateOauthXXX" was found in both ....`

**Comment by lucadegasperi** [comment]
Weird...

**Comment by jenky** [comment]
Just to be clear, follow these steps:

* Add this package to composer and run composer, after that, run `php artisan vendor:publish` and `php artisan migrate`, everything works fine.
* For whatever reasons, i need to run `php artisan vendor:publish` and `php artisan migrate` or `composer dumpautoload` again (new package, etc..) those errors will happen.
