### ISSUE TITLE
401 Unauthorized - Laravel 5 - Grant_Type=password

### ISSUE THREAD

**Issue by Gittinhub** [lucadegasperi/oauth2-server-laravel#335]
I created a brand new laravel 5 empty project as described in installation issue https://github.com/lucadegasperi/oauth2-server-laravel/issues/329.
Then, updated vendor/lucadegasperi/oauth2-server-laravel/config/oauth2.php 
 AND
config/oauth2.php
to :
...
 'password' => [
                'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
                'callback' => function($username, $password) {
                    // return an user ID if valid, otherwise return false

                     return 1000;
                },
                'access_token_ttl' => 3600
        ]
...
To avoid any user authentication failure.
Any idea on what could be happing? I appreciate any hint.
luca, what "oauth2.php" file should i use? i updated both to avoid any mistake.
Btw, in "https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Password-Grant"
you are refering to : app/config/lucadegasperi/oauth2-server-laravel/oauth2.php that i am guessing is Laravel 4.
Someone hav any hint on what could be causing this unauthorized?
I am using apache 2.4 and linux

**Comment by Gittinhub** [comment]
Updated .htaccess as described at:
https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Apache-ModRewrite
but still no lucky.
Any other idea?

**Comment by Gittinhub** [comment]
luca, i see that posting ONLY the grant_type=password parameter does return 401 Unauthorized  too.
According to oauth proto: http://tools.ietf.org/html/rfc6749#section-4.3.1 , the username AND password fields are requirede, so it should return a BAD Request, not Unauthorized.

**Comment by lucadegasperi** [comment]
It means the flow failed at some point, either validating the client or the user.

**Comment by Gittinhub** [comment]
i added a sample client to the oauth_clients table and then added in the post the variables:
client_id = 1
and
client_secret = mysecret
Finally i could get an access_token!!!!!!
It's working, but note... According to the oauth 2 proto :  http://tools.ietf.org/html/rfc6749#section-4.3.1 , the client_id and client_secret are NOT variables REQUIRED to issue an access_token.

**Comment by lucadegasperi** [comment]
> If the client type is confidential or the client was issued client
   credentials (or assigned other authentication requirements), the
   client MUST authenticate with the authorization server as described
   in Section 3.2.1.

Having an anonymous client is not secure, and the main purpose of this package and the underlying one is to be secure.
