### ISSUE TITLE
Command "oauth2-server:migrations" is not defined.

### ISSUE THREAD

**Issue by gaomd** [lucadegasperi/oauth2-server-laravel#336]
There is no `artisan oauth2-server:migrations` command in `4.0.x@dev`, the [doc](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Laravel-5-Installation#migrations-and-configuration-publishing) seems out-dated.

**Comment by lucadegasperi** [comment]
Thanks for pointing it out.

**Comment by gaomd** [comment]
After `php artisan vendor:publish`, all migrations are now included in `/database/migrations/*`.

I have a separate database for OAuth, what is the recommended way to migrate only OAuth tables on it? Laravel 5 [removed](http://laravel.io/forum/01-08-2015-package-migrations-not-working-in-laravel-5) `--package` option from the `migrate` command.

My current solution is to move oauth-server related migrations to a separate directory, luckily, the `--database` and `--path` options of `migrate` command are still available. Do you have a better plan? @lucadegasperi

**Comment by lucadegasperi** [comment]
You should be able to specify the database connection to use on each migration as well. What I'm not sure is where the migrations table will be located in this case.
