### ISSUE TITLE
Could the client creation command be extended with a redirect uri?

### ISSUE THREAD

**Issue by aFreshMelon** [lucadegasperi/oauth2-server-laravel#339]
As the redirect_uri is required it would be useful to be able to specify a redirect_uri in the creation command as the second parameter.

I was looking at the Command, it uses the FluentClient class that has no method to hit the ``oauth_client_endpoints`` table.

This would be especially good for small apps, because right now you basically you have to build a GUI for it.

I think this would be very useful. Opinions?

**Comment by lucadegasperi** [comment]
I removed the commands from L5. Will eventually release an utils package for it.

**Comment by aFreshMelon** [comment]
Oh, well I was using the command in L5 just fine. I just wish it had the redirect_uri param.
