### ISSUE TITLE
Revoking the access tokens

### ISSUE THREAD

**Issue by msimkunas** [lucadegasperi/oauth2-server-laravel#340]
I'm aware that the client can simply forget the access token and be done with it, but that's not the point of this question.

What I'm asking is how can I manually log out a user from the authorization server? I.e. revoke all access tokens for the given user ID? Should I just query the database tables and manually delete rows or is there a class method to achieve this?

EDIT: would it be enough to fetch all sessions in `oauth_sessions` where `owner_type` is `user` and `owner_id` is the user ID and delete them? (cascading would delete the access tokens as well).

**Comment by lucadegasperi** [comment]
Yes.

**Comment by MarcinOrlowski** [comment]
Quite old ticked and closed, but as it shows up quite high in search results, here's code snippet that wipes current session.

    use LucaDegasperi\OAuth2Server\Facades\Authorizer;


    Route::post('logout', ['middleware' => ['oauth2'], function () {
                                     DB::table('oauth_sessions')
                                            ->where('owner_id', Authorizer::getResourceOwnerId())
                                            ->delete();
    }]);


The oauth2 refers to middleware group:

		'oauth2' => [
			\LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware::class,
			\LucaDegasperi\OAuth2Server\Middleware\OAuthUserOwnerMiddleware::class,
		],

Still, that orphans some data in other tables, which I personally would also remove.
