### ISSUE TITLE
'Check the access_token parameter.' - Laravel 5 + Angularjs

### ISSUE THREAD

**Issue by EwanValentine** [lucadegasperi/oauth2-server-laravel#341]
Hi there,

I've been getting the following errors:

{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"access token\" parameter."}

I've tried:

```
$http.post(url, {
        data: {
          title:   content.title,
          content: content.content,
          artist:  artist,
          user:    $cookies.userId,
	 access_token: token,
        }
      }).then(function(res) {
        deffered.resolve(res);
      });
```

And

```

$http.post(url, {
        data: {
          title:   content.title,
          content: content.content,
          artist:  artist,
          user:    $cookies.userId,
        },
       headers: {
          'Authorization': 'Bearer ' + token
        }
      }).then(function(res) {
        deffered.resolve(res);
      });
```

And also 

```
$http.post(url, {
        data: {
          title:   content.title,
          content: content.content,
          artist:  artist,
          user:    $cookies.userId,
        },
       params: {
         access_token: token
       }
      }).then(function(res) {
        deffered.resolve(res);
      });

```

I've tried all sorts. Still can't seem to get it working? I've seen a few similar problems, but none of the solutions have worked for me :(

Cheers

**Comment by lucadegasperi** [comment]
What software is the server running, Apache? There's an article in the Wiki describing how to make apache correctly deal with headers. https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Apache-ModRewrite

**Comment by EwanValentine** [comment]
Hi there,

Thanks for your quick response. I was including `headers: {}` on each $post method in my factories. I created a listener in angularjs which automatically injected the token into the headers and it started working! 

For anyone else having this issue, make sure the authorisation token it being set properly in the request headers.

Cheers
