### ISSUE TITLE
Return Oauth2 - Facebook Token

### ISSUE THREAD

**Issue by mylonick** [lucadegasperi/oauth2-server-laravel#346]
Very helpful bundle. Helped a lot.
I was wondering if you could help me out with a specific problem i face.

I am currently using oauth2 to authenticate users with the Password Grant Type.
I would like to use it to provide access tokens to users who login with facebook through a mobile app.
So, the mobile app is programmed in a way it handles the Facebook authentication process and it only sends me a facebook access token.
My API gets this token and checks whether it is a new or existing user by checking the facebook ID.
In either of these two cases i would like to produce a new session token binded to the specific user.
A possibly helpful image is attached.
Thanks a lot in advance.
![oauth2 fw](https://cloud.githubusercontent.com/assets/6692511/7107977/5084266c-e180-11e4-9715-fe8379b44f75.png)

**Comment by lucadegasperi** [comment]
To do what you have in mind you should create a custom grant type that accepts a Facebook access token, validates it and gives back an access token, I don't have an example at hand but it shouldn't be too hard, especially using something like the password grant type as a base.

**Comment by mylonick** [comment]
First of all, thanks for the reply. I created a new file (FacebookTokenGrant.php) in the same folder as the rest, by copying the contents of the password grant file. Then i started changing it to make it return the created token object. I also declared it in the grants array inside the oauth2.php file. However, for some reason, when  i try to execute a post request with the new grant type, i get an error that it is unsupported. I also recreated the composer autoload files, but the problem persists.

I suppose that i also have to declare it somewhere else inside the source code for the package, is that right? Or maybe i am simply not declaring the required fields that the package is looking for. Any ideas?

**Comment by mylonick** [comment]
I fixed it, i was declaring the new class in a wring way.
I used require app_path().'/FacebookTokenGrant.php'; in globals.php file.
It works smoothly.
Thanks a lot for your help !

**Comment by marijang** [comment]
Where can i get facebookgrantype code?

**Comment by gn0rt0n** [comment]
I would be interested in seeing the code for FacebookTokenGrant as well if you would be willing to share it. I haven't found any good example apps showing this. If there is one, I would appreciate a link.

**Comment by mylonick** [comment]
Greetings,
Sorry for the late reply.
Sure i can share the code. The new grant type accepts "client_id" , "client_secret" and a "facebook_token" acquired by the front end. It registers the new user to the system or updates an existing one.
It also uses the https://github.com/SammyK/LaravelFacebookSdk/tree/1.3
I don't know if i have done this with the optimal way since the code is in a helper function called by the facebook grant but it runs great. So, i am going to post it tomorrow (i am out of office) and maybe lucadegasperi will correct me.

**Comment by gn0rt0n** [comment]
@mylonick You are awesome! Thank you for a quick response.

**Comment by mylonick** [comment]
Guys, here is what you need for the facebook token grant.

I created a new directory under 'app', called it 'CustomGrants'.
There, i created a new file 'FacebookGrant.php'

```php
<?php

namespace League\OAuth2\Server\Grant;

use League\OAuth2\Server\Entity\AccessTokenEntity;
use League\OAuth2\Server\Entity\ClientEntity;
use League\OAuth2\Server\Entity\RefreshTokenEntity;
use League\OAuth2\Server\Entity\SessionEntity;
use League\OAuth2\Server\Event;
use League\OAuth2\Server\Exception;
use League\OAuth2\Server\Util\SecureKey;
use Symfony\Component\HttpFoundation\Response;

/**
 * Password grant class
 */
class FacebookGrant extends AbstractGrant
{
    /**
     * Grant identifier
     *
     * @var string
     */
    protected $identifier = 'facebook';

    /**
     * Response type
     *
     * @var string
     */
    protected $responseType;

    /**
     * Callback to authenticate a user's name and password
     *
     * @var callable
     */
    protected $callback;

    /**
     * Access token expires in override
     *
     * @var int
     */
    protected $accessTokenTTL;

    /**
     * Set the callback to verify a user's username and password
     *
     * @param callable $callback The callback function
     *
     * @return void
     */
    public function setVerifyCredentialsCallback(callable $callback)
    {
        $this->callback = $callback;
    }

    /**
     * Return the callback function
     *
     * @return callable
     *
     * @throws
     */
    protected function getVerifyCredentialsCallback()
    {
        if (is_null($this->callback) || !is_callable($this->callback)) {
            throw new Exception\ServerErrorException('Null or non-callable callback set on Password grant');
        }

        return $this->callback;
    }

    /**
     * Complete the password grant
     *
     * @return array
     *
     * @throws
     */
    public function completeFlow()
    {
        // Get the required params
        $clientId = $this->server->getRequest()->request->get('client_id', $this->server->getRequest()->getUser());
        if (is_null($clientId)) {
            throw new Exception\InvalidRequestException('client_id');
        }

        $clientSecret = $this->server->getRequest()->request->get('client_secret',
            $this->server->getRequest()->getPassword());
        if (is_null($clientSecret)) {
            throw new Exception\InvalidRequestException('client_secret');
        }

        // Validate client ID and client secret
        $client = $this->server->getClientStorage()->get(
            $clientId,
            $clientSecret,
            null,
            $this->getIdentifier()
        );

        if (($client instanceof ClientEntity) === false) {
            $this->server->getEventEmitter()->emit(new Event\ClientAuthenticationFailedEvent($this->server->getRequest()));
            throw new Exception\InvalidClientException();
        }


        $facebook_token = $this->server->getRequest()->request->get('facebook_token', null);
        $client_id = $this->server->getRequest()->request->get('client_id', null);

        $userId = createOrUpdateFbCustomer($facebook_token,$client_id);

        //If not integer means error in the helper function, return it FOR DEBUGGING ONLY
        if (!is_int($userId)){
            return $userId;
        }
        if ($userId === false) {
            $this->server->getEventEmitter()->emit(new Event\UserAuthenticationFailedEvent($this->server->getRequest()));
            throw new Exception\InvalidCredentialsException();
        }

        // Validate any scopes that are in the request
        $scopeParam = $this->server->getRequest()->request->get('scope', '');
        $scopes = $this->validateScopes($scopeParam, $client);

        // Create a new session
        $session = new SessionEntity($this->server);
        $session->setOwner('customer', $userId);
        $session->associateClient($client);

        // Generate an access token
        $accessToken = new AccessTokenEntity($this->server);
        $accessToken->setId(SecureKey::generate());
        $accessToken->setExpireTime($this->getAccessTokenTTL() + time());

        // Associate scopes with the session and access token
        foreach ($scopes as $scope) {
            $session->associateScope($scope);
        }

        foreach ($session->getScopes() as $scope) {
            $accessToken->associateScope($scope);
        }

        $this->server->getTokenType()->setSession($session);
        $this->server->getTokenType()->setParam('access_token', $accessToken->getId());
        $this->server->getTokenType()->setParam('expires_in', $this->getAccessTokenTTL());

        // Associate a refresh token if set
        if ($this->server->hasGrantType('refresh_token')) {
            $refreshToken = new RefreshTokenEntity($this->server);
            $refreshToken->setId(SecureKey::generate());
            $refreshToken->setExpireTime($this->server->getGrantType('refresh_token')->getRefreshTokenTTL() + time());
            $this->server->getTokenType()->setParam('refresh_token', $refreshToken->getId());
        }

        // Save everything
        $session->save();
        $accessToken->setSession($session);
        $accessToken->save();

        if ($this->server->hasGrantType('refresh_token')) {
            $refreshToken->setAccessToken($accessToken);
            $refreshToken->save();
        }

        return $this->server->getTokenType()->generateResponse();
    }
}
```

As you can see, a $userId = createOrUpdateFbCustomer($facebook_token,$client_id) is called.
I placed this function in the helpers.php file and it is as follows : 

<?php

use Facebook\FacebookRequest;
use Facebook\FacebookSession;
use Facebook\FacebookSDKException;
use Facebook\Entities\AccessToken;

```php
function createOrUpdateFbCustomer($facebook_token, $client_id)
{

    //Your FB applion app id and secret (normally in the config file of the package) 

    FacebookSession::setDefaultApplication('XXXXXXXXXXX', 'XXXXXXXXXX');
    Facebook::setAccessToken($facebook_token);
    $token = new AccessToken($facebook_token);

   //extending token life in order not to ask for the user permission again   

 if (!$token->isLongLived()) {
        try {
            $token = $token->extend();

        } catch (Exception $e) {
            return array(
                'status' => 'error',
                'message' => 'Invalid facebook token'
            );
        }
    }

    FacebookSession::enableAppSecretProof(false);
    try {
        $facebook_user = Facebook::object('me')
            ->fields('id', 'first_name', 'last_name', 'gender', 'email', 'birthday', 'cover','location')
            ->get();

    } catch (FacebookQueryBuilderException $e) {
        return array(
            'status' => 'error',
            'message' => 'Could not connect to Facebook'
        );
    }

        $facebook_birthday = Carbon\Carbon::createFromFormat('m/d/Y', $facebook_user['birthday']);
        $facebook_birthday = $facebook_birthday->toIso8601String();
        $facebook_user['birthday'] = $facebook_birthday;

        $facebook_user = (array)json_decode($facebook_user);

    $customer_facebook = CustomerFacebook::where('facebook_id', '=', $facebook_user['id'])
        ->with('customer')->first();

/**
 * HERE I HAVE A LOT OF CODE, ONLY RELEVANT TO MY PROJECT
 *MANIPULATING DATA, CHECKING IF CUSTOMER EXISTS OR IS NEW
 */
$customer_facebook->save();
return $customer->id;
}

```

Now, in  app / config / packages / lucadegasperi / oauth2-server-laravel / oauth2.php inside the 'grant_types' array :
```php
        'facebook' => [
            'class'                 => 'League\OAuth2\Server\Grant\FacebookGrant',
            'access_token_ttl'      => 36000,
        ],
```

Please note the following 3 lines on the FacebookGrant.php

1) protected $identifier = 'facebook';
Has to be the same as 'facebook' =>  in oauth2.php
2) $userId = createOrUpdateFbCustomer($facebook_token,$client_id);
It calls the external function on the helper file, now i see it after a while i can't see a reason to pass the $client_id, it should have been a reason back then.
3)$session->setOwner('customer', $userId);
You most probably need $session->setOwner('user', $userId);
I just had set multiple owners with many different grant_types to allocate permissions.
It is the owner_id you will find in the oauth_sessions table.
![dbtable](https://cloud.githubusercontent.com/assets/6692511/11015526/b99ce5f6-856a-11e5-92d3-3735fe7517bb.jpg)

Don't forget to load the new file 
require app_path().'/CustomGrants/FacebookGrant.php';
you can do it in the end of global.php in app/start

Now you are ready to call the route you have for the oauth2 to acquire tokens by giving 
grant_type => facebook
facebook_token => 'token acquired from the external app'

Of course you could just include the facebook code inside the FacebookGrant instead of using an external file. I remember there was an implication and this is why i didn't. I just needed something to work soon.

I wrote this on the fly, and haven't touched this code for a long time, please let me know if there are any mistakes.
It is not the optimal way to do it but is surely works. 
If someone of you improves it, please let me know.
Hope i helped.

**Comment by gn0rt0n** [comment]
@mylonick Thank you so much for sharing your code as well as your detailed explanation. I really appreciate it. I will try a similar implementation this coming week.

**Comment by mylonick** [comment]
@gn0rt0n , if you successfully done a more abstract implementation i would be very interested.

**Comment by mylonick** [comment]
@gn0rt0n Did you have any luck with a more modular approach ?

**Comment by gn0rt0n** [comment]
Sorry, No I have not tried it yet. I got pulled another direction  on a project and haven't looked back into this since November. It is still on my "todo" list, but not for the near future. Sorry, I really do appreciate the help you gave me and for your detailed answer. Sometimes I just not able to dictate the direction the project takes. :(

**Comment by mylonick** [comment]
@gn0rt0n No worries. I am about to redesign my API and i though i should ask if someone else has found a more abstract solution.
I will implement it next month. Will post it here since i have it. Good luck with your project.

**Comment by lenyapugachev** [comment]
@mylonick Hello, did you shared somewhere your current solution?

**Comment by DaanGeurts** [comment]
I've changed some of the Facebook API calls, because the Facebook SDK dependency of [Laravel Facebook SDK](https://github.com/SammyK/LaravelFacebookSdk) has changed.

` //Your FB applion app id and secret (normally in the config file of the package) 
        $app = new Facebook(['app_id' => '', 'app_secret' => '']);

        $token = new AccessToken($facebookToken);
        try {
            $response = $app->get('me?fields=id,name,email,location,birthday', $token);
        }
        catch(\Facebook\Exceptions\FacebookResponseException $e) {
            print json_encode(
                [
                    'error' => [
                        "messages" => "Graph returned an error: " . $e->getMessage(),
                        "code" => $e->getCode(),
                    ]
                ], JSON_PRETTY_PRINT
            );
            exit;
        } catch(\Facebook\Exceptions\FacebookSDKException $e) {
            print json_encode(
                [
                    'error' => [
                        "messages" => "Facebook SDK returned an error: " . $e->getMessage(),
                        "code" => $e->getCode(),
                    ]
                ], JSON_PRETTY_PRINT
            );
            exit;
        }
        // get facebook user
        $facebookUser = $response->getGraphUser();
        `
You can access the facebook properties like this:

`
// Get user email
 $facebookUser->getEmail()

// Get user facebook id

 $facebookUser->getId()

// Get user name

 $facebookUser->getName()

// Get user location

 $facebookUser->getLocation()->getName()

 // Get user birthday

 $facebookUser->getBirthday()->format(DATE_ISO8601)
   `
