### ISSUE TITLE
About Resource Owner Password Credentials Grant

### ISSUE THREAD

**Issue by qiuc** [lucadegasperi/oauth2-server-laravel#350]
I am new in oauth2 . When I read some documents about it, I noticed that in Owner Password Credentials Grant, the client isn't need to pass client_id and client_secret to the authorization server. The sending data is just like:

```
POST /token HTTP/1.1
  Host: server.example.com
  Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
  Content-Type: application/x-www-form-urlencoded;charset=UTF-8
  
  grant_type=password&username=johndoe&password=A3ddj3w
```

But in the code, I have to pass client_id and client_secret, otherwise an error will be alarmed. So I want to ask that what is the consideration to pass these two parameters?

**Comment by lucadegasperi** [comment]
Security. You want to know who is acting on user's behalf and so does the user. If he wants to revoke access to a certain client, this way he would be able to. Not knowing the client and using the password grant type means any app (even malicious ones) could ask the user for credentials and act on his behalf.

**Comment by qiuc** [comment]
Thanks a lot! I've learned something really important.
