### ISSUE TITLE
Lumen Support?

### ISSUE THREAD

**Issue by nacr-dev** [lucadegasperi/oauth2-server-laravel#351]
Hello,

Just a quick question is there any plans for implementing this package on a Lumen PHP framework.

Since Lumen is based on Laravel?

Tks

**Comment by lucadegasperi** [comment]
Link to Lumen please?

**Comment by pavankumarkatakam** [comment]
[Lumen](http://lumen.laravel.com/) microframework by Taylor Otwell.

**Comment by lucadegasperi** [comment]
Man, it has been announced an hour ago. Ok the hype and the eager to try new stuff, but let's hold on for a moment.

**Comment by nacr-dev** [comment]
Sorry for the hype. Ok I will wait for more feedback on this!

**Comment by devmark** [comment]
+1

**Comment by crisu83** [comment]
+1

**Comment by jwondrusch** [comment]
+1 :)

**Comment by rokde** [comment]
+1 :)

**Comment by nacr-dev** [comment]
Hello any feed back?

**Comment by vinkla** [comment]
Added in 483d6afc4c435fd2e13b598d743303558488ec44
