### ISSUE TITLE
Composer Update - ReflectionException - ClientCreatorCommand does not exis

### ISSUE THREAD

**Issue by iamthewit** [lucadegasperi/oauth2-server-laravel#355]
I updated to the latest dev version (4.0.x@dev) this morning via composer and received this error:
```
[ReflectionException]
  Class LucaDegasperi\OAuth2Server\Console\ClientCreatorCommand does not exist

Script php artisan clear-compiled handling the post-update-cmd event returned with an error
```

I went from dev-master 7c94eef to dev-master 171fac7.

Everything I'm working on seems to be working still, but just thought I'd let you know incase it break's anything else for anyone else.

**Comment by lucadegasperi** [comment]
Had no problem on my install when updating the package after I removed the command.

**Comment by iamthewit** [comment]
I double checked and realised the problem is on my end. Thanks for the quick response and sorry for any confusion caused.

**Comment by maulsea** [comment]
@iamthewit Could you tell me your solution here? I'm stuck with the same.

**Comment by iamthewit** [comment]
@maulsea sure, as I followed the setup on the wiki (https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Laravel-5-Installation#command-to-create-clientid-and-clientsecret) to add the command to  generate clientIDs and clientSecrets, all I had to do was remove this line from Kernel.php:
```
 'LucaDegasperi\OAuth2Server\Console\ClientCreatorCommand',
```
Hope that helps.

@lucadegasperi If you are removing the command from the project, maybe you could update the wiki to match?

**Comment by maulsea** [comment]
I just figured. Thanks for your follow up though! :-)

**Comment by lucadegasperi** [comment]
@iamthewit yes, will remove it from the L5 Wiki pages.
