### ISSUE TITLE
ReflectionException: ClientCreatorCommand does not exist

### ISSUE THREAD

**Issue by fabianweb** [lucadegasperi/oauth2-server-laravel#358]
For anyone else who is getting this error when updating the package.

Remove the following line from `app/Console/Kernel.php`
```php
'LucaDegasperi\OAuth2Server\Console\ClientCreatorCommand',
```

**Comment by cethak89** [comment]
Yes i am and we are talking in this link https://github.com/lucadegasperi/oauth2-server-laravel/issues/366
but nothing change
