### ISSUE TITLE
Problem create client

### ISSUE THREAD

**Issue by eidea** [lucadegasperi/oauth2-server-laravel#359]
hi all,

when i try to create a client get the following error:

php artisan oauth2-server:create-client xxxx@xxxx.com

                                                                   
  [InvalidArgumentException]                                       
  There are no commands defined in the "oauth2-server" namespace. 

all looks like good:

php artisan migrate:status
+------+----------------------------------------------------------+
| Ran? | Migration                                                |
+------+----------------------------------------------------------+
| Y    | 2014_10_12_000000_create_users_table                     |
| Y    | 2014_10_12_100000_create_password_resets_table           |
| Y    | 2015_01_01_000001_create_oauth_scopes_table              |
| Y    | 2015_01_01_000002_create_oauth_grants_table              |
| Y    | 2015_01_01_000003_create_oauth_grant_scopes_table        |
| Y    | 2015_01_01_000004_create_oauth_clients_table             |
| Y    | 2015_01_01_000005_create_oauth_client_endpoints_table    |
| Y    | 2015_01_01_000006_create_oauth_client_scopes_table       |
| Y    | 2015_01_01_000007_create_oauth_client_grants_table       |
| Y    | 2015_01_01_000008_create_oauth_sessions_table            |
| Y    | 2015_01_01_000009_create_oauth_session_scopes_table      |
| Y    | 2015_01_01_000010_create_oauth_auth_codes_table          |
| Y    | 2015_01_01_000011_create_oauth_auth_code_scopes_table    |
| Y    | 2015_01_01_000012_create_oauth_access_tokens_table       |
| Y    | 2015_01_01_000013_create_oauth_access_token_scopes_table |
| Y    | 2015_01_01_000014_create_oauth_refresh_tokens_table      |
+------+----------------------------------------------------------+

where is the problem=

thanks in advanced
javier

**Comment by lucadegasperi** [comment]
Command doesn't exist anymore, reason being it will be moved onto another package.
