### ISSUE TITLE
Understanding OAuth 2

### ISSUE THREAD

**Issue by vinkla** [lucadegasperi/oauth2-server-laravel#360]
It would be great if there were some kind of example application we could use as a reference when setting this up ourselves. Maybe it already exists somewhere?

**Comment by lucadegasperi** [comment]
There isn't any as far as I know, Once I write some acceptance testings you could use them as a reference for your implementation.

**Comment by vinkla** [comment]
To bad. Would be good to use as a reference. Do you know when the testing will be ready?

**Comment by lucadegasperi** [comment]
Don't have much time at the moment.

**Comment by vinkla** [comment]
Okay. I found one repo that utilizes this package: [Comic-Cloud-API](https://github.com/kidshenlong/Comic-Cloud-API/).

**Comment by lucadegasperi** [comment]
Good find!

**Comment by vinkla** [comment]
@lucadegasperi How do you work with mobile apps and OAuth2 with client credentials? I'm about to build an API and an iOS application but how does every downloaded app get their own client credentials? How do you usually work with that? Do you generate them on the run?

**Comment by lucadegasperi** [comment]
A client is just the iOS App, not every single iOS App that gets downloaded. The Application binary will have the client id and client secret stored inside.

**Comment by vinkla** [comment]
OAuth2 is mainly when building APIs for third-party users can use? Is there any best practices when working with internal APIs like the one I described above?

**Comment by lucadegasperi** [comment]
No it is not, it has some grant types that are more specific to deal with third parties (like the auth_code) and some for dealing with applications you trust a lot more (like the password grant type)

**Comment by vinkla** [comment]
Let's say I implement OAuth2 in my API, how do I blacklist a specific user? If the user in question has tried to break the oauth.

**Comment by lucadegasperi** [comment]
Blacklisting is up to you. Once the user tries to request an api endpoint with an access token, if the user associated with the access token is blacklisted, you simply deny the request.

**Comment by vinkla** [comment]
Cool. This is standard practice in the community? This is how big applications like Twitter and Facebook handles authentication?

Thanks for taking the time to answer btw. All this is quite new to me. Really appreciate it :)

**Comment by lucadegasperi** [comment]
Yes, that's how they do it.

If you (or your company) are the owner of the iOS application the you can use the password grant type which doesn't require the redirect_url. Third party applications integrating with your API might use the authorization code grant type opening a browser window to your website for authentication.

**Comment by vinkla** [comment]
Thanks, this really clear things up a bit. Maybe you saw my tweet on Twitter yesterday but I'm posting it here for others having similar problems. [OAuth 2 Simplified](http://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified) is a good starting point if you're just getting into OAuth 2 and if you're trying to get the gist of it.
