### ISSUE TITLE
Create client

### ISSUE THREAD

**Issue by eidea** [lucadegasperi/oauth2-server-laravel#361]
hi,

how we can add clients on the last version for testing?

thanks
javier

**Comment by lucadegasperi** [comment]
Open a connection to the database or use the tinker command and insert one.

**Comment by manuelro** [comment]
I seriously believe it is important to create a Model for this, for instance: `OAuthClient` could easily use the `oauth_clients` table, and be related to users (or whatever you use). That way there won't be any orphan clients out there.

**Comment by lucadegasperi** [comment]
There's the FluentClientStorage class you can use to fetch client informations. Right now you can only add clients manually via the DB
