### ISSUE TITLE
How to delete Expire token in DB

### ISSUE THREAD

**Issue by Naranbat1123** [lucadegasperi/oauth2-server-laravel#362]
How to delete Expire token in DB.

**Comment by lucadegasperi** [comment]
This functionality hasn't been implemented yet, it will eventually be integrated in a separate package when I have the time

**Comment by maximebeaudoin** [comment]
@lucadegasperi Currently we have no way to get expired access tokens and refresh tokens from `FluentAccessToken` and `FluentRefreshToken`. I'm trying to create my command to delete them but, i need to extend and replacement those by new implementation.

I would like to create a pull request to add new method to those FluentAdapter if you are agree with that ?

**Comment by lucadegasperi** [comment]
@maximebeaudoin thanks for your offer, right now this package focuses on providing an easy way to use league/oauth2-server inside laravel. All the management stuff could be done inside a separate package as I envision it.

**Comment by mansouralex** [comment]
Any updates on this?
