### ISSUE TITLE
thephpleague/oauth2-client

### ISSUE THREAD

**Issue by eidea** [lucadegasperi/oauth2-server-laravel#363]
i need to install

thephpleague/oauth2-client

so i can authenticate api (client/server) or i can both acction with the package?

thanks

**Comment by lucadegasperi** [comment]
Do you need to authenticate your server with third party servers like Facebook or GitHub? If yes, you need both libraries, if you are building a server then you only need this package.

**Comment by eidea** [comment]
no, i don't need to authenticate with third , i need protect my api, in that case with you package is enought? 

----- Mensaje original -----

De: "Luca Degasperi" <notifications@github.com> 
Para: "lucadegasperi/oauth2-server-laravel" <oauth2-server-laravel@noreply.github.com> 
CC: "eidea" <fcojpa@gmail.com> 
Enviados: Lunes, 27 de Abril 2015 19:43:41 
Asunto: Re: [oauth2-server-laravel] thephpleague/oauth2-client (#363) 


Do you need to authenticate your server with third party servers like Facebook or GitHub? If yes, you need both libraries, if you are building a server then you only need this package. 
— 
Reply to this email directly or view it on GitHub . 




-- 

Javier Pardo Albelda 
Consultor Senior Online 
email: javier.pardo@eidea.es 
skype: eidea.consultores 
url: http://www.eidea.es 
Telf: +34 660363107 
--------------------------------------------------- 
CONFIDENCIALIDAD 
Este correo electrónico contiene información privada y confidencial, sujeta a secreto profesional. Si usted no es el destinatario del mensaje no está autorizado a leerlo, copiarlo o difundirlo. Si lo ha recibido por error, por favor contacte con el remitente y destruya su contenido. 
---------------------------------------------------

**Comment by lucadegasperi** [comment]
Yes
