### ISSUE TITLE
 Class LucaDegasperi\OAuth2Server\Console\ClientCreatorCommand does not exist

### ISSUE THREAD

**Issue by DamPe88** [lucadegasperi/oauth2-server-laravel#366]
Hi,
When i try to include elastic search to the composer and try to execute composer update above error comes.
"require": {
		"laravel/framework": "5.0.*",
		"lucadegasperi/oauth2-server-laravel": "4.0.x@dev",
                "elasticsearch/elasticsearch":"1.0.*"

this is the composer code.earlier i was able to install "lucadegasperi/oauth2-server-laravel" without any errors, but now i cant update the composer.
Any possible reasons?.

**Comment by lucadegasperi** [comment]
Remove the package and install it again.

**Comment by DamPe88** [comment]
@lucadegasperi how to remove the package?

**Comment by lucadegasperi** [comment]
Remove it from composer, do an install, add it again, do another install.

**Comment by DamPe88** [comment]
Did it,But error raise again.
Steps that i followed.
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "5.0.*"
		
	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1"
		
	},
	"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php -r \"copy('.env.example', '.env');\"",
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	}
}
Execute "Composer update"
and then I added the following lines to composer
"lucadegasperi/oauth2-server-laravel": "4.0.x@dev",
 "elasticsearch/elasticsearch":"1.0.*"

When i update the composer,this error comes.

 [ReflectionException]
 Class LucaDegasperi\OAuth2Server\Console\ClientCreatorCommand does not exist

**Comment by lucadegasperi** [comment]
You need to clear the compiled composer autoload file. and Install again

**Comment by cethak89** [comment]
% composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files


                                                                                
  [ReflectionException]                                                         
  Class LucaDegasperi\OAuth2Server\Console\ClientCreatorCommand does not exist  
                                                                                


Script php artisan clear-compiled handling the post-update-cmd event returned with an error


                      
  [RuntimeException]  
  Error Output:       
                      


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]


i remove  oauth2-server-laravel package. And try to run composer update. 
*Before this command I cleared the cache with this command  "composer clear-cache"
Thank you for helping

**Comment by lucadegasperi** [comment]
Delete the vendor folder and try to run composer again

**Comment by cethak89** [comment]
1. Delete vendor
2. composer clearcache
3. composer install / composer update ( i tried both)

Result:

Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files


                                                                                
  [ReflectionException]                                                         
  Class LucaDegasperi\OAuth2Server\Console\ClientCreatorCommand does not exist  
                                                                                


Script php artisan clear-compiled handling the post-update-cmd event returned with an error


                      
  [RuntimeException]  
  Error Output:

**Comment by lucadegasperi** [comment]
Remove /bootstrap/compiled.php and try again

**Comment by cethak89** [comment]
Sorry i dont have compiled.php in bootstrap. Only have app.php and autoload.php.

**Comment by lucadegasperi** [comment]
http://laravel.com/docs/5.0/upgrade

**Comment by cethak89** [comment]
i am using last version of laravel 5.28 

  - Installing laravel/framework (v5.0.28)
    Downloading: 100%      
And i dont have /bootstrap/compiled.php file.

**Comment by lucadegasperi** [comment]
Then you might have some cached files laying around. which version of this package is telling you composer you have downloaded? Because I tagged 4.0.0 recently

**Comment by cethak89** [comment]
It is the last version of composer.

**Comment by cethak89** [comment]
Hey if i delete 'LucaDegasperi\OAuth2Server\Console\ClientCreatorCommand', from $commands array in App/Console/Kernel.php

Everything works perfect.

After the reinstalling project, it doesnt work if i dont delete the line.

Thanks for your helping.

**Comment by gaomd** [comment]
@cethak89 Thanks, problem solved.

This issue exists because previously there is an guide on the Wiki about CreatCreateCommand, then @lucadegasperi removed the command from the code.

More detail at issue https://github.com/lucadegasperi/oauth2-server-laravel/issues/355.

**Comment by gaomd** [comment]
Here's the exact Wiki [diff](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Laravel-5-Installation/_compare/ea13e6c1134f9844e8a6037594905e2aa984e8bb...e1dca41c9454351b13693d4950633085298ce71c) which involving adding `'LucaDegasperi\OAuth2Server\Console\ClientCreatorCommand'` to the `$commands` array of `App\Console\Kernel` class.

And the code [diff](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Laravel-5-Installation/_compare/ea13e6c1134f9844e8a6037594905e2aa984e8bb...e1dca41c9454351b13693d4950633085298ce71c) which removes the *Command*.

---

@lucadegasperi I've heard 4.0.0 was tagged, maybe we should update the [wiki](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Laravel-5-Installation) to remove `@dev` from `"lucadegasperi/oauth2-server-laravel": "4.0.x@dev"`?
