### ISSUE TITLE
Support Laravel 5 and MongoDB 3.0 with OAuth2

### ISSUE THREAD

**Issue by gauravdave01** [lucadegasperi/oauth2-server-laravel#367]
I just want to know, does this package supports Laravel 5 with MongoDB 3.0?

**Comment by lucadegasperi** [comment]
L5 is supported, someone ported the storage interfaces to mongo as well, You might just need to google it.

**Comment by gauravdave01** [comment]
I have founded that, but your have pulled that mongo compatible code, So when are you going to pull?
