### ISSUE TITLE
Can we get a simple isOwnerValid method?

### ISSUE THREAD

**Issue by idiotstrike** [lucadegasperi/oauth2-server-laravel#368]
Right now, from what I can see, the only way to reasonably check whether a request contains a valid Authorization token that isn't expired is using something messy like this:

    try {
        Authorizer::validateAccessToken();
        // is logged in
    } catch (\Exception $e) {
        // is not logged in
    }

Can we get an alias method for this that will return a boolean value?

**Comment by lucadegasperi** [comment]
There's an ```oauth``` filter you can use on your routes. This filter will take care of validating the token and check if it is not expired. Once the filter runs successfully, you'll be able to access the token owner id and so forth

**Comment by idiotstrike** [comment]
That's not what I want. For example, I want to attach additional data to the response if the user is authenticated. I cannot do that with any different method than the try-catch block like I said.

**Comment by lucadegasperi** [comment]
Then that's the only way to do it.

**Comment by idiotstrike** [comment]
That's why I'm creating this issue - I think it would be helpful to have a built-in alias method that does exactly this, but returns a boolean value, for example:

    public function isOwnedValid()
    {
        try {
            Authorizer::validateAccessToken();
            return true;
        } catch (\Exception $e) {
            return false;
        }
    }

I would submit a PR, not sure how to do that, though. It's a very simple addition that would come in handy.

**Comment by rtablada** [comment]
@idiotstrike in L5 you can override the existing exception handling Middleware to create your custom response and this can be a global handler to create whatever response you want.

Not sure if you can get all the information you want from the exception variable but it should be there.
