### ISSUE TITLE
Rotate_refresh_token not working

### ISSUE THREAD

**Issue by gerardnll** [lucadegasperi/oauth2-server-laravel#376]
Hello, thanks for the fantastic work.

Although i've found issues talking about this matter it is hard to see an answer or solution. This should not be closed if it's not solved.

I'm using this package (3.0.2 or 3.x-dev 1e0b04d) with dingo/api (0.8.2) and i'm running into some problems regarding the configuration. I've set up 2 grant types, the password and the refresh_token ones. 
I understand this is the proceeding for authenticating to the API:
1- request to /access_token with params: client id, client secret, user and pass and grant_type=password.
2.- save refresh_token for when needed.
3.- if access_token expires, use refresh_token with client id, client secret and grant_type=refresh_token and request a new access_token

The thing is that even though i've got rotate_refresh_token to false, this last request invalidates the refresh token and gives me a new one. 

Thanks.

**Comment by lucadegasperi** [comment]
It might be a problem in how league/oauth2-server handles the rotate_refresh_token parameter. I'll dig this thing further and report back asap

**Comment by suraleb** [comment]
is this fixed?

**Comment by lucadegasperi** [comment]
i have no clue, it's a problem with league/oauth2-server

**Comment by vinkla** [comment]
Since this is a Laravel wrapper of the PHP leagues package, this question is better suited at their repository. Please open an issue there https://github.com/thephpleague/oauth2-server/issues/new
