### ISSUE TITLE
Custom Grant for Facebook login

### ISSUE THREAD

**Issue by Eanghort** [lucadegasperi/oauth2-server-laravel#377]
It is such a nice package for Laravel user. However, in my application, I use Facebook as an authentication to login to their account from their phone. My problem is I would like to create a custom grant type to implement this process. When I click on a link you provided to learn how to create custom grant type (http://oauth2.thephpleague.com/authorization-server/custom-grants/), it display nothing.

**Comment by lucadegasperi** [comment]
Your best thing to do is look at the password grant type and tweak it to your needs.

**Comment by Eanghort** [comment]
Thank you sir! However, I am very new to oAuth technology. Is there any great tutorial to learn it faster?

**Comment by lucadegasperi** [comment]
To get a hang of oauth you could give a read to: http://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified

**Comment by Eanghort** [comment]
Thank you once again! :)
