### ISSUE TITLE
PROPOSAL - Break out issuer storage to a separate method

### ISSUE THREAD

**Issue by rtablada** [lucadegasperi/oauth2-server-laravel#378]
While I understand that this package is primarily meant to be used with the provided Fluent builder storage, it would be super helpful for the `$issuer` portion of the service provider in it's own method.

For instance if you want to switch from Fluent storage to a different driver, you would have to at least get rewrite the entire service provider or at least the entire `registerAuthorizer`.

If instead there was a `setupIssuerStorage` function, then you could extend the service provider and only override a few lines of code to change the storage for the issuer.

I'm working on a PR but just starting to get the proposal out there first.

**Comment by lucadegasperi** [comment]
If I understand correctly you'd want to switch the storage method from let's say fluent to mongo, right? But only for the issuer?

**Comment by rtablada** [comment]
Well by issuer I mean the underlying `League\OAuth2\Server\AuthorizationServer` so meaning the storage mechanism for all OAuth session.

**Comment by lucadegasperi** [comment]
Right now you would only need to swap the FluentStorageServiceProvider with another implementation like MongoStorageServiceProvider or similar to swap the storage, isn't it enough.

**Comment by rtablada** [comment]
\*\*Sound of face meeting palm**

I was reading the source late and thought I had read that instances from this package were being injected instead of the League interfaces...

**Comment by lucadegasperi** [comment]
No worries Ryan! Feel free to contribute in other ways you see fit :)
