### ISSUE TITLE
Lumen bridge

### ISSUE THREAD

**Issue by esbenp** [lucadegasperi/oauth2-server-laravel#380]
Hi, I saw you had a lot of requests for Lumen support. I needed it as well and build a small bridge for your package https://github.com/esbenp/oauth2-server-lumen. Feel free to link to it or copy the code into your package.

**Comment by lucadegasperi** [comment]
Awesome, will give it a look soon!

**Comment by esbenp** [comment]
Cool. I have written a blog post on its use http://esbenp.github.io/2015/05/26/lumen-web-api-oauth-2-authentication/

**Comment by lucadegasperi** [comment]
Thanks, a lot again. If you feel to work on a Lumen pull request to this repo, without changing much of the file structure, I'll gladly accept it!

**Comment by esbenp** [comment]
I might look into it at a later point. :-)

**Comment by lukasoppermann** [comment]
A PR would be awesome. :+1:

**Comment by lucadegasperi** [comment]
@esbenp commented here just to let you know I've decided to integrate Lumen support right into this package from the next release. In fact there's already a working version on the develop branch as well as installation instructions (based on your repo) in the wiki. Let me know if it is ok for you this way.

**Comment by esbenp** [comment]
Great @lucadegasperi. Let me know when and I will deprecate my library and link to yours. One recommendation is to remove the use of the `Config` facade `AbstractMigration` to remove the need to add the alias call.

**Comment by Chimit** [comment]
Awesome! Thanks, guys! Waiting for the new version with full Lumen support.

**Comment by vinkla** [comment]
I agree with @esbenp. Maybe we should just drop the `AbstractMigration` entirely? If developers wants to have custom database connection for their migrations they can create it themselves. 

@lucadegasperi What is your opinion on this?

**Comment by lucadegasperi** [comment]
Whatever keeps things simpler is best. I'd go for a removal of ```AbstractMigration``` but would add a note on the wiki for users that might want to run the migrations on a different DB.

**Comment by vinkla** [comment]
Great! I'll create an PR.

**Comment by vinkla** [comment]
This is fixed in #482
