### ISSUE TITLE
Update Repository Description

### ISSUE THREAD

**Issue by vinkla** [lucadegasperi/oauth2-server-laravel#381]
It seams the repo description still says L4. Maybe we should update it to just "Laravel" since it supports both 4 and 5?
![screen shot 2015-04-30 at 10 35 09](https://cloud.githubusercontent.com/assets/499192/7409200/98fbcd44-ef24-11e4-8ad3-bf6e3efdf49c.png)

**Comment by lucadegasperi** [comment]
Done :)

**Comment by vinkla** [comment]
:+1:
