### ISSUE TITLE
oauth not found

### ISSUE THREAD

**Issue by Eanghort** [lucadegasperi/oauth2-server-laravel#384]
Hi! Sorry to disturb you again! after I set up your oauth package in laravel 5, I got an issue when accessing my rest api. It displays 'class oauth does not exist'. Here is my part of codes in Route.php:

Route::group(['namespace' => 'Api', 'middleware' => 'oauth'], function(){
........
});

I think I need to alias class oauth in routeMiddleware in Kernel.php, but I wonder which class should I alias?

**Comment by lucadegasperi** [comment]
oauth is meant to be used as ```'before_filter' => 'oauth'``` this because it can have parameters passed to it.

**Comment by Eanghort** [comment]
is oauth a class name or what? I am not pretty sure about it.

**Comment by lucadegasperi** [comment]
it's a string

**Comment by Eanghort** [comment]
Thank you!
