### ISSUE TITLE
invalid_request

### ISSUE THREAD

**Issue by Eanghort** [lucadegasperi/oauth2-server-laravel#385]
Hi

When I request access token by access into oauth/access_token, there is an error message as following: "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"grant_type\" parameter.". Here is my header:
Content-Type: x-www-form-urlencoded
grant_type: facebook

I also try to pass grant_type through url parameter, but it still display the same error.

**Comment by lucadegasperi** [comment]
it should be passed in the query string indeed. Facebook is a grant type you declared i assume. Check if you registered it correctly

**Comment by Eanghort** [comment]
here is my application information:
- url: http://sportpill.app:8000/api/oAuth/access_token?grant_type=facebook

- my registration:

'grant_types' => [
        'facebook' => [
            'class' => 'App\Library\oAuth\FacebookGrant',
            'callback' => function($fb_access_token, $fb_id) {

            },
            'access_token_ttl' => 3600
        ]
    ],

NOTE: I use Laravel 5.0

**Comment by Eanghort** [comment]
When I change http method from POST to GET. It return another error as following: "The authorization grant type \"facebook\" is not supported by the authorization server."

**Comment by Eanghort** [comment]
Dont know why! Now everything is OK! thanks
