### ISSUE TITLE
Multiple Tokens

### ISSUE THREAD

**Issue by vinkla** [lucadegasperi/oauth2-server-laravel#386]
How do you handle multiple tokens? What if the client requests the server multiple times. Currently it creates a new `access_token` and returns it. What is the standard? Should you return the same one if it hasn't expired or remove the old one and create a new one?

**Comment by lucadegasperi** [comment]
Could be very well that the user is using the client from multiple devices, you don't need to expire them, nor delete the old one. Unless you intend for the user to use only one instance of a client at any given time.

**Comment by vinkla** [comment]
Okay, thanks for getting back. Lets say the client is a phone. If the user deletes the application from its phone and then downloads it again. Then the client will try to fetch a new access token again. Wouldn't this make the database huge or is there something else I'm missing?

**Comment by lucadegasperi** [comment]
Yes it would make the database bigger, but you don't know what the user did with the application. You could only delete the access token which are expired.

**Comment by vinkla** [comment]
You're saying I won't be able to know what they do if I remove the access token?

**Comment by lucadegasperi** [comment]
I'm saying if the user deletes the app, you have no clue it has been deleted. Therefore the access token is still valid until expiration. Different case is when the user logs out. In that case there's the token revocation endpoint to hit to delete the token from DB. Which should conform to the token revocation spec

**Comment by vinkla** [comment]
Okay, thanks for helping out. Really appreciated!
