### ISSUE TITLE
Laravel 5, command "oauth2-server" is not defined. 

### ISSUE THREAD

**Issue by SoldierCorp** [lucadegasperi/oauth2-server-laravel#387]
Hi!

I installed this package but I can't run the commands to manage the oauth2 using the terminal and even is not showing the commands for this package in the artisan help.

*command "oauth2-server" is not defined.*

So, how can I get it? I already performed a reinstallation but the issue is still alive.

**Comment by lucadegasperi** [comment]
Yeah because it is no longer defined, it will eventually be reimplemented in a separate package.

**Comment by SoldierCorp** [comment]
I see, and how can I get my api keys, the user and password to test with my app client?

**Comment by lucadegasperi** [comment]
Connect to the database and add them to the table.

**Comment by SoldierCorp** [comment]
Thanks! I already add it but now I have an issue with the route to get the access_token... will be great if you could check my question here http://stackoverflow.com/questions/30198706/laravel-5-oauth-2-server-package-not-working

**Comment by lucadegasperi** [comment]
That's an issue I have no clue how to solve but as someone stated, it seems to not be related to this package.
