### ISSUE TITLE
Convert Filters to Middleware

### ISSUE THREAD

**Issue by vinkla** [lucadegasperi/oauth2-server-laravel#388]
Before the Laravel **5.1** release of this package it would be cool to convert the old filters to middleware instead. In **5.1** it will be possible to send parameters to the middlewares just like with filters. This feature was merged in https://github.com/laravel/framework/pull/8524 

@lucadegasperi What do you think? Is this something that you would consider?

**Comment by lucadegasperi** [comment]
Absolutely! Let's do it!

**Comment by vinkla** [comment]
@lucadegasperi Cool!

**Comment by vinkla** [comment]
Filters are now deprecated since 5.1 https://github.com/laravel/framework/commit/3728d0b6d15f27c5c6852da5a46b965401188c23

**Comment by lucadegasperi** [comment]
once 5.1 gets tagged i'll work on implementing everything as a middleware

**Comment by vinkla** [comment]
Awesome! It will probably be released soon. They've said it should be released right after Symfony 2.7.

**Comment by lucadegasperi** [comment]
Up on the develop branch.

**Comment by vinkla** [comment]
Nice. Keep up the good work!
