### ISSUE TITLE
Password Grant Question

### ISSUE THREAD

**Issue by vinkla** [lucadegasperi/oauth2-server-laravel#389]
About the password grant. When a client fetch an access token with this grant should the user be considered loged in? Or is it custom to have a separate call to login the user?

**Comment by lucadegasperi** [comment]
I don't see why you would log the user in. What's your scenario?

**Comment by vinkla** [comment]
Aah, thats true. Maybe I can skip to login the user entirely? I want to login the user in the iOS application and then return the user data back.

**Comment by lucadegasperi** [comment]
client sends user's credentials to oauth endpoint with password grant -> token is generated -> token gets stored by the iOS app -> token is used to request user's info on an hypothetical ```/users/self``` endpoint

**Comment by vinkla** [comment]
Aah okay, know I get it. Thanks as always :)

**Comment by lucadegasperi** [comment]
You're welcome!
