### ISSUE TITLE
Client Credentials access token can get everything

### ISSUE THREAD

**Issue by chris-peng-1244** [lucadegasperi/oauth2-server-laravel#390]
I create a client 'test' in the table, then request an access token with the /oauth/access_token endpoint

    $response = $this->client->post('/oauth/access_token', [
      'body' => [
        'client_id' => 1,
        'client_secret' => '123456',
        'grant_type' => 'client_credentials',
      ],
    ]);

With the token I got, I can access everything I want, but I want to restrict it only to the resource of this client,

    $response = $this->client->post('/api/1/orders', [
      'headers' => [
        'Authorization' => 'Bearer '.$token,
      ],
      ....
    ]);

I was expecting when I change the endpoint to '/api/2/orders', it would be denied.

This is the routes.php file

    /**
     * OAuth2.0
     */
    Route::post('oauth/access_token', function() {
      return Response::json(Authorizer::issueAccessToken());
    });

    /**
     * API endpoint
     */
    Route::post('api/{client_id}/orders', ['before' => 'oauth', function($client_id) {
      // something
    }]);

I think I missed something, any suggestions for me?

**Comment by lucadegasperi** [comment]
You have to validate the client in order to check whether it can access an endpoint or not. api/1/orders or api/2/orders contain no intrinsic logic to allow or deny the access.

**Comment by chris-peng-1244** [comment]
Oh, is that mean I need to create a client-resource map, and after a token is accepted by the oauth, I check whether the resource like `api/1/orders` belongs to the client?

**Comment by lucadegasperi** [comment]
No, you just need to check wether the /1/ in the URL matches the client associated with the access token . You can do that by running Authorizer::getResourceOwnerId()
