### ISSUE TITLE
Custom Password Grant

### ISSUE THREAD

**Issue by vinkla** [lucadegasperi/oauth2-server-laravel#391]
In my use case I want to be able to fetch both the password grant the normal way. Though, I also need to be able to login users with Facebook. The client in this case will only send me the users Facebook ID. Is there any good approach here? Do I've to create a new custom grant?

**Comment by lucadegasperi** [comment]
Yes you have to create a custom grant that receives the Facebook token from your client, validates it against the Facebook server, fetches the user id or email from FB and checks if the user exists in the DB or create a new one if the user is the first time it logs into your system with FB.

**Comment by vinkla** [comment]
Okay, then I'll do that. Thanks!

**Comment by vinkla** [comment]
Just visited the [documentation page](http://oauth2.thephpleague.com/authorization-server/custom-grants/) for custom grants and it was kind of disappointment. I guess I'll be digging into the existing grants instead :)

**Comment by lucadegasperi** [comment]
I know, password grant type is the best one to start.

**Comment by vinkla** [comment]
Okay, thanks. Hope they will add it soon!

**Comment by vinkla** [comment]
@lucadegasperi Do you know of any examples using more advanced callbacks? I need to see if the user exists or generate a new user within the callback and it would be nice if one could move the callbacks to a class somewhere where I can inject other dependencies. Is that possible to do?

**Comment by lucadegasperi** [comment]
You would do without a callback if you are the one implementing the grant type. Or you could just call a method on a class that implements a specific interface

**Comment by vinkla** [comment]
Thats true, sounds much easier! Thanks again.
