### ISSUE TITLE
AuthCodeGrant error undefined index:client [Lumen]

### ISSUE THREAD

**Issue by antonybudi** [lucadegasperi/oauth2-server-laravel#394]
Hello, Has anyone ever experiences this one?
ErrorException in AuthCodeGrant.php line 150:
Undefined index: client

In the documentation, i think i only need to POST the following:
client_id, redirect_uri, response_type, user_id.
but why it asks the "client" index? (it asks ClientEntity object)
and of course I already supplied the data that exists in the oauth_clients and endpoints table.
Thank you.

**Comment by antonybudi** [comment]
Sorry, I mistake my Lumen "middleware" with "before", and it's solved.

**Comment by KeitelDOG** [comment]
I'm having the same problem in Laravel 4.2 with and undefined index client, resulting from an empty params array on getAuthCodeRequestParams() method. I use check-authorization-params filter with before, but with no luck.
Can you please point me a hint @antonybudianto
