### ISSUE TITLE
Please tag 4.0.1 

### ISSUE THREAD

**Issue by mvdstam** [lucadegasperi/oauth2-server-laravel#395]
To allow Laravel 5.1 support. Also recommend changing the illuminate version constraints to *^5.0.0* (or ~5.0 if you want to be less explicit) to allow minor and patch version increments in those dependencies so future (minor) Laravel releases will work with this package as well.

**Comment by lucadegasperi** [comment]
Got an example?

**Comment by mvdstam** [comment]
What do you mean? Example for version constraints or..?

**Comment by lucadegasperi** [comment]
Yes.
