### ISSUE TITLE
Confused about creating an API with oauth2 server

### ISSUE THREAD

**Issue by JerryBels** [lucadegasperi/oauth2-server-laravel#401]
Hello guys !

I'm trying to create my first rest API using Laravel, to pair with a Chrome extension I want to produce. I've read that in order to do that, the most secure authentification way I can use is an Oauth2 server.

So I created a subdomain api.example.com when my main API live. And then I created another subdomain oauth.example.com when I installed another Laravel installation and added this package to it : https://github.com/lucadegasperi/oauth2-server-laravel

This is the way countless people recommend making an API. But, noob with that kind of technology that I am right now, I can't see how to use it at all. So :

- Is what I made the right way ?
- How to register users to the Oauth server ? I can't see any way to do that !
- How to tell the API server that these users exist and can make requests ? I can't see how to use the access tokens to do that.

Well, I'm really confused. Thanks ahead for any help !

**Comment by JerryBels** [comment]
My main issue here is how the hell can I register new users into the Oauth server database, and after that how the API server will know they are real users allowed to access data ?

**Comment by lucadegasperi** [comment]
Users are handled by you. The oauth server has no responsibility in that regard. When requesting an access token with the different grant type you exchange user credentials with an access token, these credentials will get validated in the process, and the access token will be associated with the user. Everitime an endpoint is hit with the access token, it gets validated and if valid, you can access the user associated with it.

**Comment by JerryBels** [comment]
Hey @lucadegasperi , thanks for answering !!

So I would create users using regular Laravel flow, and then use their credentials to gain the access token ?

Should I have users table and all the oauth tables on the same database ? And is it forced to be the same database my API will be plugged into ?

You're really very kind for answering, anyway.

**Comment by lucadegasperi** [comment]
Yes exactly, you would need both tables, but they don't need to be in the same db if you want to.

**Comment by JerryBels** [comment]
Okay, lets take my case. I have my api.example.com, and I want to call a resource in it, protected and linked to my user account.

If I follow, I need first to register the user using regular Laravel flow, then call oauth.example.com/Auth?credentials or something like that to get an access token, and only when that call returns me the access token, I can call api.example.com/mydata by joining the access token to the call. I think I got that much.

Now, how to tell my API that it's protected by Oauth2 and it should check the token ? Do I have to create a middleware for it ?

BTW, I think it's incredible that I didn't found even 1 example online of a tutorial working with that kind of flow !

Thanks again !

**Comment by lucadegasperi** [comment]
To check the access token, you'll have to protect your routes with the ```oauth``` filter (soon to be a middleware in L5.1) Afterwards you can access all the methods on the Authorizer class to see who is making the request, and allow or deny it case by case.

**Comment by JerryBels** [comment]
Thank you very much for now, I will work on it again today, you helped me a lot to better understand all of this.
