### ISSUE TITLE
Permanent token

### ISSUE THREAD

**Issue by whitefoxy** [lucadegasperi/oauth2-server-laravel#402]
Hello,

This is not safe, but there are some situations where it is much more easier to work with this. Then why Google and other Social Networks give this ability? Maybe you could do it by adding scope "offline", like it is in Google API?

I am planning to using Password grant type (for mobile app) and Authorisation code type (for 3rd party service). Setting long time for access token is bad idea, but what is the better option? Always refresh token is also not good.

**Comment by lucadegasperi** [comment]
Do it the safe way even if it is not as easy, it will reward you in the long run.
