### ISSUE TITLE
Access token length query

### ISSUE THREAD

**Issue by spronkey** [lucadegasperi/oauth2-server-laravel#405]
Looking at some other oauth2 server implementations like facebook and google, I see frequently token lengths far in excess of the 40 chars used here.

Looking into implementing this for myself I found that because of the use of the token as primary key vs a surrogate int or similar, it causes a few less than ideal queries.

Has any thought been given into how best to support longer access tokens?

**Comment by vinkla** [comment]
Since this is a Laravel wrapper of the PHP leagues package, this question is better suited at their repository. Please open an issue there https://github.com/thephpleague/oauth2-server/issues/new

**Comment by spronkey** [comment]
Hmm, the League's package doesn't specify length I believe, the issue is with the storage providers implemented by *this* package.

**Comment by vinkla** [comment]
Yes they do? Please see https://github.com/thephpleague/oauth2-server/blob/master/src/Util/SecureKey.php
