### ISSUE TITLE
Consider renaming TestCase

### ISSUE THREAD

**Issue by Daveawb** [lucadegasperi/oauth2-server-laravel#406]
Hi Luca, thanks for creating this package!

Your abstract `TestCase` class clashes with Laravels native `TestCase` class as both are in the root namespace. While this does not cause any problems in use, it's an annoyance in IDE's such as PHPStorm that recognise them both in the root namespce. This confuses the IDE and method hinting is removed. It's not imperative but would you consider renaming your `TestCase` class to something more inline with your package such as `OAuth2ServerTestCase`?

Many thanks

**Comment by vinkla** [comment]
Merged in 0fe06f3
