### ISSUE TITLE
Laravel 5 Compatibility?

### ISSUE THREAD

**Issue by activatedgeek** [lucadegasperi/oauth2-server-laravel#408]
The README shows no Laravel 5 compatibility? Are there any structural changes required?

**Comment by lucadegasperi** [comment]
Yes it is compatible. Follow the documentation in the wiki on how to set it up.

**Comment by activatedgeek** [comment]
I would suggest adding to the `README`. Thanks! :+1:

**Comment by vinkla** [comment]
@activatedgeek It is in there. The repository title is **PHP OAuth 2.0 Server for Laravel**. It also shows Laravel 5 under https://github.com/lucadegasperi/oauth2-server-laravel#version-compability
