### ISSUE TITLE
Invalid Scope Exception

### ISSUE THREAD

**Issue by vinkla** [lucadegasperi/oauth2-server-laravel#411]
I've setup a user scope for a single request in my application:

```php
$this->beforeFilter('oauth:user', ['only' => ['show']]);
```

Though, when requesting this endpoint this error is returned by the server:

```bash
The requested scope is invalid, unknown, or malformed. Check the "user" scope.
```

All the public scope calls works fine. Is there any good way to debug this? I'm currently stuck.

**Comment by vinkla** [comment]
Nevermind.

**Comment by lucadegasperi** [comment]
do you have a user scope in you oauth_scopes table? I assume yes. or you are trying to grant access to the endpoint only to users and not clients? if that's the case use the oauth-owner:user filter

**Comment by vinkla** [comment]
Yeah, thats correct. I'm trying to only grant access for requests done by the `password` grant.

**Comment by lucadegasperi** [comment]
The grant used to retrieve the access token is not stored. You could only know if the access token has been issued to a client (client_credentials) or a user (all the other grants)

**Comment by vinkla** [comment]
This is possible with `oauth-owner:user`?

**Comment by lucadegasperi** [comment]
yes.

**Comment by vinkla** [comment]
Aah cool, I'll try that. Thanks!
