### ISSUE TITLE
Authenticate user from access token?

### ISSUE THREAD

**Issue by adnanpri** [lucadegasperi/oauth2-server-laravel#412]
This is more of a question than an issue so please feel free to close it.

I know during a Password Grant the database stores a chain of info from `oauth_access_tokens` to `oauth_sessions` connecting the access token to a user (`owner_type` and `owner_id`). This _can_ be used to authenticate a user but my question is is this something that's expected to be done? If not, what do you recommend for authentication?

I had half expected the `oauth` filter to do this automatically but I guess it's not a good practice?

Edit: To clarify: the idea is to do this in a auth middleware so Auth::user() can be used in the rest of the codebase.

**Comment by lucadegasperi** [comment]
```Auth::user()``` can't be used with oauth because the authenticated client can be both accessing data on user's behalf and on it's own. Plus it could go ahead and set some cookies, and APIs should be stateless in this regard. Just stick to ```Authorizer::getOwnerId()``` and ```Authorizer::getOwnerType()```

**Comment by adnanpri** [comment]
I.. did not know about `Authorizer::getOwnerId()` and `Authorizer::getOwnerType()`! Thanks that helps.

The idea behind using `Auth::user()` is just to make it easy to retrieve the owner information for access control purposes inside controllers and middleware so you can use the existing Auth stuff from Laravel. The API itself is stateless and requires no session information so it doesn't authenticate a session this way, per se. Thanks!
