### ISSUE TITLE
Laravel 5.1 support

### ISSUE THREAD

**Issue by robinvalk** [lucadegasperi/oauth2-server-laravel#415]
I thought it would be a great idea to create some kind of to-do list for Laravel 5.1 support. 

These are my suggestions to begin with:

- [x] Create a new version and branch
- [x] Replace the filters with middlewares
- [x] Update the `composer.json`
- [x] Update the `README.md` and the wiki
- [x] Publish version 5.0

**Comment by lucadegasperi** [comment]
Worked on the first two points, what updates do you believe are needed on the composer.json file other than requiring a higher version of laravel?

**Comment by vinkla** [comment]
Dropping PHP 5.4, remove Laravel 5.0 and add stable version of orchestra/testbench package.

**Comment by digitalmio** [comment]
To be honest, the first three are the most important ones.
@lucadegasperi do you have any ETA when version for 5.1 would be ready from Composer?
Many thanks.

**Comment by vinkla** [comment]
@digitalmio It already is actually. I've been using it with 5.1 for almost a month now.

**Comment by digitalmio** [comment]
It works for me as well, beside of filter as they fee dropped from 5.1.

**Comment by vinkla** [comment]
They aren't dropped yet. Just deprecated. They will be dropped in 5.2 though.

**Comment by robinvalk** [comment]
I dont think anything else has to be edited other then the php and laravel version in the composer.json

**Comment by webdevtasolutions** [comment]
@vinkla Please share how u got filters/Middleware working to verify tokens in 5.1.
Because i can not see any 'oauth' Middleware to verify tokens.

Note: I am using Laravel 5.1

**Comment by digitalmio** [comment]
Filters do still work:
````
class UserController extends Controller
{

    public function __construct()
    {
        $this->beforeFilter('oauth');
    }
````

**Comment by webdevtasolutions** [comment]
can i define filters in group or routes?
Still i prefer to use Middleware. Wat do u suggest?

**Comment by digitalmio** [comment]
New release will use middleware instead of filters (check second message in this thread). 
I'm using filters temporarily, waiting for new version, then will replace them with middleware.

**Comment by webdevtasolutions** [comment]
@digitalmio I tried using Filters with group but they didn't work. Can you tell me how can i make it work in 5.1 using group.

Here is my code,

Route::group(array('before' => 'oauth'), function() {
Route::post('users/self', 'UserController@self');
});

**Comment by digitalmio** [comment]
```
Route::group(['before' => 'oauth'], function () { ... });
```
works fine for for me.

**Comment by hkmix** [comment]
@webdevtasolutions Make sure you're on the right version. I had the same problem because I pulled the dev branch instead of the master. If you're on the dev branch, you need to add:

```php
'oauth' => \LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware::class
```

to your Kernel.php file, and then use it as middleware:

```php
Route::group(['middleware' => 'oauth'], function () { /* route group */ });
```

**Comment by kirkbushell** [comment]
What version should we be using for this support?

**Comment by vinkla** [comment]
@kirkbushell the latest version is specified as `5.0.*dev`.

**Comment by kirkbushell** [comment]
Ah right, thank you.

**Comment by vinkla** [comment]
Version 5.0 is released!
![finished](http://i.giphy.com/nTqBNQXlEixLa.gif)
