### ISSUE TITLE
Access Token Expired - How to get a new access token.

### ISSUE THREAD

**Issue by Udders-HX** [lucadegasperi/oauth2-server-laravel#416]
I working on a application at the moment. I have the oAuth partially working, in so much that I can get an access token, and use it to pull data from my secure API endpoints. My problems come when the access token expires after 30 days.

In an ideal world I would like to just give each user a new access token every 30 days, so they never get logged out unless the explicitly request to be logged out, and then cant access the endpoints.

My problem is that I do not understand the flow of the refresh token, in my config I have the following, 

`'grant_types' => array(

        'authorization_code' => array(
            'class'            => 'League\OAuth2\Server\Grant\AuthCode',
            'access_token_ttl' => 3600,
            'auth_token_ttl'   => 3600,
        ),

        'password' => array(
            'class'            => 'League\OAuth2\Server\Grant\Password',
            'access_token_ttl' => 2592000,
            'refresh_totken_ttl' => 2592000,
            'callback'         => function ($username, $password) {
                
                $credentials = array(
                    'email' => $username,
                    'password' => $password,
                );

                $valid = Auth::validate($credentials);

                if (!$valid) {
                    return false;
                }

                return Auth::getProvider()->retrieveByCredentials($credentials)->id;
            }
        ),

        'refresh_token' => array(
            'class'                 => 'League\OAuth2\Server\Grant\RefreshToken',
            'access_token_ttl'      => 2592000,
            'refresh_token_ttl'     => 2592000,
            'rotate_refresh_tokens' => false,
        ),
        
    )`

To get a new access token I can send a post request with the user credentials to `/outh/access_token` and this is what I do for users logins. How do I run the refresh token when that access token expires?

**Comment by lucadegasperi** [comment]
Same as with the password grant type, you hit the ```oauth/access_token``` endpoint with the right set of parameters and you are set with a new access token.

**Comment by Hazemwd** [comment]
@lucadegasperi 
How can I check if the access token is expired ? so that I call the "oauth/access_token" endpoint to retrieve the new access token ?

**Comment by lucadegasperi** [comment]
Every access token comes with a expire time, store that along with the token and you'll know when the token is about or has already expired

**Comment by Hazemwd** [comment]
So should I call the api normally using my stored access token,and If I got an error message, then I'll have to call the webservice which sends a new access token. ?

**Comment by lucadegasperi** [comment]
Yes. Along with the access token you would also get an expire time. You can use that to require a new access token ahead of time. You can also have a refresh token issued to you. This would allow to require a new access token without going through the authorization process by the user (useful when using the authorization_code grant)
