### ISSUE TITLE
Need help to test the module

### ISSUE THREAD

**Issue by kartikagarwal1993** [lucadegasperi/oauth2-server-laravel#425]
I am done with the setup of the module in laravel 5. Now I need to test if the module is working on my machine. Please provide me with the steps to do so.

**Comment by kartikagarwal1993** [comment]
I tried to use postman, But when I send a post request it says 

FatalErrorException in routes.php 
Class 'Authorizer' not found


I have added following code in routes.php

Route::post('oauth/access_token', function() {
    return Response::json(Authorizer::issueAccessToken());
});

**Comment by ddelnano** [comment]
Did you use the full namespace in the file anywhere using `use LucaDegasperi\OAuth2Server;`
