### ISSUE TITLE
Wiki wrong facade

### ISSUE THREAD

**Issue by godlevel** [lucadegasperi/oauth2-server-laravel#427]
The facade class provided in the wiki is wrong. 

'Authorizer' => 'LucaDegasperi\OAuth2Server\Facades\Authorizer',

should be

'Authorizer' => 'LucaDegasperi\OAuth2Server\Facades\AuthorizerFacade',

**Comment by lucadegasperi** [comment]
thanks for reporting

**Comment by aqlx86** [comment]
Thanks, Saved my day.

**Comment by vinkla** [comment]
**Version 4.0**
```
'Authorizer' => 'LucaDegasperi\OAuth2Server\Facades\AuthorizerFacade'
```

**Version 5.0**
```
'Authorizer' => 'LucaDegasperi\OAuth2Server\Facades\Authorizer'
```
