### ISSUE TITLE
Issue with verifying tokens

### ISSUE THREAD

**Issue by kartikagarwal1993** [lucadegasperi/oauth2-server-laravel#428]
I am making a request to access user resource like this 

http://localhost:8000/user/kartik?access_token=a19ca2112a04b76ef3286c80db19d3b03f72356b

Following error occurs : Only one method may be used to authenticate at a time (Auth header, GET or POST)

I haven't send any data using post, nor I have attached any headers.

The function Bearer::getAccessTokenParameter() uses the following code 
$methodsUsed = !empty($headers) + (bool) ($request->query($this->config['token_param_name'])) + (bool) ($request->request($this->config['token_param_name']));

to count the number of methods used. The value of $methodsUsed becomes 2 .  That's why this error occurs.But since I have used only get method this should not occur.

**Comment by lucadegasperi** [comment]
It should not occur indeed, but the problem might lie somewhere else, are you sure you don't send the access token multiple times? My advice is to always use headers.

**Comment by kartikagarwal1993** [comment]
Yes. I am not sending access token multiple times. Can you tell me the format of request using headers

**Comment by kartikagarwal1993** [comment]
As far as I can analyse. The problem lies in the values returned by 
(bool) ($request->query($this->config['token_param_name']))    and
(bool) ($request->request($this->config['token_param_name']))

They both return 1, so the $methodsUsed is set to 2.

**Comment by lucadegasperi** [comment]
yes but why are they both populated with the same data? server configuration or php configuration i guess.

**Comment by kartikagarwal1993** [comment]
Ok thanks for your assistance. Any suggestions, on how can I rectify this.

**Comment by lucadegasperi** [comment]
Have no clue, never happened before and since this code is part of leauge/oauth2-server laravel, i would suggest to open an issue over there.

**Comment by kartikagarwal1993** [comment]
Ok thanks.

**Comment by kartikagarwal1993** [comment]
Anyways. Using the headers for access token solved my problem. Thanks a lot

**Comment by webdevtasolutions** [comment]
i just started using this with Laravel 5.1 and when trying to verify tokens , i am also facing issue. i feel it is missing the 'oauth' middleware  which should be there

**Comment by kartikagarwal1993** [comment]
I have added a middleware for token verification, still I faced the same issue. Try to use headers for accesstokens. It worked for me. However, the get method is still not working.

**Comment by webdevtasolutions** [comment]
@kartikagarwal1993 can u share the Middleware with me?

**Comment by kartikagarwal1993** [comment]
Yes I will be happy to

<?php

namespace App\Http\Middleware;

use Closure;
use OAuth2;
use App;
use \Illuminate\Http\Response as Response;
class AuthenticateToken
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $bridgedRequest  = OAuth2\HttpFoundationBridge\Request::createFromRequest($request);
        $bridgedResponse = new OAuth2\HttpFoundationBridge\Response();
        if (App::make('oauth2')->verifyResourceRequest($bridgedRequest, $bridgedResponse)) {
            return $next($request);
        }
        else {
            return "Error : ".$bridgedResponse->getStatusCode();
        }
    }
}

**Comment by lucadegasperi** [comment]
I'm working on middlewares for 5.1 right now, in the meanwhile you can use filters too.

**Comment by webdevtasolutions** [comment]
@lucadegasperi I tried using Filters with group but they didn't work. Can you tell me how can i make it work in 5.1.

Here is my code,
Route::group(array('before' => 'oauth'), function() {

	Route::post('users/self', 'UserController@self');
});

**Comment by hkmix** [comment]
@webdevtasolutions See my comment in #415
