### ISSUE TITLE
Grant_type parameter not accepted

### ISSUE THREAD

**Issue by IamRobin** [lucadegasperi/oauth2-server-laravel#429]
Hi,

I've been searching for hours, but I can't seem to get it to work. I've installed the package according to the instructions in the wiki and added the following to config/oath2.php

    'grant_types' => [
        'password' => [
            'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
            'callback' => function($username, $password) {
                if( Auth::validate([
                    'name'    => $username,
                    'password' => $password,
                ])){
                      $user = User::where('name',$username)->first();
                      return $user->id;
                  } else {
                      return false;
                  }
            },
            'access_token_ttl' => 3600
        ]
    ],

I've also added a route for posting to /oauth/access_token . However, when I post to http://localhost:8080/oauth/access_token?grant_type=password it keeps saying:
 
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"grant_type\" parameter."}

I know it also needs the other parameters, but it already gets stuck on the grant_type, which is checked first. The config is also set to accept query parameters in the url, instead of only in the request header.

**Comment by lucadegasperi** [comment]
If you do a POST request the parameters should be in the payload, not in the query string.

**Comment by IamRobin** [comment]
Ok, you're right. It works. I completely misunderstood the 'http_headers_only' setting.

Can you elaborate on what the setting 'http_headers_only' means? Does that only affect requests with an access token?

**Comment by lucadegasperi** [comment]
Yes. There are 3 ways to pass data around.
1. Query String
2. Payload
3. Headers

Query strings are used for filtering as well as for metadata
Headers are for metadata
Payload is for actual data.

You can combine these 3 together.

**Comment by IamRobin** [comment]
Ok. Thanks for your support.

**Comment by pavankataria** [comment]
@lucadegasperi Hey so, how can I pass the access_token into the header? I tried but it's not picking it up. I want to avoid sending the access_token for every request to a route via form variables.

**Comment by IamRobin** [comment]
You should set a header with Authorization => Bearer <token>. Obviously replace <token> with your acces token.

**Comment by IamRobin** [comment]
Authorization => Bearer token

**Comment by pavankataria** [comment]
But what if I want the header key for the access_token to be 
key: `X-ACCESS-TOKEN`, value: "access_token"?

**Comment by pavankataria** [comment]
@IamRobin But what if I want the header key for the access_token to be 
key: X-ACCESS-TOKEN, value: "access_token"?

**Comment by lucadegasperi** [comment]
That won't be standard compliant.
