### ISSUE TITLE
getResourceOwnerId() returns 1 for access_tokens generated by the password grant type

### ISSUE THREAD

**Issue by kn0ll** [lucadegasperi/oauth2-server-laravel#431]
if i obtain an access_token through the authorization code flow, like so: `curl -X POST -d 'grant_type=authorization_code&client_id=xxx&client_secret=xxx&code=xxx' http://localhost:8080/v1/oauth/access_token`

resources accessed with that access token return the proper user ID for Authorizer::getResourceOwnerId().

however, if i obtain an access_token through the password grant flow, like so: `curl -X POST -d 'grant_type=password&client_id=xxx&client_secret=xxx&username=xxx&password=xxx' http://localhost:8080/v1/oauth/access_token`

the same controller methods return 1 for Authorizer::getResourceOwnerId().

am i missing something? i am using Laravel v5.1.2, oauth2-server-laravel 4.0.2. i suppose it could be version incompatibility, but that seems somewhat unlikely since this is the only issue i've run into.

**Comment by lucadegasperi** [comment]
How does your password grant callback look like?

**Comment by teamsoo** [comment]
The callback should return the ID of authorized user, so that the same ID will be returned from calling Authorizer::getResourceOwnerId().

**Comment by kn0ll** [comment]
ah right. :persevere:

thank you both.
