### ISSUE TITLE
Argument 1 passed to League\OAuth2\Server\Entity\AbstractTokenEntity::__construct() must be an instance of League\OAuth2\Server\AbstractServer, null given

### ISSUE THREAD

**Issue by developernaren** [lucadegasperi/oauth2-server-laravel#433]
I am trying to implement an oauth2 in lumen.
Everything is working fine.

I am trying to revoke a token and I have concluded that to revoke a token I need to remove all the token related to refresh token as well.

I created an instance of  `League\OAuth2\Server\Storage\RefreshTokenInterface`

I added this to the config file;
`'refresh_token' => [
        'class' => 'League\OAuth2\Server\Storage\RefreshTokenInterface'
    ]`

`$config = Config::get('oauth2');
        $class = $config['refresh_token']['class'];
        $input = app()->make('request')->all();
        $refreshToken = $input['token'];
        $refreshTokenObj = app()->make( $class )->get( $refreshToken );`

I am trying to get the instance of the refreshtoken. I coudl directly write a query but I am trying to do this the right way.

I get this error on `get()` method

`Argument 1 passed to League\OAuth2\Server\Entity\AbstractTokenEntity::__construct() must be an instance of League\OAuth2\Server\AbstractServer, null given`

Also, i get this error if I try to delete the refresh token

`Argument 1 passed to LucaDegasperi\OAuth2Server\Storage\FluentRefreshToken::delete()`

Please help.

**Comment by lucadegasperi** [comment]
You should implement token deletion all by yourself, there's no delete method on the FluentRefreshToken as it is not an Eloquent record.

**Comment by developernaren** [comment]
I tried to do this like this because there seems to be a class 

    public function get($token)
    {
        $result = $this->getConnection()->table('oauth_refresh_tokens')
                ->where('oauth_refresh_tokens.id', $token)
                ->where('oauth_refresh_tokens.expire_time', '>=', time())
                ->first();

        if (is_null($result)) {
            return null;
        }

        return (new RefreshTokenEntity($this->getServer()))
               ->setId($result->id)
               ->setAccessTokenId($result->access_token_id)
               ->setExpireTime((int)$result->expire_time);
    }

there is this class `FluentRefreshToken` and I am trying use this `get` method and by my code I see that the query is successfully executed and it is just that it is having a hard time creating this 
`new RefreshTokenEntity($this->getServer())`  class. If this accomplished I could use the delete method in the same class.I am trying to do this like this to consolidate my codes. Is this possible. is there any solution or do I have to do this all by myself? I i could just get the `RefreshTokenEntity` class to successfully create, I seem to be able to do this.

**Comment by lucadegasperi** [comment]
It is having a hard time because you would need to pass an AbstractServer instance in the constructor.

**Comment by developernaren** [comment]
Not exactly, I looked into the codes and I see no way that I can pass the server instance, it seems to fetch it itself using some other class. There is nothing I can do without changing the source code. The class is failing to create the server instance. If that somehow can be fixed, my code would work flawless but i am not sure how to do that.

**Comment by lucadegasperi** [comment]
In the first place why are you revoking an access token by using a refresh token? to extend the functionality of the provided storage classes try to subclass them and register them in the IoC to replace the one you are extending.

**Comment by developernaren** [comment]
first things is I am totally new to this implementation and I am learning as I go.
I am using this in one of my angular apps and using `angular-oauth2` for that. When it hits the `revokeAccessToken` method, it seems to send the `token` as post. I have the `access token` in `header`. My first instinct was that I would simply `delete` the `access token` from the `table` but since I got `refresh token` in post as 'token', i thought it should be "right" to delete that to delete all the tokens related to that( they seem to cascade). 

Like I said, I am learning as i am implementing this. I tried to google the "correct" way to revoke an `access token` but could not find a good resource on that so I thought this is the "right" way because it made sense to me and trying to implement that and also I looked around in the `classes` and there were `methods` and `classes` that did that, so just trying things out, the things that seemed better.

**Comment by lucadegasperi** [comment]
The refresh token is just a "temporary" type of token and is always associated to an access token, in order to revoke them both, you would need to delete the session associated with the access token. Plus there's a specification by the IETF for explicitly revoking tokens. http://tools.ietf.org/html/draft-ietf-oauth-revocation-06

**Comment by developernaren** [comment]
Thanks for the link, its helpful 
I will create a class/system based on this.
And thanks for the quick replies. You are the best :)
