### ISSUE TITLE
Naming Conflict -- DatabaseSeeder

### ISSUE THREAD

**Issue by mixnetworks** [lucadegasperi/oauth2-server-laravel#435]
Can you rename your DatabaseSeeder class? It has no namespace defined and by default, the app/database/seeds/DatabaseSeeder class also has no namespace which causes conflict.

**Comment by ht2** [comment]
+1!

**Comment by vinkla** [comment]
Fixed in b572ab6b4f952f0a963c4ce086540d98e04cdefe.
