### ISSUE TITLE
Authorization Server with the Password Grant - I am probably missing something

### ISSUE THREAD

**Issue by huglester** [lucadegasperi/oauth2-server-laravel#436]
Hello,

this is my first shot into 0Auth2 server world :)

I will share what I have done..
So I migrated and seeded database with some default data from this repo.

I have added:
```php
    'grant_types' => [

        'password' => array(
            'class'            => 'League\OAuth2\Server\Grant\PasswordGrant',
            'access_token_ttl' => 604800,
            'callback'         => 'App\UserVerifier',
        ),

    ]

// Verifier:
<?php

namespace App;

class UserVerifier {

    public function verify($username, $password)
    {
        $credentials = [
          'email'    => $username,
          'password' => $password,
        ];

        // if (Auth::once($credentials)) {
        //     return Auth::user()->id;
        // }
        return 'client1id';

        return false;
    }
}

```

I have these routes:
```php
Route::post('oauth/access_token', function() {

    return Response::json(Authorizer::issueAccessToken());
});

Route::get('news', function() {

    return [
        ['id' => 2, 'title' => 'Something new'],
        ['id' => 1, 'title' => 'USA spying on France'],
    ];
});

Route::get('users', ['middleware' => 'oauth', function() {

    return [
        ['id' => 2, 'username' => 'User2'],
        ['id' => 1, 'username' => 'User1'],
    ];
}]);
```

I am able to access 'news' routes;
tried accesssing /users with access_token = totallyanaccesstoken1 (from seeded data), but I get:
```json
{
    "error": "access_denied", 
    "error_description": "The resource owner or authorization server denied the request."
}
```

And finnaly I am not sure what to post to /oauth/access_token?
I tried: ` http POST http://testapi.app/oauth/access_token username=username password=secret `
But no luck. I simply get this:
```json
{
    "error": "invalid_request", 
    "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"grant_type\" parameter."
}

```

I am sure I am missing something here. Could anyone point me on some directions?
I tried reading wiki few times, but probably still missed something :/

Thanks a lot in advance!

**Comment by lucadegasperi** [comment]
to get an access token with the password grant type you have to pass the following things in the payload

```
username=youruserusername
password=youruserpassword
grant_type=password
client_id=theclientid
client_secret=theclientsecret
```

Once you get a valid access token try hitting the route again.

**Comment by huglester** [comment]
Hello, you were absolutely right. This one works!

Thanks for this. But I have then one more question then...
Let's imagine there is frontend (www.site.com)
and API (api.site.com)

I want user entering username/password combo - be validated via API.

In this scenario, user entering the www.site.com/login, and posting username/password .. where would I get the `client_id` and `client_secret` then? Is there more steps needed here?  Maybe I have missed some steps in the WIKI ?

Thanks in advance!

**Comment by lucadegasperi** [comment]
Usually the authentication part is kept separated from the API, which means www.site.com is responsible for providing the access tokens back to the client to then make requests to the API. Now, the client can be one you trust (for example your own iOS app) or one you don't trust (a third party app). Based on this you would choose the best grant type to use.
In the first case the user enters its credentials straight into the app, which then sends the data to the access token endpoint (with the password grant type) and gets an access token back.
In the second case, the client opens a browser window to your login page, the user enters its credentials there and is prompted to authorize the client to access its data. On success, the browser redirects to a specific page on the client website with an authorization code. The client then hits the access token endpoint (with the authorization_code grant type) with the authorization code and gets an access token.

**Comment by huglester** [comment]
Understood. Thanks for explanation.

I do not want to start new topic, but for example I try to get 'access_token' via:
`http POST http://testapi.app/oauth/access_token username=user password=password grant_type=password client_id=clientid client_secret=clientsecret`

I get the token. But is there a way, to 'specify' sope from the backend side?

Because, what I want, is to 'bind' scope to be like 'user groups'.
And do, something like this in verifier:

```php
class UserVerifier {

    public function verify($username, $password)
    {
        // login stuff..
        $user = User...
        if ($user->isAdmin()) {
            // allow ALL scopes
            return $user->id;
        elseif ($user->isPublisher()) {
            // allow scope 'publisher'
            return $user->id;
        }
        else {
           return $user->id;
        }

        return false;
    }
}
```

is that possible to achive somehow? Because when user is trying to log in, I do not know what to which   group/scope he does belongs.

Thanks !

**Comment by lucadegasperi** [comment]
Scopes and groups are two different things. Scopes are to tell what information the client can access on user's behalf, groups are to tell what the user itself can access inside the app, they are in fact complementary.

**Comment by huglester** [comment]
`what information the client can access on user's behalf` - you mean 'email', 'date_of_birth' and so on?

Am I wrong or current wiki does not yet have information about the 'Groups' usage? After looking threw the mysql tables, I do see anything similar to 'groups'. Maybe you could point me somewhere? 

Thanks a lot for you time @lucadegasperi !

**Comment by lucadegasperi** [comment]
yes exactly.

groups are something up to your business logic to implement.

**Comment by huglester** [comment]
So to sum up, I basicly can clone PasswordGrant.php class to my app. And try to configure it the way my app needs it to be?

**Comment by lucadegasperi** [comment]
nope. Groups are a separate thing and don't need to interact with oauth in any way. Once you get the user id associated with the access token with the Authorizer::getResourceOwnerId() method, you fetch the user's group membership and display your data accordingly.

**Comment by huglester** [comment]
Hello, I think we solved the main issue :) thans for help!
