### ISSUE TITLE
Laravel 5.0 Configuration Issue: Class LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware does not exist

### ISSUE THREAD

**Issue by nekyian** [lucadegasperi/oauth2-server-laravel#438]
I followed the wiki and did all the steps. When accessing a protected route I get:
ReflectionException in Container.php line 779:
Class LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware does not exist

I am trying to setup the password grant_type.

When trying to access oauth/access_token I get another error:
ErrorException in PasswordGrant.php line 62:
Argument 1 passed to League\OAuth2\Server\Grant\PasswordGrant::setVerifyCredentialsCallback() must be callable, string given, called in /home/nekyian/Projects/rolii/vendor/lucadegasperi/oauth2-server-laravel/src/OAuth2ServerServiceProvider.php on line 103 and defined

Could you please help? I tried googling these errors with no success before creating this issue :(

**Comment by lucadegasperi** [comment]
That version of the wiki page is for L5.1 and the develop branch of this package, heres the one you should use for L5.0 https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Laravel-5-Installation/a62950c8bf785bf80177a4aeca4b5aa05fec02ff

**Comment by nekyian** [comment]
Thank you VERY MUCH for the prompt reply! If you have something setup I want to donate!(10$)
I will get back after trying :)
Thanks again for all your work!

**Comment by nekyian** [comment]
I followed the docs. No change.
I am trying to call the oauth/access_token url with grant_type=password and get:
ErrorException in PasswordGrant.php line 62:
Argument 1 passed to League\OAuth2\Server\Grant\PasswordGrant::setVerifyCredentialsCallback() must be callable, string given, called in /home/nekyian/Projects/rolii/vendor/lucadegasperi/oauth2-server-laravel/src/OAuth2ServerServiceProvider.php on line 103 and defined

Here is my grant_types array
```PHP
    'grant_types' => [
	    'client_credentials' => [
		    'class' => '\League\OAuth2\Server\Grant\ClientCredentialsGrant',
		    'access_token_ttl' => 3600
	    ],
	    'password' => [
		    'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
		    'callback' => '\App\Verifier@verify',
		    'access_token_ttl' => 3600
	    ],
	    'refresh_token' => [
		    'class' => '\League\OAuth2\Server\Grant\RefreshTokenGrant',
		    'access_token_ttl' => 3600,
		    'refresh_token_ttl' => 36000
	    ]
    ],
```

I have put client and password the grant_types for start.

**Comment by lucadegasperi** [comment]
Here: https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Password-Grant/e6e4c0bc676ede5c3ee12df750bf012d7b1ebf33

**Comment by nekyian** [comment]
:( I manage to figure this one out myself, but I forgot to mention I am on MongoDB with Moloquent.
I am trying to install swaaj/oauth2-server-laravel but it doesnt have a package :(

**Comment by nekyian** [comment]
I saw you accepted a pull request with mongo support then removed it. Too bad...

**Comment by lucadegasperi** [comment]
Don't think I ever accepted a mongo PR, but there should be a package around that implements the correct storage interfaces for mongo.

**Comment by nekyian** [comment]
Error: Class LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware does not exist
The problem was the autoload_psr4.php file that composer generated, which didnt include the path to this package.
I managed to install https://github.com/swaaj/oauth2-server-laravel, that has mongo support, by specifiying the repo and the autoload for that repo.

The second problem I solved by putting a closure in oauth2.conf like this:

```PHP
    'grant_types' => [
	    'password' => [
		    'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
		    'callback' =>function ($username, $password) {
				$credentials = [
					'email'    => $username,
					'password' => $password,
				];

				if (Auth::once($credentials)) {
					return Auth::user()->id;
				}

				return false;
			},
		    'access_token_ttl' => 3600
	    ],
	    'refresh_token' => [
		    'class' => '\League\OAuth2\Server\Grant\RefreshTokenGrant',
		    'access_token_ttl' => 3600,
		    'refresh_token_ttl' => 36000
	    ]
    ],
```

Please excuse me for opening this issue, I should've read the docs more before asking...
