### ISSUE TITLE
scope id

### ISSUE THREAD

**Issue by suraleb** [lucadegasperi/oauth2-server-laravel#439]
if I use 'before' => 'oauth:"scope_id"' its work correct, but when I use "scope" from table oauth_scopes than  its not work! how can I fix it?

**Comment by lucadegasperi** [comment]
what do you mean?

**Comment by suraleb** [comment]
befo oauth use id from oauth_scopes table, but I want to use "scope" from this table

**Comment by lucadegasperi** [comment]
not sure what the problem is, the scope names you should use in the oauth filter are the one you set in the oauth_scopes table.

**Comment by suraleb** [comment]
in oauth_scopes table I have
# id, scope, name, description, created_at, updated_at
'2', 'rw', 'read, write', 'read and write', '2015-06-25 08:23:59', '2015-06-25 08:23:59'
'1', 'r', 'read', 'read', '2015-06-25 08:23:59', '2015-06-25 08:23:59'

if in routes I use 'before' => 'oauth:1' all work fine
but if I use 'before' => 'oauth:r' its dosent work

**Comment by suraleb** [comment]
wow sorry for font-size its copy-paste

**Comment by suraleb** [comment]
Is any ideas what i do wrong?

**Comment by suraleb** [comment]
sorry, not correct database structure!
