### ISSUE TITLE
Get access token owner in password grant type.

### ISSUE THREAD

**Issue by kartikagarwal1993** [lucadegasperi/oauth2-server-laravel#440]
How can I find the owner of an access token while using password grant type. I am using oauth middleware for verfication of tokens

**Comment by lucadegasperi** [comment]
```Authorizer::getAccessTokenOwnerId()```

**Comment by kartikagarwal1993** [comment]
I want the username for profile related operations.

**Comment by lucadegasperi** [comment]
You'll get an ID back, use that to fetch the user from Eloquent or your storage system.

**Comment by rjcoupe** [comment]
@lucadegasperi The user ID is returned when the credentials are verified, but can it be retrieved on later requests with the access_token given instead?

**Comment by lucadegasperi** [comment]
@rjcoupe ```Authorizer::getResourceOwnerId()```
