### ISSUE TITLE
secure endpoint by access token owner

### ISSUE THREAD

**Issue by cenob8** [lucadegasperi/oauth2-server-laravel#441]
As explained here at the bottom of the page (https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Securing-your-API-endpoints) I am trying to secure an endpoint so that only the user grant type has access by adding the following line being called in the controller constructor :

```
$this->middleware('oauth-owner:user', ['only' => ['index']]);        
```

This throws an error : 

```
in_array() expects parameter 2 to be array, string given
```

In OAuthOwnerMiddleware.php the handle method expects an array for the ownerTypes instead of a string : 

```
    public function handle($request, Closure $next, $ownerTypes = [])
    {
        
        if (!in_array($this->authorizer->getResourceOwnerType(), $ownerTypes)) {
            throw new AccessDeniedException();
        }

        return $next($request);
    }

```

So how am i supposed to accomplish this? Or is this a bug?

**Comment by lucadegasperi** [comment]
most definitively a bug. Checking wether it's Laravel's or my fault.

**Comment by lucadegasperi** [comment]
What happens if you enter ```'oauth-owner:user,client'```` does it work properly in that case?

**Comment by cenob8** [comment]
no, still gives the same error. If I var_dump the $ownerTypes parameter in the handle method it returns "user":
```
   public function handle($request, Closure $next, $ownerTypes)
    {
        var_dump($ownerTypes);
```

**Comment by lucadegasperi** [comment]
Weird, which version of Laravel 5.1 are you on?

**Comment by lucadegasperi** [comment]
Okay now I see, parameters are splitted up and sent as function arguments. This isn't good. I need to work on a solution.

**Comment by cenob8** [comment]
The latest version I think. But aren't multiple arguments supposed to be passed by defining a variable for each argument ?

Like so : 
```
public function handle($request, Closure $next, $argument1, $argument2)
```
This way if i pass 'oauth-owner:user,client'` i can fetch "user" with $argument1 and "client" with $argument2

**Comment by cenob8** [comment]
Yeah our comments crossed :-)  
Indeed, to pass an array of arguments some workaround is needed i guess

**Comment by lucadegasperi** [comment]
Indeed they are, problem is you can pass an arbitrary amount of parameters to a middleware. Probably changing the string splitter character is going to solve this.

**Comment by cenob8** [comment]
What about using a variadic parameter? This works  : 

```
public function handle($request, Closure $next, ...$ownerTypes)
{ var_dump($ownerTypes);
```

returns : 

```
array:2 [
  0 => "user"
  1 => "client"
]
```

**Comment by lucadegasperi** [comment]
They are implemented in 5.6, I need to support PHP 5.5.9 Minimum.

Anyways the solution is to not use the ```,``` as a delimiter. I've opted for ```+``` instead.

**Comment by lucadegasperi** [comment]
Everything should work fine with the latest commit.

**Comment by cenob8** [comment]
Thanks. Will try it out when i get back home.

**Comment by cenob8** [comment]
Confirmed. It works. Thanks !

**Comment by pavankataria** [comment]
@cenob8 Hey buddy, you seem to be aware on the purpose of the having something only accessibly by the user grant type. This is the passage I'm confused with: 
```When using the client_credentials grant type, the access token owner and the client can be the same entity to distinguish this particular case there's the oauth-owner middleware. Parameters for this middleware are either client or user```

Could you tell me some applications where this oauth-owner middleware would be used? I'm making an API for a mobile app, thank you.
