### ISSUE TITLE
Middleware format error in wiki for Laravel 5.1

### ISSUE THREAD

**Issue by hkmix** [lucadegasperi/oauth2-server-laravel#443]
Laravel 5.1
oauth2-server-lavavel dev (~4.1)

The series of middleware should be changed to an array instead of a pipe-delimited list, so:

```php
Route::get('oauth/authorize', ['middleware' => 'check-authorization-params|auth', function() {
```

should be:
```php
Route::get('oauth/authorize', ['middleware' => ['check-authorization-params', 'auth'], function() {
```

Otherwise, it throws `Class check-authorization-params|auth does not exist`.

**Comment by lucadegasperi** [comment]
Thanks!
