### ISSUE TITLE
Lumen 5.1 installation fails

### ISSUE THREAD

**Issue by rjcoupe** [lucadegasperi/oauth2-server-laravel#445]
After following the [guide in the wiki](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Lumen-Installation):

````
 $ grep oauth2-server-laravel composer.json && composer update
	"lucadegasperi/oauth2-server-laravel": "~4.1"
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package lucadegasperi/oauth2-server-laravel could not be found in any version, there may be a typo in the package name.
````

**Comment by lucadegasperi** [comment]
add @dev after the version number

**Comment by rjcoupe** [comment]
Success; thanks.

**Comment by rjcoupe** [comment]
@lucadegasperi - A bit further down the line, an error is thrown due to config_path() not being defined, but called at `/vendor/lucadegasperi/oauth2-server-laravel/src/OAuth2ServerServiceProvider.php:48`.

Isn't this function missing from Lumen altogether?

**Comment by lucadegasperi** [comment]
https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Lumen-Installation#migrate

**Comment by rjcoupe** [comment]
I have the alias set in app.php already (and `$app->withFacades()` uncommented).

**Comment by rjcoupe** [comment]
Hard-coding the path to the config file resolves this - obviously not ideal but serves as a band-aid.

**Comment by lucknerjb** [comment]
The issue still happens on Lumen 5.1 with the following composer line:

"lucadegasperi/oauth2-server-laravel": "~4.1@dev"

Looking at the tags and packagist versions, there is no version 4.1 published. 4.0.1 and 4.0.2 are valid versions... should we be using those instead (4.0.*)?

**Comment by vinkla** [comment]
Try using version 5.0 instead.
