### ISSUE TITLE
Undefined index: client in AuthCodeGrant

### ISSUE THREAD

**Issue by nmakow** [lucadegasperi/oauth2-server-laravel#447]
Hi there,

I'm not sure why/where this error comes from. I having installed the OAuth and I'm using the exact controller/view setup as described in this post: https://github.com/lucadegasperi/oauth2-server-laravel/issues/364.
Edit: The full error message is: 
ErrorException in AuthCodeGrant.php line 150:
Undefined index: client

There was another issue raised about this but there was not a very informative response/solution. 
Edit: similar issues were found in #394, #393, and a few others. 

Whenever you get a moment please let me know what you think might be causing this! I appreciate it!

Noah

**Comment by nmakow** [comment]
Just to give some extra information:

I send the GET request to /oauth/authorize with the client_id, response_type=code, redirect_uri (all of these items are correctly stored in the oauth_clients and oauth_client_endpoints tables). This request seems to go through, as it renders the view for the authorization form. It is upon submitting the authorization form that this error arises.

**Comment by nmakow** [comment]
I fixed the above issue, however I still am confused on the following:

I never actually enter my credentials/log in to the site for which I am obtaining the access token. How does the access_token created know which user it is for if I do not specify by logging in?

**Comment by lucadegasperi** [comment]
Well, you should authenticate your user (using a normal login form) before showing the client authorization page.

**Comment by nmakow** [comment]
thanks for the response, I appreciate it. I was forgetting the 'auth' middleware on the routes.

**Comment by KeitelDOG** [comment]
I'm having the same problem in Laravel 4.2 with and undefined index client, resulting from an empty params array on getAuthCodeRequestParams() method. I use check-authorization-params filter with before, but with no luck.
I don't want to open an issue yet, but however, all issues about this was closed as solved, but none of them pointed at and hint or the cause of their problem.
