### ISSUE TITLE
Call to a member function getSession() on null

### ISSUE THREAD

**Issue by pavankataria** [lucadegasperi/oauth2-server-laravel#448]
Why is it that I can use the getResourceOwnerId() in a method where we use the oauth middleware but we can use it in the `auth` route?

This is the code I have so far:

```php
Route::post('auth', function() {
   $accessTokenArray = Authorizer::issueAccessToken();

   return Response::json($accessTokenArray);
});

Route::post('hello', ['middleware' => 'oauth', function() {
	$id = Authorizer::getResourceOwnerId()

	return "Access token validation successful . {$id}";
}]);
```

Using `$id = Authorizer::getResourceOwnerId();` after the access token is created before the response is returned I get a `Call to a member function getSession() on null`

**Comment by lucadegasperi** [comment]
Because in order to get the owner of the access token you would need to parse and validate it and that's what the oauth middleware does.

**Comment by pavankataria** [comment]
Thank you for replying @lucadegasperi, could you guide me then on how I could retrieve the user associated to the access token issued please?

Something must be possible as the user has successfully authenticated and therefor it should be possible to retrieve the user.

$accessTokenArray = Authorizer::issueAccessToken();
How can I retrieve the user? perhaps the user can be identified that's associated to this access token? Or perhaps another way?

**Comment by lucadegasperi** [comment]
```Authorizer::getResourceOwnerId()```

**Comment by teamsoo** [comment]
@pavankataria , try this flow if you really want to get user from token.


    $token = $accessTokenArray['access_token']
    $AccessToken = OauthAccessToken::find($token);
    $OauthSession = OauthSession::find($AccessToken->session_id);
   
    User::find($OauthSession->owner_id)->first();

First, get token string from the result array. then get *OauthAccessToken* object from db (table oauth_access_token maybe ... I'm not sure about the name).

Now you can use session_id of *OauthAccessToken* to get *OauthSession* ( table oauth_session or something).

Finally, the *OauthSession* will contains the owner_id and you can use the ID to get authorized user.

***OR!***
Sometimes, you can juse use the username and password to get the authorized user? User will send username, password, client_id, bla bla bla

You can just use ***Input::get('username')*** and use that username to query from your user table.

Hope this is what you're looking for.

**Comment by lucadegasperi** [comment]
Guys there's the ```Authorizer::getResourceOwnerId()``` that returns the owner of the access token.

**Comment by teamsoo** [comment]
@lucadegasperi 

In his case,

calling 

    Authorizer::getResourceOwnerId()

right after 

    $accessTokenArray = Authorizer::issueAccessToken()

wouldn't work.

Ex.

    Route::post('auth', function() {
        $accessTokenArray = Authorizer::issueAccessToken();
        $user_id = Authorizer::getResourceOwnerId(); <------ This wouldn't work
        return Response::json($accessTokenArray);
    });


So, I think he needs a little work around to get what he wants (if I understand his question correctly).

**Comment by lucadegasperi** [comment]
Yes that's true, which grant type are you using in this particular case?

**Comment by teamsoo** [comment]
Password type should work. Maybe :+1:

**Comment by lucadegasperi** [comment]
Ok then you should have access to the payload, verify the user by yourself and get back its id.

**Comment by teamsoo** [comment]
So, this may work only with Password Grant then. Thanks.

**Comment by lucadegasperi** [comment]
It will work with the authorization_code grant as well.

**Comment by teamsoo** [comment]
@lucadegasperi  OK. Thanks :)

**Comment by sshfl** [comment]
This error also encounter to me, I use laravel 5.1 recently;
I use oauth 2 via composer with "lucadegasperi/oauth2-server-laravel": "5.0.*",;

fix this bug:
// call first
Authorizer::validateAccessToken();
// then call
Authorizer::getResourceOwnerId();
// ok I get the uid
