### ISSUE TITLE
The request is missing a required parameter

### ISSUE THREAD

**Issue by dharmendrajadon** [lucadegasperi/oauth2-server-laravel#449]
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"client_id\" parameter."}

**Comment by lucadegasperi** [comment]
Are you passing the data in the payload or in the query string?

**Comment by dharmendrajadon** [comment]
In query string

**Comment by lucadegasperi** [comment]
put it in the payload since it is a post request.

**Comment by neerajgoyal12** [comment]
What all parameters need to be sent to post request 
I am sending a 
+ username - one@example.com
+ password - 123456
I am using postman to send the request to the url.

**Comment by lucadegasperi** [comment]
```
grant_type=password
client_id=client id you have registered in the db
client_secret=client secret you have registered in the db
username=username
password=password
```

**Comment by neerajgoyal12** [comment]
Thanks a lot that worked.

**Comment by rjcoupe** [comment]
I'm having the same issue as @neerajgoyal12, only the payload suggested by @lucadegasperi hasn't helped.

Attached is an image from Postman showing the query and response.

![screen shot 2015-06-29 at 11 29 11](https://cloud.githubusercontent.com/assets/129647/8406222/40855376-1e52-11e5-8317-318d91fb1eb0.png)

+ Lumen 5.1.1

**Comment by dharmendrajadon** [comment]
First time it do receives these all parameters(in middleware) but on clicking Approve button, I gets an error for missing parameters.
This is my Authorize form, I'm not getting $params['client_id'], it is undefined.
    {!! Form::open(array('class'=>'form-horizontal form-signin', 'url'=> URL::route('post oauth authorize', $params))) !!}
    {!! Form::hidden('client_id', '1', array('class' => 'form-control')) !!}
    {!! Form::hidden('redirect_uri', $params['redirect_uri'], array('class' => 'form-control')) !!}
    {!! Form::hidden('response_type', $params['response_type'], array('class' => 'form-control')) !!}
    {!! Form::hidden('state', $params['state'], array('class' => 'form-control')) !!}
    {!! Form::submit('Approve', array('name'=>'approve', 'class'=>'btn bg-blue btn-primary')) !!}
    {!! Form::submit('Deny', array('name'=>'deny', 'class'=>'btn bg-red')) !!}
    {!! Form::close() !!}

**Comment by lucadegasperi** [comment]
@rjcoupe You are on the right way, if you get that error, you need to enable the correct grant type in the configuration.

**Comment by lucadegasperi** [comment]
@dharmendrajadon the parameters in that case need to be in the form action inside the query string.

**Comment by rjcoupe** [comment]
@lucadegasperi That's what I initially assumed, but I'm not sure what's wrong with what I already have:

````
'grant_types' => [
        'password' => [
            'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
            'callback' => '\App\Http\Controllers\AuthController@verify',
            'access_token_ttl' => 3600
        ]   
    ]
````

**Comment by lucadegasperi** [comment]
oh I see, since you are on lumen the configuration file isn't read. Have you enabled the $app->configure() to read the config file?

**Comment by rjcoupe** [comment]
@lucadegasperi Boom! That was it - adding `$app->configure('oauth2');` to app.php seems to have resolved the issue.

Thanks for your patience and help!
