### ISSUE TITLE
Not seeing my user

### ISSUE THREAD

**Issue by beznez** [lucadegasperi/oauth2-server-laravel#452]
I'm not sure if this is the most appropriate place to ask this question since it's about the use of the package. I'm making an API in Laravel 5.1 and I'm trying to implement this package. I followed the [laravel installation guide](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Laravel-5-Installation) in the wiki. For this package, I couldn't get `4.1` as it threw an error so I'm using `dev-master` installed through `composer`. After I installed the package, I followed the [password grant guide](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Password-Grant) in the wiki. I tried looking through the [5.1 support issue](https://github.com/lucadegasperi/oauth2-server-laravel/issues/415) but I couldn't find my problem. However, it did solve some other preliminary problems I had.

So I used curl to try to get an access token.

```curl
curl "http://domain.com/oauth/access_token" -d "grant_type=password" -d "client_id=client1id" -d "client_secret=client1secret" -d "username=user" -d "password=pass"
```

And I get this response.

```json
{"error":"invalid_credentials","error_description":"The user credentials were incorrect."}
```

I have the user `user` in my `users` table and the password is `Hash::make('pass')`. I also ran the migrations and seeded my database with the seeders so I have all the oauth tables and there is data in them. Is the package looking in one of the oauth tables for the user?

**Comment by kielabokkie** [comment]
@beznez Use `bcrypt('pass')` to set the password for a user instead of `Hash::make('pass')`

**Comment by lucadegasperi** [comment]
Nope, you need to provide a callback method to authenticate the user against your system. In order to get version 4.1 of the package, you need to append @dev after the version since I haven't tagged it yet.

**Comment by beznez** [comment]
That worked fine and I now have the 4.1 dev package. Thanks a lot! Any idea when the full version of 4.1 will be released?
