### ISSUE TITLE
Mistake in the wiki

### ISSUE THREAD

**Issue by kylescousin** [lucadegasperi/oauth2-server-laravel#454]
On this page https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Auth-Code-Grant - 

"app/config/packages/lucadegasperi/oauth2-server-laravel/oauth2.php" is not the path to that file (anymore?) - it's just app/config/oath2.php

**Comment by vinkla** [comment]
What version of Laravel are you using? It looks like the Laravel 4 implementation is written in the wiki. We should probably update it to Laravel 5.

**Comment by kylescousin** [comment]
Yeah I am using L5.1 so

**Comment by vinkla** [comment]
This has now been fixed. Thanks.
