### ISSUE TITLE
Error when trying to seed dbs

### ISSUE THREAD

**Issue by lukasoppermann** [lucadegasperi/oauth2-server-laravel#458]
Hey,

when I run the example seeds, I get the following error using lumen 5.1.1.

```SQL
[PDOException]
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`oauth`.`oauth_auth_codes`, CONSTRAINT `oauth_auth_codes_session_id_foreign` FOREIGN KEY (`session_id`) REFERENCES `oauth_sessions` (`id`) ON DELETE CASCADE)
```

**Comment by lucadegasperi** [comment]
there are no example seeds, they are meant for testing only.

**Comment by lukasoppermann** [comment]
Ahh, I see, I though you added those maybe to address this one https://github.com/lucadegasperi/oauth2-server-laravel/issues/175. I will close this issue, but maybe you should add some Warning or something?

Thanks for the quick reply.
