### ISSUE TITLE
ReflectionException in Container.php line 736: Class LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware does not exist

### ISSUE THREAD

**Issue by cschalenborgh** [lucadegasperi/oauth2-server-laravel#461]
Hey guys,

I get this error:
```php
ReflectionException in Container.php line 736:
Class LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware does not exist
```

When trying to add the middleware to my controller via:
```php
    public function __construct()
    {
        $this->middleware('oauth');
    }
```

Any ideas why this is happening and how to fix?

If I use the WithoutMiddleware trait in my unit tests it works though. But the normal endpoints return that error.

**Comment by brti** [comment]
I'm getting a similar error when trying to use the `check-authorization-params` middleware.

`Class LucaDegasperi\OAuth2Server\Middleware\CheckAuthCodeRequestMiddleware does not exist`

Any ideas?

**Comment by lucadegasperi** [comment]
Which version of this package are you using?

**Comment by brti** [comment]
Managed to fix it changed from 4.0 to 4.1@dev in my composer. json

**Comment by EwanValentine** [comment]
I can't actually seem to use version 4.1? I can't see it tagged in the repo, and when I update I get

```
Problem 1
    - The requested package lucadegasperi/oauth2-server-laravel 4.1@dev could not be found.
```

**Comment by brti** [comment]
Put either `dev-master` in the version or `4.1.*@dev`, if you're unsure as to which version to use just check the page on packagist https://packagist.org/packages/lucadegasperi/oauth2-server-laravel.

**Comment by EwanValentine** [comment]
Ahhh brilliant! Thanks, that sorted it.

**Comment by EwanValentine** [comment]
When I run ```$ php artisan vendor:publish ``` now, it returns ``` Nothing to publish for tag []. ``` I raised a separate ticket but no one's responding...

**Comment by mpetkov** [comment]
I am using L5 and 4.1.*@dev and I am still getting this error.  When I went into the vendor folder for LucaDegasperi, I can't find a class with the name"OAuthMiddleware".  What should I do?

**Comment by lucadegasperi** [comment]
If using L5.0 use version 4.0 of the package. You won't have all the middlewares there though, and you should use filters instead.

**Comment by j4k** [comment]
will these eventually be moved to middleware?

**Comment by lucadegasperi** [comment]
Everything is moved to middleware if using L5.1 and 4.1@dev of this package. L5.0 didn't support middleware parameters so stuff had to be implemented with filters.
