### ISSUE TITLE
Duplicate class DatabaseSeeder

### ISSUE THREAD

**Issue by jurosh** [lucadegasperi/oauth2-server-laravel#467]
Hi I get this warning while updating composer. Can you fix that ?

using version ~4.1@dev = dev-develop

Warning: Ambiguous class resolution, "DatabaseSeeder" was found in both "$baseDir . '/database/seeds/DatabaseSeeder.php" and "/home/vagrant/Code/ticketware/vendor/lucadegasperi/oauth2-server-laravel/database/seeds/DatabaseSeeder.php", the first will be used.

**Comment by vinkla** [comment]
I can confirm this warning. @lucadegasperi maybe we should just rename it?

**Comment by AndyWendt** [comment]
:+1:  for rename

**Comment by vinkla** [comment]
Fixed in https://github.com/forkify/oauth2-server-laravel/commit/b572ab6b4f952f0a963c4ce086540d98e04cdefe
