### ISSUE TITLE
$authorizer->getResourceOwnerId() Returning strange HTTP Response string

### ISSUE THREAD

**Issue by james-ff** [lucadegasperi/oauth2-server-laravel#469]
When I run $authorizer->getResourceOwnerId() I get back a string non-object that looks something like this:

"HTTP/1.0 200 OK\r\nCache-Control: no-cache\r\nContent-Type:  application/json\r\nDate:          Sun, 19 Jul 2015 19:25:17 GMT\r\n\r\n{\"user_id\":\"1\"}"

Anyone have any ideas why it isn't passing the ID on its own, or how to extract the ID from this?

**Comment by lucadegasperi** [comment]
Probably some weird setup on your side. This is by far the strangest thing that happened.

**Comment by james-ff** [comment]
Fixed.

I agree, I believe it was something strange on my side. Probably a cached file that wasn't being updated.

My apologies
