### ISSUE TITLE
Laravel 5 Installation Issue 

### ISSUE THREAD

**Issue by j4k** [lucadegasperi/oauth2-server-laravel#470]
```php
'oauth-owner' => 'LucaDegasperi\OAuth2Server\Middleware\OAuthOwnerMiddleware',
'check-authorization-params' => 'LucaDegasperi\OAuth2Server\Middleware\CheckAuthCodeRequestMiddleware'
```

Is mentioned in the docs, however these seem to be in the filters namespace in `4.0.1` are these intended to be middleware, or are the docs incorrect? Should I amend the docs?

**Comment by lucadegasperi** [comment]
Docs is updated for the upcoming 4.1 release of the package that supports L5.1 going back a few revisions on the wiki, you should find the right way to set it up.

**Comment by mishudark** [comment]
I have the same problem, any suggestion?

**Comment by axelardu** [comment]
Where did the laravel5 release go? Can't seem to find it!

**Comment by vinkla** [comment]
What version have you specified?

**Comment by axelardu** [comment]
@vinkla version 4.1

**Comment by vinkla** [comment]
That version isn't released yet. Try using `4.0` for stable version or `5.0.*@dev` for latest changes.

**Comment by axelardu** [comment]
@vinkla Thanks, i'll try the dev version out!

**Comment by vinkla** [comment]
:+1:

**Comment by edyrkaj** [comment]
Installing in Laravel 5 from Composer "lucadegasperi/oauth2-server-laravel": "~4.0" gives an error:
Warning: Ambiguous class resolution, "DatabaseSeeder" was found in both "$baseDir . '/database/seeds/DatabaseSeeder.php" and "{application path}\vendor\lucadegasperi\oauth2-server-laravel\seeds\DatabaseSeeder.php", the first will be used.

**Comment by vinkla** [comment]
@edyrkaj This is just a warning. It is fixed in b572ab6b4f952f0a963c4ce086540d98e04cdefe.

**Comment by edyrkaj** [comment]
Ok Thank you @vinkla.

**Comment by BlueManLine** [comment]
Hi all,

My project is on Laravel 5.0.33 and I have a problem upgrading the OAuth2 package to support the L5 middlewares.

Before I had in composer:
`"lucadegasperi/oauth2-server-laravel": "4.0.*@dev",`
but after changes to `5.0.*@dev` and trying to upgrade the composer I'm getting an errors:
`- lucadegasperi/oauth2-server-laravel 5.0.x-dev requires illuminate/database 5.1.* -> satisfiable by laravel/framework[5.1.x-dev], illuminate/database[5.1.x-dev, v5.1.1, v5.1.2, v5.1.6, v5.1.8].
    - Can only install one of: laravel/framework[5.1.x-dev, 5.0.x-dev].`

Is it a option to do not upgrade the Laravel project to 5.1 and use your OAuth2 package?

**Comment by vinkla** [comment]
@BlueManLine in order to use the middlewares you have to upgrade to Laravel 5.1

**Comment by BlueManLine** [comment]
I just copy the package middlewares to my middleware folder and it is working fine :)

**Comment by vinkla** [comment]
@BlueManLine yeah they will work except you won't be able to send any parameters to the middlewares. Those were added in 5.1.

**Comment by BlueManLine** [comment]
@vinkla indeed. Right now I do not need to pass any parameters.
Thanks :)
