### ISSUE TITLE
Better PSR-2 Support

### ISSUE THREAD

**Issue by vinkla** [lucadegasperi/oauth2-server-laravel#475]
Would you accept an pull request for better PSR-2 support? Maybe adding PHP CS Fixer file?

**Comment by lucadegasperi** [comment]
Absolutely!

**Comment by vinkla** [comment]
Super! I'll send you an PR.

**Comment by lucadegasperi** [comment]
Made you a collaborator. This should make things easier as long as we agree on the line :)

**Comment by vinkla** [comment]
Thank you :)

**Comment by vinkla** [comment]
@lucadegasperi Is it okay if I add this package to https://styleci.io/ ? This will give us syntax check for alls commits and pull requests.

**Comment by lucadegasperi** [comment]
Yes, add it.

**Comment by vinkla** [comment]
Great! I've opened #476 with all updates.

**Comment by vinkla** [comment]
Seems you've to add it since you're the owner. It quite simple. Login at https://styleci.io/auth/login and then go to your account and enable this repository.

**Comment by vinkla** [comment]
Since this has been merged I'll open a second issue (#484) for StyleCI.
