### ISSUE TITLE
Register FluentStorageServiceProvider

### ISSUE THREAD

**Issue by vinkla** [lucadegasperi/oauth2-server-laravel#478]
What about registering FluentStorageServiceProvider directly from OAuth2ServiceProvider? Then it will be easier to setup. Developers will then only have to register the OAuth2ServiceProvider.

**Comment by lucadegasperi** [comment]
Because one would want to register a different storage provider like mongo for example

**Comment by vinkla** [comment]
Aah okay, I see.
