### ISSUE TITLE
Migrations Are Published Automatically

### ISSUE THREAD

**Issue by vinkla** [lucadegasperi/oauth2-server-laravel#479]
Seems the migrations are getting publish when I'm running my unit tests. This could be a potential bug.

**Comment by GrahamCampbell** [comment]
Don't think so? You need to actually call the vendor publish command.

**Comment by vinkla** [comment]
Weird, wonder why they get published then? Could it be something when we publish the migrations?

```php
/**
 * Setup the migrations.
 *
 * @return void
 */
protected function setupMigrations()
{
    $source = realpath(__DIR__.'/../database/migrations/');
    $this->publishes([$source => database_path('migrations')], 'migrations');
}
```

**Comment by vinkla** [comment]
Weird. Wonder why they get published then? Could it be something when we publish the migrations?

```php
/**
 * Setup the migrations.
 *
 * @return void
 */
protected function setupMigrations()
{
    $source = realpath(__DIR__.'/../database/migrations/');

    $this->publishes([$source => database_path('migrations')], 'migrations');
}
```

The code above is taken from our service provider.

**Comment by vinkla** [comment]
@lucadegasperi Do you have any ideas about this?

**Comment by vinkla** [comment]
This was something on my side.
