### ISSUE TITLE
oAuth middleware return custom errors.

### ISSUE THREAD

**Issue by lukasoppermann** [lucadegasperi/oauth2-server-laravel#487]
Hey,

at the moment the oauth middleware will return an error to the user when the token or scopes are wrong.
My problem is that this error does not conform with my apis error style. Is there a way to catch this before the response is sent to the user? Or to modify the response object? Maybe a configuration could be added, or an argument or something?

**Comment by fabianweb** [comment]
See https://github.com/lucadegasperi/oauth2-server-laravel/issues/444

**Comment by lukasoppermann** [comment]
Thanks, actually I just found out it probably makes more sense for my case to just trigger the validateAccessToken function manually instead of using the middleware.
