### ISSUE TITLE
Implementation Problem

### ISSUE THREAD

**Issue by rienierpatron** [lucadegasperi/oauth2-server-laravel#488]
Hello,
I'd like to use this to implement oauth to the APIs that Im about to create, but I got the following problems:
 - On composer update, it says that the package is not found in any version so I used version 4.0 instead.

 - On the migration part, I got an error [InvalidArgumentException] Database [my-db] not configured. The migration only creates migrations, users, and password_resets tables.

What are the things that I should do to make these work.

Thank you.

**Comment by mallinus** [comment]
Same problem here. ~4.1 not found.

We aware when using 4.0 you won't have access to the middlewares. (oauth, oauth-owner, ...)

I'm not able to install the package for 5.1 right now. Any tips?

**Comment by mentos1386** [comment]
Try looking at https://github.com/lucadegasperi/oauth2-server-laravel/issues/461

**Comment by mentos1386** [comment]
Try looking at https://github.com/lucadegasperi/oauth2-server-laravel/issues/461

**Comment by vinkla** [comment]
As @mentos1386 mentioned try installing version `5.0.*@dev` instead.

**Comment by GKavyashree** [comment]
ReflectionException in Container.php line 736:
Class LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware does not exist

$this->middleware('oauth', ['only' => 'store']);

I'm using L5.1 and "lucadegasperi/oauth2-server-laravel": "4.1.x-dev"

**Comment by vinkla** [comment]
@GKavyashree the new version is specified as `5.0.*@dev` instead of `4.1.*@dev`.

Please try to open a new issue in the future. Makes it easier for us to find your question since this issue already is closed.
