### ISSUE TITLE
Getting token without http request

### ISSUE THREAD

**Issue by dimsav** [lucadegasperi/oauth2-server-laravel#489]
Hi there,

I'm using this package for Laravel 4.2. I was wondering, is it possible to issue a user token without making an HTTP request?

Thanks in advance.

**Comment by lucadegasperi** [comment]
Definitively possible, but not with the provided classes and methods. You would need to skip all the request checking part and issue an access token using the underlying entities. Why would you want to do that though? Way easier to always use http.

**Comment by dimsav** [comment]
The reason is mostly for performance. Accessing the database should be faster than doing an http request.

**Comment by vinkla** [comment]
It is possible to do as @lucadegasperi describes above. Though, it some what looses the necessity of using this package.
