### ISSUE TITLE
How to pass the username and password manually to the "/oauth/access_token" web service

### ISSUE THREAD

**Issue by Hazemwd** [lucadegasperi/oauth2-server-laravel#492]
I'm trying to create a dummy account in each call to the webservice called "/oauth/access_token".
So I'll need the user to only pass the grant_type, client_id, client_secret.

Another question, how can I make the access token live forever with no expire date ?

**Comment by Hazemwd** [comment]
@lucadegasperi

**Comment by Hazemwd** [comment]
I figured out the solution,
This can be achieved by modifying the completeFlow method in the \vendor\league\oauth2-server\src\Grant\PasswordGrant.php file.

**Comment by vinkla** [comment]
Why do you want to pass them manually? Why not send them with the HTTP request?

**Comment by Hazemwd** [comment]
THANKS @vinkla 
I wasn't aware that I can use two grant types with the same application, now it's clear to me.

**Comment by vinkla** [comment]
Anytime! You can use how many you want too :)
