### ISSUE TITLE
Store token type in database.

### ISSUE THREAD

**Issue by lukasoppermann** [lucadegasperi/oauth2-server-laravel#493]
I was wondering, shouldn't the `token type` be stored in the database as well? I know that as of now there is only `Bearer` but this could change. At the moment it seems the value is returned, but it is not stored anywhere in the database.

**Comment by lucadegasperi** [comment]
what would the benefit be? It's just an access token, the resource server would validate it according to the values he finds in the authorization header.

**Comment by lukasoppermann** [comment]
Well, what happens if in future versions other type of tokens are implemented? This was basically the idea. Although it might be an unrealistic case, I don't know that.

**Comment by lucadegasperi** [comment]
The resource server gets an access token that can be wrapped in other stuff (a mac signature or a JWT token for example) but the content is always the same for all of them. The resource server would need to recognize the type of token used based on the format provided by the client.

**Comment by lukasoppermann** [comment]
Ahh, I see, I guess I was lacking some knowledge there. :)
