### ISSUE TITLE
How to use the "oauth-owner" middleware and get Owner ID in Laravel 5 version ?

### ISSUE THREAD

**Issue by Hazemwd** [lucadegasperi/oauth2-server-laravel#494]
I'm trying to use the oauth-owner middleware in laravel 5 (not 5.1) but I get class not found and after I searched the issues, I found a comment for @lucadegasperi saying that this is for L5.1.
How can I use this middleware with L5 with out the need to upgrade ?

Also I'm trying to use 

Authorizer::getResourceOwnerId()

to get the owner ID but get

Class 'LucaDegasperi\OAuth2Server\Facades\Authorizer' not found

Please help

**Comment by vinkla** [comment]
The middlewares doesn't support Laravel 5.0 you have to update to 5.1 to use them.

The [Laravel 5.1 upgrading guide](http://laravel.com/docs/5.1/upgrade#upgrade-5.1.0) is almost none existing. Once updated to 5.1 the facade error wont be thrown.

**Comment by Hazemwd** [comment]
Thanks, I'll try the upgrade :+1:

**Comment by vinkla** [comment]
:+1:
