### ISSUE TITLE
Way to implement custom storage.

### ISSUE THREAD

**Issue by felixdv** [lucadegasperi/oauth2-server-laravel#495]
I'm using Laravel 5.1.

On http://oauth2.thephpleague.com/implementing-storage-interfaces/, examples are shown that allow you to implement custom storage classes adhering to a specific interface. I can see pretty much the same thing happening in https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/src/OAuth2ServerServiceProvider.php, but I don't really see a way to override some of those classes in the config. In specific, I need to override the ClientStorage class since I use a different data model (integrating oauth2 client credentials with an existing table).

What's the best way to make this possible?

**Comment by vinkla** [comment]
If you're using Laravel 5.1 you should be looking on the develop branch instead. The master branch doesn't have the latest changes regarding Laravel 5.1. 

What you could do is extending our service provider and overwrite that entire method:
```php
use LucaDegasperi\OAuth2Server\OAuth2ServerServiceProvider as ServiceProvider

/**
 * This is the oauth2 server service provider class.
 *
 * @author Luca Degasperi <packages@lucadegasperi.com>
 */
class OAuth2ServerServiceProvider extends ServiceProvider
{
    /**
     * Register the Authorization server with the IoC container.
     *
     * @return void
     */
    public function registerAuthorizer()
    {
        // Your custom setup goes here.
    }
}
```
Then you can register your custom OAuth2ServerServiceProvider in `app/config.php`.

**Comment by felixdv** [comment]
That might work, thanks for the pointer!
