### ISSUE TITLE
Problems using Token

### ISSUE THREAD

**Issue by jeanrl** [lucadegasperi/oauth2-server-laravel#497]
I can get the Token, but I can not see using it.

My route this way:

Route::group(['before'=>'oauth'], function()
{
    Route::get('teste', 'TesteController@index');
});

My method in the controller looks like this:

 public function index()
 {
      return '["a", "b", "c", "d"]';
 }

And when I try to pass the token with headers, it returns me error, following image:

![erro_token](https://cloud.githubusercontent.com/assets/3492508/8962689/3c117844-35f2-11e5-8b20-c983aa9aa38b.jpg)

Thank's.

**Comment by jeanrl** [comment]
I could make it work, I took the "Authorization" the headers and set the parameter: access token in parameters.

Is that really correct?

Thank you and congratulations on the excellent product.

**Comment by lucadegasperi** [comment]
There are two ways of passing an access token to the endpoint. One is to use the query string, easy but not generally recommended. The other one is to use the Headers. Headers on some server configurations might have some issues; Here's described how to solve them when using Apache as your web server. https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Apache-ModRewrite

**Comment by jeanrl** [comment]
Ok @lucadegasperi I do not use .htaccess, I direct the changes in Apache, so I'll adapt the wiki for my situation and to report back here if it worked.

Thank you for the answer.

**Comment by jeanrl** [comment]
Hi @lucadegasperi !

I made changes to the wiki shows, but still get the error message:

{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"access token\" parameter."}

The configuration in my domain.com.conf in /etc/apache2/sites-available:

<VirtualHost *:80>
	ServerName ...com.br
	ServerAlias www....com.br

	ServerAdmin jeanrlima@gmail.com
	DocumentRoot /var/www/folder/public

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

    <Directory /var/www/folder/public>

    <IfModule mod_rewrite.c>
	<IfModule mod_negotiation.c>
    	    Options -MultiViews
        </IfModule>

	RewriteEngine On

        # Redirect Trailing Slashes...
	RewriteRule ^(.*)/$ /$1 [L,R=301]
        # Authorization Header
        RewriteCond %{HTTP:Authorization} .
	RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
        # Handle Front Controller...
	RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
	RewriteRule ^ index.php [L]
    </IfModule>

</Directory>

Can you help me where I am going wrong?

Thank you.

**Comment by jeanrl** [comment]
Hi @lucadegasperi !

Finally succeeded, following my .conf of my vhost for the event in the future need someone, is there:

*---VirtualHost *:80
	ServerAdmin jeanrlima@gmail.com
	ServerName domain.com.br
	ServerAlias www.domain.com.br
	DocumentRoot /var/www/folder/public/

	RewriteEngine On
        RewriteCond %{HTTP:Authorization} ^(.*)
	RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	<Directory />
	    Options FollowSymLinks
	    AllowOverride All
	</Directory>

	<Directory /var/www/folder/public/>

	    Options Indexes FollowSymLinks MultiViews
	    AllowOverride All
	    Order allow,deny
	    allow from all

	    <IfModule mod_rewrite.c>
	        <IfModule mod_negotiation.c>
	            Options -MultiViews
	        </IfModule>

	    </IfModule>

	</Directory>

*--/VirtualHost>

Thank you very much.
