### ISSUE TITLE
Password grant and scopes

### ISSUE THREAD

**Issue by mentos1386** [lucadegasperi/oauth2-server-laravel#499]
How to know if user was authenticated using password grant or any other grant? 

If i am correct you cant set any scopes to password grant as they don't use client id/client secret. I want to use scopes for 3th party clients that use other grants, but if user uses password grant I want for him to have all scopes because he is using "offical" app or web site.

Is there a way to detect which grant did user used or anything like that?

**Comment by lucadegasperi** [comment]
You can only assign specific scopes to be used only by specific grant types or clients. The password grant type still requires client id and client secret params to be passed when handshaking. What you could do is assign a "super-user" scope to be used only by your official clients (aka your apps) and limit that scope to be used only when requiring it by using the password grant type.

**Comment by mentos1386** [comment]
OK thanks, that could work.

One more question, the official app will be based on AngularJS, and I read that you shouldn't store client id and client secret in JS app, because it's not safe. What is the best approach to solving this? And I would be using password grant.

I was thinking in a way that you could check if request is from specific ip (offical app ip), and if it is, add client id and client secret to request.

**Comment by lucadegasperi** [comment]
Does the app run inside a container like phone gap or similar? If yes, there's no problem in storing them on the device, just like a native app would. If it runs in the browser you should consider having a proxy to the authorization mechanism, something like a server side page where you submit username and password, and get a token back. The server side page will do the actual request to the authorization endpoint adding your client id and client secret to the request.

**Comment by vinkla** [comment]
Also, if you are running on the same domain as the JS application you could skip OAuth 2 entirely. Then it would be enough checking the IP and maybe a CSRF token or something similar.

**Comment by mentos1386** [comment]
It runs in browser so I'll go with the server side page.

But I don’t understand one part.

```
AngularJS --[redirects]-> Server side login page --[sends POST with data]-> api/access_token

```
How will the AngularJS app see api/access_token response?

**Comment by mentos1386** [comment]
I made it so that:
```
1. AngularJS sends username and password to ProxyController on API
2. ProxyController checks HTTP_ORIGIN if it is "official" (or maybe add some other requirements in the future)
3. If it is, add client_id and client_secret
4. send request to access_token
5. return response
```
Thanks for the help.
