### ISSUE TITLE
Authenticating controller with dual Auth systems in L5

### ISSUE THREAD

**Issue by tellsaqib** [lucadegasperi/oauth2-server-laravel#500]
I am migrating my app from plain PHP to Laravel 5.1 . Most of my routes will reside under controller actions.

* App backend will be accessed from a Single page application for that I have used Laravel's own authentication mechanism. 
* Additionally the app will also be accessed using the API for that I have used **client_credentials** Grant

Currently I am doing this in the constructor of my controllers

```php
if ($request->getBaseUrl() == "myapp.com") {
    //My single Page Application
    $this->middleware('auth');
} else {
    //API access from somewhere else
    $this->middleware('oauth');
}

```

I always make sure that **id** field in oauth_client table equals to the primary key in my users table. Then I have to add this at the start of each controller action.

```php
if (array_key_exists('oauth', $this->getMiddleware())) {
    auth()->loginUsingId(Authorizer::getResourceOwnerId());
}
```

This enables me to use **auth()->user()->id** later in the code irrespective of the auth mechanism.

While this approach is working for me but there would be certain things I could do to optimize the code and make thing secure at my end. Can anyone please point any improvements in this approach.

Thanks.

**Comment by lucadegasperi** [comment]
Clients != Users. Clients are Apps, Users are users. Clients can get authorized by the user to access data on its behalf. You probably want to use the password grant type. the client_credentials grant is for client to client communication with no user involvement.

**Comment by tellsaqib** [comment]
@lucadegasperi  I tried password grant too but for that user has to provide the username and password to get the access token. Right? 

I want to use username/password combo only for my Web application access and for web services each user will have his own client secret so it's sort of one to one mapping between user and clients.

**Comment by vinkla** [comment]
@tellsaqib Yes, with the password grant the user has to provide the username and password. 

Think of the client as your front-end. Lets say you build the Twitter mobile app. Each user that use the Twitter app doesn't have a unique set of client id and secret. Instead the Twitter mobile app has one set of client credentials for maybe each platform. iOS has their own, Android has their own and so on.

**Comment by tellsaqib** [comment]
@vinkla @lucadegasperi Thanks for the prompt replies. I have switched to Password Grant and things are now looking much better. 

Now only redundant thing is that I have to add code shown below into each of my controller's constructor

    if ($request->getBaseUrl() == "myapp.com") {//My single Page Application
        $this->middleware('auth');
    } else {//API access from somewhere else
        $this->middleware('oauth');
    }

Is there a cleaner way to apply the right middleware on the basis of URL called?

**Comment by vinkla** [comment]
Better is to create two different routes, one for your single page application and one for the API.

**Comment by vinkla** [comment]
Since your issue is solved I'm closing this. Please write back if you are still having issues.
