### ISSUE TITLE
Get Client Info

### ISSUE THREAD

**Issue by lukasoppermann** [lucadegasperi/oauth2-server-laravel#501]
Hey,

is there a way to get the clients info (client_secrect, name) or do I need to do an Eloquent select?

I can get the id with `$this->authorizer->getClientId()` so I was wondering if there is a way to get the rest (for e.g. when creating a client I would need to somehow display the info).

I actually did it with a db query now, and I noticed, that you would need something like `getClientById(':client_id:')`. 

Additionally it would be interesting to get the scopes for a given client by id.

Just to explain what I need it for:

I have a system, where a client can signup (= create a new api client).
This means one needs to be shown the client_id & client_secret to use for getting access tokens.

I have an oauth server, so the flow for this would be:

1. User requests client_info in system
2. System does an oAuth authentication with its own id & secret (it has scopes to view, create and delete clients)
3. After successful auth, the data for a different user (as currently the system is authenticated) needs to be show by ID (this is the user who requested the info).

**Comment by vinkla** [comment]
Thanks for you suggestion. We want to keep this package as simple as possible. Though, we have future plans moving this kind of stuff into a second package.
