### ISSUE TITLE
service provider miss used $this->app as config providers

### ISSUE THREAD

**Issue by hasangilak** [lucadegasperi/oauth2-server-laravel#503]
https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/src/OAuth2ServerServiceProvider.php#l55

$mTo = $this->app['path.database'] . '/migrations/';

what is that suppose to mean ? 

this repo works fine though
https://github.com/esbenp/oauth2-server-lumen

**Comment by vinkla** [comment]
This is fixed on the develop branch. Thanks.
