### ISSUE TITLE
access_token last forever

### ISSUE THREAD

**Issue by mathiasgrimm** [lucadegasperi/oauth2-server-laravel#505]
How can I make a client_credentials token last forever? without having to specify a date in a far away future? tried 0 and -1, 0 gets 1 hour which is default and -1 makes it in the past which is always expired.

**Comment by lucadegasperi** [comment]
You can't. But you've got client credentials, which, can be always exchanged for a new access token anytime.

**Comment by mathiasgrimm** [comment]
but i think there is something wrong,
the maximum ttl i can get is something like 3 years.

**Comment by mathiasgrimm** [comment]
i can't get a 9999999999 timestamp, at least I should be able to specify something bigger that 3 years

**Comment by mathiasgrimm** [comment]
I am trying to avoid the token flow, providing just the api token

**Comment by lucadegasperi** [comment]
Simply don't use tokens that never expire, it's not safe. The token flow? you're using client_credentials (don't confuse it with the password grant) one request and you've got yourself a new access token.

**Comment by frednotet** [comment]
this is the max timestamp for a INT(11) :  2111753600 which is 1st December 2036 15:13:20

++
