### ISSUE TITLE
Multiple Grant Types. How to set Grant in runtime?

### ISSUE THREAD

**Issue by lollypopgr** [lucadegasperi/oauth2-server-laravel#507]
Hi there. What is the "right" way to set the grant type of the Authorizer, when multiple Grant Types are used? Can't find a proper way to do this so It would be great if I had some guidance.

**Comment by vinkla** [comment]
Don't understand your question. Could you elaborate and describe a bit more on what you want us to help you with? What is it you want to know?

**Comment by lollypopgr** [comment]
I am on version 3.0 and laravel 4.2. I have multiple grant types like 'password' and some custom ones. I guess my question is "How can I select which Grant type to use in the Authorizer facade"?

Some routes use the 'password' grant type, some other routes user the 'custom' grant type.

The http://oauth2.thephpleague.com/authorization-server/custom-grants/ is not showing anything that could help

Really sorry if I confused you.

**Comment by vinkla** [comment]
When you send a request from the client to your API you will send it with a `grant_type` parameter specifying which type of access token you want to fetch.

Then you've to setup filters to protect the resources and/or endpoints you want to secure for specific grants.

**Comment by lollypopgr** [comment]
Thanks you @vinkla . Your point cleared my head :-)

**Comment by vinkla** [comment]
:+1:
