### ISSUE TITLE
Class 'LucaDegasperi\OAuth2Server\Support\AbstractMigration' not found

### ISSUE THREAD

**Issue by newtonianb** [lucadegasperi/oauth2-server-laravel#508]
Out of nowhere I started getting this exception when running ``php artisan migrate``

I'm guessing some code has changed which makes the migrations out of date? The issue is I re-ran vendor:publish and it did not change the migrations.

```bash
[Symfony\Component\Debug\Exception\FatalErrorException] Class 'LucaDegasperi\OAuth2Server\Support\AbstractMigration' not found
```

I am using
```json
"lucadegasperi/oauth2-server-laravel": "dev-develop",

{
  "type": "git",
  "url": "https://github.com/lucadegasperi/oauth2-server-laravel.git"
}
```

Is this due to some recent change maybe?

**Comment by newtonianb** [comment]
This thing makes no sense, I completed reverted all the installation steps of OAuth2, deleted my vendor directory, cleared composer cache, deleted composer.lock, this error won't go away!

**Comment by lucadegasperi** [comment]
Indeed it is. You'll need to change the migrations for this package as they no longer use the AbstractMigration class as their parent.

**Comment by vinkla** [comment]
The fasted solution to this will be to delete your existing migrations that you have published from this pacakage and then rerun `php artisan vendor:publish`.

**Comment by newtonianb** [comment]
@lucadegasperi  @vinkla I deleted the migrations and reran ``php artisan vendor:publish`` that the problem is the migrations that keep coming back still use AbstractMigration ... I am on develop branch, is this suppose to work?

**Comment by newtonianb** [comment]
mybad ... my IDE was very slow to update and showing me previous version

**Comment by vinkla** [comment]
Using PhpStorm? Had the same problem myself. Works fine now though. 

Btw, a tip is to use version `5.0.*@dev` instead of `dev-develop`. You'll never know if we rewrite the entire package on the develop branch for version 6 but with a specified version you will now that we wont make to big changes to the package.

When following best practices it is better to never add a branch to the `composer.json` file.
