### ISSUE TITLE
OAuth2ServerServiceProvider.php, explode() expects parameter 2 to be string, object given

### ISSUE THREAD

**Issue by vilhelmjosander** [lucadegasperi/oauth2-server-laravel#509]
Hi,

I am following the guide to install this for Laravel 5.1. I keep getting the following error when trying to login:

`ErrorException in OAuth2ServerServiceProvider.php line 111:
explode() expects parameter 2 to be string, object given`

This is the password grant type in my oauth2-config:

     `grant_types'             => [
        'password'           => [
            'class'            => '\League\OAuth2\Server\Grant\PasswordGrant',
            'callback'         => function ( $username, $password ) {
               // Returns the user id else returns false
            },
            'access_token_ttl' => 2629743
        ],` 

It seems like I should give the callback a string like `'App\Http\Controllers\OauthController@verify'` judging from the  OAuth2ServerServiceProvider.php:111 though this is not in the documentation from what I can see? This doesnt work for me still though, I just get the following error (the verify function in the OauthController is the same as the closure-callback):

`FatalErrorException in Container.php line 685:
Maximum function nesting level of '500' reached, aborting!`

If I change the following in the OAuth2ServerServiceProvider.php around line 110 it works when using a closure as the callback.

     `if (array_key_exists('callback', $grantParams)) {
            $grant->setVerifyCredentialsCallback($grantParams['callback']);
            //list($className, $method) = array_pad(explode('@', $grantParams['callback']), 2, 'verify');
            //$verifier = $app->make($className);
            //$grant->setVerifyCredentialsCallback([$verifier, $method]);
      }`

I am using the following package in my composer.json

`"lucadegasperi/oauth2-server-laravel": "5.0.*dev"`

Is this something missing in the documentation, a bug or am I missing something?

**Comment by lucadegasperi** [comment]
The callback is now a string pointing to a method called verify on a fully namespaced class. it should be something like: ```\YourAppNamespace\ClassWithVerifierMethod@verify```

**Comment by vinkla** [comment]
@vilhelmjosander Please see the [documentation page](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Password-Grant).

**Comment by vilhelmjosander** [comment]
Ah great, couldnt fint that yesterday. Looks like it just has been updated. Thanks!

**Comment by vinkla** [comment]
Anytime!

**Comment by SoldierCorp** [comment]
@vinkla Where should I put that Verifier class? if inside Controller I have a folder called API where I have all my controllers to manage my API

**Comment by sandyp143** [comment]
ErrorException in ServiceProvider.php line 66:
array_merge(): Argument #2 is not an array still exists

**Comment by felipemarques** [comment]
Ohhhh man... the closure is so simple... kkkkkk ... i lost much time to find this solution... thanks...
