### ISSUE TITLE
Extra security for password grant

### ISSUE THREAD

**Issue by axelardu** [lucadegasperi/oauth2-server-laravel#510]
Hi,

I'm currently using the password grant and the authorization code grant.
The password grant for my trusted clients (android & web-app) and authorization for 3rd party clients.

Whats the best way to extra secure my password grant because if someone gets hold of the client id & secret (and they register as a user) they can access anything in my application. 

Thanks!

**Comment by vinkla** [comment]
If they do get hold of the client id and secret you have to remove those and create a new pair of keys. Be sure to send all requests over HTTPS.

**Comment by axelardu** [comment]
Hi vinkla,

All my requests are sent over HTTPS. Changing the keys is the first thing that I would do if they are able to get them but I'm looking for an extra layer of security. Any idea's?

**Comment by lucadegasperi** [comment]
Having username and password in any case would mean the attacker can perform any action on your system. An extra security layer would be the use of permissions and access groups on your server side and the limitation of certain scopes for certain grant types and/or clients.

**Comment by axelardu** [comment]
@lucadegasperi Thanks for your answer. 

Could you give me an example on how to limit certain scopes for a specific grant type/client ?

**Comment by vinkla** [comment]
@axelardu A starting point would be the docs, please see [Securing your API endpoints](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Securing-your-API-endpoints).

**Comment by axelardu** [comment]
@vinkla How did I miss that, I must be blind.
Thanks that is exactly what I was trying to ask for and build myself.

**Comment by vinkla** [comment]
No worries :) Let us know if you need anything else!
