### ISSUE TITLE
Create client

### ISSUE THREAD

**Issue by lukasoppermann** [lucadegasperi/oauth2-server-laravel#511]
Hey,

I am at a point where I have to add a client into the database, this involves the following:
- creating a `client_id`& `client_secret` combination
- storing this data into the database
- retrieving this data to show it to a user, or use it in another way in the project

Would you be interested in a PR to include this into the package?

**Comment by vinkla** [comment]
Thanks for you suggestion. We want to keep this package as simple as possible. Though, we have future plans moving this kind of stuff into a second package.

**Comment by lukasoppermann** [comment]
Okay, thanks for the heads up. Will this answer be the same for #501?

**Comment by vinkla** [comment]
Yes, that is correct. Left the same answers there for now. 

We always appreciate this kind of feedback, don't hesitate to give us more if you have any. Thanks!
