### ISSUE TITLE
Auto Approve of Auth Code Grant 

### ISSUE THREAD

**Issue by ken8203** [lucadegasperi/oauth2-server-laravel#512]
Hello,

I have a question about auto approve of auth code grant.
I implemented a login method with oauth2 server just like the way of facebook login. But i found that when I click the login button, I need to approve it every time.

Is it possible to make it approved automatically, I mean only approve it one time.

Thank you a lot!!

**Comment by lucadegasperi** [comment]
You definitively can but the implementation is up to you. You could see if the client making the request already has an expired access token with the same permissions and allow it automatically.
