### ISSUE TITLE
Broken migrations - 5.0 release

### ISSUE THREAD

**Issue by rcrowe** [lucadegasperi/oauth2-server-laravel#515]
This commit has broken migrations - https://github.com/lucadegasperi/oauth2-server-laravel/commit/c9e7a3f6b114297b69593d3a3a0ddb41ba2600a9#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

The class can no longer be found when resetting / refreshing etc from the migrations table.

When pulled in as a dependency, the `require-dev` classmap is not included.

**Comment by vinkla** [comment]
What version have you specified in your `composer.json` file?

**Comment by rcrowe** [comment]
`"lucadegasperi/oauth2-server-laravel": "~5.0"`

**Comment by vinkla** [comment]
Have you published the migrations to your migrations directory with `php artisan vendor:publish`?

**Comment by rcrowe** [comment]
I'm using lumen, so don't have access to the `vendor` command

**Comment by rcrowe** [comment]
Not sure this is closed? The docs talk of Lumen support & there is no command to `vendor:publish` so was relying on them being in the autoloader already.

**Comment by vinkla** [comment]
Have you tried running this?

```bash
php artisan migrate --path=vendor/lucadegasperi/oauth2-server-laravel/database/migrations
```

**Comment by rcrowe** [comment]
That's what I ran, and it breaks when trying to migrate down

**Comment by rcrowe** [comment]
The migrations table stores `2014_04_24_111810_create_oauth_refresh_tokens_table` and then converts that to `CreateOauthRefreshTokensTable` which is no longer found.

**Comment by rcrowe** [comment]
I followed the wiki instructions a while back for `4.1@dev` and hadn't been tracking the changes for 5.0.

Adding fixes it:

```json
"classmap": [
    "vendor/lucadegasperi/oauth2-server-laravel/database/migrations"
]
```

Obviously prefer not to do this, but will work for now.

**Comment by vinkla** [comment]
Yeah, there doesn't seem to be a way to publish the migrations for Lumen. We can't autoload them either . I'll update the documentation about this. Thanks.

**Comment by vinkla** [comment]
Just tried this myself on a new Lumen installation and it works fine.

<img width="799" alt="screenshot 2015-08-06 18 58 17" src="https://cloud.githubusercontent.com/assets/499192/9117869/287288d8-3c6d-11e5-8f49-4db37cf0329c.png">

**Comment by rcrowe** [comment]
Migrating isn't the issue. That works fine.

But try resetting / refreshing.

**Comment by rcrowe** [comment]
It's when your using down migrations in combination with the migrations
table

**Comment by vinkla** [comment]
I'm not sure what you mean, could you explain the flow more in detail?

**Comment by rcrowe** [comment]
After you have migrated, run `php artisan migrate:reset` and things go horribly wrong.

**Comment by vinkla** [comment]
Okay, I see what you mean. I've researched publishing in Lumen and it seems there is no way to publish the migrations from our service provider. We can't either autoload them by default. Do you have any idea how to solve this? I guess copying the migrations yourself would be the easiest solution or adding the full path to the migrations directory. Though, adding the full path could break things in the future.
