### ISSUE TITLE
Error refreshing the page

### ISSUE THREAD

**Issue by jeanrl** [lucadegasperi/oauth2-server-laravel#516]
Hi people!

Even if I just get the token and give a refresh (F5) on page I get an error message as if he had the token, explain:

Just log in, it picks up the token and sends me to the main page, so far so sure, but at this moment I give a F5 to refresh the page it gives token authentication error, like I was not atutenticado, It is to solve this? (I'm using Laravel 5.1 and angularjs)

Grateful to everyone.

**Comment by vinkla** [comment]
Are you using the authentication code to redirect the users?

**Comment by jeanrl** [comment]
I do:

Login page;
If logged correctly redirect to the Dashboard.

And in the Dashboard to reload the page (F5 or refresh) it gives the authentication error.

**Comment by vinkla** [comment]
Did you follow the [implementation guide](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Auth-Code-Grant)?

**Comment by jeanrl** [comment]
Yes, Here's how I'm doing on my (I using password grant):

To enable this grant add the following to the config/oauth2.php configuration file:

    'grant_types' => [
         'password' => [
             'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
             'access_token_ttl' => 3600,
             
             'callback' => function($username, $password)
             {
                $credintials = ['email' => $username, 'password' => $password];
                if(Auth::once($credintials))
                {
                    return Auth::user()->id;
                }
                else 
                {
                   return false;
                }
             }
         ],
    ],

Routes:

Route::post('oauth/access_token', function() 
{
    return Response::json(Authorizer::issueAccessToken());
});

Route::group(['before'=>'oauth'], function()
{
    Route::get('/dashboard', 'TesteController@index'); 
});

In angularjs (after the token):

        $http(
        {
            method: 'GET',
            url: '/teste', 
            headers: {
                Authorization: 'Bearer '+ $rootScope.token
            }
        })
          .success(function(data){
                 $scope.user_Indice = data;
          })
          .error(function(data)
          {
                sweetAlert({
                        title: "Oops!", 
                        text: data.error_description, 
                        type: "error"
                });
                $scope.password = "";
                $location.path('login');
          });

Thanks.

**Comment by vinkla** [comment]
@lucadegasperi any ideas on this?

**Comment by vinkla** [comment]
@jeanrl What you're trying to do is using the access token to fetch new data?

**Comment by jeanrl** [comment]
Hi @vinkla !

Yes, exactly. The sequence is this:

(I am using angularjs on client side)
Login;
If you have the token and authenticate correctly is redirected to the main page that contains a range of information that is retrieved from $http and the token that was stored in the login through a $rootScope;

Everything works perfectly, but after it was logged and displayed data,  If I do update the page (F5) it shows the mistake of missing token.
Reading about I come to the conclusion that it's because when I update the page it resets the variables and therefore the $rootScope no longer has the token and that's why failure.
I'm rewriting the code to try to see if I can overcome this obstacle, but I'm sure the error is not the Authentication or component oauth2, but the update make you loss data.

Thanks for yours attentation.

**Comment by vinkla** [comment]
Okay, good that you solved it!
