### ISSUE TITLE
Checking access token

### ISSUE THREAD

**Issue by ukenpachi** [lucadegasperi/oauth2-server-laravel#518]
Hi, I have getting page not found and I have looked in the Laravel log file and not is in it.

Basically i have an access token which i am passing like this 
![image](https://cloud.githubusercontent.com/assets/5822229/9157119/389eac9a-3ee9-11e5-9da7-51fb2cda3c7f.png)

my route is set up like this

```php
Route::get('protected-resource', ['middleware' => 'oauth', function() {
    // return the protected resource
    
    Route::get('/profile', function() {
        echo Authorizer::getResourceOwnerId();
    });
}]);
```

I don't understand what I have done wrong, here. Thanks

**Comment by lucadegasperi** [comment]
If you get a 404 it has nothing to to with this package. the route path you're hitting is probably wrong.

**Comment by ukenpachi** [comment]
Hi Lucadegasperi thanks for your response. I believe it is because of i moved /profile outside the end point 

 Route::get('/profile', function() {
     echo "hello";
 	});

I get this response but when i move it into endpoint again. I get the error.

This is my kenel.php

    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
        'LucaDegasperi\OAuth2Server\Middleware\OAuthExceptionHandlerMiddleware',
    ];

    /**
     * The application's route middleware.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'csrf' => '\App\Http\Middleware\VerifyCsrfToken',
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'oauth' => 'LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware',
        'oauth-owner' => 'LucaDegasperi\OAuth2Server\Middleware\OAuthOwnerMiddleware',
        'check-authorization-params' => 'LucaDegasperi\OAuth2Server\Middleware\CheckAuthCodeRequestMiddleware',
    ];

I am wrong if i need to add anything else to get this package working in other for it to see the endpoint and verify the access token. Thanks

**Comment by ukenpachi** [comment]
I have also tried usign group has this is ideally the way i will be using this. 

Route::group(['prefix' => 'v1', 'middleware' => 'oauth'], function() {
    // return the protected resource

	 Route::get('/profile', function() {
     echo Authorizer::getResourceOwnerId();
 	});

});

and i am still gettting the same error

**Comment by lucadegasperi** [comment]
Oh I see, the access token needs to be passed in either the query string (not the payload) or as an authorization header. Weird you get a 404 though.

**Comment by ukenpachi** [comment]
![image](https://cloud.githubusercontent.com/assets/5822229/9165935/1d85fab6-3f49-11e5-97b1-677a18905f88.png)

Route::group(['prefix' => 'v1', 'middleware' => 'oauth'], function() {
    // return the protected resource

	 Route::get('/profile', function() {
     echo Authorizer::getResourceOwnerId();
 	});

});

I am getting a 404

**Comment by lucadegasperi** [comment]
Does the route work without the middleware? I see that you've added a v1 prefix. that means your route url should be /v1/profile and not /profile.

**Comment by ukenpachi** [comment]
Lucadegasperi issues solved. Thanks again but one more question. Why didn't it work like this 

Route::get('protected-resource', ['middleware' => 'oauth', function() {
    // return the protected resource

    Route::get('/profile', function() {
        echo Authorizer::getResourceOwnerId();
    });
}]);

the way you have shown in the guide?

**Comment by lucadegasperi** [comment]
You can't put a route::get inside another one, you can only put route::get inside a route::group eventually.

**Comment by ukenpachi** [comment]
On that note, this issue is now closed. Thank for again lucadegasperi  much appreciated, have a good day.
