### ISSUE TITLE
Class 'LucaDegasperi\OAuth2Server\Support\AbstractMigration' not found after upgrading

### ISSUE THREAD

**Issue by nickurt** [lucadegasperi/oauth2-server-laravel#519]
After I upgraded to the latest version in dev-master (e9146c3) I got the error

    Class 'LucaDegasperi\OAuth2Server\Support\AbstractMigration' not found

during refreshing database-tables ..

**Comment by vinkla** [comment]
The migrations has been changed, please see #508 for solution.
