### ISSUE TITLE
Call to a member function getSession() on a non-object 

### ISSUE THREAD

**Issue by james-ff** [lucadegasperi/oauth2-server-laravel#523]
Since the most recent update to the package getResourceOwnerId() has been returning the following as a response for me:

```
FatalErrorException 
in Authorizer.php line 244 
: 
Call to a member function getSession() on a non-object 
```

I can't figure out why this is the case.

Thanks for any assistance you can provide!

[Access tokens are being issued and stored in the database as usual]

**Comment by james-ff** [comment]
@vinkla Any idea whats going on? Is the ReadMe fully up to date?

**Comment by james-ff** [comment]
This was fixed by:
- changing 'before' to 'middleware' in routes.php
- calling ```use Authorizer``` instead of ```use LucaDegasperi\OAuth2Server\Authorizer```

**Comment by tmgast** [comment]
I'm getting a similar error:
```
FatalErrorException in Authorizer.php line 254: 
Call to a member function getSession() on a non-object 
```

I'm using the oauth-client middleware.

**Comment by tmgast** [comment]
Adding a valid request check directly in that function appears to resolve the issue:

```
    /**
     * Get the resource owner type of the current request (client or user).
     *
     * @return string
     */
    public function getResourceOwnerType()
    {
        if($this->checker->isValidRequest())   // this function actually determines $checker->access_token
            return $this->checker->getAccessToken()->getSession()->getOwnerType();
    } 
```

**Comment by james-ff** [comment]
^ A note in the docs is a good shout

**Comment by stsibel** [comment]
@tmgast thanks! `['oauth', 'oauth-client' ]` actually saved me a lot of time
