### ISSUE TITLE
Remove required username field 

### ISSUE THREAD

**Issue by olezko46** [lucadegasperi/oauth2-server-laravel#524]
I want to build the authorization using only e-mail and password. I changed the model verifier, but the request for a new token, I get 
```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"username\" parameter."}

```

How to completely remove username field?

**Comment by lucadegasperi** [comment]
username is a required OAuth2 specification parameter. Whatever you put in there then is up to you, wether it's an email, a string or some emojis. In the verifier then you can do whatever you want with that parameter and validate it against whatever you want.

**Comment by olezko46** [comment]
@lucadegasperi My API will be available for any developer in the world. It seems to me, it is not very good if I say "pass the username to anything you like." Can I somehow remove the username field of the required in the request, but stored in a database of e-mail as a username?

**Comment by vinkla** [comment]
You can create a custom grant and there specify which fields you want to use.

**Comment by olezko46** [comment]
@vinkla Could you provide a link to instructions for creating custom ```grant_tipe```? Link of the wiki is on the blank page

**Comment by vinkla** [comment]
Check out #514

**Comment by olezko46** [comment]
@vinkla Thanks a lot :+1:
