### ISSUE TITLE
Access Control and 2 user types

### ISSUE THREAD

**Issue by Udders-HX** [lucadegasperi/oauth2-server-laravel#525]
I have hit a scenario that I cannot work out, how to fit it in with this package, it may even be out of the scope of this package, but some advice would be brilliant!

I have written my API and it is locked down to only authenticated users, and this works perfectly however there is now another requirement in that a guest needs to be able to access certain sections of the API. I figure I could write a new grant type that takes the allowance of a "guest" login (email adress, and generated hash will act as there username and password). 

Is this is correct way to go? Writing a new grant type, and if it is, where do I put this grant type, and how do I implement it, the package is great, but the docs are sadly lacking this information.

It is worth noting that I am working with Laravel 4.2 not the new Laravel 5 release.

**Comment by vinkla** [comment]
You can use the `client_credentails` grant for guest usage. Since that will only require your client id and secret to work.
