### ISSUE TITLE
Class 'LucaDegasperi\OAuth2Server\Support\Migration' not found

### ISSUE THREAD

**Issue by habibridho** [lucadegasperi/oauth2-server-laravel#532]
Hi,

I want to implement the package to my project. I follow the installation steps from ![here](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Laravel-5-Installation). It works on my local server, but when I clone it to my live server and do 'php artisan migrate', I'm getting this error:

PHP Fatal error:  Class 'LucaDegasperi\OAuth2Server\Support\Migration' not found in /var/www/html/app/database/migrations/2015_01_01_000001_create_oauth_scopes_table.php on line 7

                                                                  
  [Symfony\Component\Debug\Exception\FatalErrorException]         
  Class 'LucaDegasperi\OAuth2Server\Support\Migration' not found  
                                                                  

I've run "composer update", "php artisan vendor:publish", "composer dump-autoload", but I'm still getting the same error.

I'm using Laravel 5.1 and Ubuntu 14.04 x32 for my live server.

Any idea to solve this?

**Comment by vinkla** [comment]
Try republishing the migrations and be sure to use version 5.0.

**Comment by habibridho** [comment]
It turns out that there were conflicting migration file. For example, I have 2014_04_24_110151_create_oauth_scopes_table.php and 2015_01_01_000001_create_oauth_scopes_table.php. And the second one was used. So I deleted all migration file that begins with "2015_01_...". After deleting, I ran "composer dump-autoload" and started the migration again. It works fine now.
