### ISSUE TITLE
Using oauth_clients.name instead of oauth_clients.id to get client

### ISSUE THREAD

**Issue by AndreasHeiberg** [lucadegasperi/oauth2-server-laravel#534]
Is there a reason why in FluentClient line 65 for the get function you have chosen to search by oauth_clients.id and not oauth_clients.name?

It seems common practice (to me) to search by a string not an integer, but I might be entirely wrong.

I suppose string are subject to social engineering, but having integers auto incrementing from 1 is hardly any better. Especially not if you don't have millions of clients (most don't).

Am I wrong? To me it seems like OAuth would be a place where adding the extra entropy of a long string would be important.

**Comment by eidng8** [comment]
oauth_clients.id *is* string

**Comment by vinkla** [comment]
It is a string.
```php
$table->string('id', 40)->primary();
```
