### ISSUE TITLE
oauth/access_token route for Lumen

### ISSUE THREAD

**Issue by ajtrichards** [lucadegasperi/oauth2-server-laravel#537]
Hi.

In the documentation it states the you should use the following route:

```
Route::post('oauth/access_token', function() {
    return Response::json(Authorizer::issueAccessToken());
});
```

However, this doesn't work in Laravel Lumen. How should this be written for use in Lumen? I've seen some other tutorials (http://esbenp.github.io/2015/05/26/lumen-web-api-oauth-2-authentication/) and that gives a different way but I then get an error:

```'ReflectionException' with message 'Class oauth2-server.authorizer does not exist'```

**Comment by vinkla** [comment]
Did you register the the facade correctly? http://stackoverflow.com/a/30400760/4801875
