### ISSUE TITLE
Separate Authorization + Resources

### ISSUE THREAD

**Issue by jeffsrepoaccount** [lucadegasperi/oauth2-server-laravel#541]
After reading through the wiki I'm still left with a nagging feeling I'm missing something. I stumbled on [this issue](https://github.com/lucadegasperi/oauth2-server-laravel/issues/436) where you responded to the other user exactly what I'm trying to do:

> Usually the authentication part is kept separated from the API, which means www.site.com is responsible for providing the access tokens back to the client to then make requests to the API

I want my authorization server and resource server to be in two separate projects.  I am assuming right now that I have to install this package in both projects because without doing so there will be no `oauth` middleware available in my API to protect my resources. Is this correct? 

If so I would think that breaking this package up into two separate packages (one for authorization server and one for resource server) would make sense, because I don't need any of the `oauth_*` tables to exist inside of my API. If I publish the package from artisan, then all of the migrations from this package will then be ran the next time I run `artisan migrate`.  Since this isn't how this package is structured, I think I also may just be missing something.

Is it up to the segregated resource server to implement the `oauth` middleware?

**Comment by alexw23** [comment]
@jeffsrepoaccount Did you manage to get this working with two separate servers?

**Comment by jeffsrepoaccount** [comment]
@alexw23 No, I have the authorization server set up and issuing access tokens, but still not sure I understand how to secure my routes on the resource server.

**Comment by ddelnano** [comment]
Well you need to allow your API to know how to check if an access token is valid. If you are trying to keep things separate that would mean needing to ask the Authorization server if it's valid in some way. If the authorization server isn't validating the access token then your resource server is gonna need access to  the database that has the oauth_* tables.

**Comment by amilajack** [comment]
I would also really love to see an integrated solution to this.

**Comment by lucadegasperi** [comment]
The resource server and authorization server can very well live in two different projects, they would still need to share the same database. basically what you will need to do is publish the migrations of this package for only one of the two projects (the authorization server usually). right now, and it was implemented, the models in this package cannot connect to a different db connection but it something that can be done.

**Comment by jeffsrepoaccount** [comment]
For those wanting to accomplish what I am (having completely separated DB's) I was able to accomplish this.  What I did was use everything from this package in the `src/Storage` folder (basically just copied the files over from the authorization server over and re-namespaced them) and included the `FluentStorageServiceProvider` in `config/app.php`.  I then created another service provider to be able to construct League's resource server:

```php
$app->bind('League\OAuth2\Server\ResourceServer', function() use($app) {
        return new ResourceServer(
            $app->make('App\Oauth2\Storage\FluentSession'),
            $app->make('App\Oauth2\Storage\FluentAccessToken'),
            $app->make('App\Oauth2\Storage\FluentClient'),
            $app->make('App\Oauth2\Storage\FluentScope')
        );
 });
```

Since the `config/oauth2.php` isn't created (because this package isn't being used), it also has to be created manually and the `oauth2.database` config property needs to point to the database holding the user accounts.  From what I've found this is the only configuration value necessary.

The middleware then wound up being easy, and you can see what I came up with in [this gist](https://gist.github.com/jeffsrepoaccount/455a0e93a8fee5830515).  (note I'm using `abort()` in the gist when you probably don't want to; I have a dedicated object to return error json that you probably don't, so you may or may not want to change those statements) The secret behind separating the databases is basically to duplicate the `App\User` model but set the `$connection` property in the model on the resource server to use the database connection to the authorization server instead.

The downsides are the duplicated User model in both projects, and the fact that the resource server has to be aware of the database connection to the accounts server, but being able to have my resource database _only_ have resource tables to me is worth it.

The upside is that, inside of a controller, it's easy to get the user object that the current request's token belongs to:

```php
public function aMethod(Request $request) 
{
    $user = $request->user();
    // ...
}
```

**Comment by tomsowerby** [comment]
We've just come across this while trying to set up a separate auth server that can manage access to many resource API endpoints.
Ideally I'd like to be able to complete the flow described (and diagrammed very well) in http://tutorials.jenkov.com/oauth2/authorization.html
@jeffsrepoaccount I appreciate your efforts here, it looks like you've separated as much as the library allows, and thanks for sharing your solution.
It looks as though [standards are coming](https://tools.ietf.org/html/draft-richer-oauth-introspection-06) for checking who a token belongs to by making a request to the Auth Server from a Resource Server. I notice that [others](http://stackoverflow.com/a/20010178/3169441) have their own solutions for requests too.
I'd be keen to see something implemented in this library when possible.

**Comment by jeboy** [comment]
One important question would be, who's responsible of checking the validity of an access token? The Resource Server or the Authorization Server? If it's the Authorization Server, then, in a Microservices architecture (where each service has its own database), there must be a way for the resources to check with the Authorization Server whether the access token is valid or not through API.
