### ISSUE TITLE
Warning: Ambiguous class resolution.

### ISSUE THREAD

**Issue by vjroby** [lucadegasperi/oauth2-server-laravel#542]
Hi,
I keep getting this error whenever I run a composer update. Maybe a namespace will fix it.

Warning: Ambiguous class resolution, "DatabaseSeeder" was found in both "$baseDir . '/app/database/seeds/DatabaseSeeder.php" and "/var/www/app-api.cb/vendor/lucadegasperi/oauth2-server-laravel/seeds/DatabaseSeeder.php", the first will be used.

**Comment by vinkla** [comment]
Which version are you running? This has been fixed in 5.0.

**Comment by vjroby** [comment]
3.*

**Comment by vinkla** [comment]
Okay, thats why then. It has been fixed in 5.0.

**Comment by vjroby** [comment]
Is version 4 compatible with Laravel 4.2 ? And also backwards compatible with oauth2-server-laravel
version 3 ? Thanks.

**Comment by vinkla** [comment]
No it isn't.

 Laravel  | OAuth Server | PHP 
:---------|:-------------|:----
 4.0.x    | 1.0.x        |>= 5.3
 4.1.x    | 1.0.x        |>= 5.3
 4.2.x    | 3.0.x        |>= 5.4
 5.0.x    | 4.0.x        |>= 5.4
 5.1.x    | 5.0.x        |>= 5.5.9

**Comment by vjroby** [comment]
Ok. Thank you very much!

**Comment by vinkla** [comment]
Anytime!
