### ISSUE TITLE
Authorizer request is not updated within PHPUnit TestCase

### ISSUE THREAD

**Issue by andreikun** [lucadegasperi/oauth2-server-laravel#543]
Hello,

I am using Lumen 5.1 and currently i am working with a TestCase and trying to run some test using PHPUnit. Thing is that within a single TestCase, i am using multiple requests to server. One to get the access token and another ones to secured paths to get specific resources.

Thing is that when ResourceServer class tries to check the validation of the access token by checking Authorization Header, we always get the first request. This means that $this->request is not updated.

I figured out that the problem is caused by the fact that application is boostrapped only at setUp stage within our TestCase, which means that $authorizer->setRequest is called only once, at the beggining, meaning that $this->request will always be the first request. 

Problem: $this->request is not updated accordingly, which means that i want to have always the latest request, in order to be able to get my Authorization header and check authorization.

This may be the first part of the cause. Inside Oauth2ServerServiceProvider.

    $authorizer = new Authorizer($issuer, $checker);
    $authorizer->setRequest($app['request']);

Please find a way of updating request every time a request is made, not only when application is boostrapped.

Find a link to thephpleague issue : https://github.com/thephpleague/oauth2-server/issues/375

**Comment by andreikun** [comment]
Maybe should send $request param inside filter method from OauthFilter, and before $this->authorizer->validateAccessToken, to also do a $this->authorizer->setRequest($request).

**Comment by vinkla** [comment]
We're open to pull requests if you're up for it. Pull requests are the fastest way to get this kind of stuff merged.

**Comment by andreikun** [comment]
I had an older version of the package. Version 4. It seems that issue is fixed now within handle method inside middleware by having $authorizer->setRequest($request).

Thanks.

**Comment by vinkla** [comment]
Aah I see. Great!
