### ISSUE TITLE
i don't know what shall i do after this point

### ISSUE THREAD

**Issue by phpier** [lucadegasperi/oauth2-server-laravel#545]
Hi 

Now after installation and implementation of all steps i have reached this point
https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Client-Credentials-Grant
and i don't know what shall i do then to put my api endpoint on the route of authentication and how to test if it works or not ? 
please help

**Comment by vinkla** [comment]
Try making a request against it with your client credentials.

**Comment by phpier** [comment]
this is the main route for my api pure json data

Route::get('competitions/{id}', 'CompetitionController@index');


and this is the package check route 

Route::post('oauth/access_token', function() {  
    return Response::json(Authorizer::issueAccessToken());
});


how to merge them ?

**Comment by vinkla** [comment]
You need to call before with your middleware. Please see: https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Securing-your-API-endpoints
