### ISSUE TITLE
Validate Credentials Before Middleware?

### ISSUE THREAD

**Issue by brodkin** [lucadegasperi/oauth2-server-laravel#547]
I have a use case in which I would ideally determine the current user before the middleware is executed. Is there a good way to do that? I keep bouncing back and forth in a chicken and egg situation when trying to authenticate my OAuth user with my ACL.

**Comment by lucadegasperi** [comment]
How would you know who the oauth user is if you don't run the middleware that validates the access token and fetches the user? Guess your acl has a method to set the current authenticated user somewhere

**Comment by brodkin** [comment]
I guess that's the question... I'm trying to figure out if there is a way to manually execute the middleware in some reliable fashion. Ideally I'd do this in a service provider.

The only other option is to neuter some of my ACL's features and run everything in a custom middleware. The issue stems from the fact that the ACL lib is instantiated when the user is a guest, but they become privileged during middleware execution via OAuth.

I suppose the better way to look at this would be to delay instantiation of the ACL until a user has been authenticated, but I'm not sure that's possible either. 

Closing in search of a better solution, comments still welcome.
