### ISSUE TITLE
Authorizer::getResourceOwnerID() Globally for All Routes

### ISSUE THREAD

**Issue by dtirer** [lucadegasperi/oauth2-server-laravel#549]
I'm using this package and am able to call `Authorizer::getResourceOwnerId()` to get the logged in User.  However, I would prefer to not call this on every Controller Method.

My question is, how would you integrate this functionality so that you could access $this->user (or similar) from every route without having to explicitly call `$user = User::find(Authorizer::getResourceOwnerId())` every time.

Or this perhaps not the best way to go about accessing your logged in user?

**Comment by vinkla** [comment]
I guess you mean you want to call it from a controller? In that case you could create a custom base controller which your other controllers extend. On the base controller you can create a public method called `getUser()` which returns the user `return User::find(Authorizer::getResourceOwnerId())`;
