### ISSUE TITLE
this package works with Oracle Database?

### ISSUE THREAD

**Issue by joaorobertopb** [lucadegasperi/oauth2-server-laravel#552]
My mission is to implement OAuth2 + Laravel + Oracle database.
To use Oracle on Laravel am using the package yajra / laravel-oci8. 

#Help me please!

Note: Oracle only allows object names up to 30 chars.

**Comment by lucadegasperi** [comment]
sorry for the late answer: at the time being support for oracle is not guaranteed, guess you would have to rename all the tables and relations to max 30chars.

**Comment by joaorobertopb** [comment]
Thanks for the answer.

I managed to implement, actually had to rename the tables and their relationships to a maximum of 30 characters.
