### ISSUE TITLE
Changing the oauth2 database

### ISSUE THREAD

**Issue by mrgswift** [lucadegasperi/oauth2-server-laravel#553]
Hello,

I was wondering if there is a way to change the database connection that oauth2 connects to get credentials. The project I am working on requires the credentials database to be separate from any other database. Basically I need the api server to be able to receive access_tokens.  So the api server would have read access to specific tables in the credential database.

I already added the credentials database to config/database.php, but I can't seem to find a convenient way to change the database for oauth2 to the database on the credentials server.  Am I missing something?

Thanks!

**Comment by Harry1986** [comment]
Hi mrgswift, 

You need to add a new paramater 'database' into your config/oauth2.php. The value should be connection name which you define in database.php (e.g: mysql_oauth2). 

Hope it helps.

**Comment by mrgswift** [comment]
I added the following to config/oauth2.php
    `'database' => 'mysql_oauth2',`

However, it is still trying to connect to the default db 'mysql' 
`QueryException in Connection.php line 636:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'apidb.oauth_access_tokens' doesn't exist (SQL: select * from 'oauth_access_tokens' where 'oauth_access_tokens'.'id' = 23423423423 limit 1)`

Is there something else I need to do to make it work?

My config/database.php look like this:       
  `'connections' => [

        'sqlite' => [
            'driver'   => 'sqlite',
            'database' => storage_path('database.sqlite'),
            'prefix'   => '',
        ],
        'mysql' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST', 'localhost'),
            'database'  => env('DB_DATABASE', 'apidb'),
            'username'  => env('DB_USERNAME', 'xxxxx'),
            'password'  => env('DB_PASSWORD', 'xxxxxxxxx'),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
        'mysql_oauth2' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST', 'xxxxxxxxx'),
            'database'  => env('DB_DATABASE', 'equidy-credentials'),
            'username'  => env('DB_USERNAME', 'xxxxx'),
            'password'  => env('DB_PASSWORD', 'xxxxxxxxxxxxxxxxxxx'),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],`

**Comment by Harry1986** [comment]
Can you post the content of .env file? Because it looks like you setup DB variables in the .evn file with the default DB, therefore when you call evn ('DB_DATABASE', 'equidy-credentials') it always get the value in .evn first (in this case, it is apidb). 

In my setup, I create new constants for oauth2 configuration in .evn file, such as DB_OAUTH2_DATABASE then in database.php I get it via env('DB_OAUTH2_DATABASE','xxxx'). 

Hope it helps.

**Comment by mrgswift** [comment]
Hi Harry1896,

I removed all database values from my .env file and it started working.    Thank you so much for your help!

**Comment by Harry1986** [comment]
You're welcome.

**Comment by vinkla** [comment]
Thanks for helping out @Harry1986!

**Comment by jandayanan** [comment]
Sorry for reupping this issue but, I tried adding `'database' => 'oauth',` to my oauth2.php config file but when I try to run the migrations, it will still migrate the tables to the default database. What may be the cause of the issue? Thanks

**Comment by dreferreira** [comment]
Within each migration file you can manually set the database connection via the following:
Schema::connection("my_database_name")->create('table_name_here', function (Blueprint $table) {
//blahblahblah
}
