### ISSUE TITLE
Documentation Code Inconsistency

### ISSUE THREAD

**Issue by jlien-calwater** [lucadegasperi/oauth2-server-laravel#555]
https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Choosing-a-Grant#authorisation-code-grant-section-41

Example use "auth_**token**_ttl".
```php
'authorization_code' => [
        'class' => '\League\OAuth2\Server\Grant\AuthCodeGrant',
        'access_token_ttl' => 3600,
        'auth_token_ttl' => 60
    ]
```

https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Auth-Code-Grant

Example use "auth_**code**_ttl".
```php
'grant_types' => [
    'authorization_code' => [
        'class' => '\League\OAuth2\Server\Grant\AuthCodeGrant',
        'access_token_ttl' => 3600,
        'auth_code_ttl'   => 3600
    ]
]
```

**Comment by vinkla** [comment]
Fixed. Thanks!
