### ISSUE TITLE
Connecting scopes to specific client_id and user

### ISSUE THREAD

**Issue by sudo2012** [lucadegasperi/oauth2-server-laravel#558]
How can I associate a scope to a specific client_id and user. I guess FB etc is doing it this way. 
When u get redirected by a FB app u get asked to login and grant this specific app the scopes necessary. 
Thanks in advance
Best

**Comment by vinkla** [comment]
When the client makes a request against your access_token endpoint it can send a scopes parameter to ask permission for accessing those scopes. Please see [the documentation](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Securing-your-API-endpoints#defining-scopes).
