### ISSUE TITLE
Update Refresh Token Expiration

### ISSUE THREAD

**Issue by darrylkuhn** [lucadegasperi/oauth2-server-laravel#559]
We have a requirement which is to expire access after 45 minutes of inactivity. To do this we're setting the TTL to 45 minutes and our plan is to update the expiration to t+45 minutes on the refresh token expiration on every request to. Is there an elegant way to do this (other than an ad-hoc SQL query)?

**Comment by lucadegasperi** [comment]
unfortunately there's no elegant way to do it right off the box. Usually the refresh token has a fixed expiration time and so has the access token. The security of the refresh token stands in that it is less frequently exchanged over the wire.

**Comment by darrylkuhn** [comment]
No problem - thanks for the reply
