### ISSUE TITLE
Token issued with Client Credentials asking for scope

### ISSUE THREAD

**Issue by joaoccmatos** [lucadegasperi/oauth2-server-laravel#562]
Hello,

I'm having the following message in Laravel 5.1,  "lucadegasperi/oauth2-server-laravel": "5.0.*", when using middleware oauth : 

> "The requested scope is invalid, unknown, or malformed. Check the \":class\" scope."

I'm using:

>    'grant_types' => [
        'client_credentials' => [
            'class' => '\League\OAuth2\Server\Grant\ClientCredentialsGrant',
            'access_token_ttl' => 3600
        ]
],

and in config/oauth2.php I have:

>     /*
    |--------------------------------------------------------------------------
    | Scope Parameter
    |--------------------------------------------------------------------------
    |
    | Whether or not the scope parameter is required in the query string.
    |
    */

    'scope_param' => false,

    /*
    |--------------------------------------------------------------------------
    | Scope Delimiter
    |--------------------------------------------------------------------------
    |
    | Which character to use to split the scope parameter in the query string.
    |
    */

    'scope_delimiter' => ',',

    /*
    |--------------------------------------------------------------------------
    | Default Scope
    |--------------------------------------------------------------------------
    |
    | The default scope to use if not present in the query string.
    |
    */

    'default_scope' => null,

I have no scopes defined and no need to use any.

Am I doing something wrong?

Thanks.

**Comment by vinkla** [comment]
Please show how you're adding the middleware both in `Kernel.php` and in the controller or routes file.

**Comment by joaoccmatos** [comment]
I've just found out the problem, for Kernel.php in the documentation it says to add:

>'oauth' => LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware::class,
'oauth-user' => LucaDegasperi\OAuth2Server\Middleware\OAuthUserOwnerMiddleware::class,
'oauth-client' => LucaDegasperi\OAuth2Server\Middleware\OAuthClientOwnerMiddleware::class,
'check-authorization-params' => LucaDegasperi\OAuth2Server\Middleware\CheckAuthCodeRequestMiddleware::class

but for me only works like this:

>   'oauth' => 'LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware',
     'oauth-user' => 'LucaDegasperi\OAuth2Server\Middleware\OAuthUserOwnerMiddleware',
     'oauth-client' => 'LucaDegasperi\OAuth2Server\Middleware\OAuthClientOwnerMiddleware',
     'check-authorization-params' => 'LucaDegasperi\OAuth2Server\Middleware\CheckAuthCodeRequestMiddleware'

**Comment by vinkla** [comment]
Which version of PHP are you running?

**Comment by joaoccmatos** [comment]
I'm using PHP 5.5.10

**Comment by vinkla** [comment]
Ohh, I see why. You've to add a `\` in the begging of each string. I'll update the docs. Thanks for finding it!

**Comment by joaoccmatos** [comment]
Ohh damn.. of course! =P

Thanks for the quick answers.

**Comment by vinkla** [comment]
Anytime!
