### ISSUE TITLE
Authorization header does not reach server - no access token

### ISSUE THREAD

**Issue by Twisterking** [lucadegasperi/oauth2-server-laravel#566]
So I am using Lumen with the v5.0.2 of your lib.
I already have received an access token and now want to GET some resource from the api:
```php
$app->group(['prefix' => 'api', 'middleware' => 'oauth'], function($app) {
    $app->get('resource', function() {
        return response()->json([
            "id" => 1,
            "name" => "A resource"
        ]);
    });
});
```
I followed [this tutorial](http://esbenp.github.io/2015/05/26/lumen-web-api-oauth-2-authentication/) (with some adapdations) - so I am also using the jQOAuth plugin, which appends the `Authorization` header automatically to every get request. This works just fine (according to Chrome DevTools).

Problem is that this header doesn't seem to reach the server. I get an exception saying
```bash
"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the "access token" parameter."
```
So I searched for the function throwing this error: It should be `determineAccessToken` in `vendor/league/oauth2-server/src/ResourceServer.php`.
I tried `Log::debug('HEADERS: ' . $this->getRequest()->headers);`which gives me this:
```bash
Accept:           */*
Accept-Encoding:  gzip, deflate, sdch
Accept-Language:  de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
Connection:       keep-alive
Cookie:           refreshToken=eyJpdiI6Il....
Host:             apitest.com
Referer:          http://apitest.com/
User-Agent:       Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.52 Safari/537.36
X-Csrf-Token:     null
X-Requested-With: XMLHttpRequest
```
No Authorization header. Thus no access token.
I really don't understand what's wrong here. I know that the Authorization is somehow hidden but it has to show up here. Otherwise `if ($this->getRequest()->headers->get('Authorization') !== null)` could never work?!

**Comment by vinkla** [comment]
When requesting `api/resource` did you provide a valid access token?

**Comment by Twisterking** [comment]
Yes of course. Calling `/login` first provides me with a valid access token. These are also saved in my `oauth_access_tokens` table. This is then attached to the normal GET call in the header like so: `Authorization: Bearer j4nskfh57w...`. It also shows up in the request headers of the call in chrome dev tools.

**Comment by vinkla** [comment]
What happens if you add it to the query string? Does that work?

**Comment by Twisterking** [comment]
Yes, `?access_token=f4hkdjf445...` works. Although I would really prefer sending it in the header for more security.

**Comment by vinkla** [comment]
Yeah I totally agree, it is much cleaner sending it in the header. Could you show me how you add the header to the request?

**Comment by Twisterking** [comment]
[jQOAuth](https://github.com/esbenp/jquery-oauth) handles this for me. My client.js code is completely identical to this one: [click](https://github.com/esbenp/lumen-api-oauth/blob/master/public/js/client.js)
If it helps you I can also push my whole project onto github so you can have a look. If you need that please let me know, I will do it when I come back (gotta take off now).

**Comment by vinkla** [comment]
Yeah, I can't see where the headers are added in the js file. Maybe just provide the file that add the headers?

**Comment by Twisterking** [comment]
As of said, jQOAuth does that for me, but I think it should be [here at line 176](https://github.com/esbenp/jquery-oauth/blob/master/src/jquery.oauth.js).

**Comment by vinkla** [comment]
That looks like it should work. You could use the access token in the query string in the mean time, until you figure out what the issue is. I'm personally using the header in a own project of mine without any problems.

**Comment by Twisterking** [comment]
hmm ... any other ideas on this? I am a little bit lost here as I can clearly see in chrome dev that the header is properly attached but it just doesn't reach the server.

**Comment by vinkla** [comment]
Try doing the request with outside your script files just to see if it can pick up the header. Have yuo tried [Postman](https://www.getpostman.com/)?

**Comment by Twisterking** [comment]
I tried exactly that already. same response. attached the Header like so
```
Authorization: Bearer i9xuwRCU8XSGJBT4ewKxFGrzb614n832GqWvV80U
```
Same error. :-(

**Comment by vinkla** [comment]
Can you show me a print screen of that from Postman?

**Comment by Twisterking** [comment]
There you go:
![postman](https://cloud.githubusercontent.com/assets/4247268/10365065/a0ef56d6-6dc0-11e5-8f4f-c7e96118aea6.png)

**Comment by vinkla** [comment]
That is very strange, could you try dumping the request in the middleware just to see what heppens.

**Comment by Twisterking** [comment]
Do you mean returning all the headers in the route to see all the request headers? If so, I already tried that - no Authorization header. btw I am running xampp on mac if that helps? maybe some apache problem?
New to all of this sorry - so not really sure what you mean.

**Comment by vinkla** [comment]
Yeah, try making the request outside xampp.

**Comment by DEATHMETALGORE** [comment]
I'm having the same issue and I would like to keep using the `Authorization` header.

**Comment by DEATHMETALGORE** [comment]
OK I found the issue here.

So basically, we use this to fetch the header:
```
$this->getRequest()->headers->get('Authorization')
```
Which is fine in most cases, except this one. I logged the following value like this:
```
error_log(print_r(getallheaders(), true));
```
And the output is like this:
```
[25-Oct-2015 09:56:50 UTC] Array
(
    [Host] => localhost
    [Connection] => keep-alive
    [User-Agent] => Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
    [Accept] => */*
    [X-CSRF-Token] => null
    [Authorization] => Bearer OV5RD0Eadc5WazTs36QuO08tCh5fxmv5vOs4q3RH
    [X-Requested-With] => XMLHttpRequest
    [Referer] => http://localhost/api/public/
    [Accept-Encoding] => gzip, deflate, sdch
    [Accept-Language] => en-US,en;q=0.8,de;q=0.6,sq;q=0.4,sr;q=0.2
    [Cookie] => refreshToken=eyJpdiI6ImRHeGZ5WmlGb0VPeE5CZUx6SFVwdHc9PSIsInZhbHVlIjoiRmpSQmxwd2tDVmtTQ2V0Kzg1MEdzcllNbTRScys0SStuRFJENFwvQXNIRmJJMXlvKzUzNW9mQkV0Y0VQQjg5aTlxVUR2ZEk0cVFFMHZaT2ZWQnp2V25UbmJ6MXhRZ3hmcWFaazd3N1RkYnhrdFRTTVNPbHdRNUhHR0IweHFaUzdJd1l4UzNVRzg2ajdkRWk5OHZ4RllGMklvSk5YenEzME1uRXFcL2dZNTFpbG5ZcXFWd0FLWWx3U1lMbHhibU0zb3VkbGkrWExoN28rTkJyOERJU1wveGx1cXVhTkdNeW1yTmt0Q2dzXC9RM0cxQThFeHNCenRtVFlzUjRsY0JGdFVKV3NFSGRIb2VwQTM3eFBEY2VcL3dyVGErSHp5a3JEU3d1eWUrZ2Z6NURaZzRCRVZHdHE3Tk5kSHp0RjBmVVczeUV5TldxdmJOODBYa2pKcW53YW13ZHZlRkI2MzVNT1lHTmtyKzdYM0lWd1NqMEJtUnpmM2dSeFo3NVZFQzlINnFITzIiLCJtYWMiOiJlZmVhOTFmYmNmOTFmNmU1N2Y4MzExYTg5ZWNkM2QxNGViZDNkYmY5OTU5ZDg5ZDU5MWIxYzY0MGQ4NTE4ODFhIn0%3D
)
```
Why would Lumen not take the Authorization header?

**Comment by stevegrove** [comment]
@dugajean comment on https://github.com/esbenp/lumen-api-oauth/issues/18 worked for me:

> I fixed this problem. Simply add the following to your public/.htacess after RewriteEngine On:

> RewriteCond %{HTTP:Authorization} .
> RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

**Comment by pkendre** [comment]
Hi, 
I know it is too late to comment on this, but unfortunately I just worked on it.
I have resolved this issue, "Sending access_token in header instead of body

This is how I have fixed it.
1. Config/oauth2.php
change the value of 'http_headers_only' to 'true'

2. c:\xampp\htdocs\PROJECT_NAME\vendor\lucadegasperi\oauth2-server-laravel\src\Middleware\OAuthMiddleware.php

Replace the line $this->authorizer->validateAccessToken($this->httpHeadersOnly);
by following 2 lines
$access_token = $request->headers->get('access_token');
$this->authorizer->validateAccessToken($this->httpHeadersOnly, $access_token);

The function defination of "validateAccessToken" in c:\xampp\htdocs\PROJECT_NAME\vendor\lucadegasperi\oauth2-server-laravel\src\Authorizer.php expect 2 parameter, 1 st httpHeadersOnly  and 2nd is accessToken. Both the parameters have defualt values to them, but we have to overwrite the 2nd parameter as well.

How to test it:
1. Open REST Easy (plugin for FireFox) or Postman
2. In Headers section, add the key value pair like, "access_token" as key and et4UYjf2gTR2Rq051mImQSM85Mkj3pZw3wuzdP4E as value 
3. In Data section, pass the data in whatever format you are using, form-data, row JSOn 
Click on Send button.

Hope this willl work for you as well.

I know, editing the source code of "lucadegasperi" may not be the valid way, but after googling and digging the source code for 2 days, I can find only this solution.

If anyone has better way to do the same, please post your suggestion/steps here.

-Paresh (kendreparesh@gmail.com)
