### ISSUE TITLE
How to separate Authorization Server and  Resource Server?

### ISSUE THREAD

**Issue by ken8203** [lucadegasperi/oauth2-server-laravel#568]
Hello,

I want  to separate Authorization Server and  Resource Server.
How can I design it?
Do they need to connect the same database?
If not, how does resource server verify the access token?

Thanks a lot!

**Comment by rjbaker** [comment]
You can specify a different database connection in the oauth server service provider config. That way, any credential queries, token lookups etc are run with that db connection. The authorization server stores a user ID entity as a string which is passed into to your verification handlers/callbacks (e.g. password grant). This allows you to map user entities in your resource server with user ids related to tokens stored in the authorization server.

https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/src/Storage/FluentStorageServiceProvider.php#L125

**Comment by vinkla** [comment]
Please see #541
