### ISSUE TITLE
Error 500 with laravel-cors

### ISSUE THREAD

**Issue by guilhermegonzaga** [lucadegasperi/oauth2-server-laravel#569]
Hello,

I'm having some problems while developing my application ionic/angular + laravel.

When making any request to my API with oauth2-server-laravel, the answer should be a 401 error, it returns a 500 error.

When the request returns the token, the problem does not happen.

Using POSTMAN, the problem also happens.

I realized that when I take https://github.com/barryvdh/laravel-cors package from my API, in POSTMAN works perfectly, but in my Ionic application returns "Access-Control-Allow-Origin".

Can someone help me?

**Comment by lucadegasperi** [comment]
Not a problem with the package itself you have a problem with cross origin. In short, browser tend to disallow request that try to request something on a domain different from the origin one. This happens on your ionic app while you're using the livereload extension, It should go away on the actual compiled app. or you can add specific header on the response from the api server.
