### ISSUE TITLE
Angular POST request missing parameters

### ISSUE THREAD

**Issue by arjenduinhouwer** [lucadegasperi/oauth2-server-laravel#570]
When issuing a POST request from our Angular frontend to our Laravel backend we encounter a problem when requesting the access-token. We receive a 400 error, where we can successfully request the token in Postman. 

The request arrives in good order, i can see the headers with $request->header(); 

```
array:12 [
  "content-type" => array:1 [
    0 => "application/form-encoded"
  ]
  "content-length" => array:1 [
    0 => "0"
  ]
  "host" => array:1 [
    0 => "apm.dev"
  ]
  "connection" => array:1 [
    0 => "keep-alive"
  ]
  "origin" => array:1 [
    0 => "http://localhost"
  ]
  "user-agent" => array:1 [
    0 => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
  ]
  "accept" => array:1 [
    0 => "application/json, text/javascript, */*; q=0.01"
  ]
  "username" => array:1 [
    0 => "email@email.com"
  ]
  "password" => array:1 [
    0 => "secret"
  ]
  "referer" => array:1 [
    0 => "http://localhost/apm-test/test.html"
  ]
  "accept-encoding" => array:1 [
    0 => "gzip, deflate"
  ]
  "accept-language" => array:1 [
    0 => "en-US,en;q=0.8,nl;q=0.6,fr;q=0.4,de;q=0.2"

```

Here is my request as currently used in Angular:
```
 var config = {
            headers: {
                // 'Content-Type': 'application/form-encoded',
                'grant_type' : 'password',
                'client_id' : '1',
                'client_secret' : '1234',
                'username' : this.username,
                'password' : this.password
            }
        };

        $http.post('http://apm.dev/oauth/access_token', config)
``` 
But when  I call the Response::json(Authorizer::issueAccessToken()) No token is returned, but this error is:

```
"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"grant_type\" parameter."}
```

I'm using Laravel 5.1 and oauth2-server-laravel": "5.0.*"

Could you give some hints how to get this to work? 

Thanks!

**Comment by lucadegasperi** [comment]
Have you checked this? https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Apache-ModRewrite

**Comment by arjenduinhouwer** [comment]
Thank you for replying!

I'm sorry, i forgot to mention i'm developing on Homestead, so this project runs on Nginx.

**Comment by pashamesh** [comment]
Try to use next header in request:
`"Content-Type": "application/x-www-form-urlencoded"`

**Comment by arjenduinhouwer** [comment]
Thanks for your contribution in this matter pashamesh. 

Due to other work I wasn't able to respond earlier, but this morning I tried your solution, the header was allready set, so i just moved the other data like you suggested. I'm still getting 400 errors. So no luck yet. 

Today i'll be focussing on resolving this issue and will keep you all posted.

**Comment by pashamesh** [comment]
Also you can use `$httpParamSerializerJQLike` instead of `$.param` to avoid jQuery dependency.

https://docs.angularjs.org/api/ng/service/$httpParamSerializerJQLike

**Comment by arjenduinhouwer** [comment]
Much easier to remember as well ;)

on a serious note, thank you for the suggestion!
