### ISSUE TITLE
Authorization grant flow error in get Method.

### ISSUE THREAD

**Issue by maxpinto** [lucadegasperi/oauth2-server-laravel#572]
hi, i am trying to use the Authorization code grant flow, but always returns invalid cliente credentials, this is what i am doing:

In my routes.php i have added this:

     Route::group(['prefix' => 'thirdParty','middleware' => ['csrf', 'check-authorization-params', 'auth']],
     function() {
     Route::get('oauth/authorize', ['as' => 'oauth.authorize.get', function() {
        // display a form where the user can authorize the client to access it's data
        return "hola";
        $authParams = Authorizer::getAuthCodeRequestParams();
        $formParams = array_except($authParams,'client');
        $formParams['client_id'] = $authParams['client']->getId();
        return View::make('oauth.authorization-form', ['params'=>$formParams,'client'=>$authParams['client']]);
    }]);
    
    Route::post('oauth/authorize', ['as' => 'oauth.authorize.post', function() {
        $params = Authorizer::getAuthCodeRequestParams();
        $params['user_id'] = Auth::user()->id;
        $redirectUri = '';
        // if the user has allowed the client to access its data, redirect back to the client with an auth code
        if (Input::get('approve') !== null) {
            $redirectUri = Authorizer::issueAuthCode('user', $params['user_id'], $params);
        }
        // if the user has denied the client to access its data, redirect back to the client with an error message
        if (Input::get('deny') !== null) {
            $redirectUri = Authorizer::authCodeRequestDeniedRedirectUri();
        }
        return Redirect::to($redirectUri);
    }]);
    });` 

I have added the Auth Code Grant Credentials y grant type (oauth2.php).
I am logged, so the filter auth is passed.
I have added the client and client end point

     insert into laravel5.oauth_client_endpoints values (2,'cliente1','http://www.mysite.com',null,null);
     insert into laravel5.oauth_clients values('cliente1','secret','testclient',null,null);

And considering the specifications i have done all, so when i try to get the authorization code, making the get method, such as:

http://dev.laravel5.local/thirdParty/oauth/authorize?client_id=cliente1&redirect_uri=https://www.mysite.com&response_type=code

Its always returns:
    {"error":"invalid_client","error_description":"Client authentication failed."}

And repeat i have success logged in.

Whats could be my problema?

**Comment by lucadegasperi** [comment]
Still encountering this problem?

**Comment by mpinto198** [comment]
sorry, i fixed this, i have to change a litle code, dont know because i was using laravel 5.1, but it works like a charm now. You could close the issue

**Comment by SagarNaliyapara** [comment]
How you solved this...??

**Comment by sshfl** [comment]
I also use this but I always get this error
Sorry, the page you are looking for could not be found.

**Comment by Eanghort** [comment]
I encountered this issue in Laravel 5.1 too. Could you tell me how to resolve this problem?
