### ISSUE TITLE
Could add some documents to explain how to use these database tables?

### ISSUE THREAD

**Issue by argb** [lucadegasperi/oauth2-server-laravel#573]
I am new to OAuth,so not very clear to what does these tables mean?how to use them,which case?which table do i need to add data row manually? And which table will generate data automatic?

**Comment by vinkla** [comment]
If you're up for it we would gladly accept if you would like to write this @argb. Just post it here and then we can take a look at it!

**Comment by leemason** [comment]
I think he's saying he doesn't know how to use it, not that he can add docs for it, he wants to read docs.

Ive got my head round it, but its taken me a good day to get it sorted, im probably going to build a couple of eloquent model and release that as a package as im sure alot of people will be able to understand that easier (unfortunatley not everyones so happy to dive into fluent query building).

Don't get me the wrong the docs are great at what they do provide, but for example they don't answer the following fundemental questions:

1. how do i authorise a user using the laravel auth class? (there is a way to do this using the grant type callback with class@method syntax but this is no where to be found in the docs)
2. how do i create a client?
3. how do i assign scopes to a client/user?

This is basically what i a user of this page wants to do, and nothing is present in the docs for it.

This package is awesome and i think the lack of docs for everything is mainly down the size of the feature set it provides, keep up the good work and whenever i have time ill try and help out with docs.

**Comment by argb** [comment]
@leemason You understood me :+1:

**Comment by vinkla** [comment]
I get your point but please submit an issue or PR if you guys want to improve the docs. @lucadegasperi and I are doing this on are spare time and we happily help developers out when they are having trouble getting started. If you submit a PR we would gladly take a look. We always want to improve things.

Thanks for raising the issue!

**Comment by json2x** [comment]
Thanks for this! This is so perfect for my current project! 
I would love to see a detailed documentation of this though, specially about the scopes, grants and etc (all other tables in the migration, what are they and how can be used) :+1:

**Comment by sherkhanz** [comment]
Off the topic question, But can someone tell me how secure it is? I am completely new to creating Oauth Server so Can anyone help me understand security of this package? Thanks :+1:

**Comment by vinkla** [comment]
@json2x same answer as in https://github.com/lucadegasperi/oauth2-server-laravel/issues/607#issuecomment-158766555.

**Comment by vinkla** [comment]
@sherkhanz please see https://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified

**Comment by Yanisky** [comment]
@vinkla I think there's maybe a naming miss match from the project docs and the article you provided (https://aaronparecki.com/articles/2012/07/29/1/oauth2-simplified).

If I implement the endpoint in the docs for the Password grant (https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Password-Grant) and then hit the endpoint "oauth/access_token" on the server. If I don't provide the client_secret in the request the server always responds with "The request is missing a required parameter etc..", but on the article you posted it says that only the client_id is needed for the "Password Grant", am I missing something?

**Comment by vinkla** [comment]
Both the `client_id` and `client_secret` is required.

**Comment by vinkla** [comment]
The documentation is now open sourced. Any help is appreciated!
