### ISSUE TITLE
Password grant_types on multiple tables

### ISSUE THREAD

**Issue by maivien310** [lucadegasperi/oauth2-server-laravel#575]
Our system have 2 mobile apps for **User** and **Manager**, their functions are difference. We have 2 tables in DB: 
- `users` table
 - `username`
 - `password`

- `managers` table
 - `username`
 - `password`

Now I don't know how to implement OAuth2 for our system because we have 2 types of login. 
We only have one route for client to get the `access_token`
```
Route::post('oauth/access_token', function() {
    return Response::json(Authorizer::issueAccessToken());
});
```
We don't know the way to check the client is a user or a manager, and how to login into difference tables. Please tell me this package can do that or not. 
Thanks so much

**Comment by vinkla** [comment]
When you create two custom grants class were you check for custom fields. For users you can use the default `PasswordGrant` and for managers you could create a new grant which is called `ManagerGrant`.

**Comment by maivien310** [comment]
Thanks so much. So I have to create a new GrantType. But I still have a question, how can I get the `grant_type` via `access_token`. Because I want to know the current logged user is a user or a manager.
Thanks

**Comment by vinkla** [comment]
When you send the request with the `grant_type` parameter you can simply save it with the access_token object.

**Comment by maivien310** [comment]
Oh, Now I have the solution. Thank you so much.

**Comment by vinkla** [comment]
:+1:
