### ISSUE TITLE
Documentation (LV5 install) regarding FluentStorageServiceProvider::class

### ISSUE THREAD

**Issue by brian5117** [lucadegasperi/oauth2-server-laravel#576]
composer update errors with '::class' suffix, but appears to work correctly without them.
 
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"php": ">=5.5.9",
		"laravel/framework": ">=5.1"
	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1",
		"fzaninotto/faker": "^1.5",
		"lucadegasperi/oauth2-server-laravel": "5.0.*"	
	},

**Comment by vinkla** [comment]
It works with or without, the implementation is up to you.
