### ISSUE TITLE
Missing scope pass through in authentication form

### ISSUE THREAD

**Issue by joetjen** [lucadegasperi/oauth2-server-laravel#577]
In the Wiki, in [Implementing-an-Authorization-Server-with-the-Auth-Code-Grant](https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Auth-Code-Grant) the get method and the authentication form should be updated to include the scope as otherwise when the access_token is generated the scope is lost and thus only the default scope configured in oauth2.php gets used. If scope is set to required and/or the default value is null errors happen.

My updated get method looks like
```php
// display a form where the user can authorize the client to access it's data
$authParams = Authorizer::getAuthCodeRequestParams();
$formParams = array_except($authParams, 'client');
$formParams['client_id'] = $authParams['client']->getId();
$formParams['scope'] = implode(config('oauth2.scope_delimiter'), array_map(function ($scope) {
    return $scope->getId();
}, $authParams['scopes']));

return View::make('oauth.authorization-form', ['params' => $formParams, 'client' => $authParams['client']]);
```

accordingly I updated `authorization-form.blade.php`:

```blade
[...]
{!! Form::hidden('state', $params['state']) !!}
{!! Form::hidden('scope', $params['scope']) !!}
{!! Form::submit('Approve', ['name'=>'approve', 'value'=>1, 'class'=>'btn btn-success']) !!}
[...]    
```

~Jan

**Comment by robinvalk** [comment]
Thx @joetjen! I would never have figured that out in a reasonable amount of time.

Should definitely be included!

**Comment by vinkla** [comment]
@joetjen it would be awesome if you wanted to create a pull request for this!

**Comment by joetjen** [comment]
https://github.com/lucadegasperi/oauth2-server-laravel/pull/621 Did as you asked.

**Comment by vinkla** [comment]
@joetjen thanks!
