### ISSUE TITLE
[BUG] php artisan migrate:rollback not working

### ISSUE THREAD

**Issue by williamokano** [lucadegasperi/oauth2-server-laravel#579]
Hi, I can't rollback a fresh installed version of your oauth server on a fresh installed Laravel 5.1.

I get the following error on rollback (or refresh):

[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'CreateOauthRefreshTokensTable' not found

**Comment by vinkla** [comment]
Trying running `composer dump-autoload` and try again.

**Comment by williamokano** [comment]
Hi,

It worked before I ran te dump-autload, forgot to close here.

Also, I haven´t changed anything, so... just ignore that lel.

Sorry about that!
