### ISSUE TITLE
Calling various 'get' methods without active session throws exception

### ISSUE THREAD

**Issue by tpavlek** [lucadegasperi/oauth2-server-laravel#580]
The various methods:

```
getResourceOwnerId()
getClientId()
getResourceOwnerType()
getScopes()
hasScope($scope)
```

all are internally implemented by calling `->getAccessToken()`. If these are called in the scenario where there is currently no active session with an access token, all of them will fail with `called {method} on null` which isn't a very helpful error, and causes a lot of confusion while debugging.

Likely the best solution would be to make a `NoActiveAccessTokenException` that gets thrown whenever one of these methods attempts to be called without an access token.

**Comment by lucadegasperi** [comment]
I'll accept a pull request on this :)

**Comment by tpavlek** [comment]
The fix for this was merged in, thanks guys!

**Comment by vinkla** [comment]
No, thank you!
