### ISSUE TITLE
Getting error with OAuth Password Grant Type

### ISSUE THREAD

**Issue by gr8abbasi** [lucadegasperi/oauth2-server-laravel#583]
I am getting invalid client issue as shown in below screenshot. Please can you guide me where I am going wrong. I am using MongoDB and below you can find oauth_clients resultset as well.

![oauth-issue](https://cloud.githubusercontent.com/assets/10723627/10871708/a32c1100-80ee-11e5-8057-93368c243bc9.png)

![oauth_clients_table](https://cloud.githubusercontent.com/assets/10723627/10871709/a61f82a2-80ee-11e5-91c9-0d825539a150.png)

**Comment by gr8abbasi** [comment]
Can anyone help me on this?

**Comment by lucadegasperi** [comment]
yes. at first look looks like you're using "email" as a property key instead of "username".

**Comment by gr8abbasi** [comment]
Thanks for the response. I have already tried with username as well but its same error.

**Comment by gr8abbasi** [comment]
Just to help anyone else who might face same issue, I was using MongoDB so it was all related to that. I am planning to extend this package to support MongoDB and will share with you guys if I am able to do so.
