### ISSUE TITLE
Using Auth Grant with App Facebook login

### ISSUE THREAD

**Issue by lvandyk** [lucadegasperi/oauth2-server-laravel#584]
We have users that can login with Facebook on the mobile app, once that is done, they get a token which is posted to our server where we retrieve the users details and register them. Now to provide the user with an access token, can the client use the auth code grant since the password grant is unusable as the user does not have a password.

Or should I create my own grant type using the facebook id only?

**Comment by vinkla** [comment]
Best thing would be to create a custom grant for Facebook which accepts the user Facebook ID and Facebook access token. Then you can validate the user with the ID and access token in your back-end.

**Comment by lvandyk** [comment]
Thanks for the speedy reply. Thats what I thought, do you have any sample code for this as the League website has: TODO.

**Comment by lvandyk** [comment]
Wait a mintute! We could simply use the password grant with a custom callback verifier that checks token/user id instead of username/password!

**Comment by vinkla** [comment]
You could use something similar yes but it would be good to implement it in a custom grant. If you were to use a custom grant you don't have to use a custom callback. You can do the check directly in your new Facebook grant class.
