### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by dukejib** [lucadegasperi/oauth2-server-laravel#585]
Hi There.

For the first time i tried your code and it is resulting in error (after running composer update)

Please help. Thanks.
============================================
Problem 1
    - Conclusion: remove laravel/framework v5.0.33
    - Conclusion: don't install laravel/framework v5.0.33
    - Conclusion: don't install laravel/framework v5.0.32
    - Conclusion: don't install laravel/framework v5.0.31
    - Conclusion: don't install laravel/framework 5.0.30
    - Conclusion: don't install laravel/framework v5.0.29
    - Conclusion: don't install laravel/framework v5.0.28
    - Conclusion: don't install laravel/framework v5.0.27
    - Conclusion: don't install laravel/framework v5.0.26
    - Conclusion: don't install laravel/framework v5.0.25
    - Conclusion: don't install laravel/framework v5.0.24
    - Conclusion: don't install laravel/framework v5.0.23
    - Conclusion: don't install laravel/framework v5.0.22
    - Conclusion: don't install laravel/framework v5.0.21
    - Conclusion: don't install laravel/framework v5.0.20
    - Conclusion: don't install laravel/framework v5.0.19
    - Conclusion: don't install laravel/framework v5.0.18
    - Conclusion: don't install laravel/framework v5.0.17
    - Conclusion: don't install laravel/framework v5.0.16
    - Conclusion: don't install laravel/framework v5.0.15
    - Conclusion: don't install laravel/framework v5.0.14
    - Conclusion: don't install laravel/framework v5.0.13
    - Conclusion: don't install laravel/framework v5.0.12
    - Conclusion: don't install laravel/framework v5.0.11
    - Conclusion: don't install laravel/framework v5.0.10
    - Conclusion: don't install laravel/framework v5.0.9
    - Conclusion: don't install laravel/framework v5.0.8
    - Conclusion: don't install laravel/framework v5.0.7
    - Conclusion: don't install laravel/framework v5.0.6
    - Conclusion: don't install laravel/framework v5.0.5
    - Conclusion: don't install laravel/framework v5.0.4
    - Conclusion: don't install laravel/framework v5.0.3
    - Conclusion: don't install laravel/framework v5.0.2
    - Conclusion: don't install laravel/framework v5.0.1
    - lucadegasperi/oauth2-server-laravel 5.0.0 requires illuminate/config 5.1.* -> satisfiable by illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.6, v5.1.8].
    - lucadegasperi/oauth2-server-laravel 5.0.1 requires illuminate/config 5.1.* -> satisfiable by illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.6, v5.1.8].
    - lucadegasperi/oauth2-server-laravel 5.0.2 requires illuminate/config 5.1.* -> satisfiable by illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.6, v5.1.8].
    - lucadegasperi/oauth2-server-laravel 5.0.3 requires illuminate/config 5.1.* -> satisfiable by illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.6, v5.1.8].
    - don't install illuminate/config v5.1.1|don't install laravel/framework v5.0.0
    - don't install illuminate/config v5.1.13|don't install laravel/framework v5.0.0
    - don't install illuminate/config v5.1.16|don't install laravel/framework v5.0.0
    - don't install illuminate/config v5.1.2|don't install laravel/framework v5.0.0
    - don't install illuminate/config v5.1.20|don't install laravel/framework v5.0.0
    - don't install illuminate/config v5.1.22|don't install laravel/framework v5.0.0
    - don't install illuminate/config v5.1.6|don't install laravel/framework v5.0.0
    - don't install illuminate/config v5.1.8|don't install laravel/framework v5.0.0
    - Installation request for laravel/framework 5.0.* -> satisfiable by laravel/framework[5.0.30, v5.0.0, v5.0.1, v5.0.10, v5.0.11, v5.0.12, v5.0.13, v5.0.14, v5.0.15, v5.0.16, v5.0.17, v5.0.18, v5.0.19, v5.0.2, v5.0.20, v5.0.21, v5.0.22, v5.0.23, v5.0.24, v5.0.25, v5.0.26, v5.0.27, v5.0.28, v5.0.29, v5.0.3, v5.0.31, v5.0.32, v5.0.33, v5.0.4, v5.0.5, v5.0.6, v5.0.7, v5.0.8, v5.0.9].
    - Installation request for lucadegasperi/oauth2-server-laravel 5.0.* -> satisfiable by lucadegasperi/oauth2-server-laravel[5.0.0, 5.0.1, 5.0.2, 5.0.3].

**Comment by ddelnano** [comment]
What does your composer.json file look like that output isn't very helpful without that.  You probably are trying to install a version that is not compatible with the version of laravel you are using.

**Comment by dukejib** [comment]
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"type": "project",
	"require": {
		"laravel/framework": "5.0.*",
		"Illuminate/html": "^5.0",
		"illuminate/html": "5.0.*",
		"doctrine/dbal": "^2.5",
		"barryvdh/laravel-ide-helper": "^2.0",
		"chrisbjr/api-guard": "^2.3",
		"lucadegasperi/oauth2-server-laravel": "5.0.*"
		
	},
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.1"
	},
	"autoload": {
		"classmap": [
			"database"
		],
		"psr-4": {
			"App\\": "app/"
		}
	},
	"autoload-dev": {
		"classmap": [
			"tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php -r \"copy('.env.example', '.env');\"",
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	}
}

**Comment by ddelnano** [comment]
You need to check [this](https://github.com/lucadegasperi/oauth2-server-laravel#version-compatibility).

You are trying to install the version for Laravel 5.1 you need 
`"lucadegasperi/oauth2-server-laravel": "4.0.*"`

**Comment by dukejib** [comment]
Thanks @ddelnano 
It's working now. But i am bit confused. The table clearly says

Laravel 	OAuth Server 	PHP
5.1.x 	5.0.x 	>= 5.5.9
then why i need to use OAuth 4.0 with my Laravel 5.1?

**Comment by ddelnano** [comment]
You don't have Laravel 5.1 you have 5.0

**Comment by vinkla** [comment]
Thanks for helping out @ddelnano!
