### ISSUE TITLE
Custom grant required?

### ISSUE THREAD

**Issue by russellgalpin** [lucadegasperi/oauth2-server-laravel#586]
I'm trying to use OAuth2 to authenticate API requests and I'm unsure if a custom grant should be being used or even OAuth at all?

I would like users to create access tokens via a web portal they login to using standard Laravel authentication. They can then copy and paste these access tokens into their own application. The token would be given a TTL of say 1 year. Their applications would send these access tokens in the normal 'oauth' way via the Authorization header / Bearer. The API endpoints would be protected by the oauth middleware and somehow return the UserId / User Object of the user to the application.

I cannot seem to find a way to implement these, I would have thought it'd be pretty common use case for this type of thing? Am I missing something?

Any pointers really appreciated.

Thanks

**Comment by vinkla** [comment]
Better would be to let users generate new client credentials. Then they can fetch access tokens from their own applications with those instead.
