### ISSUE TITLE
Limit users according to client scope

### ISSUE THREAD

**Issue by geshner** [lucadegasperi/oauth2-server-laravel#588]
Sorry if here is not the place to ask this, but I'm trying to use OAuth on my API, I already installed and it's working. I can get an access token for my user and I can make requests with it. Now I'm trying to restrict some routes according to clients scopes, but I don't know how to do it. I'll appreciate if someone can help me with this.

for example, i have these routes:

/state (get)
/state(post)

but I want to give the access to /state (post) if the user is using a specific client to access is it possible or I have to create user scopes? In any case how can I do it?

**Comment by vinkla** [comment]
I would go with scopes in the case. When you generate a new access token you fetch it with required scopes and the use that access token to post to `/state`.

**Comment by geshner** [comment]
Thank you @vinkla I read more about scopes, and tryied it.
It's working as I wanted.

**Comment by vinkla** [comment]
:+1:
