### ISSUE TITLE
Got ClientCredentials Working, but how to adapt username/password approach?

### ISSUE THREAD

**Issue by sentiasa** [lucadegasperi/oauth2-server-laravel#590]
I am using Lumen and I have created client_credentials example, created some `client_id` and `client_secret` and I am receiving `{"access_token":"qEURuGGqd8ZIgnpNxZPmXkaEOI5FRyuWRWeMF4Nh","token_type":"Bearer","expires_in":3600}` as response in Postman.

However, I got confused adding classic username/password approach. Let's say for example, I am submitting the credentials - username & password - from html to controller through post request. Should I validate username & password variables and if success, try to validate `client_id` and `client_secret` afterwards, or other way around?

Also, if it's not a smart thing to store `client_id` & `client_secret` in the html, should I just statically write them in the controller (or maybe .env file), so I will know it'll success every time on that step, and basically just verify username & password and pass me the token?

I am quite confused setting up the logic. Can you please guide me on that?

**Comment by vinkla** [comment]
Did you manage to solve it?

**Comment by sentiasa** [comment]
@vinkla Actually no. But I created a new question with more detailed explanation: https://github.com/lucadegasperi/oauth2-server-laravel/issues/595

**Comment by vinkla** [comment]
Okay, good.
