### ISSUE TITLE
client authentication failed with 500 status code

### ISSUE THREAD

**Issue by yansen-tan** [lucadegasperi/oauth2-server-laravel#592]
I'm using client_credential grant type to authenticate my web application on my API.
Here is the API URL
http://localhost/apiapi/public/oauth/access_token?grant_type=client_credentials&client_id=world&client_secret=hello

I already inserted the client_id and client_secret to oauth_clients table in database, but I got this response after submiting
{"message":"Client authentication failed.","status_code":500}

Do you know what is wrong with the configuration? Or any other cause of this issue?

**Comment by yansen-tan** [comment]
I mistakenly use "name" in oauth_clients table for client_id.
Problem solved. Thank you

**Comment by vinkla** [comment]
:+1:
