### ISSUE TITLE
Implementing Password Grant - Invalid Credentials

### ISSUE THREAD

**Issue by sentiasa** [lucadegasperi/oauth2-server-laravel#595]
First, I did everything Credentials_Grant as guided in documentation, seeded oauth_clients table with dummy data and using Postman, I was able to get access token.

Now, I am trying to implement Password_Grant. I did everything docs said. I replaced `grant_type => client_credentials` with `grant_type => password`, created PasswordVerifier.php and OAuthController.php. Also created User table and User Model, and seeded my table with dummy data.

Now when I try to Post using Postman,
`grant_type => password`
`client_id => Test1`
`client_secret => secret`
`username => User1`
`password => secret`, even though they are correct, I am receiving `Invalid Credentials` error with 200 response.

What am I doing wrong? 
Also I have another question. Where do I need to store client_id and client_secret? I migrated ouath_clients table with dummy data, but still couldn't figure out in my head how to call them and compare them before or after validating user inputs.

------------------------------------------------------------------------------------------
- `PasswordVerifier.php`
```
<?php
namespace App\Http\Controllers;

use Illuminate\Support\Facades\Auth;

class PasswordVerifier
{

public function verify($username, $password)
{
    $credentials = [
    'username'    => $username,
    'password' => $password,
    ];

    if (Auth::once($credentials)) {
        return Auth::user()->id;
    }

    return false;
}

}
```

------------------------------------------------------------------------------------------
- `OAuthController.php`
```
<?php

class OAuthController extends Controller
{
    /**
    * The oauth authorizer instance.
    *
    * @var \LucaDegasperi\OAuth2Server\Authorizer
    */
private $auth;

public function __construct(Authorizer $auth)
{
    $this->auth = $auth;
}

    /**
    * Issue a new access token.
    *
    * @return array
    */
public function token()
{
    return new JsonResponse(['data' => $this->auth->issueAccessToken(), 200]);
}

}
```

------------------------------------------------------------------------------------------
- `User Model`
```
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable, CanResetPassword;

    protected $table = 'users';

    protected $fillable = [
        'username',
        'password',
    ];

    protected $hidden = ['password'];

}
```

------------------------------------------------------------------------------------------
- `Route.php`
```
$app->post('/oauth/access_token', function() use ($app) {
   return response()->json($app->make('oauth2-server.authorizer')->issueAccessToken());
});
```

**Comment by sentiasa** [comment]
I found my problem. I should've put `bcrypt('password')` while seeding my db

**Comment by vinkla** [comment]
Glad you solved it.

**Comment by avlima** [comment]
I'm having the same problem, my table users is was fed password using bcrypt and still the error persists. Already checked several times the User and Password I'm trying to authenticate and everything is correct, however the return is still invalid credentials.
