### ISSUE TITLE
Can i authenticate mutable apps from one auth-server

### ISSUE THREAD

**Issue by dongkaipo** [lucadegasperi/oauth2-server-laravel#596]
I have three apps for iPhone, and three api servers for them. Can i use one auth-server to avoid creating three times auth-server for three api servers?

![snip20151113_3](https://cloud.githubusercontent.com/assets/1720338/11143761/a0e9a766-8a32-11e5-9ffa-5e54d90777f2.png)

**Comment by tankerkiller125** [comment]
Definitely possible. Just add a second DB to the laravel config that is specifically used for your oauth/user database. Both apps will then be able too use the same user database and users will be able to use both apps with one username and password.

**Comment by vinkla** [comment]
Thanks for helping out @tankerkiller125!
