### ISSUE TITLE
Is this the right grant type?

### ISSUE THREAD

**Issue by movostudios** [lucadegasperi/oauth2-server-laravel#597]
They, thanks for the awesome package. I've not set up OAuth before, so still getting my head around it.

I'm building a SPA and want a user to enter their username/email and password. Then to authenticate which generates a token to gain access to the API/app.

I've set up a 'Password' grant at the moment. I am getting a token back, however, I am needing to send OAuth:

• client_id
• client_secret
• username
• password

Am I right in thinking that I need to query the the DB prior posting to `/oauth/access_token` to get the `client_id` and `client_secret` based on the username and pw? This sounds wrong to me. I think I have got the wrong end of the stick here. 

Thanks and sorry for the simple support question.

**Comment by mickeyschwab** [comment]
The client credentials are a key piece of OAuth and are unrelated to the user's credentials. A client identifies that the accessor is the given user ON your single page application (as opposed to your iphone app). The advantage of this approach is if you offer an open api and have a client/api go rogue, you can disable the entirety of their tokens without shutting out other clients (so the one nasty phone app can no longer access user data but the rest of your system keeps humming along). It's for that reason that the password flow you're using isn't well suited for web pages as you'll inevitable have to expose the client id/secret to end-users. Alex Bilbie wrote a pretty great article on this last year, and somewhat more importantly, is the maintainer of the underlying OAuth server package from LOEP. I'd recommend if you want to go down this road you follow his advice and proxy all front end requests or look into JWT. Let me know if you have any other questions and I'll do my best to help out.

http://alexbilbie.com/2014/11/oauth-and-javascript/

**Comment by movostudios** [comment]
Mickey... You are a star. That's for the advice. I'll read that article now.

I've looked into JWTs. The reason OAuth seems more appealing is for the scopes and using them more like permissions. Perhaps this is better suited to a different approach.

Thanks again for your help, Mickey.

**Comment by vinkla** [comment]
Thanks for helping out @mickeyschwab!

@movostudios can we consider this issue fixed?

**Comment by movostudios** [comment]
Yeah. More reading for me. Once again, for for th question here.

Cheers

**Comment by vinkla** [comment]
:+1:
