### ISSUE TITLE
Error with client_credentials type

### ISSUE THREAD

**Issue by geshner** [lucadegasperi/oauth2-server-laravel#601]
I setup the client_credentials type and it's generating the access token for me. When I use the "oauth-client" middleware I get this error:

NoActiveAccessTokenException in Authorizer.php line 104:
Tried to access session data without an active access token

but when I use "oauth" middleware it works, how I can fix this?
Also I want to know how I can use the client_scopes, because I created two clients with different scopes but it is ignoring the client scopes.

**Comment by vinkla** [comment]
This is expected behaviour. You have to run both the OAuthMiddleware and OAuthClientOwnerMiddleware if you want to check that the current requests owner is a client.
