### ISSUE TITLE
Multiple grant types

### ISSUE THREAD

**Issue by phelippe** [lucadegasperi/oauth2-server-laravel#603]
Hi, I have a system with 3 types of user, Cliente, Motorista and Admin(soon), so I've implemented 2 custom grant types for the Cliente and Motorista logins. 

```
class ClientePasswordGrant extends PasswordGrant
{
    protected $identifier = 'cliente';
}
```

```
class ClientePasswordVerifier{
    public function verify($username, $password){
        $credentials = [
            'email'    => $username,
            'password' => $password,
        ];
        if (Auth::cliente()->once($credentials)) {
            return Auth::cliente()->get()->id;
        }
        return false;
    }
}
```

routes.php:
```
Route::group(['prefix' => 'api/cliente', 'middleware'=>'oauth.check.cliente', 'as' => 'api.'], function () {
    Route::get('test', function(){
        return Response::json(Authorizer::getResourceOwnerId());
    });
});
```

OAuthCheckCliente.php("part of the class(middleware)"):
```
public function handle($request, Closure $next){
    $id = Authorizer::getResourceOwnerId();
    $cliente = $this->clienteRepository->find($id);
    if(!$cliente){
       abort(403, 'Access forbidden');
    }
    return $next($request);
}
```

With this I could generate the token but a "problem"(I'm not sure if it's a problem) that I found was in the table "oauth_sessions" that save the "owner_type" as 'user'. I searched in the docs and few closed issues as well but I haven't found any docs about this table.

The application will have 3 middlewares to check each type of grant and if its valid, now im getting the following error on the route protected by the OAuthCheckCliente Middleware:
`NoActiveAccessTokenException in Authorizer.php line 104:
Tried to access session data without an active access token"`
this error is specifically at `Authorizer::getResourceOwnerId()`

Well, resuming all I need to have 3 auth types and block dont let each one access others routes, how I do this ?

**Comment by phelippe** [comment]
I've put the test project on git -> https://github.com/phelippe/multitest 

Only run composer install  and migrate with seeds

**Comment by vinkla** [comment]
In order to fetch the resource owner you've to use the middlewares in the correct order. Example:

```php
public function __construct()
{
    $this->middleware(OAuthMiddleware::class);
    $this->middleware(OAuthUserOwnerMiddleware::class);
}
```
