### ISSUE TITLE
Issues with MongoDB?

### ISSUE THREAD

**Issue by lobermann** [lucadegasperi/oauth2-server-laravel#604]
Hi,

seems that there are some issues when using mongodb as database.
After some hours of debugging why I can't get any client to authorize, I found out that in the FluentClient.php `$result = $query->first();` is not returning any result.
So I checked the query above that is called
```
} elseif (!is_null($clientSecret) && is_null($redirectUri)) {
            $query = $this->getConnection()->table('oauth_clients')
                   ->select(
                       'oauth_clients.id as id',
                       'oauth_clients.secret as secret',
                       'oauth_clients.name as name')
                   ->where('oauth_clients.id', $clientId)
                   ->where('oauth_clients.secret', $clientSecret);
```
and yes, it did not return any results.

Created a unit test with following content:
```
$query = DB::table('oauth_clients')
               ->select(
                   'oauth_clients.id as id',
                   'oauth_clients.secret as secret',
                   'oauth_clients.name as name')
               ->where('oauth_clients.id', '1')
               ->where('oauth_clients.secret', '1');

       $result = $query->first();
       var_dump($result);
```

Which return "NULL" on the var_dump ...

When removing the two `where` clauses, I get following result
```
array(1) {
  ["_id"]=>
  object(MongoId)#283 (1) {
    ["$id"]=>
    string(24) "564d04dc1706a3d9028b4576"
  }
}
```
Where the first thing I see is that all the fields are missing ...
When querying `$query = DB::table('oauth_clients')->select();` following is returned:
```
array(4) {
  ["_id"]=>
  object(MongoId)#283 (1) {
    ["$id"]=>
    string(24) "564d04dc1706a3d9028b4576"
  }
  ["id"]=>
  string(1) "1"
  ["secret"]=>
  string(1) "1"
  ["name"]=>
  string(1) "1"
}
```

I am not sure what the expected result is, but it seems not to match with what is returned by the query. Will set up a mysql server tomorrow evening for testing with mysql, but moving to mysql is not something I am looking forward to. Any ideas on what is causing this?

EDIT:
Did another quick test with following modification of the query:
```
$query = DB::table('oauth_clients')->select(
                   'id',
                   'secret',
                   'name')
               ->where('id', '1')
               ->where('secret', '1');
```
Which actually did return the correct result:
```
array(4) {
  ["_id"]=>
  object(MongoId)#282 (1) {
    ["$id"]=>
    string(24) "564d04dc1706a3d9028b4576"
  }
  ["id"]=>
  string(1) "1"
  ["secret"]=>
  string(1) "1"
  ["name"]=>
  string(1) "1"
}
```

EDIT2:
Modifed FluentClient.php with the above and also the hydrateEntity function to use indexes and now it works:
`{"access_token":"uLumtz68Ek5Jxl2PvPvaE7qIwW13AnmMIGKajCSC","token_type":"Bearer","expires_in":3600}`

How can those queries be modifed to support both types of databases? I am willing to help implementing the changes for mongodb,

**Comment by pengkong** [comment]
@lobermann here's a working implementation which you can use

https://github.com/lucadegasperi/oauth2-server-laravel/pull/616

**Comment by lobermann** [comment]
@pengkong Very nice! I also started rewriting it, removing the joins. Going to give that a try, thanks!

**Comment by vinkla** [comment]
We aren't currently supporting MongoDB but you can check out #616 by @pengkong.
