### ISSUE TITLE
Needs documentation Update

### ISSUE THREAD

**Issue by json2x** [lucadegasperi/oauth2-server-laravel#607]
This has been a very good package, but certainly needs an update on its documentation.  That package has more a lot to offer, but can not be fully utilize. I appreciate though basic wiki of the package

**Comment by vinkla** [comment]
If you have any updates you want to add then you can add them to this issue and then we will add it to the docs. Thanks.

**Comment by vinkla** [comment]
The docs are now open sources and we appreciate any help we can get!
