### ISSUE TITLE
How to store authorized clients?

### ISSUE THREAD

**Issue by jbrooksuk** [lucadegasperi/oauth2-server-laravel#610]
> **Preface:** I'm building a very simple tool for internal use only which acts like Gravatar for employees (with more information). Each subsequent app that we build internally will have a "Login with X" button  connecting with oAuth. I've already created the Socialite provider for the oAuth server.

I'm using the `authorization_code` grant which is working well. When the user clicks the "Login with X" button that we get redirected to the oAuth confirmation page (like https://github.com/lucadegasperi/oauth2-server-laravel/wiki/Implementing-an-Authorization-Server-with-the-Auth-Code-Grant), it works neatly.

The issue is that when the session expires and the user is shown the "Login with X" button again, rather than redirecting straight back to the callback, the user is asked to confirm access again. I'm not sure what I've missed?

**Comment by lucadegasperi** [comment]
The part where the user is automatically redirected back to the client is up to you to implement. What you would need to do is to check whether a past or expired session is already in the DB and therefore automatically redirect back (skipping the part where the user is asked for confirmation again).

**Comment by jbrooksuk** [comment]
Thanks @lucadegasperi I figured that'd be it. What exactly would I be linking? Existing sessions, then checking timestamps etc?

**Comment by lucadegasperi** [comment]
Check for an existing session (doesn't matter if it is expired or not) associated to the user and the client and check whether it has the same scopes (if you do use scopes) and if so redirect straight back to the client.

**Comment by jbrooksuk** [comment]
If I implement this in a middleware, would you be willing to merge it?

**Comment by jbrooksuk** [comment]
@lucadegasperi hey buddy, I've started writing an implementation of this but annoyingly new sessions are still being created. This is the middleware I've started writing. I've setup models for each `oauth_*` table and created relations between them (mostly), they should make enough sense that you can work out what is what.

```php
if ($user = $this->auth->user()) {
    if ($session = $user->session) {
        if ($accessToken = $session->accessToken) {
            $endpoint = $session->client_redirect_uri; // Redirect back to where the user went to?
            $code = $session->auth_code;

            $params = $this->authorizer->getAuthCodeRequestParams();
            $params['user_id'] = $this->auth->user()->id;

            $redirectUri = $this->authorizer->issueAuthCode('user', $params['user_id'], $params);

            return Redirect::to($redirectUri);
        }
    }
}
```

**Comment by jbrooksuk** [comment]
Looking at the code, I guess this is happening because of the call to `issueAuthCode`. How else can I generate the redirect URI without creating a new code/session?

**Comment by jbrooksuk** [comment]
Ping @lucadegasperi I've not had much luck with this, is there any advice that you could give?

**Comment by lucadegasperi** [comment]
Don't worry about generating a new session or a new auth code, that's the expected behavior and it's more secure than reissuing the same code. It might be a bit more effort to manage on the client side but from the user perspective nothing changes.

**Comment by jbrooksuk** [comment]
Surely the token shouldn't be changing for each login? The issue I have is that the user gets shown the authorize routes every time they login.

**Comment by lucadegasperi** [comment]
the token should change for each login, what you should do is check whether the user has a past session with the same scopes as the current one and if so instantaneously redirect back to the client app with a new auth code which then will be exchanged for a new access token in the background.

**Comment by jbrooksuk** [comment]
Ok, but this is my current `ContinueOAuthSession` middleware, which isn't working... It's not able to complete the flow.

```
if ($user = $this->auth->user()) {
    if ($session = $user->session) {
        dd($session->accessToken);
        if ($accessToken = $session->accessToken) {
            $endpoint = $session->client_redirect_uri; // Redirect back to where the user went to?
            $code = $session->auth_code;

            $params = $this->authorizer->getAuthCodeRequestParams();
            $params['user_id'] = $this->auth->user()->id;

            dd($this->authorizer->completeFlow());
            $redirectUri = $this->authorizer->issueAuthCode('user', $params['user_id'], $params);

            return Redirect::to($redirectUri);
        }
    }
}
```

**Comment by Utwo** [comment]
I use this in oauth_authorize_show_form() method to check if user already approved that client.

```
$check_session = OauthSession::where('client_id', $formParams['client_id'])
            ->where('owner_id', auth()->user()->id)
            ->with(['OauthScope' => function ($query) use ($formParams) {
                return $query->whereIn('oauth_scopes.id', explode(',', $formParams['scope']));
            }])->get();

        $max = 0;
        foreach ($check_session as $check) {
            if ($check->OauthScope->count() > $max) {
                $max = $check->OauthScope->count();
            }
        }
        if ($max >= count($formParams['scopes'])) {
            return redirect(Authorizer::issueAuthCode('user', auth()->user()->id, $authParams));
        }
```

**Comment by jbrooksuk** [comment]
Have you thought about implementing that as a middleware @Utwo? That'd be super useful for me.

**Comment by jbrooksuk** [comment]
Also, are you able to share your model relations?

**Comment by Utwo** [comment]
There is no need for a middleware for this because you will use this pice of code only once when you want to show approve/deny form.

Here are my models:
[models.zip](https://github.com/lucadegasperi/oauth2-server-laravel/files/170427/models.zip)

**Comment by Utwo** [comment]
Here is full method when GET /oauth/authorize
```

public function oauth_authorize_show_form()
    {
        $authParams = Authorizer::getAuthCodeRequestParams();

        $formParams = array_except($authParams, 'client');

        $formParams['client_id'] = $authParams['client']->getId();

        $formParams['scope'] = implode(config('oauth2.scope_delimiter'), array_map(function ($scope) {
            return $scope->getId();
        }, $authParams['scopes']));

        $check_session = OauthSession::where('client_id', $formParams['client_id'])
            ->where('owner_id', auth()->user()->id)
            ->with(['OauthScope' => function ($query) use ($formParams) {
                return $query->whereIn('oauth_scopes.id', explode(',', $formParams['scope']));
            }])->get();

        $max = 0;
        foreach ($check_session as $check) {
            if ($check->OauthScope->count() > $max) {
                $max = $check->OauthScope->count();
            }
        }
        if ($max >= count($formParams['scopes'])) {
            return redirect(Authorizer::issueAuthCode('user', auth()->user()->id, $authParams));
        }
        return view('oauth.authorization-form', ['params' => $formParams, 'client' => $authParams['client']]);
    }
```

**Comment by jbrooksuk** [comment]
I must have something configured incorrectly here because my `oauth_session_scopes` table is always empty...

**Comment by vinkla** [comment]
@jbrooksuk did you ever manage to solve this?

**Comment by jbrooksuk** [comment]
Unfortunately not, our users would have to always authorise (so the application was never deployed as it's internal).

**Comment by vinkla** [comment]
Okay, I see. Sorry we can't help you more. We are working on the next release including the new `league/oauth2` 5.0 version. Maybe you could wait until it is finished?

**Comment by jbrooksuk** [comment]
That's fine by me. The project was never finished, so we can wait.

**Comment by vinkla** [comment]
Okay, great 👍

**Comment by jbrooksuk** [comment]
I think I've figured it out... I wasn't storing the `scopes` in a hidden field on the authorization form.

**Comment by vinkla** [comment]
👍
