### ISSUE TITLE
Client credentials with user id

### ISSUE THREAD

**Issue by OscarRPR** [lucadegasperi/oauth2-server-laravel#611]
Currently, I'm using the client_credentials grant to give access to specific clients but I need to way to associate the client id and client secret to an user of my application (REST API)

I looked for the owner_id on the oauth_sessions which can be get with Authorizer::getResourceOwnerId() but for this grant it's set up to the same client id. I looked for other options to set this up and I have two ideas but I'm not sure if there is a better way to handle this with the package.

1. Create a table oauth_app_client where I store the relation between the user id and the client id, and everytime I try to get the user id, I'll need to call getResourceOwnerId and then look in the table for this id but I don't think it's a good choice because I'll have to do a lot of calls everytime.

2. Generate a client id with my user id but hashed which it's insecure because it will be easy to decode

3. When the user request the access token, add the relation of client and user_id then I'll retrieve the id and get the information, but I think it's not the best way to handle this in another storage.

What it's the best way to do it with the package?

Thanks

**Comment by vinkla** [comment]
This already works out of the box, try setting up the `password` grant. This grant will work for users.

**Comment by OscarRPR** [comment]
@vinkla Yes, I know, but for this case, I don't want them to use their username and password to get an access token, I just want them to use their client credentials and with this they will only have access to their account just like PayPal or Twilio does with their APIs, where Ibonly need to add the client id and secret on the request and they already know which user is trying to authenticate.

**Comment by vinkla** [comment]
The client credentials isn't connected to every specific user. The client id and secret is specific for your application. In order to login users you've to use something to check if they are valid users or not.

**Comment by OscarRPR** [comment]
Yes, I think that's the issue because I don't want them to give me their username and password to authenticate. 

But, if I create some sort of association between the client and a user as I mentioned in my first idea, it would be a bad idea? Or if I want to achieve the kind of authentication, what do you recommend to do using this package?

**Comment by vinkla** [comment]
Yes, it would be a bad idea to not follow the spec. You've to authenticate the user somehow. What kind of information do you get from your users?

**Comment by OscarRPR** [comment]
Just to give you some context, I want to create an API using this grant which can be used inside my clients platform without worrying for username and password, their developers will only have to put the client id and client secret and they would be able to make requests. 

Currently, I'm only receiving the client id and secret but I can get the username and password, but again, I don't think it's a good idea because they will have to store somewhere their credentials to send on the request for the access token.

**Comment by vinkla** [comment]
So you will give out client credentials to third-party apps?

**Comment by OscarRPR** [comment]
Yes, the idea it's have a section in my Web application for authenticated users to create an "app"  which will generate the client id and secret,  that app will have an association with the authenticated user that create that app and every request using those credentials will be limited to that user only, in this way, it's easier for them to integrate the API, besides that, they will be in charge of securing their credentials.

**Comment by vinkla** [comment]
Yeah, then I would suggest adding a `user_id` to the clients table.

**Comment by OscarRPR** [comment]
Ok, the last part of the question (I hope I'm not getting out of context), which one would be a better idea? 

1. Add the user id column and for each call of the Authorizer to getResourceOwnerId, create another call to the database to get the user id? Maybe extending the Authorizer to modify that method to get the user id on that call? 

2. Create a custom grant which will put the user id as owner id on the oauth_sessions table? 

Thanks

**Comment by vinkla** [comment]
No, the API should work with the grants just as it does otherwise you don't follow the spec.

**Comment by DanielOlarte** [comment]
Ok, that sounds good, then I'll add the user_id in the oauth_clients table, and I'll extend the Authorizer to get the user_id when I call Authorizer::getResourceOwnerId, thanks a lot for your help.

**Comment by OscarRPR** [comment]
Ok, sounds good, then I'll add the user_id column on the oauth_clients table, and I'll extend the Authorizer to get the user_id when I call Authorizer::getResourceOwnerId, thanks a lot for your help

**Comment by vinkla** [comment]
`Authorizer::getResourceOwnerId()` method shouldn't fetch the `user_id` from the `oauth_clients` table. It should only fetch the owner ID if you use the correct access token. Modifying this is at your own risk. This won't be secure if you can fetch data with the client credentials.

**Comment by DanielOlarte** [comment]
Mmm ok, then it would be better to implement something else to retrieve the `user_id` from the table after I retrieve the `owner_id` with the `Authorizer::getResourceOwnerId()`?

**Comment by OscarRPR** [comment]
Mmm ok, then it would be better to implement something else to retrieve the user_id from the table after I retrieve the owner_id with the Authorizer::getResourceOwnerId()?

**Comment by vinkla** [comment]
Yes.

**Comment by OscarRPR** [comment]
Thanks a lot @vinkla for the help, I'll do it.

**Comment by vinkla** [comment]
Anytime!

**Comment by hakobfromlightin** [comment]
I had the same problem and didn't manage to find something. Thank you very much @OscarRPR and @vinkla !!
