### ISSUE TITLE
JWT structure and question regarding payload

### ISSUE THREAD

**Issue by jonathanlundstrom** [lucadegasperi/oauth2-server-laravel#613]
Hello,

I recently finished most of the work on our API, and I am now implementing the API and Client communication using Angular for our front-end and the Satellizer library.

What I quickly realized was that there is no way for me to send a payload back to the client, and it seems to me that the JWT is malformed compared to the specification which details the three parts of a JSON web token.

For instance, look at this:
https://scotch.io/tutorials/the-anatomy-of-a-json-web-token

This clearly describes the three parts: header, payload and signature.
I would like to pass some information in the payload, which is why I'm asking.

Why is this not the case with this library, or does it work like this?

As far as I can see, the current tokens are just one part, containing no payload, such as this example token I just generated: `rAsIfRJFUhvRfmuYQJfAhVFHTsydMaPT0s0ikYxs`.

Regards,
Jonathan

**Comment by vinkla** [comment]
Please open this in a JWT package instead.

**Comment by jonathanlundstrom** [comment]
@vinkla What do you mean?

**Comment by vinkla** [comment]
We don't provide JWT.

**Comment by jonathanlundstrom** [comment]
@vinkla Alright. Thank you.

**Comment by vinkla** [comment]
No worries, try the package I referenced above.
