### ISSUE TITLE
Oauth server issue with token authentication

### ISSUE THREAD

**Issue by jonathanlundstrom** [lucadegasperi/oauth2-server-laravel#614]
Hello!

I have a route which I am requesting to fetch some information that should only be allowed when the user is authenticated and the access_token is provided. To do so, I use the provided middleware as such:

```php
    // Code in bootstrap.php
    $app->routeMiddleware([
        'oauth' => LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware::class
    ]);
    
    // Code in routes.php
    $app->get('{id:[0-9]+}/action/follow', [
        'as' => 'user.action.follow',
        'uses' => 'Users\UserController@getFollowUser',
        'middleware' => 'oauth|validate:users'
    ]);
```

When I use a REST client such as Rested or Paw, any requests to this URL containing the Authorization header yields the following response, which is correct and perfect:

    HTTP/1.1 401 Unauthorized
    Connection: keep-alive
    Content-Type: application/json
    Server: nginx/1.8.0
    0: HTTP/1.1 401 Unauthorized
    Date: Wed, 02 Dec 2015 08:30:04 GMT
    Cache-Control: no-cache
    Transfer-Encoding: Identity
    
    {
        "error": "access_denied",
        "error_description": "The resource owner or authorization server denied the request."
    }

But when the same request is performed through the web browser (Angular $http) I get the same response, but a different status code (500) and the response as HTML, which is not preferable at all: 

<img width="988" alt="skarmklipp 2015-12-02 09 57 14" src="https://cloud.githubusercontent.com/assets/4216027/11526667/4bd5b3f6-98dc-11e5-9ff1-1b5480292255.png">

If you can't see the image, visit this page: https://www.dropbox.com/s/4nsi6h4swbmn5jc/Sk%C3%A4rmklipp%202015-12-02%2009.57.14.png?dl=0

Could anyone explain why it suddenly generates an internal server error, and why it doesn't return it's response with the proper status code and payload as it does from any REST client? As far as I'm aware, this is something that started happening in the most recent update of this library, because I had not seen it occurring before.

These are the request headers sent by my REST client:

    Accept: application/json
    Accept-Encoding: gzip, deflate
    Authorization: Bearer BaUbu9Nj2quK3VR4fizcscxA31Q1mE79iqxV2uc9
    Accept-Language: sv-se

And these are the ones sent by my web browser (Google chrome, but same problem in Firefox)

    Accept:application/json, text/plain, */*
    Accept-Encoding:gzip, deflate, sdch
    Accept-Language:sv-SE,sv;q=0.8,en-US;q=0.6,en;q=0.4
    Cache-Control:no-cache
    Connection:keep-alive
    Host:*REMOVED*
    Origin:*REMOVED*
    Pragma:no-cache
    Referer:*REMOVED*
    User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

Even when I explicitly set `Accept: application/json` in the web browser, I still get the same results, and funny enough, omitting the same request header in the rest client yields the same results.

How can this be?

Thanks in advance,
Jonathan

**Comment by vinkla** [comment]
Is this the same as in #602 ?

**Comment by jonathanlundstrom** [comment]
@vinkla Nope, this is not the same error. The authorization is functioning as expected, but my issue is that when I do not provide a token, or the token is invalid, a Internal Server Error (500) is returned in the browser, but 401 (Not authorized) when I use a REST Client.

There has to be some bug in the code, as it should always use 401, and not 500. Since we are building a REST API we only handle JSON, not HTML responses.

**Comment by guilhermesoratto** [comment]
I have same error.

**Comment by vinkla** [comment]
@jonathanlundstrom just to cover some basic questions; have you registered the OAuth exception handler middleware? https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/docs/getting-started/lumen.md#register-package

**Comment by jonathanlundstrom** [comment]
@vinkla Yes, I have done so, and as I mentioned it works as expected from REST clients such as "Rested" and similar, but not in the actual web browser. My colleague is also experiencing this issue, and it started after the latest update.

I first noticed it on his computer after a fresh composer install with the latest version of this package. He started receiving 500 instead of 401. Having an older version, I didn't have these issues, but as soon as I ran ´composer update´and received a later version, this started happening to me too.

Could it have something do with this bug?
https://github.com/lucadegasperi/oauth2-server-laravel/issues/536

This is my middleware binding:

    $app->middleware([
        Illuminate\Cookie\Middleware\EncryptCookies::class,
        Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        LucaDegasperi\OAuth2Server\Middleware\OAuthExceptionHandlerMiddleware::class,
    ]);

Thanks again, I really hope we can get this bug sorted, seeing as we've integrated this package fully, and it works great other than this.

Regards,
Jonathan

**Comment by vinkla** [comment]
Maybe it is related to #536 but then it shouldn't work in later versions either. I think this has to with something in the latest version of the `league/oauth2-server` package. Does it work if you specify version `4.1.3` for the `league/oauth2-server` package?

**Comment by talevskiigor** [comment]
I just have same problem and tested all combination but the problem is in `league/oauth2-server` and not in `lucadegasperi/oauth2-server-laravel (5.1.0)`.

it work if version is fixed: `league/oauth2-server (4.1.3)`

**Comment by vinkla** [comment]
@talevskiigor do you get the same error as in #602?

**Comment by talevskiigor** [comment]
yep

**Comment by jonathanlundstrom** [comment]
@vinkla How do I fix version? If I go inside `oauth2-server-laravel` and change the version to `"league/oauth2-server": "4.1.3"` nothing happens when I run `composer update`.

**Comment by vinkla** [comment]
@jonathanlundstrom since we specify `"league/oauth2-server": "4.1.*"` you can just add `"league/oauth2-server": "4.1.3"` in your projects root `composer.json` file.

**Comment by jonathanlundstrom** [comment]
@vinkla Thank you.

I've updated my composer and installed version 4.1.3 instead of 4.1.4. Unfortunately, this doesn't make any difference at all. I still get a 500 server error as my first post states, rather than a 401 (Expired token) or 400 (No token), which I get if I use a restful client.

The request headers are set to only accept `Application/json` which is the same as any client. As I stated, this error started with the last update to this package and its dependencies.

How can this be?

**Comment by vinkla** [comment]
Yeah, that is strange. What if specify the working version of this package?

**Comment by jonathanlundstrom** [comment]
Which was the last version before the current one, that terminal is long gone :/

**Comment by vinkla** [comment]
Look at the releases page or on the packagist listing.

**Comment by jonathanlundstrom** [comment]
@vinkla Hmm, this is getting stranger. I tried with even older versions, and I still get the same issue. I'm assuming that you know what I mean. This is the setup I'm using now, so it might not be a version issue after all.

    "lucadegasperi/oauth2-server-laravel": "5.0.0",
    "league/oauth2-server": "4.1.0"

I just don't understand why this happens, and it's very frustrating. If we're not able to access the correct status codes, then we can't create a proper error handling. We can't just magically assume that an error 500 means that they're not/no longer authenticated. This should only be used in instances where the server has encountered an error.

How can `InvalidRequestException` be caught when I request the same URL through Rested or a similar application, but not when I call the same URL using Angular´s $http library, with the same headers?

Could it be that is an XHR issue? Because if I navigate to the requested URL with the browser, I get the correct response, but when the same URL is requested from the web client using XHR (cross-origin) I get the response as HTML and the `500 - Server Error` code instead of 400 or 401, as it should be. Seems like there is an actual code fault.

If we can discuss in private, I can give you access to URL:s where you can see this issue in action.

For us, this really seems like a bug, and a critical one as well, might I add.

Thanks for helping me debug this!

**Comment by vinkla** [comment]
500 will be thrown when something in your setup isn't called or executed as it should. Could you paste the controller which deals with the endpoint?

**Comment by jonathanlundstrom** [comment]
@vinkla All the endpoints have the same issue, and they're based in at least 8 or 10 different controllers. This error resides in the `ResourceServer` class (not your code), but the `OAuthMiddleware` does not seem to be working as expected under CORS. If it was, it would not let the request continue as it's either missing the access_token or the token is invalid. Hence the correct status code should be returned.

As the middleware lets the request continue, the `ResourceServer` fails to find the access_token and throws an exception, which should have been handled already in the Middleware.

**Comment by vinkla** [comment]
@jonathanlundstrom do you use slack? If so, I can invite you to a Swedish channel for front-end devs.

**Comment by jonathanlundstrom** [comment]
@vinkla Here's one of the endpoints for the API Server:

    $app->group([ 'prefix' => 'feeds', 'namespace' => 'Hubbit\Http\Controllers' ], function ($app) {
        $app->get('/posts/ids', [
            'as' => 'feeds.post.general.ids',
            'uses' => 'Feeds\FeedController@postGetGeneralIDs',
            'middleware' => 'cors|oauth'
        ]);
    });

And this is the controller code used to handle the request:

    public function postGetGeneralIDs(Request $request){

		// Set response:
		$responseCode = 200;
		$responseContainer = [ ];

		$displayedIDs = $request->has('ids') ? $request->get('ids') : [];
		$responseContainer['post_ids'] = DB::table('posts')
			->whereNotIn('id', $displayedIDs)
			->where('status', '=', 'published')
			->orderBy('created_at', 'DESC')
			->take(10)
			->lists('id');

		return $this->buildResponse($responseCode, $responseContainer);
	}

Similar code is used for the other routes.

**Comment by jonathanlundstrom** [comment]
@vinkla Yes, you can invite me at this email: `contact@jonathanlundstrom.me`. Thanks!

**Comment by vinkla** [comment]
@jonathanlundstrom Okay, you've been invited.

**Comment by jonathanlundstrom** [comment]
Great, I've joined and I'm online 😊

On Thursday, December 10, 2015, Vincent Klaiber <notifications@github.com>
wrote:

> @jonathanlundstrom <https://github.com/jonathanlundstrom> Okay, you've
> been invited.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucadegasperi/oauth2-server-laravel/issues/614#issuecomment-163595105>
> .
>


-- 

Hälsningar,

Jonathan Lundström
Telefon: 0768-95 25 25

**Comment by jonathanlundstrom** [comment]
**Problem solved! Sort of...**

It turns out that there is some kind of conflict between [laravel-cors](https://github.com/barryvdh/laravel-cors) and this package.

In order to get the proper responses, you have to modify the default Lumen Exception Handler found in `app/Exceptions/Handler.php`. You must then update the render method to look something like the code below. The *"solution"* was found in these issues: https://github.com/barryvdh/laravel-cors/issues/70 and https://github.com/lucadegasperi/oauth2-server-laravel/issues/569.

    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $e
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $e)
    {
        if ($e instanceof OAuthException){
            return response()->json([
                'error' => $e->errorType,
                'error_description' => $e->getMessage()
            ], $e->httpStatusCode, $e->getHttpHeaders());
        } else {
            return parent::render($request, $e);
        }
    }

Thanks @vinkla for the support, both here and at Slack. Hopefully a member of some of the teams will figure out what causes this, and renders the `OAuthExceptionHandlerMiddleware` useless.

// Jonathan

**Comment by ArtemFitiskin** [comment]
@jonathanlundstrom Good job, thanks!

Solved with (Laravel 5.1): 

```php
$e instanceof \League\OAuth2\Server\Exception\OAuthException
```

**Comment by jonathanlundstrom** [comment]
@ArtemFitiskin Thank you! Did you use the solution mentioned above, or something else? I'm guessing your code was just to reference the full namespace, right? :smile:

**Comment by johninvictus** [comment]
@jonathanlundstrom and @ArtemFitiskin  thanks your discussion has saved me

**Comment by enbaby** [comment]
@jonathanlundstrom 
Hello,I'm try to use your method to solve the problem,but I can't solve it.Can you help me to solve it.

https://github.com/lucadegasperi/oauth2-server-laravel/issues/641#issuecomment-224476755
thanks!
