### ISSUE TITLE
Why password grant needs client_id and client_secret?

### ISSUE THREAD

**Issue by aslikeyou** [lucadegasperi/oauth2-server-laravel#615]
Using password grant I receive following message: "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"client_id\" parameter.". I opened PasswordGrant and find out the next: 
```
// Get the required params
        $clientId = $this->server->getRequest()->request->get('client_id', $this->server->getRequest()->getUser());
        if (is_null($clientId)) {
            throw new Exception\InvalidRequestException('client_id');
        }
$clientSecret = $this->server->getRequest()->request->get('client_secret',
            $this->server->getRequest()->getPassword());
        if (is_null($clientSecret)) {
            throw new Exception\InvalidRequestException('client_secret');
        }

        // Validate client ID and client secret
        $client = $this->server->getClientStorage()->get(
            $clientId,
            $clientSecret,
            null,
            $this->getIdentifier()
        );
```
Can someone explain me?

**Comment by vinkla** [comment]
All grants need both the ID and secret.

**Comment by aslikeyou** [comment]
Following specification http://tools.ietf.org/html/rfc6749#section-4.3.1 I only need  grant_type, username, password, scope. Is it correct?

**Comment by vinkla** [comment]
>   If the client type is confidential or the client was issued client
   credentials (or assigned other authentication requirements), the
   client MUST authenticate with the authorization server as described
   in Section 3.2.1.

**Comment by aslikeyou** [comment]
So it means that I should send grant_type, username, password and also client_id and secret? What's the difference between client_credentials?

**Comment by vinkla** [comment]
Yes that is correct.

**Comment by aslikeyou** [comment]
It means that using Password is redundant as we use client_id and client_secret and can process request as client_credentials grant. It also means that we can't auth user without generating client_id and client_secret earlier what is redundant also.

**Comment by vinkla** [comment]
If you want to authenticate the user you have to use the `password` grant.

**Comment by aslikeyou** [comment]
It is what I am talking about. ```password``` grant requires client_id and client_secret fields.

**Comment by vinkla** [comment]
Yes. It isn't redundant if you want to authenticate users. Client and users are two separate things.

**Comment by aslikeyou** [comment]
I mean that it should look something like this: https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/GrantType/UserCredentials.php

**Comment by vinkla** [comment]
Then I suggest you could open an issue or better yet create a pull request at [thephpleague/oauth2-server](https://github.com/thephpleague/oauth2-server) package were the password grant exists.

**Comment by aslikeyou** [comment]
I see. Thanks for your support.

**Comment by vinkla** [comment]
No worries, let me know how it goes. You can refer to this issue.
