### ISSUE TITLE
Amother Class 'LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider' not found

### ISSUE THREAD

**Issue by pituseligmann** [lucadegasperi/oauth2-server-laravel#617]
Hello, and sorry if this is a duplicate of a duplicate. I've seen different posts of this error on Laravel, both 4.2 and 5. I myself, am running Lumen at the moment and trying to implement this package but I'm having a hard time.

I'm requiring the following version on my composer.json
```
"lucadegasperi/oauth2-server-laravel": "^5.0"
```

And I registered the package and copied the config as per the wiki suggests for Lumen.
Thank you in advance.

**Comment by vinkla** [comment]
Could you show me how you've registered it?

**Comment by pituseligmann** [comment]
I was using a different lumen version than the one supported. Everything working now.
