### ISSUE TITLE
Issue with NoActiveAccessTokenException 

### ISSUE THREAD

**Issue by lobermann** [lucadegasperi/oauth2-server-laravel#619]
Trying to solve this for 2 weeks now but can not get it to work. I am able to get an Access Token with client credetntials grant, no issues there.

```
{
  "access_token": "gUjdu9idSHkE973oxBoknPPUqwZ8IifL25TmtfIW",
  "token_type": "Bearer",
  "expires_in": 36000
}
```

But now when trying to access following route:
```
Route::group(['prefix' => 'v1', 'before' => 'oauth'], function()
{
    Route::resource('users', "UsersController");
});
```
and access following function:
```
    public function index(Authorizer $authorizer)
    {
        $user_id = $authorizer->getResourceOwnerId(); // the token user_id
        $user = \App\User::find($user_id);// get the user data from database
        return User::all()->toArray();
    }
```
I always get back a 
```
NoActiveAccessTokenException in Authorizer.php line 104:
Tried to access session data without an active access token

in Authorizer.php line 104
at Authorizer->getAccessToken() in Authorizer.php line 265
at Authorizer->getResourceOwnerId() in UsersController.php line 22
at UsersController->index(object(Authorizer))
...
```

I tried supplying it via the URL:
```
http://192.168.99.100:8004/v1/users?access_token=gUjdu9idSHkE973oxBoknPPUqwZ8IifL25TmtfIW
```
and via the header
```
GET /v1/users HTTP/1.1
Host: 192.168.99.100:8004
Authorization: Bearer gUjdu9idSHkE973oxBoknPPUqwZ8IifL25TmtfIW
Cache-Control: no-cache
Postman-Token: a9aa9439-752b-4341-cc2a-488cac53d19f
```
But I always get the exception back. 

Already tried debugging into it but I am not able to locate where the token is get from the resource server. 

Any help on this is highyl appreciated. Thanks ....

**Comment by vinkla** [comment]
This is expected behaviour. You have to run both the `OAuthMiddleware` and `OAuthClientOwnerMiddleware` if you want to check the current requests owner id.

**Comment by lobermann** [comment]
Thanks. Can you at least also point me to where I can find some documentation on this?

**Comment by vinkla** [comment]
Done https://github.com/lucadegasperi/oauth2-server-laravel/commit/df2247df4524415ebcf730caac22b050b185c7a0

**Comment by lobermann** [comment]
Thanks!
