### ISSUE TITLE
MiddleWare listing is wrong in lumen configuration documentation

### ISSUE THREAD

**Issue by Zkynet** [lucadegasperi/oauth2-server-laravel#622]
### 'oauth-owner' => \LucaDegasperi\OAuth2Server\Middleware\OAuthOwnerMiddleware::class

This middleware does not seem to exist inside the OAuth2Server\Middleware namespace.

### 'oauth-owner' => \LucaDegasperi\OAuth2Server\Middleware\OAuthUserOwnerMiddleware::class

Did you prehapse mean this ?

**Comment by vinkla** [comment]
Yes, that is correct. Could you create a PR for this?

**Comment by Zkynet** [comment]
sorry for the late reply .. I went home for the holidays and didn't look at git until now.?

Did you get it fixed or do you still want the request <3 ?

**Comment by vinkla** [comment]
Fixed.

**Comment by Zkynet** [comment]
great to hear !
