### ISSUE TITLE
Laravel 5.2 update

### ISSUE THREAD

**Issue by phelippe** [lucadegasperi/oauth2-server-laravel#629]
Do you intend to release an update to 5.2?

I tried to install on 5.2 version but I received the following error

```Call to undefined method Illuminate\Foundation\Application::bindShared()```

I think it's due to this: https://github.com/laravel/framework/pull/9037/files

Thanks

**Comment by mlanser** [comment]
I'm fairly certain "bindShared()" is now called "singleton()"

**Comment by vinkla** [comment]
Sorry about that, should be fixed in https://github.com/lucadegasperi/oauth2-server-laravel/releases/tag/5.1.1
