### ISSUE TITLE
Erro in artisan migrate:refresh command

### ISSUE THREAD

**Issue by miguelsmuller** [lucadegasperi/oauth2-server-laravel#632]
When I run the command `php artisan migrate:refresh` in my project I get the following error.

![captura de tela 35](https://cloud.githubusercontent.com/assets/4589909/12066412/ce542b88-afce-11e5-8a03-e5da16bbfd0f.png)

What can it be?

**Comment by JoeDawson** [comment]
Does a `composer dump-autoload` solve this?

**Comment by miguelsmuller** [comment]
Yes. He solved the problem here.
Thank you for your help.
