### ISSUE TITLE
Checking access token

### ISSUE THREAD

**Issue by pavankataria** [lucadegasperi/oauth2-server-laravel#633]
I'm using the password grant, and successfully able to retrieve the access token. I then pass this in as a header after having ancapsulated my route into the `oauth` middleware. 
The get request works perfectly without the oauth middleware until I wrap it around with it.

I get this:

![screen shot 2016-01-01 at 03 24 04](https://cloud.githubusercontent.com/assets/1791244/12069657/55d66022-b037-11e5-9bbe-10919113c015.png)

no matter how I set the header, I keep getting this page. I have no other active middleware. What's happening?

**Comment by pavankataria** [comment]
I've done some more digging around and found out where the problem is occuring.

<img width="947" alt="screen shot 2016-01-01 at 18 21 28" src="https://cloud.githubusercontent.com/assets/1791244/12073589/a8bf6e64-b11d-11e5-84f0-1403e6524f01.png">

When I remove that method and set the accessToken like so: 
`$accessToken = $this->getRequest()->headers->get('Authorization');`
Then the request is processed perfectly fine. So, this of course means there's a problem with the determineAccessTokenInHeader method, however I'm sure my solution, while it works, is not the long term solution. 
Could one of you guys check into this matter now that I've pin pointed the location?

**Comment by vinkla** [comment]
It looks like an issue with the oauth2-server package and not this wrapper.

**Comment by Synapse791** [comment]
@pavankataria Have you tried prefixing the token with Bearer?

The OAuth2 Header in other systems I've used should look something like this:

    Authorization: Bearer TOKEN_HERE

**Comment by Synapse791** [comment]
@pavankataria Sorry, Just noticed this was a GET request! Ignore me

**Comment by Synapse791** [comment]
@vinkla @pavankataria 
I think the format `access_token` is used when the token is appended to the query string. If you're using the headers, I'm pretty sure it needs to be in the format I mentioned above

**Comment by vinkla** [comment]
@Synapse791 yes, you are correct. The access token header must be prefixed with the `Bearar` string.

**Comment by vinkla** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
