### ISSUE TITLE
Client Authentication Failed, but the credentials are stored in the database

### ISSUE THREAD

**Issue by bfmbrandonjames** [lucadegasperi/oauth2-server-laravel#638]
I’m using this library to help streamline development of a RESTful API I’m creating.  I’ve migrated and seeded my database, which is MongoDB and done all the necessary pre-cursors to setting up my application.  I’m certain it’s installed correctly.  I got referenced to use your library from Dingo’s documentation.

About my particular configuration:

Ubuntu Server 14.04
Apache 2.4.7
MongoDB

Oauth client entry: 

    db.oauth_clients.find().pretty();
    {
           "_id" : ObjectId("568ad3f6dfdb8fcb648b4567"),
           "client_id" : "TAP01",
           "client_secret" : "aGeeRv46QSsGsWCG25w8",
           "redirect_uri" : "https://api.tapecm.com/"
    }

Laravel 5.1
Third party libraries:
dingo api
jenssegers mongodb
cellcote proxify

I get this error when I provide client credentials in the post request I put into the Routes file.  I’ve enabled the grant type in the config/oauth2.php file. I think it’s because of the MongoDB storage but I’m uncertain how to fix it. I am capable of reaching an endpoint from my browser and a REST client from an API route.

Do you have any guidance about what I need to do? Like if I am to extend the League OAuth storage or just make it easier by switching to mySQL or what?

    {
        "message": "Client authentication failed.",
        "status_code": 500,
        "debug": {
            "line": 85,
            "file": "/var/www/api.tapecm.com/vendor/league/oauth2-server/src/Grant/ClientCredentialsGrant.php",
            "class": "League\\OAuth2\\Server\\Exception\\InvalidClientException",
            "trace": [
                "#0 /var/www/api.tapecm.com/vendor/league/oauth2-server/src/AuthorizationServer.php(275): League\\OAuth2\\Server\\Grant\\ClientCredentialsGrant->completeFlow()",
                "#1 /var/www/api.tapecm.com/vendor/lucadegasperi/oauth2-server-laravel/src/Authorizer.php(117): League\\OAuth2\\Server\\AuthorizationServer->issueAccessToken()",
                "#2 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(213): LucaDegasperi\\OAuth2Server\\Authorizer->issueAccessToken()",
                "#3 /var/www/api.tapecm.com/app/Http/routes.php(21): Illuminate\\Support\\Facades\\Facade::__callStatic('issueAccessToke...', Array)",
                "#4 /var/www/api.tapecm.com/app/Http/routes.php(21): LucaDegasperi\\OAuth2Server\\Facades\\Authorizer::issueAccessToken()",
                "#5 [internal function]: App\\Providers\\RouteServiceProvider->{closure}()",
                "#6 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(155): call_user_func_array(Object(Closure), Array)",
                "#7 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(130): Illuminate\\Routing\\Route->runCallable(Object(Dingo\\Api\\Http\\Request))",
                "#8 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\\Routing\\Route->run(Object(Dingo\\Api\\Http\\Request))",
                "#9 [internal function]: Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
                "#10 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
                "#11 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
                "#12 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
                "#13 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
                "#14 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))",
                "#15 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))",
                "#16 /var/www/api.tapecm.com/vendor/dingo/api/src/Routing/Adapter/Laravel.php(65): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
                "#17 /var/www/api.tapecm.com/vendor/dingo/api/src/Routing/Router.php(559): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
                "#18 /var/www/api.tapecm.com/vendor/dingo/api/src/Http/Middleware/Request.php(110): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
                "#19 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
                "#20 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
                "#21 /var/www/api.tapecm.com/vendor/lucadegasperi/oauth2-server-laravel/src/Middleware/OAuthExceptionHandlerMiddleware.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
                "#22 [internal function]: LucaDegasperi\\OAuth2Server\\Middleware\\OAuthExceptionHandlerMiddleware->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
                "#23 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
                "#24 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
                "#25 [internal function]: Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
                "#26 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
                "#27 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
                "#28 [internal function]: Illuminate\\Session\\Middleware\\StartSession->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
                "#29 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
                "#30 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
                "#31 [internal function]: Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
                "#32 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
                "#33 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
                "#34 [internal function]: Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
                "#35 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
                "#36 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
                "#37 [internal function]: Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
                "#38 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
                "#39 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
                "#40 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Dingo\\Api\\Http\\Request))",
                "#41 /var/www/api.tapecm.com/vendor/dingo/api/src/Http/Middleware/Request.php(111): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
                "#42 /var/www/api.tapecm.com/vendor/dingo/api/src/Http/Middleware/Request.php(89): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
                "#43 [internal function]: Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
                "#44 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)",
                "#45 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
                "#46 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request))",
                "#47 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
                "#48 /var/www/api.tapecm.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
                "#49 /var/www/api.tapecm.com/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
                "#50 {main}"
            ]
        }
    }

**Comment by Fakerhardcore** [comment]
Hi,

we just focused a problem with the first entry of the clients table. Just try the second one.

**Comment by vinkla** [comment]
Sorry we don't currently support MongoDB. Please search the issues and pull requests, I know there is a lot of documentation discussion there.

**Comment by odminchek** [comment]
Да как вы не поддерживаете MongoDB, если команда php artisan migrate мне все ваши коллекции создала в базе mongo?

**Comment by bfmbrandonjames** [comment]
I quit using mongodb so I don't mind any more
