### ISSUE TITLE
Not working in Lumen 5.2

### ISSUE THREAD

**Issue by tralves** [lucadegasperi/oauth2-server-laravel#639]
The problem is that in Lumen 5.2 (for some reason) ``Laravel\Lumen\Application`` no longer implements ``\Illuminate\Contracts\Foundation\Application``.

This causes the providers ``LucaDegasperi\OAuth2Server\OAuth2ServerServiceProvider`` and ``LucaDegasperi\OAuth2Server\Storage\FluentStorageServiceProvider`` to fail, since they expect the $app to implement that contract.

I would say that the best solution is to remove that type hint ``$app`` var from the several functions and use ``$this->app`` instead, as that is the most common usage.

I am trying that now and PR in case of success.

Thanks!

**Comment by tralves** [comment]
Done. 

In case anyone needs this, the fork is fixed and tested [here](https://github.com/tralves/oauth2-server-laravel).

**Comment by vinkla** [comment]
Thanks for this, I'll check the PR.

**Comment by GrahamCampbell** [comment]
That fix looks wrong to me.

**Comment by GrahamCampbell** [comment]
You should just change the contract to use the container contract.
