### ISSUE TITLE
Alter the way in which Exceptions are handled

### ISSUE THREAD

**Issue by mstephens** [lucadegasperi/oauth2-server-laravel#641]
Hello,

As a result of [5.2 changes](https://github.com/laravel/framework/commit/f5f843396c2c3cd244334029847fee2c7809123d), this package's way of [capturing Exceptions in middleware](https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/src/Middleware/OAuthExceptionHandlerMiddleware.php) no longer works (Laravel captureds it in the Routing pipeline).  Therefore the user will need to capture this in their global Exception handler.

I don't agree with how this has been implemented, but as it's live in 5.2, I guess this needs addressing! 

Cheers

**Comment by mrgswift** [comment]
Bump!  I am also having this problem in laravel 5.2.  The exceptions that are supposed to output a REST response with proper status code are instead throwing a laravel exception with 500 status code.

**Comment by mstephens** [comment]
@mrgswift they have actually made a fix to this following me raising it as an issue (see conversation [here](https://github.com/laravel/framework/commit/f5f843396c2c3cd244334029847fee2c7809123d), however they'll still need to be code changes made :-1: . Personally I think the changes Laravel have made are the wrong ones, but hey ho.

To fix in the short term you just need to add an Exception listener in your Exception/Handler.php class, something along the lines of:

```
public function render($request, Exception $e)
{
    if($request->isJson() || $request->ajax()) {
        /**
         * Output error response depending on the exception fired
         */
        $className = get_class($e);
        switch ($className) {
            case OAuthException::class:
                // Return your JSON response here
                return;
            default:
                // Any other Ajax/JSON response
                return;
                break;
    }
    
    return parent::render($request, $e);
}
```

I've disabled the OAuth default Exception middleware and had created my own (to use it as a generic API Exception handler for all kinds of Exceptions). I copied across my rules from the middleware to the above, a bit of a pain, but looks like it'll be all change again in 5.2.8.

Happy coding!

**Comment by mrgswift** [comment]
@mstephens I ended up implementing this to make it work:
```
    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $e
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $e)
    {
        /**
         * Output error response depending on the exception fired
         */
        $className = get_class($e);
        switch (true) {
            case (strpos($className,'League\OAuth2\Server\Exception') != -1):
                // Return JSON response
                return $this->JSONHandler($e);
            case (strpos($className,'LucaDegasperi\OAuth2Server\Exceptions') != -1):
                // Return JSON response
                return $this->JSONHandler($e);
            default:
                // Any other response
                return parent::render($request, $e);
                break;
        }

    }
    /**
     * Return exception as JSON response with status code.
     *
     * @param  \Exception  $e
     * @return mixed
     */
    private function JSONHandler(Exception $e) {
        $data = [
            'error' => $e->errorType,
            'error_description' => $e->getMessage(),
        ];
        return new JsonResponse($data, $e->httpStatusCode, $e->getHttpHeaders());
    }
```

This isn't the most ideal, but for now it works until they change how it works again. :-/

**Comment by mstephens** [comment]
No worries, there's a patch that will be released in 5.2.8. For those stuck on 5.2.8 or for an immediate fix, the above seems the only plausible way. 

The reason for the change is apparently due to laravel always returning a request to middleware.

**Comment by chadhobson** [comment]
Banging into this all day today with existing code and had a suspicion there's something wrong with one of the holy trinity of extensions (Laravel/Dingo/Lucade) we're using.

So, as a test I'm running latest Laravel (5.2.10) and Dingo (5.1.3) on a fresh install and I get nothing but 500 status codes on any error. Currently just doing a POST of bad username/pass to /oauth/access_token and the returned message is correct but the status code is dead wrong.

{"message":"The user credentials were incorrect.","status_code":500}

Starting down the debugging rabbit hole now but would absolutely LOVE someone to save me the effort. :smile:

**Comment by vinkla** [comment]
Did you guys solve this? Did the new Laravel release help?

**Comment by mstephens** [comment]
Hi guys. I've committed a fix and will create a pull request.

**Comment by mhousser** [comment]
Did this make it into a release version of Lumen/Laravel? Upgraded to Lumen 5.2.4 from 5.1.* and my exception-catching middleware is completely non-functional now. :(

**Comment by mstephens** [comment]
@mhousser have you checked which version of oauth2-server-laravel you're using in the Lumen by running `composer show lucadegasperi/oauth2-server-laravel
`? You need 5.1.4 onwards to get the change.

**Comment by mhousser** [comment]
It says 5.1.4.

Sorry, to which change are you referring?

**Comment by mhousser** [comment]
Oh I think I see what you mean. I was actually using my *own* middleware class to catch OAuth exceptions - and nothing was being caught.

Correct me if I'm wrong - you're saying that the library's own `OAuthExceptionHandlerMiddleware` class (which I wasn't using - I made my own because my `JsonResponse` format is a tiny bit different - was updated with code to actually notice and re-throw exceptions. Code below:

```
    public function handle($request, Closure $next)
    {
        try {
            $response = $next($request);
            // Was an exception thrown? If so and available catch in our middleware
            if (isset($response->exception) && $response->exception) {
                throw $response->exception;
            }

            return $response;
        } catch (OAuthException $e) {
            $data = [
                'error' => $e->errorType,
                'error_description' => $e->getMessage(),
            ];

            return new JsonResponse($data, $e->httpStatusCode, $e->getHttpHeaders());
        }
    }
```

So.. if I were to take this code and put it in my own (almost virtually identical) middleware class, that re-throwing logic should solve everything?

**Comment by mstephens** [comment]
@mhousser yep that's correct. The fix I've put in to the OAuth package was due to the way Laravel changed the way exceptions are handled through middleware. 

I too use my own handler rather than this one. just use the same logic. The exception is thrown again so that you can make use of instanceof etc. 

Hope it helps.

**Comment by mhousser** [comment]
Strange. With Lumen 5.2.4, when I make an `OAuthException `throw, I'm not getting into this branch, which I fully expected would happen:

```
            if (isset($response->exception) && $response->exception) {
                throw $response->exception;
            }
```

I know it's an `OAuthException `because in the Handler I can still do a `$e instanceof OAuthException `check to handle things (which was my backup method).. puzzling.. must do some research to see how `$response->exception` is populated and operates..

**Comment by mhousser** [comment]
`$response` appears to be of type `Illuminate\Http\JsonResponse`, and I see no `exception `field in this class.

What exactly was `$response ` expecting in terms of class type..? Confused how this is supposed to work. There's clearly an exception in the middleware pipeline but `$response` in my debugging experiments is not what this code expects it to be..

**Comment by TimothyLoyer** [comment]
This is still an issue right? I see the commit above in my OAuthExceptionHandlerMiddleware class, but I still get a 500 response from InvalidCredentialsException, InvalidRefreshException, etc.

**Comment by enbaby** [comment]
@TimothyLoyer me too,I google it,but I don't find any answer to solve it.
I find this answer,but it doesn't solve my problem.
https://github.com/lucadegasperi/oauth2-server-laravel/issues/614#issuecomment-163945194
`/**
     * Report or log an exception.
     *
     * This is a great spot to send exceptions to Sentry, Bugsnag, etc.
     *
     * @param  \Exception  $e
     * @return void
     */
    public function report(Exception $e)
    {
        dd(1);
        parent::report($e);
    }

    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $e
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $e)
    {
        dd(2);
        return parent::render($request, $e);
    }`
I get 1,not 2, so I'm confused how to solve it.

**Comment by DeanWhitehouse** [comment]
For those using dingo with Oauth, I believe the issue is in Dingo and a quick fix has been suggested here. 

https://github.com/dingo/api/issues/1091
