### ISSUE TITLE
Protect my API end points

### ISSUE THREAD

**Issue by arifmahmudrana** [lucadegasperi/oauth2-server-laravel#642]
My Routes

    $api = app('Dingo\Api\Routing\Router');
    $api->version('v1', function ($api)
    {
    
        $api->group(['prefix' => 'food-nutrition', 'middleware' => ['cors', 'oauth', 'oauth-client'], 'namespace' => 'App\Http\Controllers\Api\FoodNutrition'], function ($api)
        {
    
            $api->get('food/search', 'FoodNutritionApiController@search');
            $api->get('food/{id}', 'FoodNutritionApiController@food');
            $api->get('browse', 'FoodNutritionApiController@browse');
            $api->get('food-listings', 'FoodNutritionApiController@foodListings');
    
            $api->group(['middleware' => ['oauth', 'oauth-user']], function ($api)
            {
                $api->post('diet-plan/validate', 'FoodNutritionApiController@dietPlanValidate');
                $api->get('diet-plan/search-food', 'FoodNutritionApiController@dietPlanSearchFood');
                $api->get('diet-plan/{id}/edit', 'FoodNutritionApiController@dietPlanEdit');
                $api->get('diet-plan/{id}', 'FoodNutritionApiController@dietPlanShow');
                $api->put('diet-plan/{id}', 'FoodNutritionApiController@dietPlanUpdate');
                $api->delete('diet-plan/{id}', 'FoodNutritionApiController@dietPlanDelete');
                $api->post('diet-plan', 'FoodNutritionApiController@dietPlanStore');
                $api->get('diet-plan', 'FoodNutritionApiController@dietPlanList');
            });
    
            $api->get('', 'FoodNutritionApiController@index');
    
        });
    
    });

My Grant Types

    'grant_types' => [
        'client_credentials' => [
            'class' => \League\OAuth2\Server\Grant\ClientCredentialsGrant::class,
            'access_token_ttl' => env('ACCESS_TOKEN_TTL', 3600)
        ],
        'password' => [
            'class' => \League\OAuth2\Server\Grant\PasswordGrant::class,
            'callback' => '\App\Api\PasswordVerifier@verify',
            'access_token_ttl' => env('ACCESS_TOKEN_TTL', 3600)
        ],
        'social_login' => [
            'class' => \App\Api\Server\Grant\SocialLoginGrant::class,
            'callback' => '\App\Api\SocialLoginVerifier@verify',
            'access_token_ttl' => env('ACCESS_TOKEN_TTL', 3600)
        ],
        'refresh_token' => [
            'class' => \League\OAuth2\Server\Grant\RefreshTokenGrant::class,
            'access_token_ttl' => env('ACCESS_TOKEN_TTL', 3600),
            'refresh_token_ttl' => env('REFRESH_TOKEN_TTL', 36000)
        ]

    ],

Now what I am looking for is without client id & client secret no API end points can be accessed which is done using `client_credentials` grant. I am using `oauth, oauth-client` middlewares in the group route. Inside my group route I have some route protected for `user resource` only. Now when I get access token for `password grant` & try to access any routes for user resourece that is protected with `oauth, oauth-user` middlewares it says this error **`The resource owner or authorization server denied the request`**.

Now my question is how can I protect my endpoints for clients only & some routes will be user protected. None of the routes can be accessed without client id & client secret.

**Comment by arifmahmudrana** [comment]
I have solved it by removing `oauth-client` & only adding `oauth` middleware.

Now my Routes

    $api = app('Dingo\Api\Routing\Router');
    $api->version('v1', function ($api)
    {

        $api->group(['prefix' => 'food-nutrition', 'middleware' => ['cors', 'oauth'], 'namespace' => 'App\Http\Controllers\Api\FoodNutrition'], function ($api)
        {

            $api->get('food/search', 'FoodNutritionApiController@search');
            $api->get('food/{id}', 'FoodNutritionApiController@food');
            $api->get('browse', 'FoodNutritionApiController@browse');
            $api->get('food-listings', 'FoodNutritionApiController@foodListings');

            $api->group(['middleware' => 'oauth-user'], function ($api)
            {
                $api->post('diet-plan/validate', 'FoodNutritionApiController@dietPlanValidate');
                $api->get('diet-plan/search-food', 'FoodNutritionApiController@dietPlanSearchFood');
                $api->get('diet-plan/{id}/edit', 'FoodNutritionApiController@dietPlanEdit');
                $api->get('diet-plan/{id}', 'FoodNutritionApiController@dietPlanShow');
                $api->put('diet-plan/{id}', 'FoodNutritionApiController@dietPlanUpdate');
                $api->delete('diet-plan/{id}', 'FoodNutritionApiController@dietPlanDelete');
                $api->post('diet-plan', 'FoodNutritionApiController@dietPlanStore');
                $api->get('diet-plan', 'FoodNutritionApiController@dietPlanList');
            });

            $api->get('', 'FoodNutritionApiController@index');

        });

    });

Now when accessing my API I create a token using `client_credentials` grant & collect access token & then access API end points. For user type resource I request access token with `password` type grant & request user protected API end points.

**Comment by vinkla** [comment]
:+1:
