### ISSUE TITLE
Error Exception Password Grant

### ISSUE THREAD

**Issue by michaeltansy** [lucadegasperi/oauth2-server-laravel#643]
I already follow every step written in the documentation. But It is not working in my Laravel 5.0
Could somebody help me to solve this?

The error : 
ErrorException in PasswordGrant.php line 62:
Argument 1 passed to League\OAuth2\Server\Grant\PasswordGrant::setVerifyCredentialsCallback() must be callable, array given, called in C:\xampp\htdocs\laravel-api\vendor\lucadegasperi\oauth2-server-laravel\src\OAuth2ServerServiceProvider.php on line 124 and defined

Here's my passwordgrantverifier class : 
class PasswordGrantVerifier{
    public function verifiy($username, $password){
        $credentials = [
            'email' => $username,
            'password' => $password,
        ];

        if(\Auth::once($credentials)){
            return \Auth::id();
        }
        return false;
    }
}

my grant_type : 
'grant_types' => [
        'password' => [
            'class' => 'League\OAuth2\Server\Grant\PasswordGrant',
            'access_token_ttl' => 604800,
 // the code to run in order to verify the user’s identity
            'callback' => '\App\PasswordGrantVerifier@verify',
        ]
    ],

**Comment by vinkla** [comment]
Try updating Laravel to the latest version.

**Comment by vinkla** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by hyperdrivedesigns** [comment]
I just ran across the same issue but I cannot upgrade to 5.2. I am running 5.0.8.  Any help would be greatly appreciated! 

Thanks, 

Darren

**Comment by hyperdrivedesigns** [comment]
OK. never mind fixed my own issue. Realized exactly where the issue lied and looked over the updated OAuth2ServerServiceProvider.php file and made some changes to the code throwing the issue. For anyone that might run across a Laravel 5.0 site running 4.0 version of OAuth Server her is what I changed. USE AT YOUR OWN RISK. 

I updated the foreach loop in the registerAuthorizer function code below. It now works on my Laravel instance. 

public function registerAuthorizer()
    {
        $this->app->bindShared('oauth2-server.authorizer', function ($app) {
            $config = $app['config']->get('oauth2');
            $issuer = $app->make('League\OAuth2\Server\AuthorizationServer')
                          ->setClientStorage($app->make('League\OAuth2\Server\Storage\ClientInterface'))
                          ->setSessionStorage($app->make('League\OAuth2\Server\Storage\SessionInterface'))
                          ->setAuthCodeStorage($app->make('League\OAuth2\Server\Storage\AuthCodeInterface'))
                          ->setAccessTokenStorage($app->make('League\OAuth2\Server\Storage\AccessTokenInterface'))
                          ->setRefreshTokenStorage($app->make('League\OAuth2\Server\Storage\RefreshTokenInterface'))
                          ->setScopeStorage($app->make('League\OAuth2\Server\Storage\ScopeInterface'))
                          ->requireScopeParam($config['scope_param'])
                          ->setDefaultScope($config['default_scope'])
                          ->requireStateParam($config['state_param'])
                          ->setScopeDelimiter($config['scope_delimiter'])
                          ->setAccessTokenTTL($config['access_token_ttl']);

            // add the supported grant types to the authorization server
            foreach ($config['grant_types'] as $grantIdentifier => $grantParams) {
                $grant = $app->make($grantParams['class']);
                $grant->setAccessTokenTTL($grantParams['access_token_ttl']);
                if (array_key_exists('callback', $grantParams)) {
                    list($className, $method) = array_pad(explode('@', $grantParams['callback']), 2, 'verify');
                    $verifier = $app->make($className);
                    $grant->setVerifyCredentialsCallback([$verifier, $method]);
                }
                if (array_key_exists('auth_token_ttl', $grantParams)) {
                    $grant->setAuthTokenTTL($grantParams['auth_token_ttl']);
                }
                if (array_key_exists('refresh_token_ttl', $grantParams)) {
                    $grant->setRefreshTokenTTL($grantParams['refresh_token_ttl']);
                }
                if (array_key_exists('rotate_refresh_tokens', $grantParams)) {
                    $grant->setRefreshTokenRotation($grantParams['rotate_refresh_tokens']);
                }
                $issuer->addGrantType($grant, $grantIdentifier);
            }

            $checker = $app->make('League\OAuth2\Server\ResourceServer');

            $authorizer = new Authorizer($issuer, $checker);
            $authorizer->setRequest($app['request']);
            $authorizer->setTokenType($app->make($config['token_type']));

            $app->refresh('request', $authorizer, 'setRequest');

            return $authorizer;
        });

        $this->app->bind('LucaDegasperi\OAuth2Server\Authorizer', function($app)
        {
            return $app['oauth2-server.authorizer'];
        });
    }
