### ISSUE TITLE
An OAuth

### ISSUE THREAD

**Issue by tleb** [lucadegasperi/oauth2-server-laravel#647]
> These letters are vowels in English: A, E, I, O, U, and sometimes Y.

> Use *an* before a word that starts with a vowel sound.

So it should be `An OAuth 2.0 bridge for Laravel and Lumen`.

Was just visiting the page and saw this in the description. Seems like a nice project. :)

**Comment by lucadegasperi** [comment]
Fixed now, Thanks!
