### ISSUE TITLE
Requesting tokens in testcase

### ISSUE THREAD

**Issue by tuupke** [lucadegasperi/oauth2-server-laravel#651]
When attempting to request a token in a testcase through a normal
``` PHP
$this->post('/api/token', [
            "grant_type" => "password",
            'client_id' => $client->id,
            'client_secret' => $client->secret,
            'username' => $username,
            'password' => $password
])
```
an error is always thrown: ```The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"grant_type\" parameter.```

However when we normally make this call it works perfectly everytime. After digging around in the code somewhat I figured out that the request passed to the checker is basically empty. Am I missing something with regards to what is required in the call or is this simply impossible?

**Comment by vinkla** [comment]
What happens if you dump the data from the test case in the controller?

**Comment by tuupke** [comment]
If you mean the array which we pass to the endpoint, it contains only valid data (which we manually verified) while the actual result of the call is that error message I originally posted.

**Comment by vinkla** [comment]
Please check your web server configuration.

**Comment by tuupke** [comment]
My webserver config is fine, it works on normal requests and is the same as the config I'm using in production. It is the standard Laravel nginx config which has never failed to work before.

Does the call work for you then @vinkla? (requesting a token from a testcase using the same structure as stated above; or any different structure). I've tried this when I was on Laravel 5.1 and have retried it today after upgrading to 5.2 (currently Laravel v5.2.15, v5.1.4 of this library and v4.1.5 of leagues' library)

**Comment by tuupke** [comment]
Mhh, after some upgrades it started working magically. So the issue is now resolved.
