### ISSUE TITLE
Class 'Illuminate\Auth\RequestGuard' does not have a method 'once'

### ISSUE THREAD

**Issue by rizkytahara** [lucadegasperi/oauth2-server-laravel#654]
I'm using Lumen 5.2 fresh install and add the lucadegasperi/oauth2-server-laravel. I've follow the instructions on the docs with Password Grant and when I tried to access the oauth/access_token route, it gives me error Class 'Illuminate\Auth\RequestGuard' does not have a method 'once'

Any idea how to attempt the user login on Lumen 5.2?; since I also have the same things with Lumen 5.1 and works fine...

**Comment by vinkla** [comment]
You solved it?

**Comment by rizkytahara** [comment]
I don't know if this is the right way, at the PasswordGrantVerifier.php I change to check the user and password manually; since seems the once() method already not exists ?? CMIIW

    <?php

    namespace App;

    use App\User;

    class PasswordGrantVerifier
    {

        public function verify($username, $password)
        {
            $user = User::where('user_id', $username)->first();
            if ($user && app()['hash']->check($password, $user->password)) {
                return $user;
            }

            return false;
        }

    }

**Comment by vinkla** [comment]
I'm not sure what you are talking about?

**Comment by rizkytahara** [comment]
I've follow https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/docs/authorization-server/password.md for creating the PasswordGrantVerifier.php , but when I tried to access the access_token route; it gives me the "Class 'Illuminate\Auth\RequestGuard' does not have a method 'once'" error.

It was fine when I'm using Lumen 5.1, I don't know why it's not working on Lumen 5.2 or maybe I missed something?

**Comment by vinkla** [comment]
Does it work if you change `once()` to `validate()`?

**Comment by rizkytahara** [comment]
`once()` isn't working and gives the error above; I've tried with `validate()` but still don't know how to achieve with it...

**Comment by vinkla** [comment]
So it works with validate?

**Comment by rizkytahara** [comment]
Maybe, since I don't know how to use the validate.. Any example with `validate()` so I can test it?

**Comment by rizkytahara** [comment]
Try to change `once()` with `validate()` gives me:

ErrorException in RequestGuard.php line 66:
Undefined index: request

**Comment by vinkla** [comment]
Just change the name of the method from the example.

**Comment by vinkla** [comment]
The example you've submitted above doesn't look like the example from the documentation?

**Comment by rizkytahara** [comment]
namespace App;

    class PasswordGrantVerifier
    {
        public function verify($username, $password)
        {
            $authManager = app()['auth'];

            if ($authManager->validate([
                'user_id' => $username,
                'password' => $password,
            ])) {
                return $authManager->user()->id;
            }

            return false;
        }
    }

gives me:
ErrorException in RequestGuard.php line 66:
Undefined index: request

if, I add the `request` index:

    namespace App;

    class PasswordGrantVerifier
    {
        public function verify($username, $password)
        {
            $authManager = app()['auth'];

            if ($authManager->validate([
                'request' => [
                    'user_id' => $username,
                    'password' => $password,
                ]
            ])) {
                return $authManager->user()->id;
            }

            return false;
        }
    }

gives me:
ErrorException in RequestGuard.php line 34:
Argument 2 passed to Illuminate\Auth\RequestGuard::__construct() must be an instance of Illuminate\Http\Request, array given


and if I change to:

    namespace App;

    class PasswordGrantVerifier
    {
        public function verify($username, $password)
        {
            $authManager = app()['auth'];

            if ($authManager->validate([
                'request' => app()['request']
            ])) {
                return $authManager->user()->id;
            }

            // return false;
        }
    }

gives me:
QueryException in Connection.php line 651:
SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "owner_id" violates not-null constraint
DETAIL: Failing row contains
; although the username and password already correct


any clue how to pass parameter with `validate()` ?

**Comment by vinkla** [comment]
Why aren you using `$authManager = app()['auth'];`? Use the `Auth::` facade as in the docs instead.

**Comment by rizkytahara** [comment]
`$authManager = app()['auth'];` it's just the same with the `Auth::` facade, right?
http://esbenp.github.io/2015/05/26/lumen-web-api-oauth-2-authentication/

Using the facade also gives the same errors; `Auth::once()` gives the same error above; `Auth::validate()` also gives the same error... no difference by using the `Auth` facade.. any idea?

**Comment by vinkla** [comment]
I've no idea. Sorry. Have you found anyone else having this issue?

**Comment by rizkytahara** [comment]
I don't know if anyone else having the same issue... Have you tried with fresh install of Lumen 5.2?

**Comment by vinkla** [comment]
Nope, I don't use Lumen much.

**Comment by Cosmitar** [comment]
@rizkytahara I'm in the same situation you describe. Trying the same tutorial, same errors, Lumen (5.2.4) (Laravel Components 5.2.*). Any progress about a solution?

**Comment by rizkytahara** [comment]
First, maybe because I don't know how to authenticate with Lumen 5.2 procedure so for Lumen 5.2, I'm using this code in file `PasswordGrantVerifier.php`:

```
<?php

namespace App;

use App\User;

class PasswordGrantVerifier
{

    public function verify($username, $password)
    {
        $user = User::where('user_id', $username)->first();
        if ($user && app()['hash']->check($password, $user->password)) {
            return $user->id;
        }

        return false;
    }

}
```

Change `user_id` to the fields at your User table.

I don't know if that is the correct way to authenticate with Lumen 5.2. Anyway, I'm switching back to Lumen 5.1 because another plugins still not supported for Lumen 5.2

**Comment by vinkla** [comment]
Does #653 fix your issue?

**Comment by oflannabhra** [comment]
The issue here is that with the changes to `AuthServiceProvider` in Lumen 5.2, calling `Auth::validate()` resolves to `AuthManager->viaRequest()` which expects a `Request` object. In the OAuth2 server, we don't have access to the Request object.

**Comment by oflannabhra** [comment]
I've got something working, but it feels pretty hacky. In my `PasswordGrantVerifier->verify()` method, I have 
```
public static function verify($username, $password) {

    $credentials = [
            'request' => Request::create('/', 'POST', ['username' => $username, 'password' => $password])
        ];

        if (Auth::validate($credentials)) {
            return Auth::user()->id;
        } else {
            return false;
        }
}
```
and in my `AuthServiceProvider->boot()` I have 
```
public function boot() {

   $this->app['auth']->viaRequest('api', function ($request) {
            if ($request->input('api_token')) {
                return User::where('api_token', $request->input('api_token'))->first();
            } elseif ($request->input('username') && $request->input('password')) {
                $user = User::where('name', $request->input('username'))->first();
                if (Hash::check($request->input('password'), $user->password)) {
                    return $user;
                } else {
                    return null;
                }
            }
        });
}
```

**Comment by vmartins** [comment]
@oflannabhra I used your solution, but `viaRequest` callback function is processed twice

    //class AuthServiceProvider
    public function boot()
    {
        Auth::viaRequest('api', function ($request) {
            echo "api\n";
            if ($request->input('username') && $request->input('password')) {
                //my auth...
            }
        });
    }

Result of the request via cURL
```
api
api
{"access_token":"p6n3Bgx0lABVhiM4537l2mWgP17x8RT5KgJvLsdE","token_type":"Bearer","expires_in":28800,"refresh_token":"lUO6aD1YlVYHxnC0Pa416aNQRA8l0bgDkGFZCnz7"}
```

Do you know why?

**Comment by OmarElGabry** [comment]
Just pass the request object, and leverage the username and password from the request object in `AuthServiceProvider` Class.

```php
public function verify($username, $password){

      if (Auth::validate(['request' => app()['request']]) {
          return Auth::user()->id;
      }
      return false;
}
```

**Comment by oflannabhra** [comment]
@OmarElGabry Are you sure that `app()['request']` returns the current request? I thought I tried that, but didn't get a valid Request back, which is how I arrived at the `Request::create()` hack

**Comment by OmarElGabry** [comment]
@oflannabhra Yes. Can you try this line of code and see what you've got.

```php
// In any controller(i.e. UserController.php)
public function index(Request $request){
       echo app()['request'] == $request;
}
```
