### ISSUE TITLE
OAuthExceptionHandlerMiddleware not catching OAuthException

### ISSUE THREAD

**Issue by Synapse791** [lucadegasperi/oauth2-server-laravel#655]
I've just set up this package with Laravel 5.2.* and 5.1.* of this project and I'm having an issue with the OAuthExceptionHandlerMiddleware not catching any exceptions. This means that when I make a request with an invalid token, I get the full HTML exception response instead of the JSON error response which I need for my API. 

I have added the middleware to my `$routeMiddleware` as follows:
```php
protected $routeMiddleware = [
    ...
    'oauth-exception' => \LucaDegasperi\OAuth2Server\Middleware\OAuthExceptionHandlerMiddleware::class,
    ...
];
```

then adding it to my routes like so:
```php
Route::group(['prefix' => '/api'], function() {
    Route::group(['middleware' => ['oauth-exception', 'oauth', 'oauth-user']], function() {
        Route::get('/test', function () {
            return Response::json(['message' => 'welldone!']);
        });
    });
});
```

When I'm passing a valid token, it works perfectly but when I remove one character from the token to test the exception handler, it throws the exception as the full HTML response. I've tested the middleware is getting hit by adding `echo "here";die;` to the try statement and I get back a string of hear so it is getting to the middleware, it's just not capturing the exception.

Am I doing something glaringly obviously wrong?

**Comment by jandayanan** [comment]
I think you should see: https://github.com/lucadegasperi/oauth2-server-laravel/issues/641

**Comment by mhousser** [comment]
Same issue! I have a `OAuthExceptionHandlerMiddleware` class with a `catch (OAuthException $e) ` and even a final `catch (Exception $e)` after the `return $next($request);`.

These catch blocks are *NOT* being entered, even though I've proven in the `Handler` that a derivative of `OAuthException `is being thrown!!

**Comment by vinkla** [comment]
@Synapse791 the OAuthExceptionHandlerMiddleware should not be added to `$routeMiddleware`.

From the documentation:
Add the following line to your `app/Http/Kernel.php` file in the `$middleware` array
```php
\LucaDegasperi\OAuth2Server\Middleware\OAuthExceptionHandlerMiddleware::class,
```
