### ISSUE TITLE
Selecting different database for migration

### ISSUE THREAD

**Issue by jandayanan** [lucadegasperi/oauth2-server-laravel#656]
Is it possible to declare or set a different database target for migration of tables? Because I have tried adding `'database'=>'oauth',` to my `oauth2.php` file, yet it doesn't work properly as it still migrates the new tables to the default database. Any ideas?

Thanks

**Comment by jandayanan** [comment]
Sorry for opening up this issue, this is actually not related to this repo but instead to Laravel's artisan. You can specify a migration table by runnning `php artisan migrate --database=yourdatabasename`

**Comment by mjnciceri** [comment]
You can also change your migration files like this

```php
        Schema::connection('oauth')->create('oauth_scopes', function (Blueprint $table) {
            $table->string('id', 40)->primary();
            $table->string('description');

            $table->timestamps();
        });
```
