### ISSUE TITLE
Issue in access_token action when using authorization_code grant

### ISSUE THREAD

**Issue by peacefrog333** [lucadegasperi/oauth2-server-laravel#657]
Hi, I am able to get the authorization code when I use the  'oauth/authorize' route as in the example. But when i am trying to get the access token it shows the error as : 

{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"code\" parameter."}

I made sure i set the code parameter as response retrieved from the redirect uri during authorization. In the AuthCodeGrant implementation i am unable to get the code from the database as AuthCodeEntity object, but rather gets a null everytime. 

Let me know if i am making a mistake with the request ( oauth/access_token ) and help me identify how to fix it.

Thanks

**Comment by SwiTool** [comment]
1. Add a client and a client endpoint in the database.
2. Add a route ```'oauth2/authorize'``` (make sure you are connected, or it won't work)
3. Go to that route, with ```client_id```, ```redirect_uri```, and ```response_type=code``` parameters (in GET)
4. On this page, there is the form, and make a POST request with parameters in GET (the same as 3.) (ex: ```POST http://localhost/oauth/authorize?client_id=123&redirect_uri=/perso/oauth&response_type=code```)
5. It will redirect your on your redirect URI with GET parameters indicating either the code or an error message.

**Comment by vinkla** [comment]
Thanks for helping out @SwiTool :+1:

**Comment by SwiTool** [comment]
@vinkla I'm also in distress :stuck_out_tongue_winking_eye:

**Comment by vinkla** [comment]
I understand, we still appreciate all the help we can get.

**Comment by vinkla** [comment]
This issue seem fairly old. I'm closing ti.
