### ISSUE TITLE
InvalidRequestException in ResourceServer.php line 150

### ISSUE THREAD

**Issue by johnmain** [lucadegasperi/oauth2-server-laravel#664]
I have followed the documentation and everything goes well until I attempt to go to any route.  I don't have any routes protected at the moment so should be directed to the default welcome page.

I get:
InvalidRequestException in ResourceServer.php line 150
The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the "access token" parameter.

**Comment by vinkla** [comment]
We're sorry you're having a bad experience setting this package up. In order for us to help you must first provide more information of your implementation. Snippets of your setup will help us speed up the process of helping you getting on the right track.

**Comment by johnmain** [comment]
Start with fresh Laravel install (5.2).
Followed the guide https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/docs/getting-started/laravel-5.md exact steps. including the Migration and I created a seeder to add a test user and client.

created a class for PasswordGrantVerifier:

`<?php
namespace App;

use Illuminate\Support\Facades\Auth;

class PasswordGrantVerifier
{
  public function verify($username, $password)
  {
      $credentials = [
        'email'    => $username,
        'password' => $password,
      ];

      if (Auth::once($credentials)) {
          return Auth::user()->id;
      }

      return false;
  }
}`

in oath2.php added \
`'grant_types' => [
    'password' => [
        'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
        'callback' => '\App\PasswordGrantVerifier@verify',
        'access_token_ttl' => 3600
    ]
],`

Only thing in routers.php is 

`Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);`

I had the following but removed it when I got the error.  but even an empty router.php returns the error.
`Route::post('oauth/access_token', function() {
 return Response::json(Authorizer::issueAccessToken());
});


Route::get('api', ['before' => 'oauth', function() {
 // return the protected resource
 //echo “success authentication”;
 $user_id=Authorizer::getResourceOwnerId(); // the token user_id
 $user=\App\User::find($user_id);// get the user data from database

return Response::json($user);
}]);`

**Comment by vinkla** [comment]
Could you paste your `Kernel.php` file.

**Comment by johnmain** [comment]
`<?php

namespace App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    /**
     * The application's global HTTP middleware stack.
     *
     * These middleware are run during every request to your application.
     *
     * @var array
     */
    protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        'oauth' => \LucaDegasperi\OAuth2Server\Middleware\OAuthMiddleware::class,
        'oauth-user' => \LucaDegasperi\OAuth2Server\Middleware\OAuthUserOwnerMiddleware::class,
        'oauth-client' => \LucaDegasperi\OAuth2Server\Middleware\OAuthClientOwnerMiddleware::class,
        'check-authorization-params' => \LucaDegasperi\OAuth2Server\Middleware\CheckAuthCodeRequestMiddleware::class,
    ];

    /**
     * The application's route middleware groups.
     *
     * @var array
     */
    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,

            \LucaDegasperi\OAuth2Server\Middleware\OAuthExceptionHandlerMiddleware::class,
        ],

        'api' => [
            'throttle:60,1',
        ],
    ];

    /**
     * The application's route middleware.
     *
     * These middleware may be assigned to groups or used individually.
     *
     * @var array
     */
    protected $routeMiddleware = [
        'auth' => \App\Http\Middleware\Authenticate::class,
        'auth.basic' => \Illuminate\Auth\Middleware\AuthenticateWithBasicAuth::class,
        'guest' => \App\Http\Middleware\RedirectIfAuthenticated::class,
        'throttle' => \Illuminate\Routing\Middleware\ThrottleRequests::class,
        'csrf' => App\Http\Middleware\VerifyCsrfToken::class,
    ];
}
`

**Comment by johnmain** [comment]
I think I see the issue

**Comment by johnmain** [comment]
Yes sorry for wasting your time.  I had the items in the wrong places.
