### ISSUE TITLE
How to get full session resource owner data?

### ISSUE THREAD

**Issue by morfin** [lucadegasperi/oauth2-server-laravel#669]
HI,

Instead of getting just the ID with getResourceOwnerId(), how can I get the full session data ? Does oAuth2-server-laravel just holds the ID ? Can I get the full user model data?

Or do I need to fetch the full user by my own?

Thanks.

**Comment by lucadegasperi** [comment]
Yes you need to fetch them on your own since this library makes no assumption on how you store your resource owner data
