### ISSUE TITLE
Oauth2.0 Installation issue 

### ISSUE THREAD

**Issue by andrew3008** [lucadegasperi/oauth2-server-laravel#674]
Composer :
```
"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "lucadegasperi/oauth2-server-laravel": "5.0.*"
   }
```
------------------------------------------------------------------------------------

php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.2.21
    - Conclusion: don't install laravel/framework v5.2.21
    - Conclusion: don't install laravel/framework v5.2.20
    - Conclusion: don't install laravel/framework v5.2.19
    - Conclusion: don't install laravel/framework v5.2.18
    - Conclusion: don't install laravel/framework v5.2.17
    - Conclusion: don't install laravel/framework v5.2.16
    - Conclusion: don't install laravel/framework v5.2.15
    - Conclusion: don't install laravel/framework v5.2.14
    - Conclusion: don't install laravel/framework v5.2.13
    - Conclusion: don't install laravel/framework v5.2.12
    - Conclusion: don't install laravel/framework v5.2.11
    - Conclusion: don't install laravel/framework v5.2.10
    - Conclusion: don't install laravel/framework v5.2.9
    - Conclusion: don't install laravel/framework v5.2.8
    - Conclusion: don't install laravel/framework v5.2.7
    - Conclusion: don't install laravel/framework v5.2.6
    - Conclusion: don't install laravel/framework v5.2.5
    - Conclusion: don't install laravel/framework v5.2.4
    - Conclusion: don't install laravel/framework v5.2.3
    - Conclusion: don't install laravel/framework v5.2.2
    - Conclusion: don't install laravel/framework v5.2.1
    - lucadegasperi/oauth2-server-laravel 5.0.0 requires illuminate/config 5.1.* -> satisfiable by illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - lucadegasperi/oauth2-server-laravel 5.0.1 requires illuminate/config 5.1.* -> satisfiable by illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - lucadegasperi/oauth2-server-laravel 5.0.2 requires illuminate/config 5.1.* -> satisfiable by illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - lucadegasperi/oauth2-server-laravel 5.0.3 requires illuminate/config 5.1.* -> satisfiable by illuminate/config[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8].
    - don't install illuminate/config v5.1.1|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.13|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.16|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.2|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.20|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.22|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.25|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.28|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.30|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.31|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.6|don't install laravel/framework v5.2.0
    - don't install illuminate/config v5.1.8|don't install laravel/framework v5.2.0
    - Installation request for laravel/framework 5.2.* -> satisfiable by laravel/framework[v5.2.0, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.15, v5.2.16, v5.2.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.3, v5.2.4, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9].
    - Installation request for lucadegasperi/oauth2-server-laravel 5.0.* -> satisfiable by lucadegasperi/oauth2-server-laravel[5.0.0, 5.0.1, 5.0.2, 5.0.3].

**Comment by vinkla** [comment]
You've to use `"lucadegasperi/oauth2-server-laravel": "5.1.*"`.
