### ISSUE TITLE
FluentClient implements ClientInterface miss a situation

### ISSUE THREAD

**Issue by Manasseh-Zhou** [lucadegasperi/oauth2-server-laravel#679]
FluentClient when implement ClientInterface miss a situation

when overwrite
public function get($clientId, $clientSecret = null, $redirectUri = null, $grantType = null)

miss a situation, because $clientSecret and $redirectUri can be null at the same time
if (is_null($redirectUri) && is_null($clientSecret)) {}

**Comment by Manasseh-Zhou** [comment]
else if(is_null($clientSecret) && is_null($redirectUri)) {
            $query = $this->getConnection()->table('oauth_clients')
                   ->select(
                       'oauth_clients.id as id',
                       'oauth_clients.secret as secret',
                       'oauth_clients.name as name')
                   ->where('oauth_clients.id', $clientId);
}

**Comment by vinkla** [comment]
Thanks for pointing it out. Please submit a PR for this.

**Comment by Manasseh-Zhou** [comment]
@vinkla submitted, check plz

**Comment by vinkla** [comment]
Thanks! I'll close this then we can continue talk in the PR instead.
