### ISSUE TITLE
Scope requests does not coincide the RFC6749

### ISSUE THREAD

**Issue by SwiTool** [lucadegasperi/oauth2-server-laravel#683]
The scopes (at least for Laravel 4) are wroking with **comma-separated** strings.
As per the [RFC6749 3.3 section](https://tools.ietf.org/html/rfc6749#section-3.3):

> The value of the scope parameter is expressed as a list of space-
   delimited, case-sensitive strings.  The strings are defined by the
   authorization server.  If the value contains multiple space-delimited
   strings, their order does not matter, and each string adds an
   additional access range to the requested scope.

**Comment by vinkla** [comment]
We'll look into this for the next major release. Thanks for thanks for letting us know!
