### ISSUE TITLE
Problems running the migrante  in DB Oracle 11g

### ISSUE THREAD

**Issue by nepanuceno** [lucadegasperi/oauth2-server-laravel#684]
Unfortunately I can not run "migrete"
Error:
`[Illuminate\Database\QueryException]                                                                            
  Error Code    : 2264                                                                                            
  Error Message : ORA-02264: name already used by an existing constraint                                          
  Position      : 50                                                                                              
  Statement     : alter table oauth_client_endpoints add constraint oauth_client_endpoints_client_ unique ( clie  
  nt_id, redirect_uri )                                                                                           
  Bindings      : []                                                                                              
   (SQL: alter table oauth_client_endpoints add constraint oauth_client_endpoints_client_ unique ( client_id, re  
  direct_uri ))    `

What appears is that Oracle does not implement the identification of "constraints"
Any solution?

**Comment by vinkla** [comment]
Please see https://github.com/lucadegasperi/oauth2-server-laravel/issues/552#issuecomment-145931139
