### ISSUE TITLE
Redirect URI redirect problem

### ISSUE THREAD

**Issue by ultimateprogramer** [lucadegasperi/oauth2-server-laravel#690]
Developed on top of the system a control panel which we log in and manage various OAuth parameters that are in the database tables (so we automate a lot of that). We just started testing he system by making use of systems that call the `oauth/authorize` endpoint on HTTP get. However, it ceases to redirect back to the calling application, what it does is it shows up the login screen and logs in to the control panel, instead of redirecting back to the caller.

I made the following call to the OAuth System: `oauth/authorize?client_id=my_client_id&client_secret=my_secret&redirect_uri=http://localhost/redirect_url&scope=access&response_type=code`

This redirects me to `/login` (normal Auth login for the Control Panel). It never resumes calling back the endpoint for the callback in the redirect URL, after I login it sends me to my Control Panel's dashboard.

**Further details**

```
'grant_types' => [
        'authorization_code' => [
            'class' => '\League\OAuth2\Server\Grant\AuthCodeGrant',
           ...
        ]
    ],
```

**Comment by lucadegasperi** [comment]
When calling the ```oauth/authorize``` endpoint, after logging in, your application should propose the user with a screen to ask them to allow the application to access the data on its behalf. If the user agrees with this then it should be redirected back to the application.

By looking at what you've done the oauth part looks to be correct. When logging in, after the user credentials are validated you might be missing a ```return Redirect::intended();``` statement.

**Comment by ultimateprogramer** [comment]
Thank you Luca. I am trying to figure out where to place this fragment. Did it in the Authenticate Middlewares without success. Perhaps a bit of guidance on placement might be of huge help..

**Comment by lucadegasperi** [comment]
Check if you have defined a ```authenticated``` method in ```App\Http\Controllers\Auth\AuthController``` and where does that redirect you to.

**Comment by ultimateprogramer** [comment]
So I am using Laravel 5.2 . The `authenticated` method in `AuthController` looks so:

```
    protected function authenticated($request, User $user)
    {
        return redirect()->intended();
    }
```

Have not managed to get it working still.

**Comment by hafael** [comment]
Same problem when using Laravel 5.2.x clean install and oauth2-server-laravel 5.1.x.

I generated a new installation of laravel and follow the task list of this plugin and the problem happens.
The "auth" middleware  intercepts the request and redirects to login even when the user is logged in, then, does not load the authorization screen and does not enter the given route.

I performed the same procedure using a fresh install of Laravel 5.1.x and 5.0.x oauth2 and works perfectly.

Sorry about my english.

**Comment by ultimateprogramer** [comment]
@hafael you are right downgrading helped. @lucadegasperi it works though when I am logged in but doesn’t when I need to login afresh so I need to investigate.

**Comment by hafael** [comment]
@ultimateprogramer 
Keep calm, solved!

Laravel 5.2 introduces the middleware groups concept: you can specify that one or more middleware belongs to a group, and you can apply a middleware group to one or more routes
By default Laravel 5.2 defines a group named "web", used to group the middleware handling session and other utilities.
So, if you want session handling, you should use this middleware group for all the routes in which you want to use authentication.

In this case, it would be something like:

```

Route::group(['prefix' => 'oauth', 'middleware' => 'web'], function () {
    
    Route::get('authorize', ['as' => 'oauth.authorize.get', 'middleware' => ['check-authorization-params', 'auth'], function() {
        $authParams = Authorizer::getAuthCodeRequestParams();
    
        $formParams = array_except($authParams,'client');
    
        $formParams['client_id'] = $authParams['client']->getId();
    
        $formParams['scope'] = implode(config('oauth2.scope_delimiter'), array_map(function ($scope) {
            return $scope->getId();
        }, $authParams['scopes']));
    
        return View::make('oauth.authorization-form', ['params' => $formParams, 'client' => $authParams['client']]);
    }]);
    Route::post('authorize', ['as' => 'oauth.authorize.post', 'middleware' => ['csrf', 'check-authorization-params', 'auth'], function() {
    
        $params = Authorizer::getAuthCodeRequestParams();
        $params['user_id'] = Auth::user()->id;
        $redirectUri = '/';
    
        // If the user has allowed the client to access its data, redirect back to the client with an auth code.
        if (Request::has('approve')) {
            $redirectUri = Authorizer::issueAuthCode('user', $params['user_id'], $params);
        }
    
        // If the user has denied the client to access its data, redirect back to the client with an error message.
        if (Request::has('deny')) {
            $redirectUri = Authorizer::authCodeRequestDeniedRedirectUri();
        }
    
        return Redirect::to($redirectUri);
    }]);
    Route::post('access_token', function() {
        return Response::json(Authorizer::issueAccessToken());
    });

});
```

**Comment by hafael** [comment]
hey @lucadegasperi or @vinkla ,
You think it is worth a warning in the documentation of this [authorization code grant](https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/docs/authorization-server/auth-code.md)?

**Comment by ultimateprogramer** [comment]
This is solved.. I just had to be smart enough on how to handle sessions in the Authentication middlewares (by employing URL checks). After which session states then allow us to redirect to the correct component.
