### ISSUE TITLE
Link to the "grant_types" description not working in readme.md

### ISSUE THREAD

**Issue by kroeder** [lucadegasperi/oauth2-server-laravel#698]
As said: The documentation here:
https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/docs/getting-started/config.md

Sais: "See Issuing access tokens for how to configure and use the different grant types." and links to: 
https://github.com/lucadegasperi/oauth2-server-laravel#authorization-server

Link does not work.

**Comment by kroeder** [comment]
Should this link to 
https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/docs/authorization-server/choosing-grant.md 

?

**Comment by vinkla** [comment]
Submit a PR please.

**Comment by kroeder** [comment]
Pull Request: #699

**Comment by vinkla** [comment]
Thanks!
