### ISSUE TITLE
Error 401 instead of 400

### ISSUE THREAD

**Issue by miguelsmuller** [lucadegasperi/oauth2-server-laravel#708]
When I did not send the access token the system returns me the error 400 bad request.

Is there a way to change for me to receive the error 401 Unauthorized?

**Comment by maximebeaudoin** [comment]
@michalsanger In your `\App\Exceptions\Handler`, you can catch the `InvalidRequestException` exception and return the response like you want. I do this in my projects.

```php
if ($e instanceof \League\OAuth2\Server\Exception\InvalidRequestException) {
    return response(); //Return wathever you want
}
```

**Comment by miguelsmuller** [comment]
tnks @maximebeaudoin

**Comment by vinkla** [comment]
@maximebeaudoin thanks for helping out!
