### ISSUE TITLE
Refresh Token TTL

### ISSUE THREAD

**Issue by RonnieVisser** [lucadegasperi/oauth2-server-laravel#709]
Hi,

Why does a Refresh Token expire? What I'm used to is that a Refresh Token never expires (Working a lot with Salesforce OAuth).

Is it possible to get a Refresh Token that does not expire? Of how should the flow work with an expires Refresh Token?

Best regards, 
Ronnie

**Comment by maximebeaudoin** [comment]
@RonnieVisser According to the refresh token grant type, provided by the `League\OAuth2\Server\Grant\RefreshTokenGrant` class. You MUST specify a expiration TTL. 

The refresh token is used to get a new token with or without a new refresh token. This grant type is used to get a rotation of access token.

**Comment by RonnieVisser** [comment]
Ok thank you for your explanation.

When I do a request to refresh my access token "grant_type=refresh_token", why is it removing the refresh token from the database? this way I can request only 1 refreshed access token.

**Comment by maximebeaudoin** [comment]
In your `oauth2.php` config, you must set `rotate_refresh_tokens=true` to enable refresh token rotation. When you use the refresh token to get a new access token, the `RefreshTokenGrant` will generate a new refresh token and the old token will be destroy.

**Comment by RonnieVisser** [comment]
Thank you, I already tried that and that's working. My assumption was that
if I set that to false the refresh token will exists as long as the expiry
date allows it. now I understand that's not the case.

**Comment by vinkla** [comment]
This seems fairly old. I'm closing it.
