### ISSUE TITLE
Token ttl

### ISSUE THREAD

**Issue by geshner** [lucadegasperi/oauth2-server-laravel#711]
Hi, Is there a way to set the token to expire in a spesific day? 
Like the token expire on 28th day of each month.

**Comment by maximebeaudoin** [comment]
@geshner According to `League\OAuth2\Server\Entity\AbstractTokenEntity::isExpired()`, the token expiration validation working like this `return ((time() - $this->expireTime) > 0);` so it's not possible to expire a token on a specific day.

**Comment by geshner** [comment]
@maximebeaudoin thank you.
