### ISSUE TITLE
CSRF middleware in Lumen instructions?

### ISSUE THREAD

**Issue by datawench** [lucadegasperi/oauth2-server-laravel#712]
The Lumen installation instructions tell us to add this to the route middleware array: 

`'csrf' => \Laravel\Lumen\Http\Middleware\VerifyCsrfToken::class`

but the _Middleware_ namespace is showing as undefined in my (most recent) install of Lumen, and I gather from googling around that the _VerifyCsrfToken_ class's features has been "absorbed" into another part of Laravel.

How then, should I enable CSRF token verification with this library?

**Comment by vinkla** [comment]
No, we should probably update the documentation.
