### ISSUE TITLE
how to generate client information?

### ISSUE THREAD

**Issue by uyson** [lucadegasperi/oauth2-server-laravel#715]
where is the artisan command

**Comment by messi89** [comment]
looking for it too

how to generate client information ?

**Comment by kroeder** [comment]
Do you mean something like this? 

```
    /**
     * Get user by token (send via http-header or POST/GET)
     * @return json
     */
    public function getUser() {
        $id = Authorizer::getResourceOwnerId();
        $user = User::find($id);
        return response()->json($user);
    }
```

**Comment by uyson** [comment]
@kroeder  thanks you'r comment,
 I mean is How to add Authorizer infomation in table like oauth_clients table,

**Comment by vinkla** [comment]
It is up to the developers using this to implement a solution for this. We currently don't provide this.
