### ISSUE TITLE
Modifying errors returned from middleware

### ISSUE THREAD

**Issue by paulgoodfield** [lucadegasperi/oauth2-server-laravel#716]
Hi there,

I'm using this library in an API I'm building and was wondering if there is a way of changing the default error object that gets returned from routes protected by the oauth middleware:

```
{
  "error": "invalid_request",
  "error_description": "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed. Check the \"access token\" parameter."
}
```

I'm trying to keep all responses from the api to a consistent format, similar to how the Instagram API behaves. For example:

```
{
	"meta": {
		"error_type":"OAuthParameterException",
		"code":400,
		"error_message":"Missing client_id or access_token URL parameter."
	}
}
```

**Comment by vinkla** [comment]
I suggest you looking at @GrahamCampbell's [exceptions package](https://github.com/GrahamCampbell/Laravel-Exceptions). There you can add an transformer for the oauth exceptions.
