### ISSUE TITLE
Authorization code grant in Lumen 5.2

### ISSUE THREAD

**Issue by OmarElGabry** [lucadegasperi/oauth2-server-laravel#717]
I went through the documentation for implementing Authorization code grant but it seems it's not suited for Lumen 5.2.

How can I implement Authorization code grant with Lumen 5.2? Is there any future plans on making it possible with Lumen 5.2?

Thanks

**Comment by kroeder** [comment]
see #662

**Comment by OmarElGabry** [comment]
The discussion there focused on issues related to AuthServiceProvider when using Password Grant in Lumen.

**Comment by vinkla** [comment]
We currently have issues with Lumen 5.2, please see #662.
