### ISSUE TITLE
Implement a standards compliant way of validating the access token

### ISSUE THREAD

**Issue by Loilo** [lucadegasperi/oauth2-server-laravel#719]
I played around with this repository and the task of validating an issued access token on the resource server (using the password grant).
While doing that I looked around on the internet and now (since last october) there seems to be the possibility to do that in a standardized way.

For now I validated tokens by sending them to a route on the authentication server protected by the "oauth" middleware and it works fine so far but since this library seems to be the best and most well-known PHP thing to use OAuth2 with Laravel it would be amazing to have the IETF RFC 7662 way available to check access tokens.

Anyone got any thoughts on this?

**Comment by vinkla** [comment]
Please elaborate a bit more. I'm not sure what you're asking.

**Comment by Loilo** [comment]
Oh dear, it was actually not too easy to get back to my train of thoughts from two weeks ago. :)
I was trying to use the Password Grant and everything worked pretty fine. I just missed an "official" way to check (from the OAuth2 client side) if an access token is valid.
Googling around told me that there's no official way to do that and everyone does it differently but [Stackoverflow told me](http://stackoverflow.com/a/28048217/2048874) there's a standardized scheme for a JSON response to such a request now.
What I meant was that it would be nice to have that kind of scenario somehow baked into the library.

**Comment by vinkla** [comment]
Okay, now I understand better :) We're working on the next major version and all ideas are appreciated. If you feel up for it, send us an pull request and we'll look at it.

**Comment by eidng8** [comment]
Sorry to stick to closed issue, just in case you may want to have a look.

I've made a quick trial on this, on this [gist](https://gist.github.com/eidng8/564fdfae673f3d981742cf7e56c3cba1).
