### ISSUE TITLE
Upgrade to league/oauth2-server 5.x

### ISSUE THREAD

**Issue by felixkiss** [lucadegasperi/oauth2-server-laravel#724]
There is a new major version released.

I noticed that work has started on migrating to this new version on the develop branch.

Do you have time table for this? What needs to be done? Can users contribute?

If there was an issue with everything that needs to be done first, others could chip in and help moving this forward.

**Comment by lucadegasperi** [comment]
Hello @felixkiss, here are the answers to your questions:

1. No time table yet. My daily job keeps me from making plans.
2. Make it feel like it's part of laravel - make it easy to use it out of the box - make it extensible to other storage types, and in general, make everything swappable by the end user.
3. Yes.

**Comment by vinkla** [comment]
Closing this since I consider it answered. @felixkiss feel free to comment if you wonder anything else.
