### ISSUE TITLE
InvalidArgumentException in AuthManager.php line 97: Auth guard driver [api] is not defined.

### ISSUE THREAD

**Issue by Frondor** [lucadegasperi/oauth2-server-laravel#745]
I've "googled" a lot, but still can't figure out how to solve this problem.
Is it a known bug or something like that? Or it happens only because I didn't implement the oauth2-server properly?

To make things faster, I've created a repository ([lumen-oauth-api](https://github.com/Frondor/lumen-oauth-api)) where I explain things I little better, and you can actually see what I did.

Probably this is matter of inexperience, I strongly apologize if that's the case.

**Comment by OmarElGabry** [comment]
You can't use `once()` method. Try to tweak your `verify()`method in [PasswordGrantVerifier](https://github.com/Frondor/lumen-oauth-api/blob/795e4ae2d0331e649ce12d6a2566fbd0dc1b9141/app/PasswordGrantVerifier.php#L17). See my comment [here](https://github.com/lucadegasperi/oauth2-server-laravel/issues/654#issuecomment-221886053).

**Comment by Frondor** [comment]
Yes, that worked! Thanks a lot!
