### ISSUE TITLE
Invoke Password Grant

### ISSUE THREAD

**Issue by dugajean** [lucadegasperi/oauth2-server-laravel#751]
I'm using a AuthController for my user log in. And once the user successfully logs in, I want to include the access token with the response. However, I don't know how exactly to invoke the `PasswordGrantVerifier` class in order to get a access token.

How do I invoke that class exactly? That information is not provided in the documentation.

**Comment by OmarElGabry** [comment]
It's already [there](https://github.com/lucadegasperi/oauth2-server-laravel/blob/master/docs/authorization-server/password.md).  

The user needs to make a request to `oauth/access_token` providing email, password, client_id, client_secret, & grant_type. Then, the `PasswordGrantVerifier@verify` will verify the user credentials, and if valid, an access token will be sent.

**Comment by vinkla** [comment]
Thanks for helping out @OmarElGabry!

**Comment by dugajean** [comment]
@OmarElGabry 

I definitely did all this. I also checked out the documentation at thephpleague website. However, I keep getting this error:

```
"error": {
    "message": "Tried to access session data without an active access token",
    "status": 400,
    "debug": {
      "exception": "LucaDegasperi\\OAuth2Server\\Exceptions\\NoActiveAccessTokenException",
```

I am making a `POST` request to the `/access_token` route with all the data you mentioned, but nothing is happening, except the error shown above. Therefore, I think the documentation is slightly unclear at explaining on how to achieve this verification - especially for people just starting on OAuth2 like myself.

**Comment by OmarElGabry** [comment]
@dugajean Can you share with me the way your `PasswordGrantVerify `class works?

**Comment by dugajean** [comment]
@OmarElGabry It was literally copied from the link you provided. I have been trying to follow that documentation as-is and it didn't work. My grant setup in `config/oauth2.php` has this:

```
'grant_types' => [
    'password' => [
        'class' => '\League\OAuth2\Server\Grant\PasswordGrant',
        'callback' => '\App\PasswordGrantVerifier@verify',
        'access_token_ttl' => 3600
    ]
]
```

And the `PasswordGrantVerifier.php` file is placed inside `App` and has the contents from the previous link as said. 

I created an OAuth client in the `oauth_clients` table like so:

```
mypublic	mysecret	myClient	2016-06-30 22:22:04	2016-06-30 22:22:04
```

And I make the `POST` via Postman request like this (set in `x-www-form-urlencoded`):

```
grant_type:password
client_id:mypublic
client_secret:mysecret
scope:
username:oauer1084
password:password
```

**Comment by OmarElGabry** [comment]
`NoActiveAccessTokenException ` will be thrown when you try to get the current client id, but no access token is provided. So, I suspect you are calling `Authorizer::getResourceOwnerId();` somewhere in the code, right?

**Comment by dugajean** [comment]
@OmarElGabry Please see my edit above. And no, I don't use that.

**Comment by dugajean** [comment]
I think we're experiencing a bug here. I'm trying to dump something in `PasswordGrantVerifier@verify` when doing my POST request and it's not showing anything, which means it's never hitting this callback.

**Comment by OmarElGabry** [comment]
`getAccessToken()` is enough to throw `NoActiveAccessTokenException` exception when no access token is provided.
