### ISSUE TITLE
OAuth Middleware

### ISSUE THREAD

**Issue by imjohnbon** [lucadegasperi/oauth2-server-laravel#752]
I'm currently having an issue with the following scenario: I want to have access to the currently authenticated-user (via an access token header) in a controller method, but I don't want that route to have the REQUIREMENT of having an access token.

This is problematic, because the only way to get access to the currently logged in user is to apply the "oauth" middleware to the route. But if I do that, ONLY anonymous users can see the route (it errors if you don't pass an access token and have the oauth middleware applied).

For example, let's say I have an application like Instagram, with an endpoint for getting a users followers:

/users/id/followers

Now, I want this to be a public endpoint, but I also have some code in my controller that checks if the user is private, and if they are, it checks that the authenticated-user is an approved follower of that user. So, I need access to the currently authenticated user, but the only way I can do that is to apply the "oauth" middleware. But if I do that, the endpoint errors out if the user is just an anonymous user that doesn't have an access token.

Any tips for handling this?

**Comment by OmarElGabry** [comment]
How can I give you the current authenticated user without giving me his access token?!

**Comment by imjohnbon** [comment]
@OmarElGabry Well, you can't of course. My question was more around the idea of "what do you do when you only _sometimes_ need to get the currently authenticated user inside of a controller method?" As in, you don't want the request to fail if there's no access token, but if there is an access token, you want to be able to grab the resource owner id. Currently, you can only get the resource owner id if you have the oauth middleware applied to the route, but if you do that then the request fails without an access token, leading to my issue.

Nonetheless, I think my problem actually stems from my own misunderstanding of the situation. I guess the truth is that in this case, you should never have a request without an access token. Because anything that consumes the API should get an access token (whether it's a user with a login/pass or just a web client, or something else entirely).

**Comment by OmarElGabry** [comment]
Aha, I guess using this package you can't. But, in the real world situations, you can. For example, when I open a Facebook page, and I'm not logged in, I can see everything just fine, and whenever I log in, Now, the application can get my current name, email, ...etc.

Actually, In APIs, you can have a route path that doesn't need an access token; user doesn't need to be authorized, like in [vk.com](https://api.vk.com/method/newsfeed.search?q=%23hello).
