### ISSUE TITLE
Compatibility with Mongodb eloquent

### ISSUE THREAD

**Issue by iNDicat0r** [lucadegasperi/oauth2-server-laravel#759]
Hi

I am using laravels mongodb package here: https://github.com/jenssegers/laravel-mongodb

Basically I want to install oauth2 server and therefore I need to know if this package is compatible and can be used in conjunction with jenssegers mongodb.

Regards

**Comment by vinkla** [comment]
Please see this https://github.com/lucadegasperi/oauth2-server-laravel/issues/219#issuecomment-61172289
