### ISSUE TITLE
Instalation in Laravel 5.2.* 

### ISSUE THREAD

**Issue by eteck** [lucadegasperi/oauth2-server-laravel#762]
[Composer\Downloader\TransportException]
  The "http://packagist.org/p/league/oauth2server%242d413ba39a9b7fcce5c3f94d31c884770987dde2b173b1ec3ad33474c7fe00ec.
  json" file could not be downloaded: failed to open stream: HTTP request failed!

**Comment by vinkla** [comment]
???
