### ISSUE TITLE
Bump league/oauth2-server version

### ISSUE THREAD

**Issue by craigwillis85** [lucadegasperi/oauth2-server-laravel#768]
Hi

I notice that you have listed the version of `laravel 5.2.x` as using `OAuth Server 5.1.x`, but checking through the versions on packagist, `5.2.0` and `dev-master` both are still using `4.1.*` of `OAuth Server`.

Is this a simple typo, or did someone forget to bump the `OAuth Server` version in composer.json?

**Comment by vinkla** [comment]
Thanks for asking but this update isn't just a version bump. The new `league/oauth2-server` requires a big update on our side. You can see our work on the `develop` branch.
